### ISSUE TITLE
callAttr method gives an error.

### ISSUE THREAD

**Issue by furkanbalci0** [chaquo/chaquopy#1005]
#### Chaquopy version
14.0.2

#### Devices or emulators where the issue happens
All devices and emulators.

#### Relevant parts of your code
```
Event:APP_SCOUT_HANG Thread:main backtrace:
                                             at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
                                             at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
                                             at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
                                             at com.speedreadtube.app.data.remote.YoutubeRepository.getTranscripts(YoutubeRepository.kt:18)
                                             at com.speedreadtube.app.MainViewModel$getTranscripts$2.invokeSuspend(MainViewModel.kt:24)
                                             at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                             at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                             at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                                             at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                             at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                             at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                             at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                                             at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                             at com.speedreadtube.app.MainViewModel.getTranscripts(MainViewModel.kt:23)
                                             at com.speedreadtube.app.ui.lobby.LobbyFragment$populateUi$1.invokeSuspend(LobbyFragment.kt:43)
                                             at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                             at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
                                             at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
                                             at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                                             at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                                             at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                             at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
                                             at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
                                             at android.os.Handler.handleCallback(Handler.java:942)
                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                             at android.os.Looper.loopOnce(Looper.java:211)
                                             at android.os.Looper.loop(Looper.java:300)
                                             at android.app.ActivityThread.main(ActivityThread.java:8232)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
00:43:59.042 eedreadtube.app          I  Thread[6,tid=20603,WaitingInMainSignalCatcherLoop,Thread*=0xb40000775443d000,peer=0x13541490,"Signal Catcher"]: reacting to signal 3
```

#### Describe your issue
Sometimes the app works and sometimes it doesn't. It happens completely randomly. I do this entirely in mainthread.

**Comment by mhsmith** [comment]
Please post the exception message (not just the stack trace), and the relevant parts of your code.

**Comment by mhsmith** [comment]
You still haven't posted the actual exception message. Please try to find it and understand it yourself before asking for help. It should be in in the log near the stack trace, and if the exception comes from Python code, there should be some `<python>` lines there too.

This stack trace is in an unusual format, which my searches suggest may be connected to Xiaomi MIUI devices. You may get more useful information from a different device.

**Comment by furkanbalci0** [comment]
I need to be able to access the python code in order to throw any exceptions, but since I cannot access the python code anyway, it gives the above error.

Where should “buildPython” be in Gradle?

Currently: "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3"

**Comment by mhsmith** [comment]
You've closed the issue: does this mean you've solved your problem? If so, please post a comment explaining how you solved it, as this may be useful to other people.

**Comment by furkanbalci0** [comment]
I'm sorry for keeping you busy. I have concluded that the problem is not caused by you.
