### ISSUE TITLE
 com.chaquo.python.PyException: ModuleNotFoundError: No module named 'docx'

### ISSUE THREAD

**Issue by DevTrinh** [chaquo/chaquopy#1016]
I have imported all the necessary libraries, however I got the following error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cherry.doc/com.cherry.doc.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'docx'
                                                                                         	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2958)
                                                                                         	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
                                                                                         	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                         	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                         	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
                                                                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                         	at android.os.Looper.loop(Looper.java:193)
                                                                                         	at android.app.ActivityThread.main(ActivityThread.java:6825)
                                                                                         	at java.lang.reflect.Method.invoke(Native Method)
                                                                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
                                                                                         Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'docx'
                                                                                         	at <python>.java.chaquopy.import_override(import.pxi:20)
                                                                                         	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                         	at <python>.Script.<module>(Script.py:2)
                                                                                         	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:241)
                                                                                         	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:940)
                                                                                         	at <python>.java.android.importer.exec_module(importer.py:554)
                                                                                         	at <python>.java.android.importer.exec_module(importer.py:606)
                                                                                         	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:690)
                                                                                         	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:1149)
                                                                                         	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1178)
                                                                                         	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1206)
                                                                                         	at <python>.importlib.import_module(__init__.py:126)
                                                                                         	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                         	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                         	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                         	at com.cherry.doc.MainActivity.onCreate(MainActivity.kt:49)
                                                                                         	at android.app.Activity.performCreate(Activity.java:7144)
                                                                                         	at android.app.Activity.performCreate(Activity.java:7135)
                                                                                         	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                         	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
```
                                                                                         	
it is my code:
```import os
from docx import Document
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO

docx_path = "/data/data/com.cherry.doc/cache/sample.docx"

doc = Document(docx_path)

pdf_buffer = BytesIO()
pdf_canvas = canvas.Canvas(pdf_buffer, letter)

for paragraph in doc.paragraphs:
    pdf_canvas.drawString(100, 700, paragraph.text)
    pdf_canvas.showPage()

pdf_canvas.save()

pdf_output_path = "/data/data/com.cherry.doc/cache/sample.pdf"

with open(pdf_output_path, 'wb') as pdf_file:
    pdf_file.write(pdf_buffer.getvalue())```

**Comment by mhsmith** [comment]
You'll need to install the necessary packages into your app as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements).
