### ISSUE TITLE
Failed to install pydantic-core==2.10.1 from https://files.pythonhosted.org/packages/af/31/8e466c6ed47cddf23013d2f2ccf3fdb5b908ffa1d5c444150c41690d6eca/pydantic_core-2.10.1.tar.gz#sha256=0f8682dbdd2f67f8e1edddcbffcc29f60a6182b4901c367fc8c1c40d30bb0a82 (from pydantic<3,>=1.9.0->openai).

### ISSUE THREAD

**Issue by airtel121** [chaquo/chaquopy#1019]
#### Chaquopy version
We used this version: "14.0.2"

#### Relevant parts of your build.gradle file
python {
            version "3.8"
            //buildPython "/usr/local/bin/python3.8"
            // BDD CHAQUOPY installing six package as I am trying out chaquopy_console_master for now
            pip {
                install "six"
                install "openai"
             //   install "tiktoken"
                install "scipy"
              //  install "numpy"
                install "pandas"
                install "openpyxl"
            }
        }

ndk.abiFilters 'armeabi-v7a','arm64-v8a'

#### Describe your issue
While building project it failed on Task :app:generateDebugPythonRequirements 

Log:
Collecting pydantic-core==2.10.1
  Using cached pydantic_core-2.10.1.tar.gz (347 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\pranav.tank\AppData\Local\Programs\Python\Python311\python.exe' 'D:\Android_Branches\development\SarasAndroid\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\PRANAV~1.TAN\AppData\Local\Temp\tmp1ab3otwb'
    ERROR: Command errored out with exit status 1:

         cwd: C:\Users\pranav.tank\AppData\Local\Temp\pip-install-coz5_l69\pydantic-core
    Complete output (26 lines):
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory C:\Users\pranav.tank\AppData\Local\Temp\pip-modern-metadata-17w0iret --interpreter C:\Users\pranav.tank\AppData\Local\Programs\Python\Python311\python.exe`
    Traceback (most recent call last):
      File "D:\Android_Branches\development\SarasAndroid\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "D:\Android_Branches\development\SarasAndroid\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Android_Branches\development\SarasAndroid\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pranav.tank\AppData\Local\Temp\pip-build-env-unpl5lbx\overlay\Lib\site-packages\maturin\__init__.py", line 207, in prepare_metadata_for_build_wheel
        _output = subprocess.check_output(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pranav.tank\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pranav.tank\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
        with Popen(*popenargs, **kwargs) as process:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pranav.tank\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\pranav.tank\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Failed to install pydantic-core==2.10.1 from https://files.pythonhosted.org/packages/af/31/8e466c6ed47cddf23013d2f2ccf3fdb5b908ffa1d5c444150c41690d6eca/pydantic_core-2.10.1.tar.gz#sha256=0f8682dbdd2f67f8e1edddcbffcc29f60a6182b4901c367fc8c1c40d30bb0a82 (from pydantic<3,>=1.9.0->openai).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install pydantic-core==2.10.1 from https://files.pythonhosted.org/packages/af/31/8e466c6ed47cddf23013d2f2ccf3fdb5b908ffa1d5c444150c41690d6eca/pydantic_core-2.10.1.tar.gz#sha256=0f8682dbdd2f67f8e1edddcbffcc29f60a6182b4901c367fc8c1c40d30bb0a82 (from pydantic<3,>=1.9.0->openai).

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'py'' finished with non-zero exit value 1

**Comment by Saeppo** [comment]
This worked for me.

python {
            version 3.8
            pip {
                install "pydantic<2"
            }
 }

**Comment by mhsmith** [comment]
For further discussion of pydantic version 2, see #1017.
