### ISSUE TITLE
How to link a .so file into chaquopy project and have python find it

### ISSUE THREAD

**Issue by ZSenZhang** [chaquo/chaquopy#1021]
Hi I am very new to Chaquopy. I am trying to include a prebuilt python library with its required .so file into my project with Chaquopy. I looked through the issues list and didn't seem to find the right answer to solve this problem.

The error I got is following:
```
com.example.chaquopy_test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chaquopy_test, PID: 5041
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.chaquopy_test/com.example.chaquopy_test.MainActivity}: com.chaquo.python.PyException: ImportError: dlopen failed: library "libgnuradio-blocks.so" not found
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.chaquo.python.PyException: ImportError: dlopen failed: library "libgnuradio-blocks.so" not found
```
The part of my build.gradle file is like this:
```
ndk{
            abiFilters "arm64-v8a"
        }
        python {
            pip {
                install "matplotlib"
            }
        }
        sourceSets {
            main {
                python.srcDirs "~/prebuilt-gnuradio-python-toolchain/jni/arm64-v8a"
                jniLibs.srcDirs = ['~/prebuilt-gnuradio-python-toolchain/jni']
            }
        }
 ```
 I put the `libgnuradio-blocks.so` file is inside of `prebuilt-gnuradio-python-toolchain/jni/arm64-v8a`. I also put in under `src/main/python` directory but both does not work. I wonder where should I put this .so file to have python find the file.

The chaquo.python version I am using is `classpath "com.chaquo.python:gradle:9.1.0"`
And I am doing it in Android Studio 4.1.

Appreciate any help in advance.

**Comment by ZSenZhang** [comment]
I realized the problem is when python trying to load one .so file (`_blocks_swig0.so`) while the .so file trying to load another .so file (`libgnuradio-blocks.so`) and it failed. So I wonder if there's a way for Android to automatically search for the dependent .so file in a certain folder? I'm thinking `LD_LIBRARY_PATH` might be a way but I am not sure which is the right way to include the path.

**Comment by mhsmith** [comment]
> I realized the problem is when python trying to load one .so file (`_blocks_swig0.so`) while the .so file trying to load another .so file (`libgnuradio-blocks.so`)

Where did you get these files from? `.so` files from Linux or any other OS won't work; they must be built specifically for Android, such as with the [Chaquopy build tool](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md).

> `python.srcDirs "~/prebuilt-gnuradio-python-toolchain/jni/arm64-v8a`

I don't think the `~` symbol will work here, but you can use a path relative to the directory containing the build.gradle file.

> The chaquo.python version I am using is classpath "com.chaquo.python:gradle:9.1.0"

That's quite an old version. Please update to the newest version if possible.

If you need any more help, please post:
* The full stack trace, *including* any "Caused by" sections
* The relevant sections of your code

**Comment by ZSenZhang** [comment]
Thanks for responding! 

I cross compiled the .so file with Android NDK, and it is working with Android.

I tried with `python.srcDirs "/home/jason/Desktop/Work5-SDR/docker-toolchain/jni/arm64-v8a"` as well, and it is still not able to find the `libgnuradio-blocks.so` file.

I tried with the newest version: `com.chaquo.python:gradle:14.0.2` the problem didn't solve.

The directly clone the code from Chaquopy matplotlib example (https://github.com/chaquo/chaquopy-matplotlib). I modified the plot.py code as following:
```
import io
import matplotlib.pyplot as plt
import os
import sys

sys.path.append('./')

os.environ['LD_LIBRARY_PATH'] = '/data/user/0/com.example.chaquopy_test/files/chaquopy/AssetFinder/app/arm64-v8a'

from gnuradio import blocks
```

And the build.gradle code is the same as before
```
ndk{
            abiFilters "arm64-v8a"
        }
        python {
            pip {
                install "matplotlib"
            }
        }
        sourceSets {
            main {
                python.srcDirs "~/prebuilt-gnuradio-python-toolchain/jni/arm64-v8a"
                jniLibs.srcDirs = ['~/prebuilt-gnuradio-python-toolchain/jni']
            }
        }
```
In gnuradio what it did is:
```
dirname, filename = os.path.split(os.path.abspath(__file__))
        print("in __file__:" + str(__file__) + " dirname is " + dirname)
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_blocks_swig0')).lstrip('.')
        try:
            importlib.import_module(mname)
        except:
            importlib.import_module('_blocks_swig0')
        ```
       but it failed with the error `ImportError: dlopen failed: library "libgnuradio-blocks.so" not found`. This is because _blocks_swig0.so is trying to use libgnuradio-blocks.so, but not able to find the .so file which caused the failure. So I wonder where I should put the .so file to make it find the .so file.

**Comment by ZSenZhang** [comment]
For more information, I tried to print out the file list uploaded into app from `/home/jason/prebuilt-gnuradio-python-toolchain/jni/arm64-v8a` with the following code in MainActivity.kt:
```
val py = Python.getInstance()
        // Path to the directory
        val path =
            "/data/data/com.example.chaquopy_test/files/chaquopy/AssetFinder/app/"

        // Creating a File object for the directory
        val directory = File(path)

        // Listing all the files in the directory
        val files = directory.listFiles()
        if (files != null) {
            for (file in files) {
                // Printing the name of each file
                Log.d("Files", "FileName:" + file.name)
            }
        } else {
            Log.d("Files", "Directory is empty or does not exist")
        }

        val module = py.getModule("plot")
        ```
        And interestingly, all the files are uploaded except the .so files. Do you have any idea why this is happening?
        
        The list of files in `home/jason/prebuilt-gnuradio-python-toolchain/jni/arm64-v8a`:
        ```
        ls /home/jason/prebuilt-gnuradio-python-toolchain/jni/arm64-v8a/
cmake                                             libfftw3f_threads.la
dpfp                                              libgmp.a
dpfp_threaded                                     libgmp.la
engines-3                                         libgmp.so
fxload                                            libgmpxx.a
hotplugtest                                       libgmpxx.la
libboost_atomic-clang-mt-a64-1_69.a               libgmpxx.so
libboost_chrono-clang-mt-a64-1_69.a               libgnuradio-analog.so
libboost_container-clang-mt-a64-1_69.a            libgnuradio-blocks.so
libboost_context-clang-mt-a64-1_69.a              libgnuradio-digital.so
libboost_contract-clang-mt-a64-1_69.a             libgnuradio-fft.so
libboost_coroutine-clang-mt-a64-1_69.a            libgnuradio-filter.so
libboost_date_time-clang-mt-a64-1_69.a            libgnuradio-grand.so
libboost_exception-clang-mt-a64-1_69.a            libgnuradio-ieee802_11.so
libboost_fiber-clang-mt-a64-1_69.a                libgnuradio-ieee802_15_4.so
libboost_filesystem-clang-mt-a64-1_69.a           libgnuradio-osmosdr.so
libboost_graph-clang-mt-a64-1_69.a                libgnuradio-pmt.so
libboost_iostreams-clang-mt-a64-1_69.a            libgnuradio-runtime.so
libboost_locale-clang-mt-a64-1_69.a               libgnuradio-sched.so
libboost_log-clang-mt-a64-1_69.a                  libgnuradio-uhd.so
libboost_log_setup-clang-mt-a64-1_69.a            libgnuradio-zeromq.so
libboost_math_c99-clang-mt-a64-1_69.a             libhackrf.a
libboost_math_c99f-clang-mt-a64-1_69.a            libhackrf.so
libboost_math_c99l-clang-mt-a64-1_69.a            libpython2.7.a
libboost_math_tr1-clang-mt-a64-1_69.a             libpython3.8.a
libboost_math_tr1f-clang-mt-a64-1_69.a            librtlsdr.a
libboost_math_tr1l-clang-mt-a64-1_69.a            librtlsdr.so
libboost_prg_exec_monitor-clang-mt-a64-1_69.a     libssl.a
libboost_program_options-clang-mt-a64-1_69.a      libssl.so
libboost_random-clang-mt-a64-1_69.a               libssl.so.3
libboost_regex-clang-mt-a64-1_69.a                libthrift-0.13.0.so
libboost_serialization-clang-mt-a64-1_69.a        libthrift.a
libboost_stacktrace_basic-clang-mt-a64-1_69.a     libthrift.la
libboost_stacktrace_noop-clang-mt-a64-1_69.a      libuhd.so
libboost_system-clang-mt-a64-1_69.a               libusb1.0.so
libboost_test_exec_monitor-clang-mt-a64-1_69.a    libvolk.a
libboost_thread-clang-mt-a64-1_69.a               libvolk.so
libboost_timer-clang-mt-a64-1_69.a                libzmq.a
libboost_type_erasure-clang-mt-a64-1_69.a         libzmq.la
libboost_unit_test_framework-clang-mt-a64-1_69.a  listdevs
libboost_wave-clang-mt-a64-1_69.a                 pkgconfig
libboost_wserialization-clang-mt-a64-1_69.a       python2.7
libcrypto.a                                       python3
libcrypto.so                                      python3.7
libcrypto.so.3                                    python3.8
libfftw3f.a                                       sam3u_benchmark
libfftw3f.la                                      stress
libfftw3f_threads.a                               xusb
```
And the printout of the list of files in `/data/data/com.example.chaquopy_test/files/chaquopy/AssetFinder/app/`:
```
2023-11-18 16:35:58.458 23891-23891/com.example.chaquopy_test D/Files: FileName:libfftw3f_threads.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_coroutine-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_prg_exec_monitor-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:librtlsdr.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_random-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_filesystem-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_container-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_math_tr1-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_wave-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libgmp.la
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:.placeholder
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_graph-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libgmpxx.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_wserialization-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_regex-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libvolk.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_program_options-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_fiber-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_log-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_unit_test_framework-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:sam3u_benchmark
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_timer-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_contract-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_math_tr1f-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_date_time-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_type_erasure-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_test_exec_monitor-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libgmp.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:xusb
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libzmq.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:fxload
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:listdevs
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:hotplugtest
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_system-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_locale-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_math_tr1l-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_serialization-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_thread-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:dpfp_threaded
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_math_c99-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libzmq.la
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libthrift.la
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libssl.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_chrono-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libfftw3f.la
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_atomic-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libgmpxx.la
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_log_setup-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:stress
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_math_c99f-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_math_c99l-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libfftw3f_threads.la
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libfftw3f.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_context-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:pkgconfig
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libhackrf.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:dpfp
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_iostreams-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_stacktrace_noop-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:cmake
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_stacktrace_basic-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libcrypto.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libboost_exception-clang-mt-a64-1_69.a
2023-11-18 16:35:58.459 23891-23891/com.example.chaquopy_test D/Files: FileName:libthrift.a
```

**Comment by ZSenZhang** [comment]
Here's the full stack of the error information:
```
Launching 'app' on Physical Device.
Install successfully finished in 20 s 360 ms.
$ adb shell am start -n "com.example.chaquopytest/com.example.chaquopytest.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 32424 on device 'oneplus-gm1925-7bf4dd08'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/le.chaquopytes: Late-enabling -Xcheck:jni
E/le.chaquopytes: Unknown bits set in runtime_flags: 0x8000
I/Perf: Connecting to perf service.
I/le.chaquopytes: [GL_OOM] ClampGrowthLimit 268435456
I/Instrumentation: android.app.Application@d9c1628 onCreate begin
V/Font: Change font:1
V/Font: Default family:android.graphics.Typeface@6bf821b3
I/Instrumentation: android.app.Application@d9c1628 onCreate in 2ms
D/DecorView: calNavBarColor: color=ff000000, barColor=0, flag=10100, mSemiTransparentBarColor=66000000, sysuiVis=0, scrimTrans=false
    calNavBarColor: color=ff000000, barColor=0, flag=810100, mSemiTransparentBarColor=66000000, sysuiVis=0, scrimTrans=false
    calNavBarColor: color=ff000000, barColor=0, flag=810100, mSemiTransparentBarColor=66000000, sysuiVis=0, scrimTrans=false
D/PhoneWindow: PackageName: com.example.chaquopytest mNavigationBarColor:ff1a2b3c, targetSdk:28, Translucent:false, gesture:false, isNoNeedChangeColor false, isNeedChangeColor false
D/DecorView: calNavBarColor: color=ffebebeb, barColor=ffebebeb, flag=80810100, mSemiTransparentBarColor=66000000, sysuiVis=0, scrimTrans=false
D/DecorView: calNavBarColor: color=ffebebeb, barColor=ffebebeb, flag=80810100, mSemiTransparentBarColor=66000000, sysuiVis=0, scrimTrans=false
V/FlingOptimizerScroller: FlingOptimizerOverScroller Init
E/Perf: Fail to get file list com.example.chaquopytest
E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
    Fail to get file list com.example.chaquopytest
    getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
W/le.chaquopytes: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/le.chaquopytes: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/le.chaquopytes: Accessing hidden method Landroid/os/Handler;-><init>(Landroid/os/Looper;Landroid/os/Handler$Callback;Z)V (greylist, JNI, allowed)
    Accessing hidden method Landroid/os/Handler;-><init>(Z)V (greylist, JNI, allowed)
W/le.chaquopytes: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (greylist, JNI, allowed)
W/le.chaquopytes: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (greylist, JNI, allowed)
W/asset: seek out of range: want -20, end=22
W/le.chaquopytest: type=1400 audit(0.0:172597): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/stdlib-arm64-v8a/_pickle.so" dev="dm-3" ino=1483359 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
W/le.chaquopytest: type=1400 audit(0.0:172598): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/stdlib-arm64-v8a/_socket.so" dev="dm-3" ino=1483360 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
W/le.chaquopytest: type=1400 audit(0.0:172599): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/stdlib-arm64-v8a/array.so" dev="dm-3" ino=1483361 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
W/le.chaquopytest: type=1400 audit(0.0:172600): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/stdlib-arm64-v8a/_queue.so" dev="dm-3" ino=1483362 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
W/le.chaquopytest: type=1400 audit(0.0:172623): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/requirements/matplotlib/_path.so" dev="dm-3" ino=1483533 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
W/le.chaquopytest: type=1400 audit(0.0:172627): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/stdlib-arm64-v8a/unicodedata.so" dev="dm-3" ino=1483534 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
W/le.chaquopytest: type=1400 audit(0.0:172629): avc: granted { execute } for path="/data/data/com.example.chaquopytest/files/chaquopy/AssetFinder/requirements/matplotlib/backends/_backend_agg.so" dev="dm-3" ino=1483536 scontext=u:r:untrusted_app_27:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chaquopytest, PID: 32424
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.chaquopytest/com.example.chaquopytest.MainActivity}: com.chaquo.python.PyException: ImportError: dlopen failed: library "libgnuradio-blocks.so" not found
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.chaquo.python.PyException: ImportError: dlopen failed: library "libgnuradio-blocks.so" not found
        at <python>.java.android.importer.create_module(importer.py:567)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.gnuradio.blocks.blocks_swig0.swig_import_helper(blocks_swig0.py:16)
        at <python>.gnuradio.blocks.blocks_swig0.<module>(blocks_swig0.py:17)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.gnuradio.blocks.blocks_swig.<module>(blocks_swig.py:24)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.gnuradio.blocks.<module>(__init__.py:36)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.plot.<module>(plot.py:10)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:507)
        at <python>.java.android.importer.exec_module(importer.py:556)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:155)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.example.chaquopytest.MainActivity.onCreate(MainActivity.kt:48)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
I/Process: Sending signal. PID: 32424 SIG: 9
```

And the related part of code is:
plot.py:
```
import io
import matplotlib.pyplot as plt
import os
import sys

sys.path.append('./')

#os.environ['LD_LIBRARY_PATH'] = '/data/user/0/com.example.chaquopy_test/files/chaquopy/AssetFinder/app/arm64-v8a'

from gnuradio import blocks
```

blocks/__init__.py:
```
from __future__ import absolute_import
from __future__ import unicode_literals

import os

try:
    from .blocks_swig import *
except ImportError:
    dirname, filename = os.path.split(os.path.abspath(__file__))
    __path__.append(os.path.join(dirname, "..", "..", "swig"))
    from .blocks_swig import *
```

block_swig.py:
```
from __future__ import absolute_import

from .blocks_swig0 import *
```

block_swig0.py:
```
from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_blocks_swig0')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_blocks_swig0')
    _blocks_swig0 = swig_import_helper()
    del swig_import_helper
```

It failed when `importlib.import_module('_blocks_swig0')`

Let me know if there's any further information you might need. Sincerely appreciate your help!

**Comment by ZSenZhang** [comment]
To make it simple, I think this problem could be solved if I could update the LD_LIBRARY_PATH before Chaquopy starts the python module. Is there a way to update LD_LIBRARY_PATH?

**Comment by ZSenZhang** [comment]
I think one way to solve this problem is maybe we can set LD_LIBRARY_PATH in Android before running python. I wonder if there's a way in Chaquopy to do this?

**Comment by mhsmith** [comment]
LD_LIBRARY_PATH won't make any difference – it's only read when the process starts up, but with Chaquopy, Python runs in the same process as the rest of your app.

> And interestingly, only partial of files are uploaded except those .so files. Do you have any idea why this is happening?

This is because, to make your app start up faster, Chaquopy doesn't extract .so files from the APK until they're needed. But they need to be in the right place for this to work, and the only supported way of doing this is to use the [package build tool](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md) to build them into .whl files, then install those files using pip. You'll need to follow the instructions in the "Adding a package" section.

**Comment by ZSenZhang** [comment]
ok, I think I found the solution to work through this. Even though I don't know I will have time to dig into it to see where is the cause of this solution. I will put it there in case anyone else might need and have time to figure out the source reason.

What I did is creating a C++ Android project. In the CMake.txt, I added these .so files in `target_link_libraries` like this:
```
target_link_libraries(native-lib
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-runtime.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-pmt.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-blocks.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libusb-1.0.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-osmosdr.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-grand.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-analog.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-filter.so
        ${TOOLCHAIN}/${ANDROID_ABI}/lib/libgnuradio-fft.so
        ${log-lib} )
```
There, you need to set the ${TOOLCHAIN} and ${ANDROID_ABI} according to the directory path you had locally. Then the Android will automatically upload these files into `nativeLibraryDir`, which is the `/lib` inside of Android app. And dlopen will  lookup files in this directory and link the function.
