### ISSUE TITLE
basicsr install error 

### ISSUE THREAD

**Issue by YouSirY** [chaquo/chaquopy#1036]
#### Chaquopy version

14.0.2
#### Relevant parts of your build.gradle file

**build.gradle**
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            version "3.8"
            buildPython "E:/Python38/python.exe"
            pip{
                options "--extra-index-url", "https://pypi.tuna.tsinghua.edu.cn/simple"
                install "-r", "requirements.txt"
            }
        }
**requirements.txt**
        basicsr
        tb-nightly

#### Describe your issue

INSTALL ERROR:
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0, https://chaquo.com/pypi-13.1, https://pypi.tuna.tsinghua.edu.cn/simple
Collecting basicsr
  Using cached basicsr-1.4.2.tar.gz (172 kB)
    ERROR: Command errored out with exit status 1:
     command: 'E:\Python38\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jimmy You\\AppData\\Local\\Temp\\pip-install-fthhc226\\basicsr\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jimmy You\\AppData\\Local\\Temp\\pip-install-fthhc226\\basicsr\\setup.py'"'"';import chaquopy_monkey; chaquopy_monkey.disable_native();f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base 'C:\Users\Jimmy You\AppData\Local\Temp\pip-pip-egg-info-j8xhbun6'
         cwd: C:\Users\Jimmy You\AppData\Local\Temp\pip-install-fthhc226\basicsr\
    Complete output (37 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Jimmy You\AppData\Local\Temp\pip-install-fthhc226\basicsr\setup.py", line 147, in <module>
        setup(
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\dist.py", line 717, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
    ERROR: Command errored out with exit status 1:

      File "E:\androidWorkSpace\app\build\generated\python/bp\pkg_resources\__init__.py", line 782, in resolve
        dist = best[req.key] = env.best_match(
      File "E:\androidWorkSpace\app\build\generated\python/bp\pkg_resources\__init__.py", line 1067, in best_match
        return self.obtain(req, installer)
      File "E:\androidWorkSpace\app\build\generated\python/bp\pkg_resources\__init__.py", line 1079, in obtain
        return installer(requirement)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\command\easy_install.py", line 855, in install_eggs
        return [self.install_wheel(dist_filename, tmpdir)]
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\command\easy_install.py", line 1068, in install_wheel
        self.execute(
      File "E:\Python38\lib\distutils\cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "E:\Python38\lib\distutils\util.py", line 303, in execute
        func(*args)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\wheel.py", line 101, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\wheel.py", line 105, in _install_as_egg
        dist_info = self.get_dist_info(zf)
      File "E:\androidWorkSpace\app\build\generated\python/bp\setuptools\wheel.py", line 96, in get_dist_info
        raise ValueError("unsupported wheel format. .dist-info not found")
    ValueError: unsupported wheel format. .dist-info not found
    ----------------------------------------
ERROR: Failed to install basicsr from https://files.pythonhosted.org/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz#sha256=b89b595a87ef964cda9913b4d99380ddb6554c965577c0c10cb7b78e31301e87 (from -r requirements.txt (line 1)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install basicsr from https://files.pythonhosted.org/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz#sha256=b89b595a87ef964cda9913b4d99380ddb6554c965577c0c10cb7b78e31301e87 (from -r requirements.txt (line 1)).

Chaquopy: Exit status 1

**Comment by YouSirY** [comment]
Thank you，
But Now use --use-pep517, I have a  different error:

>   Using cached lmdb-1.4.1.tar.gz (881 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'E:\Python38\python.exe' 'E:\androidWorkSpace\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\JIMMYY~1\AppData\Local\Temp\tmpkfk0fjuk'
       cwd: C:\Users\Jimmy You\AppData\Local\Temp\pip-install-1bbuga1v\lmdb
  Complete output (24 lines):
  py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
  Traceback (most recent call last):
    File "<string>", line 92, in <module>
  ModuleNotFoundError: No module named 'patch_ng'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "E:\androidWorkSpace\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "E:\androidWorkSpace\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "E:\androidWorkSpace\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Jimmy You\AppData\Local\Temp\pip-build-env-l8aqn6ay\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\Jimmy You\AppData\Local\Temp\pip-build-env-l8aqn6ay\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\Jimmy You\AppData\Local\Temp\pip-build-env-l8aqn6ay\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\Jimmy You\AppData\Local\Temp\pip-build-env-l8aqn6ay\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 94, in <module>
  Exception: Building py-lmdb from source on Windows requires the "patch-ng" python module.
  ----------------------------------------
ERROR: Failed to install lmdb from https://files.pythonhosted.org/packages/de/13/dd9b0c1924f0becc93e0bacd123a4e7a347966e3e74753ace3b1e85acc39/lmdb-1.4.1.tar.gz#sha256=1f4c76af24e907593487c904ef5eba1993beb38ed385af82adb25a858f2d658d (from basicsr->-r requirements.txt (line 1)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
  ERROR: Command errored out with exit status 1:

Failed to install lmdb from https://files.pythonhosted.org/packages/de/13/dd9b0c1924f0becc93e0bacd123a4e7a347966e3e74753ace3b1e85acc39/lmdb-1.4.1.tar.gz#sha256=1f4c76af24e907593487c904ef5eba1993beb38ed385af82adb25a858f2d658d (from basicsr->-r requirements.txt (line 1)).

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'E:/Python38/python.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by mhsmith** [comment]
Please mark code and logs with <code>```</code>, as shown [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

lmdb has already been requested at #658; you may be able to build it yourself.

**Comment by YouSirY** [comment]
when I build lmdb use code:
```./build-wheel.py --python 3.8 --abi arm64-v8a lmdb
have a problem,How to solve this problem？
```building 'cpython' extension
creating build/temp.linux_aarch64-cpython-38
creating build/temp.linux_aarch64-cpython-38/build
creating build/temp.linux_aarch64-cpython-38/build/lib
creating build/temp.linux_aarch64-cpython-38/lmdb
/home/youzh/chaquopy-master/server/pypi/packages/lmdb/build/1.4.1/cp38-cp38-android_21_arm64_v8a/wrappers/aarch64-linux-android21-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/home/youzh/chaquopy-master/server/pypi/packages/lmdb/build/1.4.1/cp38-cp38-android_21_arm64_v8a/requirements/chaquopy/include -idirafter /home/youzh/chaquopy-master/server/pypi/packages/lmdb/build/1.4.1/cp38-cp38-android_21_arm64_v8a/requirements/chaquopy/include/python3.8 -fPIC -Ilib/py-lmdb -Ibuild/lib -I/home/youzh/chaquopy-master/server/pypi/packages/lmdb/build/1.4.1/cp38-cp38-android_21_arm64_v8a/env/include -I/home/youzh/anaconda3/envs/build-wheel/include/python3.8 -c build/lib/mdb.c -o build/temp.linux_aarch64-cpython-38/build/lib/mdb.o -DHAVE_PATCHED_LMDB=1 -UNDEBUG -w
Chaquopy: ignored invalid -I directory: '/home/youzh/anaconda3/envs/build-wheel/include/python3.8'
Traceback (most recent call last):
  File "/home/youzh/chaquopy-master/server/pypi/compiler-wrapper.py", line 50, in <module>
    main()
  File "/home/youzh/chaquopy-master/server/pypi/compiler-wrapper.py", line 46, in main
    os.execv(args_out[0], args_out)
PermissionError: [Errno 13] Permission denied
error: command '/home/youzh/chaquopy-master/server/pypi/packages/lmdb/build/1.4.1/cp38-cp38-android_21_arm64_v8a/wrappers/aarch64-linux-android21-clang' failed with exit code 1
build-wheel: Error: Backend subprocess exited when trying to invoke build_wheel

**Comment by mhsmith** [comment]
It's been over a year, and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
