### ISSUE TITLE
Facing issues in creating/loading keras model. 

### ISSUE THREAD

**Issue by MustofAhmed41** [chaquo/chaquopy#1069]
I am working on a project where I am trying to train a small fully connected neural network model using the popular IMDb dataset. For this I first took a small portion of the IMDb dataset, preprocessed it in Colab, and kept it in the same directory as the Chaquopy Python file. In the Chaquopy Python file I loaded the preprocessed data and used it to train and evaluate a small deep-learning model. 

About a week ago I wrote the code and it worked perfectly fine. But now when I am trying to run the same code again it is not working. I am finding it difficult to pinpoint the issue from the error message. The problem is whenever I am trying to create or load a Keras model, I get the same error **_"com.chaquo.python.PyException: TypeError: list indices must be integers or slices, not str"_**. To do this task I used the 3 approaches (as described below), but all gave the same error message.

### 1. Creating the model from scratch in the Python file.
    from keras.models import Sequential
    from keras.layers import Dense

    model = Sequential()
    model.add(Dense(100 , input_shape=(500, ) ,  activation='relu'))  # this line throw the error
    model.add(Dense(1),  activation='softmax' )
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### 2. Loading the model architecture using .h5 format. 
First, I created the model in Colab and saved it in .h5 format. Then I moved the .h5 file to the same directory as in the Python file. 

    from keras.models import Sequential
    from keras.layers import Dense
    from tensorflow import keras

    model = Sequential()
    model.add(Dense(100 , input_shape=(500, ) ,  activation='relu')) 
    model.add(Dense(1),  activation='softmax' )
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.save('my_model.h5')

In the Chaquopy Python file I used 'load_model' from keras to load the model. 
    model = keras.models.load_model('my_model.h5')  # this line throw the error

3. I used the same approach as described in number 2 but the model was stored in .keras format. 

#### Chaquopy version
Tried a few versions. 15.0.1 / 14.0.2 / 13.0.0

#### Devices or emulators where the issue happens
The issue occurred on emulator. 

## Error Message

Here is the error message. 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.fl2, PID: 5982
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.fl2/com.example.fl2.MainActivity}: com.chaquo.python.PyException: TypeError: list indices must be integers or slices, not str
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.chaquo.python.PyException: TypeError: list indices must be integers or slices, not str
        at <python>.google.protobuf.internal.containers.__getitem__(containers.py:70)
        at <python>.tensorflow.python.framework.ops._NodeDef(ops.py:1569)
        at <python>.tensorflow.python.framework.ops._create_op_internal(ops.py:3307)
        at <python>.tensorflow.python.framework.func_graph._create_op_internal(func_graph.py:593)
        at <python>.tensorflow.python.framework.op_def_library._apply_op_helper(op_def_library.py:740)
        at <python>.tensorflow.python.ops.gen_array_ops.placeholder(gen_array_ops.py:6031)
        at <python>.tensorflow.python.ops.array_ops.placeholder(array_ops.py:2718)
        at <python>.tensorflow.python.keras.backend.placeholder(backend.py:1054)
        at <python>.tensorflow.python.keras.engine.input_layer.__init__(input_layer.py:122)
        at <python>.tensorflow.python.keras.engine.input_layer.Input(input_layer.py:270)
        at <python>.tensorflow.python.keras.engine.sequential.add(sequential.py:180)
        at <python>.tensorflow.python.training.tracking.base._method_wrapper(base.py:457)
        at <python>.my_script.train_model(my_script.py:10)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.fl2.MainActivity.onCreate(MainActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

I ran this same code in Colab and also in the same Python.exe file that I am using in this Android project. There I am not getting any error but here I am facing this problem. Can someone suggest a solution to this or any other alternative method that I can use to train a small neural network using Keras/TensorFlow? 
N.B: this is the first time I posted an issue in Github. If I made any mistake or forgot to clarify any thing please correct me.

**Comment by MustofAhmed41** [comment]
I found that this issue is not related to Chaqoupy. When we run the project, the Tensorflow version used is 2.1.0. I believe this problem is related to Tensorflow rather than Chaquopy. A thing to note here is that this error occurs whenever I include 'input_shape=(500, )'  parameter in the keras models. I still haven't figured out a way to get past this.

**Comment by scuwangwei** [comment]
Hi, I‘m probably facing the same issue,

here is the error message:

E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.it_cough, PID: 3798
    com.chaquo.python.PyException: TypeError: list indices must be integers or slices, not str
        at <python>.google.protobuf.internal.containers.__getitem__(containers.py:70)
        at <python>.tensorflow.python.framework.ops._NodeDef(ops.py:1569)
        at <python>.tensorflow.python.framework.ops._create_op_internal(ops.py:3307)
        at <python>.tensorflow.python.framework.func_graph._create_op_internal(func_graph.py:593)
        at <python>.tensorflow.python.framework.op_def_library._apply_op_helper(op_def_library.py:740)
        at <python>.tensorflow.python.ops.gen_array_ops.placeholder(gen_array_ops.py:6031)
        at <python>.tensorflow.python.ops.array_ops.placeholder(array_ops.py:2718)
        at <python>.tensorflow.python.keras.backend.placeholder(backend.py:1054)
        at <python>.tensorflow.python.keras.engine.input_layer.__init__(input_layer.py:122)
        at <python>.tensorflow.python.keras.engine.input_layer.Input(input_layer.py:270)
        at <python>.models.keras_yamnet.yamnet.YAMNet(yamnet.py:109)
        at <python>.cough_record/lib/model_loading.model_object(model_loading.py:9)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.it_cough.RecordPage.coughDetection(RecordPage.kt:604)
        at com.example.it_cough.RecordPage.access$coughDetection(RecordPage.kt:63)
        at com.example.it_cough.RecordPage$startStreaming$1.invoke(RecordPage.kt:590)
        at com.example.it_cough.RecordPage$startStreaming$1.invoke(RecordPage.kt:589)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
  
here is the source code:

 def YAMNet(
        include_top=True,
        weights=None,
        input_tensor=None,
        input_shape=None,
        pooling='avg',
        classes=521,
        classifier_activation="sigmoid"):
    """Define the core YAMNet mode in Keras."""

    if input_tensor is None:
        input_shape = input_shape if input_shape is not None else (
            params.PATCH_FRAMES, params.PATCH_BANDS)
        input_tensor = layers.Input(shape=input_shape)
    net = layers.Reshape(input_shape+(1,))(input_tensor)

    for (i, (layer_fun, kernel, stride, filters)) in enumerate(_YAMNET_LAYER_DEFS):
        net = layer_fun('layer{}'.format(i + 1), kernel, stride, filters)(net)

    if include_top:
        if weights is not None and classes != params.NUM_CLASSES:
          model_temp = Model(inputs=input_tensor, outputs=net)
    
          if weights is not None:
            model_temp.load_weights(weights)

          net = model_temp.output

        net = layers.GlobalAveragePooling2D()(net)
        logits = layers.Dense(units=classes, use_bias=True)(net)
        predictions = layers.Activation(
            name=params.EXAMPLE_PREDICTIONS_LAYER_NAME,
            activation=classifier_activation)(logits)
        
    else:
        if weights is not None:
          model_temp = Model(inputs=input_tensor, outputs=net)
    
          if weights is not None:
            model_temp.load_weights(weights)

          net = model_temp.output

        if pooling == 'avg':
            predictions = layers.GlobalAveragePooling2D()(net)
        elif pooling == 'max':
            predictions = layers.GlobalMaxPooling2D()(net)
        else:
            predictions = net
    
    model = Model(inputs=input_tensor, outputs=predictions)
    
    if weights is not None and classes == params.NUM_CLASSES:
      model.load_weights(weights)

    return model

It looks like it failed in " input_tensor = layers.Input(shape=input_shape)",
I'm sure that input_shape = (96,64) which is a tuple contains two integers

The codes works fine in few months ago, However, I Re-sync the build.gradle recently ,then this issue happened. I have tried multiple numpy version for python 3.8, but none of them works.

**Comment by scuwangwei** [comment]
Hi, I‘m probably facing the same issue,

here is the error message:

E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.it_cough, PID: 3798
    com.chaquo.python.PyException: TypeError: list indices must be integers or slices, not str
        at <python>.google.protobuf.internal.containers.__getitem__(containers.py:70)
        at <python>.tensorflow.python.framework.ops._NodeDef(ops.py:1569)
        at <python>.tensorflow.python.framework.ops._create_op_internal(ops.py:3307)
        at <python>.tensorflow.python.framework.func_graph._create_op_internal(func_graph.py:593)
        at <python>.tensorflow.python.framework.op_def_library._apply_op_helper(op_def_library.py:740)
        at <python>.tensorflow.python.ops.gen_array_ops.placeholder(gen_array_ops.py:6031)
        at <python>.tensorflow.python.ops.array_ops.placeholder(array_ops.py:2718)
        at <python>.tensorflow.python.keras.backend.placeholder(backend.py:1054)
        at <python>.tensorflow.python.keras.engine.input_layer.__init__(input_layer.py:122)
        at <python>.tensorflow.python.keras.engine.input_layer.Input(input_layer.py:270)
        at <python>.models.keras_yamnet.yamnet.YAMNet(yamnet.py:109)
        at <python>.cough_record/lib/model_loading.model_object(model_loading.py:9)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.it_cough.RecordPage.coughDetection(RecordPage.kt:604)
        at com.example.it_cough.RecordPage.access$coughDetection(RecordPage.kt:63)
        at com.example.it_cough.RecordPage$startStreaming$1.invoke(RecordPage.kt:590)
        at com.example.it_cough.RecordPage$startStreaming$1.invoke(RecordPage.kt:589)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
  
here is the source code:

 def YAMNet(
        include_top=True,
        weights=None,
        input_tensor=None,
        input_shape=None,
        pooling='avg',
        classes=521,
        classifier_activation="sigmoid"):
    """Define the core YAMNet mode in Keras."""

    if input_tensor is None:
        input_shape = input_shape if input_shape is not None else (
            params.PATCH_FRAMES, params.PATCH_BANDS)
        input_tensor = layers.Input(shape=input_shape)
    net = layers.Reshape(input_shape+(1,))(input_tensor)

    for (i, (layer_fun, kernel, stride, filters)) in enumerate(_YAMNET_LAYER_DEFS):
        net = layer_fun('layer{}'.format(i + 1), kernel, stride, filters)(net)

    if include_top:
        if weights is not None and classes != params.NUM_CLASSES:
          model_temp = Model(inputs=input_tensor, outputs=net)
    
          if weights is not None:
            model_temp.load_weights(weights)

          net = model_temp.output

        net = layers.GlobalAveragePooling2D()(net)
        logits = layers.Dense(units=classes, use_bias=True)(net)
        predictions = layers.Activation(
            name=params.EXAMPLE_PREDICTIONS_LAYER_NAME,
            activation=classifier_activation)(logits)
        
    else:
        if weights is not None:
          model_temp = Model(inputs=input_tensor, outputs=net)
    
          if weights is not None:
            model_temp.load_weights(weights)

          net = model_temp.output

        if pooling == 'avg':
            predictions = layers.GlobalAveragePooling2D()(net)
        elif pooling == 'max':
            predictions = layers.GlobalMaxPooling2D()(net)
        else:
            predictions = net
    
    model = Model(inputs=input_tensor, outputs=predictions)
    
    if weights is not None and classes == params.NUM_CLASSES:
      model.load_weights(weights)

    return model

It looks like it failed in " input_tensor = layers.Input(shape=input_shape)",
I'm sure that input_shape = (96,64) which is a tuple contains two integers

The codes works fine in few months ago, However, I Re-sync the build.gradle recently ,then this issue happened. I have tried multiple numpy version for python 3.8, but none of them works.

**Comment by mhsmith** [comment]
It looks like Tensorflow 2.1.0 is incompatible with protobuf 4.25, which was released a couple of months ago. Try adding this line to the `pip` block in your build.gradle file:
```
install "protobuf<4.25"
```

**Comment by MustofAhmed41** [comment]
Thank you @mhsmith, the solution worked for me ^.^
