### ISSUE TITLE
qiskit package support

### ISSUE THREAD

**Issue by TheMagicNacho** [chaquo/chaquopy#108]
I'm having issues where the application continues to crash once the python script is called.
I think the reason is becaue we need required package support for qiskit.
If I try to build using qiskit instead of qiskit_terra the whole build will fail.

##Here is the import script which I am calling:
```
from qiskit import IBMQ
import qiskit_tera as qiskit
import math
```

##Packages used:
```
            pip {
                install "numpy"
                install "qiskit_terra==0.7.1"
                //install "qiskit==0.8.0" //ideally I want to use this package, but this will not even build
            }
```
##Here is the debugging log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.quantum_dice_mobile, PID: 22411
    com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/android_asset/chaquopy/requirements-common.zip/qiskit/qasm/libs'
        at <python>.qiskit.qasm._qasmlexer.<module>(_qasmlexer.py:24)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qiskit.qasm._qasmparser.<module>(_qasmparser.py:20)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qiskit.qasm._qasm.<module>(_qasm.py:12)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qiskit.qasm.<module>(__init__.py:15)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qiskit.circuit.quantumcircuit.<module>(quantumcircuit.py:20)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qiskit.circuit.<module>(__init__.py:9)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qiskit.<module>(__init__.py:23)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
E/AndroidRuntime:     at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.qengine.<module>(qengine.py:9)
        at <python>.java.android.importer.load_module_impl(importer.py:460)
        at <python>.java.android.importer.load_module(importer.py:378)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
        at <python>.importlib.import_module(__init__.py:126)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.quantum_dice_mobile.MainActivity$onCreate$1.onClick(MainActivity.kt:46)
        at android.view.View.performClick(View.java:7232)
        at android.view.View.performClickInternal(View.java:7209)
        at android.view.View.access$3300(View.java:797)
        at android.view.View$PerformClick.run(View.java:27572)
        at android.os.Handler.handleCallback(Handler.java:878)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
```

**Comment by mhsmith** [comment]
Looks like this package is finding its resource files in an unusual way. We'll fix this in the next version of Chaquopy. Unfortunately I can't suggest a workaround at the moment.

**Comment by mhsmith** [comment]
Please try a pre-release build of Chaquopy by editing your app's top-level `build.gradle` file as follows:

* Change `https://chaquo.com/maven` to `https://chaquo.com/maven-test`.
* Change the version number of `com.chaquo.python` to `6.2.2`.

Also add the following line to the `python` block of the app-level `build.gradle`:

```
extractPackages "qiskit"
```

Finally, you'll need to add the following workaround before any `qiskit` import statements:

```
from concurrent import futures
futures.ProcessPoolExecutor = futures.ThreadPoolExecutor
```

With those changes, the line `from qiskit import IBMQ` completes successfully. However, there doesn't appear to be any package called `qsikit_tera` or `qsikit_terra`, so I'm not sure what you were trying to do there.

Please give this a try and let me know how you get on.

**Comment by TheMagicNacho** [comment]
Following the steps will allow the application to build.
However, when I press the button which calls the Qiskit python script, the application crashes.

**Import Section of Python Script**

```
from concurrent import futures
futures.ProcessPoolExecutor = futures.ThreadPoolExecutor

import qiskit
from qiskit import IBMQ
import math
```

**Debug Output-after clicking call button**
```
W/tum_dice_mobile: type=1400 audit(0.0:11564): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/files/chaquopy/bootstrap-native/arm64-v8a/java/chaquopy.so" dev="sda35" ino=3473477 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
W/tum_dice_mobile: type=1400 audit(0.0:11565): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/files/chaquopy/bootstrap-native/arm64-v8a/select.so" dev="sda35" ino=3473485 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
W/tum_dice_mobile: type=1400 audit(0.0:11566): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/files/chaquopy/bootstrap-native/arm64-v8a/_ctypes.so" dev="sda35" ino=3473486 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
W/tum_dice_mobil: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (greylist, JNI, allowed)
W/tum_dice_mobil: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (greylist, JNI, allowed)
W/tum_dice_mobile: type=1400 audit(0.0:11567): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/cache/chaquopy/AssetFinder/stdlib-arm64-v8a.zip/pyexpat.so" dev="sda35" ino=3473491 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
W/tum_dice_mobile: type=1400 audit(0.0:11568): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/cache/chaquopy/AssetFinder/stdlib-arm64-v8a.zip/_socket.so" dev="sda35" ino=3473492 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
W/tum_dice_mobile: type=1400 audit(0.0:11569): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/cache/chaquopy/AssetFinder/stdlib-arm64-v8a.zip/_hashlib.so" dev="sda35" ino=3473493 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
W/tum_dice_mobile: type=1400 audit(0.0:11570): avc: granted { execute } for path="/data/data/com.run.quantum_dice_mobile/cache/chaquopy/AssetFinder/stdlib-arm64-v8a.zip/_multiprocessing.so" dev="sda35" ino=3473496 scontext=u:r:untrusted_app_27:s0:c181,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c181,c256,c512,c768 tclass=file
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.run.quantum_dice_mobile, PID: 8954
    com.chaquo.python.PyException: ModuleNotFoundError: No module named 'qiskit'
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.java._vendor.six.reraise(six.py:686)
        at <python>.java.chaquopy.import_override(import.pxi:59)
        at <python>.qengine.<module>(qengine.py:4)
        at <python>.java.android.importer.load_module_impl(importer.py:458)
        at <python>.java.android.importer.load_module(importer.py:376)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
        at <python>.importlib.import_module(__init__.py:126)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.run.quantum_dice_mobile.MainActivity$onCreate$2.onClick(MainActivity.kt:94)
        at android.view.View.performClick(View.java:7251)
        at android.view.View.performClickInternal(View.java:7228)
        at android.view.View.access$3500(View.java:802)
        at android.view.View$PerformClick.run(View.java:27843)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7116)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
I/Process: Sending signal. PID: 8954 SIG: 9
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'
```

**Comment by mhsmith** [comment]
Have you changed the `pip` block in your `build.gradle`, or is it the same as in your original post, with `install "qiskit_terra==0.7.1"`?

**Comment by TheMagicNacho** [comment]
The above comment is if I do not include qiskit at all within the pip block.

If I use the pip install block:
```
        python {
            extractPackages "qiskit"
            pip {
                install "numpy"
                install "qiskit"
            }
            buildPython "/home/admin/anaconda3/bin/python"
        }
```
The whole application will not build.

**Run Task Build Error**
```
org.gradle.api.GradleException: buildPython failed (org.gradle.process.internal.ExecException: Process 'command '/home/admin/anaconda3/bin/python'' finished with non-zero exit value 1). For full details, open the 'Build' window and switch to text mode with the 'Toggle view' button on the left.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at com.chaquo.python.PythonPlugin.execBuildPython(PythonPlugin.groovy:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:78)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:414)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:340)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at com.chaquo.python.PythonPlugin$_createReqsTask_closure12$_closure31.doCall(PythonPlugin.groovy:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:647)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:620)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
	at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
	at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
	at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
	at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
	at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
	at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
	at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

**Android Gradle Plugin Error:**
```
Failed to install scikit-learn>=0.20.0 from https://files.pythonhosted.org/packages/57/5c/133b464c8d0be7ac8c9414b6ff2ae848808a35ce03b146fc2c43777e51f9/scikit-learn-0.21.2.tar.gz (from qiskit-aqua==0.5.1->qiskit).
```


I'm not sure if this helps you at all, but here's a link to the documentation:  https://qiskit.org/documentation/install.html

**Comment by mhsmith** [comment]
Try using the requirement `qiskit_terra==0.7.1` which you were using before: I believe that is sufficient to provide the `IBMQ` import.

**Comment by mhsmith** [comment]
Instead of `qiskit`, try using `qiskit_terra==0.7.1` as in your original post. I think that will be enough to provide the `IBMQ` import.

**Comment by TheMagicNacho** [comment]
After a little bit of effort I found using a requirements specifier with qiskit got everything to work properly.
For whatever reason qiskit release 0.7.0 works best.

```
        python {
          extractPackages "qiskit"
            pip {
                install "numpy"
                install "qiskit==0.7.0"
            }
            buildPython "/home/admin/anaconda3/bin/python"
        }
```

**Comment by mhsmith** [comment]
If you're using the above pre-release build, please now switch to the released version, 6.3.0:

* Change `https://chaquo.com/maven-test` back to `https://chaquo.com/maven`.
* Change the version number of `com.chaquo.python:gradle` to `6.3.0`.

The pre-release build will be removed in 2 weeks.

**Comment by mhsmith** [comment]
The pre-release build has now been removed: see the previous comment for what to do if you're still using it.

**Comment by TheMagicNacho** [comment]
Hello,
Would you kindly please provide me an updated license key?
After moving off of maven-test, Chaquopy no longer recognizes my key.

Thanks for everything.

Very Respectfully,
Justin
