### ISSUE TITLE
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by WarmYunyang** [chaquo/chaquopy#1086]
Why is an error reported when Python code does not introduce tkiner
bug：
FATAL EXCEPTION: Thread-7
                 Process: com.example.projectplan, PID: 22740
                 com.chaquo.python.PyException: ModuleNotFoundError: No module named 'tkinter'
                 	at <python>.java.chaquopy.import_override(import.pxi:20)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.biosppy.inter_plotting.ecg.<module>(ecg.py:20)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.biosppy.inter_plotting.<module>(__init__.py:18)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.biosppy.signals.acc.<module>(acc.py:28)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.biosppy.signals.<module>(__init__.py:23)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.biosppy.<module>(__init__.py:19)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.pyhrv.hrv.<module>(hrv.py:41)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.pyhrv.<module>(__init__.py:36)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.udFunctions.<module>(udFunctions.py:3)
                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                 	at <python>.myfile.<module>(myfile.py:3)
                 	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                 	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                 	at <python>.java.android.importer.exec_module(importer.py:554)
                 	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                 	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                 	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                 	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                 	at <python>.importlib.import_module(__init__.py:127)
                 	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                 	at com.chaquo.python.Python.getModuleNative(Native Method)
                 	at com.chaquo.python.Python.getModule(Python.java:84)
                 	at com.example.projectplan.MainActivity2$9.run(MainActivity2.java:370)

Python Version - 3.9.6
use PythonFile import package.
1、myfile.py
import numpy as np
from scipy.signal import butter, convolve, find_peaks,filtfilt
import udFunctions
import pyhrv
import math

2、udFunctions.py
import numpy as np
import random
import pyhrv
import math

build.gradle：
plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    compileSdkVersion 31

    defaultConfig {
        applicationId "com.example.projectplan"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        python {
            pip {
                install "scipy"
                install "numpy"
                install "pyhrv"
            }
        }

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

        sourceSets {
            main {
                python.srcDir "src/main/python"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

build.gradle：
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.2.2"
        classpath "com.chaquo.python:gradle:14.0.2"
    }
}

The tkiner package was not introduced and an error was reported. What is the reason for this?

**Comment by mhsmith** [comment]
See #1023, and in future please search for existing issues before creating new ones.
