### ISSUE TITLE
Google Generative AI newer version are not available.

### ISSUE THREAD

**Issue by Thejas775** [chaquo/chaquopy#1097]
I was trying to install the google-generativeai. It installed successfully but it only had two versions 0.1.0rc1 and 0.1.0rc2 only, which are old and doesn't support the newer classes in it. The google.generativeai.GenerativeModel() isn't present in it which is compulsorily required for new things. Hoping you add new versions soon. Thanks.

**Comment by mhsmith** [comment]
The current version of this package requires Python 3.9 or newer. You can change your app's Python version as shown in the [documentation](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

**Comment by Thejas775** [comment]
> The current version of this package requires Python 3.9 or newer. You can change your app's Python version as shown in the [documentation](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

We are using 3.9 still it's not working

**Comment by mhsmith** [comment]
If you still need help, please post the requested information, and I'll reopen the issue.

**Comment by siyengar04** [comment]
I have the same issue, here's my logcat output:
`FATAL EXCEPTION: Thread-2
                                                                                                    Process: com.chaquo.python.console, PID: 31654
                                                                                                    com.chaquo.python.PyException: ModuleNotFoundError: No module named 'google'
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:20)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.main.<module>(main.py:3)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                                                                                                    	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:634)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.chaquo.python.console.MainActivity$Task.run(MainActivity.java:115)
                                                                                                    	at com.chaquo.python.utils.ConsoleActivity$Task.lambda$start$0$com-chaquo-python-utils-ConsoleActivity$Task(ConsoleActivity.java:351)
                                                                                                    	at com.chaquo.python.utils.ConsoleActivity$Task$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`
                                                                                                    	builds fine, just crashes at runtime

**Comment by mhsmith** [comment]
Did you install the package into your app as described in the [documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements)?

If so, please post the following:

* The `chaquopy` or `python` section of your build.gradle file
* The full build log (Build > Rebuild Project in Android Studio)
* The code in your app that imports the package
