### ISSUE TITLE
Build failed and Cmake Error when try to install ultralytics

### ISSUE THREAD

**Issue by rovedashcam** [chaquo/chaquopy#1102]
> Process 'command '/Users/cdp/AndroidStudioProjects/chaquopy-matplotlib/app/build/python/env/debug/bin/python'' finished with non-zero exit value 1 
I am trying to read python code using Android kotlin code i am able to read simple sum code but  some code which is read based on library so i am unable to read it 

```
import json
import pandas as pd
from ultralytics import YOLO
model = YOLO("file:///android_asset/YoloV8_model.pt")
def detectOCR(imagePath):
    try:
        results = model(imagePath)
        df = pd.DataFrame(results[0].boxes.data)
        df.sort_values(by=[0], inplace=True)
        df.reset_index(inplace=True, drop=True)

        output = ""
        kwh = False
        names = results[0].names

        for i in range(len(df)):
            if names[int(df[5][i])] == "kwh":
                kwh = True
                continue
            output += names[int(df[5][i])]
        if kwh:
            output += " kwh"
        return json.dumps({"status": "success", "msg": "successfully processed", "result": output})
    except:
        return "error"
```
This is python code for this we need install ultralytics and pandas 
both library installed   i install like  using build.gradle file .
```
 python {
            version '3.8'
            pip {
              //  install "matplotlib"
                install "pandas"
          //      install "torch"
        //       install "YOLO"
                install "ultralytics"
            }
        }
```        
please suggest me where i am doing wrong and what i am doing wrong .

Thanks

**Comment by mhsmith** [comment]
The error is:

`ERROR: Failed to install opencv-python>=4.6.0 from https://files.pythonhosted.org/packages/c0/52/9fe76a56e01078a612812b40764a7b138f528b503f7653996c6cfadfa8ec/opencv-python-4.8.1.78.tar.gz#sha256=cc7adbbcd1112877a39274106cb2752e04984bc01a031162952e97450d6117f6 (from ultralytics).`

The newest version of ultralytics which is compatible with our current `opencv` and `numpy` packages is:

                install "ultralytics==8.0.16"
                install "seaborn==0.12.2"

To be notified when we upgrade opencv, please subscribe to #620.

**Comment by rovedashcam** [comment]
Thanks @mhsmith  for help me and i am able to build code  using your solution but when  run try to  read  above python code using kotlin android  i am getting below exception :


com.chaquo.python.PyException: ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logged at level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

can you please suggest me what i am doing wrong .
 Thanks

**Comment by mhsmith** [comment]
It may not be related to this error, but the only obvious thing I can see wrong with the code is the `android_asset` syntax, which probably won't work in this context. To include data files in your app, follow [these instructions](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

If that doesn't help, please post the full stack trace of the exception.

**Comment by rovedashcam** [comment]
Again Thanks for Help me .
so you mean you telling model = YOLO("file:///android_asset/YoloV8_model.pt" this code is wrong its not reading from correct path ?
i kept one file which is required to execute python code [YoloV8_model.pt] can you please tell me where we should and how we should read the file .
here is full stack trace:

FATAL EXCEPTION: main
                                                                                                    Process: com.chaquo.myapplication, PID: 12423
                                                                                                    com.chaquo.python.PyException: ImportError: Failed to initialize: Bad git executable.
                                                                                                    The git executable must be specified in one of the following ways:
                                                                                                        - be included in your $PATH
                                                                                                        - be set via $GIT_PYTHON_GIT_EXECUTABLE
                                                                                                        - explicitly set via git.refresh()
                                                                                                    
                                                                                                    All git commands will error until this is rectified.
                                                                                                    
                                                                                                    This initial message can be silenced or aggravated in the future by setting the
                                                                                                    $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
                                                                                                        - quiet|q|silence|s|silent|none|n|0: for no message or exception
                                                                                                        - warn|w|warning|log|l|1: for a warning message (logged at level CRITICAL, displayed by default)
                                                                                                        - error|e|exception|raise|r|2: for a raised exception
                                                                                                    
                                                                                                    Example:
                                                                                                        export GIT_PYTHON_REFRESH=quiet
                                                                                                    
                                                                                                    	at <python>.git.<module>(__init__.py:142)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.yolo.utils.<module>(__init__.py:17)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.nn.autobackend.<module>(autobackend.py:15)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.yolo.engine.predictor.<module>(predictor.py:34)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.yolo.v8.classify.predict.<module>(predict.py:5)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.yolo.v8.classify.<module>(__init__.py:3)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.yolo.v8.<module>(__init__.py:3)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.yolo.<module>(__init__.py:3)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ultralytics.<module>(__init__.py:5)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.ocr_detect.<module>(ocr_detect.py:3)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                                                                                                    	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:634)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:721)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.chaquo.myapplication.MainActivity.addTwoNumbersInPython(MainActivity.kt:69)
                                                                                                    	at com.chaquo.myapplication.MainActivity.onCreate$lambda-0(MainActivity.kt:22)
                                                                                                    	at com.chaquo.myapplication.MainActivity.$r8$lambda$6F8C5vjTenzcRb8zzlQytptsxnY(Unknown Source:0)
                                                                                                    	at com.chaquo.myapplication.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7506)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29334)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-02-29 17:03:55.429 12423-12423 AndroidRuntime          com.chaquo.myapplication             E  

Thanks let me know if any more

**Comment by rovedashcam** [comment]
@mhsmith  above is Log can you please check why this error is coming as git  is working in machine i am using mac machine but when  execute python code i am getting above error it mention its error with chaquo com.chaquo.python.PyException: ImportError: Failed to initialize: Bad git executable.
can you please help me in this .

Thanks

**Comment by mhsmith** [comment]
According to the message, you can disable the exception by setting the environment variable `GIT_PYTHON_REFRESH=quiet`. You can do this within your app using `os.environ` before importing ultralytics.

Neither environment variables nor Git executables on your Mac will make any difference, as your app has no access to them.

> i kept one file which is required to execute python code [YoloV8_model.pt] can you please tell me where we should and how we should read the file .

I've already linked you to [these instructions](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

**Comment by rovedashcam** [comment]
Thank @mhsmith 
That error is gone after applying this code 
```

import json
import pandas as pd
import os
from ultralytics import YOLO
os.environ['GIT_PYTHON_REFRESH'] = 'quiet'
from os.path import dirname, join
filename = join(dirname(__file__), "/Users/cdp/Desktop/YoloV8_model.pt")


# model = YOLO("/Users/cdp/Desktop/YoloV8_model.pt")
def detectOCR(imagePath):
    try:
        results = model(imagePath)
        df = pd.DataFrame(results[0].boxes.data)
        df.sort_values(by=[0], inplace=True)
        df.reset_index(inplace=True, drop=True)

        output = ""
        kwh = False
        names = results[0].names

        for i in range(len(df)):
            if names[int(df[5][i])] == "kwh":
                kwh = True
                continue
            output += names[int(df[5][i])]
        if kwh:
            output += " kwh"
        return json.dumps({"status": "success", "msg": "successfully processed", "result": output})
    except:
        return "error"

```
but after that i am getting below Error :


  Process: com.chaquo.myapplication, PID: 18576
                                                                                                    com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: '/tmp'
                                                                                                    	at <python>.pathlib.mkdir(pathlib.py:1288)
                                                                                                    	at <python>.pathlib.mkdir(pathlib.py:1292)
                                                                                                    	at <python>.ultralytics.yolo.utils.get_user_config_dir(__init__.py:284)
                                                                                                    	at <python>.ultralytics.yolo.utils.<module>(__init__.py:289)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.nn.autobackend.<module>(autobackend.py:15)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.yolo.engine.predictor.<module>(predictor.py:34)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.yolo.v8.classify.predict.<module>(predict.py:5)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.yolo.v8.classify.<module>(__init__.py:3)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.yolo.v8.<module>(__init__.py:3)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.yolo.<module>(__init__.py:3)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ultralytics.<module>(__init__.py:5)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ocr_detect.<module>(ocr_detect.py:6)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                                                                                                    	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:554)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:606)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.chaquo.myapplication.MainActivity.addTwoNumbersInPython(MainActivity.kt:69)
                                                                                                    	at com.chaquo.myapplication.MainActivity.onCreate$lambda-0(MainActivity.kt:22)
                                                                                                    	at com.chaquo.myapplication.MainActivity.$r8$lambda$6F8C5vjTenzcRb8zzlQytptsxnY(Unknown Source:0)
                                                                                                    	at com.chaquo.myapplication.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7506)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29334)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
---------------------------- PROCESS ENDED (18576) for package com.chaquo.myapplication ----------------------------


Can you please tell me where i am doing wrong .

Thanks

**Comment by mhsmith** [comment]
It looks like the relevant code is here: 

https://github.com/ultralytics/ultralytics/blob/v8.1.0/ultralytics/utils/__init__.py#L626

You could probably work around this either by creating the directory `Path.home() / ".config"`, or setting the environment varieble `YOLO_CONFIG_DIR`.

Like your previous question, It looks like this would also have been explained by a message appearing in the log. Please try to actually follow the hints in the messages before asking for help. That will allow you to progress much faster.

**Comment by rovedashcam** [comment]
@mhsmith 
I really confused about this i tried to find /tmp directory and gave read and write permission but still i am getting same error i don't what is the issue . i am totally new in this i kept YoloV8_model.pt file in my desktop  and add  path in code .
Here is my updated code :

i```
mport json
import pandas as pd
import os
os.environ['GIT_PYTHON_REFRESH'] = 'quiet'
from ultralytics import  YOLO
# from os.path import dirname, join
#
# filename = join(dirname(__file__), "/Users/cdp/Desktop/YoloV8_model.pt")
zip_file_path = '/Users/cdp/Desktop/YoloV8_model.pt'
target_directory = '/Users/cdp/Desktop'

with os.ZipFile(zip_file_path, 'r') as zip_file:
    zip_file.extractall(target_directory)

model = YOLO("/Users/cdp/Desktop/YoloV8_model.pt")
def detectOCR(imagePath):
    try:
        results = model(imagePath)
        df = pd.DataFrame(results[0].boxes.data)
        df.sort_values(by=[0], inplace=True)
        df.reset_index(inplace=True, drop=True)

        output = ""
        kwh = False
        names = results[0].names

        for i in range(len(df)):
            if names[int(df[5][i])] == "kwh":
                kwh = True
                continue
            output += names[int(df[5][i])]
        if kwh:
            output += " kwh"
        return json.dumps({"status": "success", "msg": "successfully processed", "result": output})
    except:
        return "error"

```

But same error it will really help full if will give me eject solution.

Thanks

**Comment by mhsmith** [comment]
You still haven't done either of the things I recommended in my previous comment, so of course you're still getting the same error.

As for the references to `/Users/cdp` – you cannot access the filesystem of your development machine from inside an Android app, not even in an emulator. Put the data file in the same directory as your Python source code, then follow [these instructions](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

**Comment by mhsmith** [comment]
The rest of the conversation is unrelated to the original question, so I've moved it to #1106. Please continue there.
