### ISSUE TITLE
ERROR: Failed to install PyGObject>=3.36

### ISSUE THREAD

**Issue by yefl2064** [chaquo/chaquopy#1112]
Collecting PyGObject>=3.36; platform_system != "Windows"
  Using cached pygobject-3.48.1.tar.gz (714 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/bin/python /Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/tmpv59kogr1
         cwd: /private/var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/pip-install-8xgf96x3/PyGObject
    Complete output (35 lines):
    Traceback (most recent call last):
      File "/Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/Users/yefl/Downloads/chaquopy-15.0.1/demo/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/pip-build-env-uk9kexvh/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 985, in wrapper
        return func(*args, **kwargs)
      File "/private/var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/pip-build-env-uk9kexvh/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 1038, in build_wheel
        with _project(config_settings) as project:
      File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/private/var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/pip-build-env-uk9kexvh/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 912, in _project
        yield Project(source_dir, build_dir, meson_args, editable_verbose)
      File "/private/var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/pip-build-env-uk9kexvh/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 635, in __init__
        self._meson = _get_meson_command(pyproject_config.get('meson'))
      File "/private/var/folders/6g/k8rxky554fl__kkt95y92jvr0000gn/T/pip-build-env-uk9kexvh/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 947, in _get_meson_command
        meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
      File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'meson'
    ----------------------------------------
ERROR: Failed to install PyGObject>=3.36; platform_system != "Windows" from https://files.pythonhosted.org/packages/a9/73/ff037ab99c40522ed53c759baa0e3969d03933d3650f02e50ee0cb639666/pygobject-3.48.1.tar.gz#sha256=2c4cd7c805ee9e727904172423a7519338017fd7e122b62218ac211627436875 (from inkex).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
Unfortunately it looks like `inkex` requires GTK, which won't work on Android. It might be possible to use some of its functions without PyGObject, but you'd have to ask the Inkscape developers about that.

If anyone else needs PyGObject, let us know by clicking the thumbs-up button above, and post a comment explaining what you're trying to do.
