### ISSUE TITLE
pip install imufusion running error

### ISSUE THREAD

**Issue by Nicely123** [chaquo/chaquopy#1117]
#### Chaquopy version

15.0.1
#### Devices or emulators where the issue happens

xiaomi13
#### Relevant parts of your code

```
pip {
            install("matplotlib")
            install("numpy")
            install("imufusion")
        }
```
#### Describe your issue

I tried using the latest version of numpy and I tried imufusion 1.1.0 and 1.2.0 and the latest versions to no avail
```
> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-13.1, https://pypi.tuna.tsinghua.edu.cn/simple
Collecting matplotlib
  Using cached https://chaquo.com/pypi-13.1/matplotlib/matplotlib-3.6.0-0-cp38-cp38-android_21_arm64_v8a.whl (6.9 MB)
Collecting numpy
  Using cached https://chaquo.com/pypi-13.1/numpy/numpy-1.19.5-0-cp38-cp38-android_21_arm64_v8a.whl (3.8 MB)
Collecting imufusion
  Using cached imufusion-1.2.4.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\AS-test\CalibrationTool\app\build\python\env\debug\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-wtf9w1hq\\imufusion\\setup.py'"'"'; __file__='"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-wtf9w1hq\\imufusion\\setup.py'"'"';import chaquopy_monkey; chaquopy_monkey.disable_native();f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base 'C:\Users\lenovo\AppData\Local\Temp\pip-pip-egg-info-x99b6s94'
         cwd: C:\Users\lenovo\AppData\Local\Temp\pip-install-wtf9w1hq\imufusion\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lenovo\AppData\Local\Temp\pip-install-wtf9w1hq\imufusion\setup.py", line 1, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ERROR: Command errored out with exit status 1:

    ----------------------------------------
ERROR: Failed to install imufusion from https://files.pythonhosted.org/packages/b9/92/d6a87d967ca8361d89eb62c06d601da2796664311333fff2e2ea065feffb/imufusion-1.2.4.tar.gz#sha256=c1e2bd32529eb8e3fadaa437ece80252494a3ed9dca7111855a1df5b067d3a0b.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install imufusion from https://files.pythonhosted.org/packages/b9/92/d6a87d967ca8361d89eb62c06d601da2796664311333fff2e2ea065feffb/imufusion-1.2.4.tar.gz#sha256=c1e2bd32529eb8e3fadaa437ece80252494a3ed9dca7111855a1df5b067d3a0b.

Chaquopy: Exit status 1
```

**Comment by mhsmith** [comment]
This package contains native components, so it would have to be built into an Android wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

**Comment by mhsmith** [comment]
It's been over a year, and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
