### ISSUE TITLE
Extension modules fail to load on API level 23

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#1139]
This is a new problem with Chaquopy 15.0.1. It isn't present in 14.0.2, and the reason it was missed in 15.0.1 is because we no longer do pre-release testing on API level 23 since we've abandoned TensorFlow.

It affects both x86_64 and ARM64, and both Python 3.8 and 3.11. But it only happens on API level 23, not 21, 22 or 24.

The demo app starts normally, but when you run the Python unit tests it crashes as follows:

```
 FATAL EXCEPTION: Thread-462
                                 Process: com.chaquo.python.demo3, PID: 9901
                                 com.chaquo.python.PyException: ImportError: dlopen failed: library "libpython3.8.so" not found
                                 	at <python>.java.android.importer.extension_create_module_override(importer.py:734)
                                 	at <python>.java.chaquopy.import_override(import.pxi:20)
                                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                                 	at <python>.socket.<module>(socket.py:49)
                                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                                 	at <python>.asyncio.base_events.<module>(base_events.py:23)
                                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                                 	at <python>.asyncio.<module>(__init__.py:8)
                                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                                 	at <python>.unittest.async_case.<module>(async_case.py:1)
                                 	at <python>.java.chaquopy.import_override(import.pxi:60)
                                 	at <python>.unittest.<module>(__init__.py:60)
                                 	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                                 	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                                 	at <python>.java.android.importer.exec_module(importer.py:335)
                                 	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                                 	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                 	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                 	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                 	at <python>.importlib.import_module(__init__.py:127)
                                 	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                 	at com.chaquo.python.Python.getModuleNative(Native Method)
                                 	at com.chaquo.python.Python.getModule(Python.java:84)
                                 	at com.chaquo.python.utils.PythonTestActivity$Task.run(PythonTestActivity.java:27)
                                 	at com.chaquo.python.utils.ConsoleActivity$Task.lambda$start$0$com-chaquo-python-utils-ConsoleActivity$Task(ConsoleActivity.java:351)
```

**Comment by mhsmith** [comment]
If we desupport API level 23 in the next Chaquopy version (#718), then we could completely avoid looking into this.
