### ISSUE TITLE
Could not use instagrapi

### ISSUE THREAD

**Issue by spapapan** [chaquo/chaquopy#1213]
classpath "com.chaquo.python:gradle:15.0.1"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {
            version "3.10"

            pip {
                options "--no-deps"
                install "-r", "requirements.txt" 
            }
        }

In the requirements.txt:

     Pillow==10.4.0

ERROR: Failed building wheel for Pillow
Could not build wheels for Pillow which use PEP 517 and cannot be installed directly

 Any idea how I can install Pillow or if anyone has any pre-built wheel for Pillow?

 
More logs:

> Building wheels for collected packages: Pillow
>   Building wheel for Pillow (setup.py): started
>   Building wheel for Pillow (setup.py): finished with status 'error'
>   ERROR: Command errored out with exit status 1:
>    command: 'C:\******\******\env\debug\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\******\\******\\******\\*****\\*****\\Pillow\\setup.py'"'"'; __file__='"'"'C:\\******\\******\\******\\*****\\*****\\Pillow\\setup.py'"'"';import chaquopy_monkey; chaquopy_monkey.disable_native();f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\\******\\******\\Temp\\pip-wheel-******'
>        cwd: C:\\******\\******\\******\\*****\\*****\\Pillow\\
>   Complete output (165 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-cpython-310
>   creating build\lib.win-amd64-cpython-310\PIL
>   copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-310\PIL
>   copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-310\PIL
>   ...
>   ...
>   ...

---

EDIT: When I am using the version 9.2.0 I can build successfully my project but when I run my code, I get this error:

> com.chaquo.python.PyException: Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1

**Comment by mhsmith** [comment]
> Any idea how I can install Pillow or if anyone has any pre-built wheel for Pillow?

As I guess you've already worked out, you can only use certain versions of Pillow. See [here](https://chaquo.com/pypi-13.1/pillow/) for a list: "cp" indicates the compatible Python version.

> When I am using the version 9.2.0 I can build successfully my project but when I run my code, I get this error:
> 
> > com.chaquo.python.PyException: Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1

Please post the full stack trace.

**Comment by spapapan** [comment]
I tried also with the latest version 10.1.0 but I still get the same error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.imanager/com.app.imanager.main.MainActivity}: com.chaquo.python.PyException: Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

Caused by: com.chaquo.python.PyException: Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1
at <python>.instagrapi.mixins.clip.<module>(clip.py:18)
at <python>.java.chaquopy.import_override(import.pxi:26)
at <python>.instagrapi.<module>(__init__.py:12)
at <python>.java.chaquopy.import_override(import.pxi:26)
at <python>.instagram_client.<module>(instagram_client.py:3)
at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:488)
at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:994)
at <python>.java.android.importer.exec_module(importer.py:634)
at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:935)
at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:1331)
at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1360)
at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1387)
at <python>.importlib.import_module(__init__.py:90)
at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
at com.chaquo.python.Python.getModuleNative(Native Method)
at com.chaquo.python.Python.getModule(Python.java:84)
at com.app.imanager.main.PythonIGClient.<init>(PythonIGClient.java:24)
at com.app.imanager.main.MainActivity.init(MainActivity.java:210)
at com.app.imanager.main.MainActivity.onCreate(MainActivity.java:176)
at android.app.Activity.performCreate(Activity.java:8595)
at android.app.Activity.performCreate(Activity.java:8573)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)

**Comment by mhsmith** [comment]
The current version of `instagrapi` depends on a number of other things we don't support, e.g. pinned versions of `pydantic` and `pycryptodomex`. So it's not clear how you're installing it. Please post your requirements.txt file.

**Comment by spapapan** [comment]
requirements.txt file

> Pillow==10.1.0
> instagrapi==2.0.0
> pycryptodomex 
> requests
> urllib3
> idna
> certifi 
> pydantic==1.10.9
> typing_extensions

**Comment by mhsmith** [comment]
That requirements.txt works for me on Python 3.12, and if I change the Pillow version to 9.2.0 I can also install it on Python 3.10. However, they both give this non-fatal message, which may cause you problems in the future:

`ERROR: instagrapi 2.0.0 has requirement pycryptodomex==3.18.0, but you'll have pycryptodomex 3.9.4 which is incompatible.`

In both cases, I can then `import instagrapi` with no problems.

Are you still receiving the same "You don't have PIL installed " error as before? If so, are you sure you've actually rebuilt and reinstalled your app after changing it?

**Comment by mhsmith** [comment]
You could also try importing `PIL` before importing `instagrapi`, and seeing if that gives a different error.

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information, and I'll reopen the issue.
