### ISSUE TITLE
Module not found when running Python code with runpy.run_path

### ISSUE THREAD

**Issue by deva666** [chaquo/chaquopy#1219]
#### Chaquopy version
15.0.1

#### Devices or emulators where the issue happens
OnePlus 7 Pro

#### Relevant parts of your code
```
import runpy

def run_code(path):
    runpy.run_path(path)
```
#### Describe your issue
I have a main.py file and in the same folder another one, utils.py
I run the main.py file with the above run_path code.
If I try to import anything from utils.py file I get an error
```
Traceback (most recent call last):
   File "/data/data/files/chaquopy/AssetFinder/app/module_runner.py", line 25, in run_user_module
     runpy.run_path(file)
   File "stdlib/runpy.py", line 265, in run_path
   File "stdlib/runpy.py", line 97, in _run_module_code
   File "stdlib/runpy.py", line 87, in _run_code
   File "/storage/emulated/0/Documents/test6/main.py", line 2, in <module>
     import utils
   File "import.pxi", line 60, in java.chaquopy.import_override
  File "import.pxi", line 20, in java.chaquopy.import_override
ModuleNotFoundError: No module named 'utils'
```
The same code on the desktop works, ie. import can recognize other local Python files

**Comment by mhsmith** [comment]
If you want to be able to run `import utils`, then the directory containing utils.py must be added to `sys.path`.

**Comment by deva666** [comment]
Works, thank you.
