### ISSUE TITLE
OSError: Can't get source for <function swish_jit at 0x72d59118b0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

### ISSUE THREAD

**Issue by mfilg** [chaquo/chaquopy#1222]
I´m trying to run some python code but the error `OSError: Can't get source for <function swish_jit at 0x72d59118b0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.` keeps showing.

The code is supposed to work outside this enviroment. I messed around a lot with the requirements just so the build didn´t fail.

#### Logcat

```
FATAL EXCEPTION: main
Process: buffml.com.moleScanner, PID: 4709
com.chaquo.python.PyException: OSError: Can't get source for <function swish_jit at 0x72793da8b0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
	at <python>.torch._utils_internal.get_source_lines_and_file(_utils_internal.py:62)
	at <python>.torch.jit.frontend.get_jit_def(frontend.py:240)
	at <python>.torch.jit._script.script(_script.py:986)
	at <python>.timm.models.layers.activations_jit.<module>(activations_jit.py:19)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.layers.create_act.<module>(create_act.py:7)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.layers.evo_norm.<module>(evo_norm.py:32)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.layers.create_norm_act.<module>(create_norm_act.py:12)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.layers.conv_bn_act.<module>(conv_bn_act.py:9)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.layers.<module>(__init__.py:10)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.fx_features.<module>(fx_features.py:18)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.helpers.<module>(helpers.py:21)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.beit.<module>(beit.py:50)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.models.<module>(__init__.py:1)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.timm.<module>(__init__.py:2)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.segmentation_models_pytorch.encoders.<module>(__init__.py:1)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.segmentation_models_pytorch.<module>(__init__.py:2)
	at <python>.java.chaquopy.import_override(import.pxi:26)
	at <python>.segmentation.<module>(segmentation.py:6)
	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
	at <python>.java.android.importer.exec_module(importer.py:634)
	at <python>.java.android.importer.exec_module(importer.py:721)
	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
	at <python>.importlib.import_module(__init__.py:127)
	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
	at com.chaquo.python.Python.getModuleNative(Native Method)
	at com.chaquo.python.Python.getModule(Python.java:84)
	at buffml.com.moleScanner.ScannerFragment.onCreateView(ScannerFragment.kt:74)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
```

#### Dependencies

```
pip {
                install "pydantic<2"
                install "transformers==4.15.0"
                options "--no-binary", "timm==1.0.7"
                install "pyinstaller==4.5.1"
                install "urllib3==1.25.4"
                install "-r", "requirements.txt"
            }
```
Inside requirements.txt
```
adabelief_pytorch==0.2.1
albumentations<1.4.0
matplotlib<3.7.5
numpy
opencv_python
opencv_python_headless==4.10.0.84
pillow==9.2.0
scikit_learn<1.3.2
scipy<1.10.1
segmentation-models-pytorch<0.3.3
scikit-image<0.21.0
scikit-learn<1.3.2
torch<2.3.1
torchvision
tqdm==4.66.4
monai<1.2.0
setuptools_rust
transformers==4.15.0
tokenizers==0.10.3 
```
**The code I´m trying to run**

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import torch
import albumentations as albu
import segmentation_models_pytorch as smp
import torchvision.transforms as T
import cv2
import sys
import matplotlib.pyplot as plt
from skimage import measure

img = sys.argv[1]
color = sys.argv[2]     # 'r', 'b', 'g', 'y', 'm'
out_filename = img.split(".")[0] + '.pdf'

ACTIVATION = 'sigmoid'
DEVICE = 'cpu'
MODEL = smp.Unet              # smp.Unet OR smp.FPN OR ...
ENCODER = 'densenet161'
ENCODER_WEIGHTS = 'imagenet'
CHECKPOINT = 'bestModel.pt'

def get_validation_augmentation(height, width):
    test_transform = [
        albu.Resize(height, width, interpolation=1, always_apply=True)
    ]
    return albu.Compose(test_transform)

def to_tensor(x, **kwargs):
    return x.transpose(2, 0, 1).astype('float32')

def get_preprocessing(preprocessing_fn):

    _transform = [
        albu.Lambda(image=preprocessing_fn),
        albu.Lambda(image=to_tensor, mask=to_tensor),
    ]
    return albu.Compose(_transform)

def run():
    img = cv2.imread(img)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    height = img.shape[0]
    width = img.shape[1]

    image = get_validation_augmentation(512, 576)(image=img)['image']
    image = get_preprocessing(None)(image=image)['image']

    model = MODEL(
        encoder_name=ENCODER,
        encoder_weights=ENCODER_WEIGHTS,
        activation=ACTIVATION,
    )
    model = model.to(DEVICE)
    bestCheckpoint = torch.load(CHECKPOINT, map_location=torch.device(DEVICE))
    model.load_state_dict(bestCheckpoint)

    image = torch.utils.data.default_convert(image[None])
    image = image.to(DEVICE)
    with torch.no_grad():
        y_pred = model.forward(image)

    transform = T.Resize(size = (height,width))
    segmented = transform(y_pred)
    segmented = segmented.cpu().numpy().squeeze(0).squeeze(0)
    segmented[segmented<0.7] = 0
    segmented[segmented>0] = 1
    (labeled, n) = measure.label(segmented, return_num=True, connectivity=2)

    fig, ax = plt.subplots()
    ax.axis("off")
    ax.imshow(img, cmap=plt.cm.gray)

    contours = measure.find_contours(labeled)
    for contour in contours:
        ax.plot(contour[:, 1], contour[:, 0], color, linewidth=1)

    plt.savefig(out_filename, bbox_inches='tight')
```

**Comment by mhsmith** [comment]
A single `` ` `` doesn't correctly format multiple lines of code. Instead, please use ` ``` ` as shown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). 

To make the source code of a package available at runtime, use the [`extractPackages`](https://chaquo.com/chaquopy/doc/current/android.html#extractpackages) setting.

**Comment by mfilg** [comment]
Thanks, that worked
