### ISSUE TITLE
Build is not getting successful while installing pyramid-arima 

### ISSUE THREAD

**Issue by ANANDAAndroid** [chaquo/chaquopy#1236]
```
  ERROR: Command errored out with exit status 1:
     command: 'C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Scripts\python.exe' 'C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\SENTIE~1\AppData\Local\Temp\tmpfimt3927'
         cwd: C:\Users\SENTIENTGEEKS\AppData\Local\Temp\pip-install-nh3rdwcg\scipy
    Complete output (46 lines):
    Traceback (most recent call last):
      File "C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\AppData\Local\Temp\pip-build-env-t0wwyn4t\overlay\Lib\site-packages\mesonpy\__init__.py", line 1020, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\AppData\Local\Temp\pip-build-env-t0wwyn4t\overlay\Lib\site-packages\mesonpy\__init__.py", line 1073, in build_wheel
        with _project(config_settings) as project:
      File "C:\python\Lib\contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\AppData\Local\Temp\pip-build-env-t0wwyn4t\overlay\Lib\site-packages\mesonpy\__init__.py", line 947, in _project
        yield Project(source_dir, build_dir, meson_args, editable_verbose)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\AppData\Local\Temp\pip-build-env-t0wwyn4t\overlay\Lib\site-packages\mesonpy\__init__.py", line 662, in __init__
        self._meson = _get_meson_command(pyproject_config.get('meson'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\SENTIENTGEEKS\AppData\Local\Temp\pip-build-env-t0wwyn4t\overlay\Lib\site-packages\mesonpy\__init__.py", line 982, in _get_meson_command
        meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\python\Lib\subprocess.py", line 548, in run
        with Popen(*popenargs, **kwargs) as process:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\python\Lib\subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\python\Lib\subprocess.py", line 1538, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Failed to install scipy from https://files.pythonhosted.org/packages/62/11/4d44a1f274e002784e4dbdb81e0ea96d2de2d1045b2132d5af62cc31fd28/scipy-1.14.1.tar.gz#sha256=5a275584e726026a5699459aa72f828a610821006228e841b94275c4a7c08417.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
    ERROR: Command errored out with exit status 1:

Failed to install scipy from https://files.pythonhosted.org/packages/62/11/4d44a1f274e002784e4dbdb81e0ea96d2de2d1045b2132d5af62cc31fd28/scipy-1.14.1.tar.gz#sha256=5a275584e726026a5699459aa72f828a610821006228e841b94275c4a7c08417.

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:\Users\SENTIENTGEEKS\Desktop\Projects\Stocks\app\build\python\env\debug\Scripts\python.exe'' finished with non-zero exit value 1 
```

**Comment by mhsmith** [comment]
`pyramid-arima` has been renamed to `pmdarima` – see #425.

However, this error message appears to be unrelated, and is probably caused by us not having SciPy for Python 3.11 or later (#1237).
