### ISSUE TITLE
SciPy for Python 3.11 or later

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#1237]
We currently only support SciPy for Python 3.8, 3.9 and 3.10. For the available versions, see [the repository](https://chaquo.com/pypi-13.1/scipy/), and to set the Python version of your app, see [these instructions](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

**Comment by rbebb** [comment]
It would be great to have the latest version of scipy for each Python version!

**Comment by Aashishkebab** [comment]
Is this still the case?

**Comment by mhsmith** [comment]
Yes, and it will probably continue to be for at least the next 6 months.

**Comment by Aashishkebab** [comment]
> Yes, and it will probably continue to be for at least the next 6 months.

So if I download the wheel file directly from the link you put (1.8.1 arm64), I always get:

> scipy-1.8.1.whl is not a valid wheel filename.

This is true whether I just use the filename or use the absolute path on my drive, whether I use forward slashes or back slashes, etc.
If I use `scipy==1.8.1` to try to get it that way, it claims to require at least 3.12.

Am I doing something wrong? I am able to get numpy working without any issues.

**Comment by Aashishkebab** [comment]
> > Yes, and it will probably continue to be for at least the next 6 months.
> 
> So if I download the wheel file directly from the link you put (1.8.1 arm64), I always get:
> 
> > scipy-1.8.1.whl is not a valid wheel filename.
> 
> This is true whether I just use the filename or use the absolute path on my drive, whether I use forward slashes or back slashes, etc. If I use `scipy==1.8.1` to try to get it that way, it claims to require at least 3.12.
> 
> Am I doing something wrong? I am able to get numpy working without any issues.

I figured out that I am not supposed to rename the file lol.

But now it goes back to:

> Package 'scipy' requires a different Python: 3.12.4 not in '>=3.8,<3.11'

**Comment by mhsmith** [comment]
Follow the instructions at the top of this page to set your app's Python version to 3.10 or older.

Because of #1295, it may also be necessary to install a corresponding Python version on your build machine, and [configure Chaquopy to use it](https://chaquo.com/chaquopy/doc/current/android.html#buildpython).

**Comment by Aashishkebab** [comment]
> Follow the instructions at the top of this page to set your app's Python version to 3.10 or older.
> 
> Because of #1295, it may also be necessary to install a corresponding Python version on your build machine, and [configure Chaquopy to use it](https://chaquo.com/chaquopy/doc/current/android.html#buildpython).

I am using Python 3.10 in build.gradle. The official Python website no longer has the installer for 3.10, but it doesn't seem to be necessary as it builds successfully and even runs the Python code (if I remove the pip installs).

As I found out, I have to use SciPy 1.4.1. Any of the newer ones in the repository don't work. It still doesn't install, but this time it just gives a generic error "failed to install".

Now, however, I am struggling with numpy using the older version of Python, and this is regardless of the wheel file version I use from the Chaquopy repository.
![image](https://github.com/user-attachments/assets/9de282dc-cd39-48f8-8d04-bc30bec62c20)

I know this is unrelated so I can file a separate issue if you'd like.

**Comment by mhsmith** [comment]
> The official Python website no longer has the installer for 3.10

It still has installers for [3.10.11 and older](https://www.python.org/downloads/). This will probably fix your current problem.

> As I found out, I have to use SciPy 1.4.1

No, we don't have SciPy 1.4.1 for Python 3.10, only [3.8 and 3.9](https://chaquo.com/pypi-13.1/scipy/).

> this time it just gives a generic error "failed to install".

Unfortunately Android Studio doesn't make this obvious, but you can view the full build log by clicking the “Build ... failed” caption at the top of your screenshot. It should look like the "Monitor the build process" image on [this page](https://developer.android.com/studio/run).

Please include the full log in any future questions, using copy and paste, not a screenshot.

**Comment by tejasmankar** [comment]
I am using Python 3.12. Is the below error also caused by the same issue?

`Collecting scipy
  Downloading scipy-1.15.0.tar.gz (59.4 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Admin\Documents\test1\test2\app\build\python\env\debug\Scripts\python.exe' 'C:\Users\Admin\Documents\test1\test2\app\build\python\env\debug\Lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Admin\AppData\Local\Temp\test'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-test\scipy
    Complete output (2 lines):
    
    meson-python: error: meson executable "meson" not found
    ----------------------------------------
ERROR: Failed to install scipy from https://files.pythonhosted.org/packages/d9/7b/2b8ac283cf32465ed08bc20a83d559fe7b174a484781702ba8accea001d6/scipy-1.15.0.tar.gz#sha256=300742e2cc94e36a2880ebe464a1c8b4352a7b0f3e36ec3d2ac006cdbe0219ac (from easyocr).`

This is the task being executed as part of the Gradle build:
`> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-13.1
Collecting easyocr
  Using cached easyocr-1.7.2-py3-none-any.whl (2.9 MB)`
  
  Any solution?

**Comment by tejasmankar** [comment]
I am using Python 3.12. Is the below error also caused by the same issue?

`Collecting scipy
Downloading scipy-1.15.0.tar.gz (59.4 MB)
Installing build dependencies: started
Installing build dependencies: still running...
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Installing backend dependencies: started
Installing backend dependencies: finished with status 'done'
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: 'C:\Users\Admin\Documents\test1\test2\app\build\python\env\debug\Scripts\python.exe' 'C:\Users\Admin\Documents\test1\test2\app\build\python\env\debug\Lib\site-packages\pip_vendor\pep517_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Admin\AppData\Local\Temp\test'
cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-test\scipy
Complete output (2 lines):

meson-python: error: meson executable "meson" not found

ERROR: Failed to install scipy from https://files.pythonhosted.org/packages/d9/7b/2b8ac283cf32465ed08bc20a83d559fe7b174a484781702ba8accea001d6/scipy-1.15.0.tar.gz#sha256=300742e2cc94e36a2880ebe464a1c8b4352a7b0f3e36ec3d2ac006cdbe0219ac (from easyocr).`

This is the task being executed as part of the Gradle build:
Task :app:generateDebugPythonRequirements Chaquopy: Installing for arm64-v8a Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-13.1 Collecting easyocr Using cached easyocr-1.7.2-py3-none-any.whl (2.9 MB)

Any solution?

**Comment by tejasmankar** [comment]
I am using Python 3.10. What could be the reason for this error?

Collecting python-bidi
  Downloading python_bidi-0.6.3.tar.gz (45 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Admin\Documents\test\test\app\build\python\env\debug\Scripts\python.exe' 'C:\Users\Admin\Documents\test\test\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Admin\AppData\Local\Temp\test'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-1ge1bls4\python-bidi
    Complete output (20 lines):
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory C:\Users\Admin\AppData\Local\Temp\pip-modern-metadata-p3ese_eg --interpreter C:\Users\Admin\Documents\test\test\app\build\python\env\debug\Scripts\python.exe`
    Traceback (most recent call last):
      File "C:\Users\Admin\Documents\test\test\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\Users\Admin\Documents\test\test\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\Admin\Documents\test\test\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Admin\AppData\Local\Temp\test\overlay\Lib\site-packages\maturin\__init__.py", line 203, in prepare_metadata_for_build_wheel
        _output = subprocess.check_output(command)
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Failed to install python-bidi from https://files.pythonhosted.org/packages/74/b5/c1684fb8120ad868b43e4b037ac83aafaa70724cdb078d066bae836c31f6/python_bidi-0.6.3.tar.gz#sha256=e12114969001a328aea859f79efc30ab9c15241befb86e07029d8961d97fae36 (from easyocr).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by rbebb** [comment]
Cross-post from : I've been playing around with building 1.9.3 for Python 3.11 because it appears to still have a lot of the files needed to do a setuptools build. It seems to get pretty far, but then it runs into a Fortran error. If people are interested in the patch file and output, I can add those to this thread.

**Comment by MordehayM** [comment]
@mhsmith Will Scipy be updated for 1.13 (python 3.10 or 3.9)?
The use case is for the class ShortTimeFFT. I think there are additional changes, but this is the one I addressed.

**Comment by mhsmith** [comment]
I'm currently focusing on helping packages to release their own Android wheels on PyPI. Unfortunately SciPy has a number of complex dependencies including Meson, BLAS and Fortran, so I wouldn't expect that to be released on PyPI until at least 6 months from now.

Meanwhile, I'm still happy to accept PRs updating Chaquopy's own recipes, though I won't be updating any myself. The PR linked in the previous comment may be a good starting point, though it looks like `ShortTimeFFT` was added in SciPy 1.12.

**Comment by rbebb** [comment]
@MordehayM @mhsmith Once I can address the threads on this PR, I'll have a follow-up PR for SciPy 1.11! Hopefully that'll help us figure out how to get 1.12+ working.

**Comment by rarcher** [comment]
The SciPy versions currently available in the package repository have a known security vulnerability in them:  https://osv.dev/vulnerability/PYSEC-2023-102

**Comment by mhsmith** [comment]
As discussed in https://github.com/scipy/scipy/issues/16235#issuecomment-1625361328, this is not really a security vulnerability.

**Comment by mhsmith** [comment]
I'm now working on adding official Android support to this package (https://github.com/scipy/scipy/pull/24341).

**Comment by mhsmith** [comment]
Unfortunately it looks like this package won't be officially released for Android until next year. Meanwhile, I've uploaded some unofficial wheels for Python 3.13, which you can use by adding this line to the `pip` section of your build.gradle file:
```gradle
options("--extra-index-url", "https://chaquo.com/pypi-upstream/")
```
