### ISSUE TITLE
permission Error 

### ISSUE THREAD

**Issue by arshiacomplus** [chaquo/chaquopy#1281]
#### Chaquopy version
com.chaquo.python:gradle:15.0.1

#### Devices or emulators where the issue happens
All devices

#### Relevant parts of your code

```
file_path = "/storage/emulated/0/Download/wwarpscanner/warp_setting"


try:
    with open(file_path, "r") as f:
        num = f.readlines()
        Cpu_speed = num[0].strip()
        do_you_save = num[1].strip()
        wich_pannel = num[2].strip()
        port_go = num[3].strip()
        ping_range_see = int(num[4].strip())
        timeout_see = int(num[5].strip())
        count_see = int(num[6].strip())
        interval_see = int(num[7].strip())


    if len(num) != 8:
        raise ValueError("Incorrect file format")

except (OSError, ValueError, IndexError) as e:
    print(f"Error: {e}")
    if not os.path.exists('/storage/emulated/0/Download/wwarpscanner'):
        try:
            os.makedirs('/storage/emulated/0/Download/wwarpscanner')
        except Exception:
            pass
    with open(file_path, "w") as f:
        f.write("faster\n")
        f.write("no\n")
        f.write("bpb\n")
        f.write("no\n")
        f.write("500\n")
        f.write("5\n")
        f.write("2\n")
        f.write("1\n")
```

#### Describe your issue
I used toga framework
If user opens the application, the permission to read and write the files will be revoked and a file and folder will be created in their mobile storage 
If the user deletes and reinstalls the app for any reason, the user will face this problem and  will have to manually delete the folder to run the app
 Code on GitHub : https://github.com/arshiacomplus/WarpScanner-android-GUI/tree/main/android-toga/v0.0.5

Error:
```

 --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.arshiacomplus.warpscanner.warpscanner, PID: 30564
E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.arshiacomplus.warpscanner.warpscanner/org.beeware.android.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wwarpscanner/warp_setting'                                                                    
E/AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3606)                                                                                    
E/AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)                                                                                     
E/AndroidRuntime:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)                                                                          
E/AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)                                                              
E/AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)                                                                        
E/AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)                                                                                          
E/AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime:    at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:8097)
E/AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)                                                                             
E/AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/AndroidRuntime: Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wwarpscanner/warp_setting'                   
E/AndroidRuntime:    at <python>.warpscanner.app.<module>(app.py:92)
E/AndroidRuntime:    at <python>.java.chaquopy.import_override(import.pxi:26)
E/AndroidRuntime:    at <python>.__main__.<module>(__main__.py:1)
E/AndroidRuntime:    at <python>.runpy._run_code(<frozen runpy>:88)
E/AndroidRuntime:    at <python>.runpy._run_module_code(<frozen runpy>:98)
E/AndroidRuntime:    at <python>.runpy.run_module(<frozen runpy>:226)
E/AndroidRuntime:    at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
E/AndroidRuntime:    at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)                                                            
E/AndroidRuntime:    at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
E/AndroidRuntime:    at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
E/AndroidRuntime:    at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
E/AndroidRuntime:    at org.beeware.android.MainActivity.onCreate(MainActivity.java:156)
E/AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:8142)
E/AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:8114)
E/AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)                                                                                   
E/AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3579)                                                                                    
E/AndroidRuntime:    ... 11 more
E/warpscanner: Uncaught exception: Unable to start activity ComponentInfo{com.arshiacomplus.warpscanner.warpscanner/org.beeware.android.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wwarpscanner/warp_setting'                                                                               
E/warpscanner: android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3606)
E/warpscanner: android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
E/warpscanner: android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)                                                                                   
E/warpscanner: android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)                                                                       
E/warpscanner: android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)                                                                                 
E/warpscanner: android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/warpscanner: android.os.Handler.dispatchMessage(Handler.java:106)
E/warpscanner: android.os.Looper.loop(Looper.java:236)
E/warpscanner: android.app.ActivityThread.main(ActivityThread.java:8097)
E/warpscanner: java.lang.reflect.Method.invoke(Native Method)
E/warpscanner: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)                                                                                      
E/warpscanner: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by mhsmith** [comment]
This is explained in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-sdcard).

**Comment by arshiacomplus** [comment]
Thanks
