### ISSUE TITLE
fter installing "ultralytics==8.0.16", the following error occurs when running the program:

### ISSUE THREAD

**Issue by caiyongrt** [chaquo/chaquopy#1285]
1.The environment used is chaquopy 16.0.0, and the Python version is 3.12.7.
2.The code in the build.gradle of the app is:
chaquopy {
    defaultConfig {
        pip {
            install "ultralytics==8.0.16"
            install "seaborn==0.12.2"
        }
    }
}
3.python代码为：
import os
os.environ['GIT_PYTHON_REFRESH'] = 'quiet'

from pathlib import Path
# Return the appropriate config directory for each operating system
sub_dir="Ultralytics"
path = Path.home() / ".config" / sub_dir
# Create the subdirectory if it does not exist
path.mkdir(parents=True, exist_ok=True)
USER_CONFIG_DIR = path  # Ultralytics settings dir
print('import from pathlib import Path成功')
print(USER_CONFIG_DIR)

from ultralytics import YOLO
print('import ultralytics successfully')

import cv2
print('import cv2 successfully')

def test(videoPath):

    print('The test function is called successfully')
    return video_path
4.The above code cannot import the ultralytics library. The print statement 'import ultralytics successfully' is not printed.。
5.The error prompt for program running is:【com.chaquo.python.PyException: AttributeError: module 'torch.distributed' has no attribute 'is_initialized'】
6.The complete error prompt is as follows:
FATAL EXCEPTION: main
at android.app.ActivityThread.performLaun  chActivity(ActivityThread.java:3668)
											at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823)
											at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
											at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
											at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
											at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279)
											at android.os.Handler.dispatchMessage(Handler.java:107)
											at android.os.Looper.loop(Looper.java:230)
											at android.app.ActivityThread.main(ActivityThread.java:7987)
											at java.lang.reflect.Method.invoke(Native Method)
											at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
											at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
										Caused by: com.chaquo.python.PyException: AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
											at <python>.ultralytics.yolo.utils.torch_utils.torch_distributed_zero_first(torch_utils.py:34)
											at <python>.contextlib.__enter__(contextlib.py:113)
											at <python>.ultralytics.yolo.utils.get_settings(__init__.py:464)
											at <python>.ultralytics.yolo.utils.<module>(__init__.py:505)
											at <python>.ultralytics.nn.autobackend.<module>(autobackend.py:15)
											at <python>.ultralytics.yolo.engine.predictor.<module>(predictor.py:34)
											at <python>.ultralytics.yolo.v8.classify.predict.<module>(predict.py:5)
											at <python>.ultralytics.yolo.v8.classify.<module>(__init__.py:3)
											at <python>.ultralytics.yolo.v8.<module>(__init__.py:3)
											at <python>.ultralytics.yolo.<module>(__init__.py:3)
											at <python>.ultralytics.<module>(__init__.py:5)
											at <python>.java.chaquopy.import_override(import.pxi:26)
											at <python>.cy.<module>(cy.py:14)
											at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
											at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
											at <python>.java.android.importer.exec_module(importer.py:626)
											at <python>.java.android.importer.exec_module(importer.py:714)
											at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
											at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
											at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
											at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
											at <python>.importlib.import_module(__init__.py:127)
											at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:127)
											at com.chaquo.python.Python.getModuleNative(Native Method)
											at com.chaquo.python.Python.getModule(Python.java:84)
											at cycom.example.cy_test1.MainActivity.callPythonCode(MainActivity.java:211)
											at cycom.example.cy_test1.MainActivity.onCreate(MainActivity.java:67)
											at android.app.Activity.performCreate(Activity.java:7894)
											at android.app.Activity.performCreate(Activity.java:7883)
											at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1353)
											at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
											at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823) 
											at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
											at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
											at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
																												Process: cycom.example.cy_test1, PID: 16410
										java.lang.RuntimeException: Unable to start activity ComponentInfo{cycom.example.cy_test1/cycom.example.cy_test1.MainActivity}: com.chaquo.python.PyException: AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
																			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279) 
											at android.os.Handler.dispatchMessage(Handler.java:107) 
											at android.os.Looper.loop(Looper.java:230) 
											at android.app.ActivityThread.main(ActivityThread.java:7987) 
											at java.lang.reflect.Method.invoke(Native Method) 
											at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526) 
											at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by mhsmith** [comment]
In future, please mark code blocks with triple backticks as shown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

This error was reported with ultralytics 8.0.18 at https://github.com/ultralytics/ultralytics/issues/612, and was apparently fixed somewhere around version 8.0.21. So I'm not sure why it didn't happen in #1106. I can only guess that either they were using a different version of ultralytics, or they were overriding the opencv version requirement.

The following combination of versions allows ultralytics to be installed and imported:
```
                install "ultralytics==8.0.21"
                install "seaborn==0.12.2"
                install "opencv-python==4.5.1.48"
```

There will be a non-fatal error about the opencv requirement conflict, but hopefully that doesn't matter.

**Comment by caiyongrt** [comment]
[ install "ultralytics==8.0.21"
                install "seaborn==0.12.2"
                install "opencv-python==4.5.1.48"
                There are problems with the above configuration:]
"install 'ultralytics==8.0.21'" requires opencv-python>=4.6.0.
The highest version of opencv-python supported by Chaquopy is: opencv-python==4.5.1.48.
This leads to the failure of installing "ultralytics==8.0.21".

**Comment by mhsmith** [comment]
No it doesn't – like I said, that error is non-fatal, even if Android Studio chooses to focus on it.

**Comment by Edward-YS** [comment]
> ```
>            [ install "ultralytics==8.0.21"
>             install "seaborn==0.12.2"
>             install "opencv-python==4.5.1.48"
>             There are problems with the above configuration:]
> ```
> 
> "install 'ultralytics==8.0.21'" requires opencv-python>=4.6.0. The highest version of opencv-python supported by Chaquopy is: opencv-python==4.5.1.48. This leads to the failure of installing "ultralytics==8.0.21".
Could you use the ultralytics in aright way and realize the object detection?
