### ISSUE TITLE
Getting Chaquopy Errors while building the android app from Jenkins pipeline.

### ISSUE THREAD

**Issue by ravi-nissan** [chaquo/chaquopy#1303]
#### Chaquopy version

15.0.1

#### Relevant parts of your build.gradle file

```
chaquopy {
	defaultConfig {
		version = "3.8"
		pip {
			install("numpy")
			install("scipy")
			install("joblib")
			install("threadpoolctl")
			install("scikit-learn")
		}
	}

	sourceSets {
		getByName("main") {
			srcDir("app/src/main/python")
		}
	}
}
```

#### Describe your issue

We are building  app in Jenkins linux platform,
```
> Task :app:generateNissanDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-13.1
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='chaquo.com', port=443): Read timed out. (read timeout=15)")': /pypi-13.1/numpy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='chaquo.com', port=443): Read timed out. (read timeout=15)")': /pypi-13.1/numpy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='chaquo.com', port=443): Read timed out. (read timeout=15)")': /pypi-13.1/numpy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='chaquo.com', port=443): Read timed out. (read timeout=15)")': /pypi-13.1/numpy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='chaquo.com', port=443): Read timed out. (read timeout=15)")': /pypi-13.1/numpy/
Collecting numpy
  Downloading numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/bin/python /home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp6w8bqsj9
       cwd: /tmp/pip-install-2mcolh03/numpy
  Complete output (35 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'
  Traceback (most recent call last):
    File "/home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "/home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/lib/python3.12/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "/tmp/pip-build-env-_ciowtye/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
      import setuptools.version
    File "/tmp/pip-build-env-_ciowtye/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
      import pkg_resources
    File "/tmp/pip-build-env-_ciowtye/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  ----------------------------------------
ERROR: Failed to install numpy from https://files.pythonhosted.org/packages/a4/9b/027bec52c633f6556dba6b722d9a0befb40498b9ceddd29cbe67a45a127c/numpy-1.24.4.tar.gz#sha256=80f5e3a4e498641401868df4208b74581206afbee7cf7b8329daae82676d9463.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateNissanDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateNissanDebugPythonRequirements'.
> Process 'command '/home/jenkins/workspace/APIDA/DOM-Debug/app/build/python/env/nissanDebug/bin/python'' finished with non-zero exit value 1 
```

**Comment by mhsmith** [comment]
The build was unable to connect to https://chaquo.com/pypi-13.1, which stores the Android-compatible builds of NumPy and other packages. 

If this persists, check the machine's network configuration, including any firewalls. If you need to use a proxy server, you can configure it using a [`pip { options }`](https://chaquo.com/chaquopy/doc/current/android.html#requirements) line to pass the [`--proxy`](https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server) option.
