### ISSUE TITLE
Reading/Loading a file

### ISSUE THREAD

**Issue by kongkip** [chaquo/chaquopy#144]
How can i read a file in the project directory with python?
i.e.
```python
with open('chatbot.txt','r', encoding='utf8', errors ='ignore') as fin:
    raw = fin.read().lower()
```
or where should put it for easier loading

**Comment by kongkip** [comment]
Thanks for that, it worked with version 6.3.0.

**Comment by Leandropslv** [comment]
I want to understand why it's not working here, I have a .txt file inside the same folder as the .py file. I use this code:

from os.path import dirname, join
with open(join(dirname(__file__), 'chatbot.txt'), ...

And this error is returned:
 com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/android_asset/chaquopy/app.zip/csa.txt'

**Comment by mhsmith** [comment]
As mentioned above, you must be using Chaquopy 6.3.0 or later for this technique to work.

**Comment by Leandropslv** [comment]
I received this error:

com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.codecs.decode(codecs.py:321)
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.new.test(new.py:180)
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
E/MethodChannel#processing.channel/milho_scan(24144): 	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.example.milho_scan_app.MainActivity.lambda$onCreate$0(MainActivity.java:63)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.example.milho_scan_app.-$$Lambda$MainActivity$FJZXqDLBvILvLH7E3hcCNSZrVNA.onMethodCall(lambda)
E/MethodChannel#processing.channel/milho_scan(24144): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#processing.channel/milho_scan(24144): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#processing.channel/milho_scan(24144): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#processing.channel/milho_scan(24144): 	at android.app.ActivityThread.main(ActivityThread.java:5530)
E/MethodChannel#processing.channel/milho_scan(24144): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
E/MethodChannel#processing.channel/milho_scan(24144): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)

**Comment by Leandropslv** [comment]
My code is this:

 from os.path import dirname, join

  f =  open(join(dirname(__file__), 'my_classifier.pickle'))

    import pickle

    classifier = pickle.load(f)

    resultado = classifier.predict(dados)    #Essa é a linha 180

    print(resultado)

**Comment by Leandropslv** [comment]
My code is this:

from os.path import dirname, join

f = open(join(dirname(file), 'my_classifier.pickle'))

import pickle

classifier = pickle.load(f)

resultado = classifier.predict(dados)    #Essa é a linha 180

print(resultado)

**Comment by Leandropslv** [comment]
My code in the normal Pyhon environment is this:

import pickle

f = open('my_classifier.pickle', 'rb')

classifier = pickle.load(f)
print(type(f))
f.close()

resultado = classifier.predict(dados)

print(resultado)


My code in the normal Pyhon environment is this: <class '_io.TextIOWrapper'>

In the python environment, open returns me: <class '_io.BufferedReader'>

**Comment by Leandropslv** [comment]
My code in the normal Pyhon environment is this:

import pickle

f = open('my_classifier.pickle', 'rb')

classifier = pickle.load(f)
print(type(f))
f.close()

resultado = classifier.predict(dados)

print(resultado)


My code in the Chaquopy environment returns: <class '_io.TextIOWrapper'>

In the python environment, open returns me: <class '_io.BufferedReader'>

**Comment by Leandropslv** [comment]
The (open) method in the Chaquopy environment returns: <class '_io.TextIOWrapper'>
In the Normal Python environment, returns: <class '_io.BufferedReader'>


My code in the Normal Python environment is this:

import pickle

f = open('my_classifier.pickle', 'rb')

classifier = pickle.load(f)
print(type(f))
f.close()

resultado = classifier.predict(dados)

print(resultado)

**Comment by Raghu17s** [comment]
Hi,

Is there any way to read data from internal storage ('/storage/emulated/0/filename') other than in app folder?

**Comment by AbsolutelySaurabh** [comment]
> In Chaquopy 6.3.0 and later, you can access data files using a path relative to `__file__`. For example, if the data file is in the same directory as the Python file:
> 
> ```
> from os.path import dirname, join
> filename = join(dirname(__file__), "chatbot.txt")
> ```
> 
> If the data file and the Python files are in different directories, then change the relative path accordingly. For example, if the Python file is `src/main/python/alpha/hello.py`, and the data file is `src/main/python/bravo/filename.txt`, then replace `chatbot.txt` with `../bravo/chatbot.txt`.

@mhsmith  you rocked man, this worked after sucking up for 2 days.

**Comment by sarthaksharma058439** [comment]
Finally I got a solution after a long time, this guy explains in simple way how to open and read file data using chaquopy in android studio  Check this [link](https://youtu.be/m_vV5ZKBuNg)
