### ISSUE TITLE
Unable to load pickle files of sklearn models

### ISSUE THREAD

**Issue by ronalddon** [chaquo/chaquopy#168]
I saved a decision tree model using pickle and tried to load it in android
`tree = pickle.load(open(join((dirname(package1.__file__)),"models", "tree.pickle"), 'rb'))`
but an error is raised and the model can't be loaded:

```
com.chaquo.python.PyException: ValueError: Did not recognise loaded array layout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I am using anaconda for model training and saving. Both sklearn in anaconda and chaquopy have the same version
Tried joblib also but is getting the same result

**Comment by mhsmith** [comment]
According to [the scikit-learn documentation](https://scikit-learn.org/stable/modules/model_persistence.html), "dumping a model on one architecture and loading it on another architecture is not supported". There are many similar issues on the scikit-learn GitHub tracker: usually they recommend using another model format (e.g. [here](https://github.com/scikit-learn/scikit-learn/issues/11033)).

**Comment by mhsmith** [comment]
> According to [the scikit-learn documentation](https://scikit-learn.org/stable/modules/model_persistence.html), "dumping a model on one architecture and loading it on another architecture is not supported".

This has now changed to "Aside for a few exceptions, pickled models should be portable across architectures, assuming the same versions of dependencies and Python are used." And it also says: "While models saved using one version of scikit-learn might load in other versions, this is entirely unsupported and inadvisable." 

So when using pickled models, make sure to generate the model file using the same Python and scikit-learn versions as Chaquopy uses (currently Python 3.8 and scikit-learn 0.24.1). 

Alternatively, you could use an interoperable format like ONNX or PMML: see [these instructions](https://scikit-learn.org/stable/modules/model_persistence.html#interoperable-formats).
