### ISSUE TITLE
How should I stop the python program?

### ISSUE THREAD

**Issue by chenzhuojie** [chaquo/chaquopy#182]
After I started the python program, I didn't find a way to stop it

**Comment by mhsmith** [comment]
By default, Chaquopy runs Python within your main app process. So your Python code will have to terminate itself, either by returning or throwing an exception.

If you really need to be able to stop a Python script at any time, then you could try running it in a separate process using the [`process`](https://developer.android.com/guide/topics/manifest/activity-element.html#proc) option in AndroidManifest.xml. But this will significantly complicate your app.

**Comment by alexcarnero97** [comment]
I am trying to use Chaquopy in order to execute a python script within my Android app. My application takes care of taking several photos until a certain condition is met, which is given by the python script. The python script receives and processes each of the images and finally predicts what type of object appears in them (out of two possible). The problem is that the python script only executes well with the first image that is passed to it, while with the following images it does not, and this I think is due to the fact that the PyObject variable has already been instantiated previously and it calls all the time to my prediction function without waiting for a new photograph to be taken, which I do not understand (I leave here the code that calls the python script):

        String result;

        while(!found) {
            takePicture();

            PyObject py = Python.getInstance().getModule("prediction");
            PyObject[] obj = new PyObject[1];
            obj[0] = py.callAttr("predict", currentPhotoPath);
            result = obj[0].toString();

            System.out.println(result);

            if (result.contains("turbine")) {
                found = true;
            }
        }

The error thrown is the following one:

2021-04-15 10:32:55.562 20510-20510/com.example.windturbinesai E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.windturbinesai, PID: 20510
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.windturbinesai/com.example.windturbinesai.PhotoActivity}: com.chaquo.python.PyException: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x78bb970680>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: com.chaquo.python.PyException: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x78bb970680>
        at <python>.PIL.Image.open(Image.py:2895)
        at <python>.keras_preprocessing.image.utils.load_img(utils.py:114)
        at <python>.prediction.predict(prediction.py:17)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.windturbinesai.PhotoActivity.start(PhotoActivity.java:63)
        at com.example.windturbinesai.PhotoActivity.onCreate(PhotoActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:8086)
        at android.app.Activity.performCreate(Activity.java:8074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)

After the exception I go into my mobile's folder where pictures are saved and there is one picture taken without any data (it is empty), but it has been saved, so that's why I think the python script is being called before I can finish to take another photo, so everything is messed up here. I have already tried with different threads but it does not work well either.

My python script ends with a return statement (as you recommend in order to let a program finishes), but it seems like it does not wait the explicit call from my Java code. Is there a way to open and close the Python session for each of the times I want to run the script? I think there should be a better fix because I guess this solution would not be the best one in terms of efficiency.

**Comment by mhsmith** [comment]
Linking to #58 which is the canonical answer to this question.
