### ISSUE TITLE
How to read csv file from internal storage ('/storage/emulated/0/filename')?

### ISSUE THREAD

**Issue by Raghu17s** [chaquo/chaquopy#184]
Hi,

Is there any way to read data from internal storage ('/storage/emulated/0/filename') other than the in-app folder? When I place a larger size file (>300 Mb), it throws a memory-related error. So thought of reading the file from the internal storage of mobile.

**Comment by mhsmith** [comment]
See #38.

**Comment by Raghu17s** [comment]
I have followed the #38 procedure, but it is throwing following error. But it was working when I place the file inside the app folder. 

/storage/emulated/0
/storage/emulated/0/EEG_Sub_02_Preprocessed.csv

Exception in thread Thread-1:
Traceback (most recent call last):
  File "stdlib/threading.py", line 916, in _bootstrap_inner
  File "stdlib/threading.py", line 864, in run
  File "/data/user/0/com.chaquo.python.console/files/chaquopy/AssetFinder/app/chaquopy/utils/console.py", line 14, in <lambda>
  File "class.pxi", line 695, in java.chaquopy.JavaMethod.__get__.lambda2
  File "class.pxi", line 715, in java.chaquopy.JavaMethod.__call__
  File "class.pxi", line 805, in java.chaquopy.JavaMethod.call_nonvirtual_method
  File "env.pxi", line 242, in java.chaquopy.CQPEnv.CallNonvirtualVoidMethodA
  File "env.pxi", line 484, in java.chaquopy.CQPEnv.check_exception
com.chaquo.python.PyException: OSError: Initializing from file failed
	at <python>.pandas._libs.parsers.TextReader._setup_parser_source(parsers.pyx:720)
	at <python>.pandas._libs.parsers.TextReader.__cinit__(parsers.pyx:402)
	at <python>.pandas.io.parsers.__init__(parsers.py:1695)
	at <python>.pandas.io.parsers._make_engine(parsers.py:1049)
	at <python>.pandas.io.parsers.__init__(parsers.py:818)
	at <python>.pandas.io.parsers._read(parsers.py:449)
	at <python>.pandas.io.parsers.parser_f(parsers.py:709)
	at <python>.main.main(main.py:30)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at com.chaquo.python.console.MainActivity$Task.run(MainActivity.java:20)
	at com.chaquo.python.utils.ConsoleActivity$Task$1.run(ConsoleActivity.java:352)

**Comment by Raghu17s** [comment]
I have followed instructions given @ #38. But it throws the following error.  It looks like something related permission error. 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "stdlib/threading.py", line 916, in _bootstrap_inner
  File "stdlib/threading.py", line 864, in run
  File "/data/user/0/com.chaquo.python.console/files/chaquopy/AssetFinder/app/chaquopy/utils/console.py", line 14, in <lambda>
  File "class.pxi", line 695, in java.chaquopy.JavaMethod.__get__.lambda2
  File "class.pxi", line 715, in java.chaquopy.JavaMethod.__call__
  File "class.pxi", line 805, in java.chaquopy.JavaMethod.call_nonvirtual_method
  File "env.pxi", line 242, in java.chaquopy.CQPEnv.CallNonvirtualVoidMethodA
  File "env.pxi", line 484, in java.chaquopy.CQPEnv.check_exception
com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/EEG_Sub_02_Preprocessed.csv'
	at <python>.pandas.io.common._get_handle(common.py:393)
	at <python>.pandas.io.parsers.__init__(parsers.py:2074)
	at <python>.pandas.io.parsers._make_engine(parsers.py:1059)
	at <python>.pandas.io.parsers.__init__(parsers.py:818)
	at <python>.pandas.io.parsers._read(parsers.py:449)
	at <python>.pandas.io.parsers.parser_f(parsers.py:709)
	at <python>.main.main(main.py:30)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at com.chaquo.python.console.MainActivity$Task.run(MainActivity.java:20)
	at com.chaquo.python.utils.ConsoleActivity$Task$1.run(ConsoleActivity.java:352)
