### ISSUE TITLE
MemoryError for data file with size 300mb

### ISSUE THREAD

**Issue by Raghu17s** [chaquo/chaquopy#194]
Hi,

I am trying to process the csv file which has nearly 300 mb, but it is showing following memory error. Could you please guide me to solve this issue?

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "stdlib/threading.py", line 916, in _bootstrap_inner
  File "stdlib/threading.py", line 864, in run
  File "/data/user/0/com.chaquo.python.sezect/files/chaquopy/AssetFinder/app/chaquopy/utils/console.py", line 14, in <lambda>
  File "class.pxi", line 695, in java.chaquopy.JavaMethod.__get__.lambda2
  File "class.pxi", line 715, in java.chaquopy.JavaMethod.__call__
  File "class.pxi", line 805, in java.chaquopy.JavaMethod.call_nonvirtual_method
  File "env.pxi", line 242, in java.chaquopy.CQPEnv.CallNonvirtualVoidMethodA
  File "env.pxi", line 484, in java.chaquopy.CQPEnv.check_exception
com.chaquo.python.PyException: MemoryError: 
	at <python>.main.main(main.py:31)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at com.chaquo.python.console.MainActivity$Task.run(MainActivity.java:20)
	at com.chaquo.python.utils.ConsoleActivity$Task$1.run(ConsoleActivity.java:352)
```

**Comment by mhsmith** [comment]
I assume this corresponds to the file https://github.com/Raghu17s/sezect/blob/master/app/src/main/python/main.py:
```
30    EEG1 = pd.read_csv(d+'/LAWRENCE_RMCH_Preprocessed_new.csv', engine='python')
31    EEG = np.array(EEG1)
```

Which of these lines is line 31 in your current version? If it's `pd.read_csv`, have a look at the ideas at https://stackoverflow.com/questions/17557074.

It also seems inefficient to read the data using pandas and then copy it into numpy. Could you load it into numpy directly using [`loadtxt`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html)?

**Comment by Raghu17s** [comment]
Yes, It is the same project. 

 [loadtext ](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html)worked,  but https://stackoverflow.com/questions/17557074 did not work.

**Comment by mhsmith** [comment]
OK, glad you were able to solve it.
