### ISSUE TITLE
Trying to import face_recognition into my python code

### ISSUE THREAD

**Issue by bv-noake** [chaquo/chaquopy#214]
I installed the face_recognition library in pip 
python {
            buildPython "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3"
            pip {

                install "face_recognition"
            }
        }

This worked, however now it's not importing face_recognition in the python file or letting me load my images I have saved 
<img width="1039" alt="Screenshot 2020-01-31 at 15 06 44" src="https://user-images.githubusercontent.com/45761671/73550039-c8274f00-443b-11ea-8775-515e92d4088a.png">

**Comment by bv-noake** [comment]
Gives me this error

Process: com.example.project, PID: 6831
    com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: 'Aniston.jpg'
        at <python>.PIL.Image.open(Image.py:2580)
        at <python>.face_recognition.api.load_image_file(api.py:83)
        at <python>.facerecognition.main(facerecognition.py:10)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.example.project.Whoisit.python(Whoisit.java:105)
        at com.example.project.Whoisit$1.onPictureTaken(Whoisit.java:68)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by mhsmith** [comment]
You need to give the full directory path: see #144.

**Comment by bv-noake** [comment]
That seems to work to get the path, I am now getting this error which closes my app

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.project, PID: 13265
    com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
        at <python>.codecs.decode(codecs.py:321)
        at <python>.PIL.Image.open(Image.py:2589)
        at <python>.face_recognition.api.load_image_file(api.py:83)
        at <python>.facerecognition.main(facerecognition.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.example.project.Whoisit.python(Whoisit.java:106)
        at com.example.project.Whoisit$1.onPictureTaken(Whoisit.java:69)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 13265 SIG: 9
Process 13265 terminated.

**Comment by mhsmith** [comment]
If you're calling `open` yourself, you'll need to use mode "rb" for binary. 

Or just pass the filename directly to `load_image_file`.
