### ISSUE TITLE
passing a parameter from java to python 

### ISSUE THREAD

**Issue by bv-noake** [chaquo/chaquopy#215]
I have my app taking a picture using the app camera and then I would like to send the photo to my python code so that it can make use of it. Currently i have this code to try and send it 

```
public void python(Camera camera) {
            context = getApplicationContext();
            Python.start(new AndroidPlatform(context));

           Python py = Python.getInstance();
            PyObject pyObject = py.getModule("facerecognition").callAttr("main", ""+camera);
}
```

However, this doesn't seem to work as it gives me this error when I try to use it:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.project, PID: 12159
    com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
        at <python>.codecs.decode(codecs.py:321)
        at <python>.PIL.Image.open(Image.py:2589)
        at <python>.face_recognition.api.load_image_file(api.py:83)
        at <python>.facerecognition.main(facerecognition.py:12)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.example.project.Whoisit.python(Whoisit.java:105)
        at com.example.project.Whoisit$1.onPictureTaken(Whoisit.java:68)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 12159 SIG: 9
Process 12159 terminated.
```

**Comment by mhsmith** [comment]
I assume `Camera` is [`android.hardware.Camera`](https://developer.android.com/reference/android/hardware/Camera.html). The documentation on that page explains how to take a photo. Converting the Camera object to a String (which will be the result of `""+camera`) is unlikely to be helpful.

Once you've taken a photo, the easiest way to pass it to Python would be to [write it to a file](https://developer.android.com/training/data-storage) and then pass that filename to your Python code.
