### ISSUE TITLE
Trying to perform face_recognition library function

### ISSUE THREAD

**Issue by bv-noake** [chaquo/chaquopy#217]
I have been trying to get my python code to perform a facial recognition comparison and i have used this code 

def main(picture):
    print("hello")
    # noinspection PyInterpreter
    import face_recognition
    print("2")
    from os.path import dirname, join
    f = open(join(dirname(__file__), "Aniston.jpg"))
    print("3")

#These two lines of code not working
    aniston_image = face_recognition.load_image_file(f)
    print("4")
    aniston_face_encoding = face_recognition.face_encodings(aniston_image)[0]

    from os.path import dirname, join
    f1 = open(join(dirname(__file__), 'Noake.jpg'))

    chris_image = face_recognition.load_image_file(f1)
    chris_face_encoding = face_recognition.face_encodings(chris_image)[0]

    print("1")

    unknown_image = face_recognition.load_image_file(picture)

    unknown_encoding = face_recognition.face_encodings(unknown_image)[0]

    known_face_encodings = [
        aniston_face_encoding,
        chris_face_encoding
    ]
    known_face_names = [
        "Jennifer Aniston",
        "Chris Noake",
    ]

    results = face_recognition.compare_faces(known_face_encodings, unknown_encoding)

    print(results)

However, i can see it is stopping at the lines i have hashtagged and it is giving me this error:

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.project, PID: 19113
    com.chaquo.python.PyException: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
        at <python>.codecs.decode(codecs.py:321)
        at <python>.PIL.Image.open(Image.py:2589)
        at <python>.face_recognition.api.load_image_file(api.py:83)
        at <python>.facerecognition.main(facerecognition.py:14)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.example.project.Whoisit$1.onPictureTaken(Whoisit.java:93)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 19113 SIG: 9
Process 19113 terminated.

**Comment by bv-noake** [comment]
I also have this bit of code to install the face_recognition library 

python {
            buildPython "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3"
            pip {

                install "face_recognition"
            }
        }

**Comment by mhsmith** [comment]
I already gave you the solution in https://github.com/chaquo/chaquopy/issues/214#issuecomment-580791707.
