### ISSUE TITLE
java.lang.ClassCastException: TypeError: Cannot convert int64 object to int

### ISSUE THREAD

**Issue by LuArtur** [chaquo/chaquopy#237]
I have an array of integer values that I need to graph but when trying to convert them with the method
toJava (int []. class) I miss this error

> java.lang.ClassCastException: TypeError: Cannot convert int64 object to int
![trasa](https://user-images.githubusercontent.com/60788857/76374339-4b7c7000-6319-11ea-8050-b7bca385c531.png)

Some time ago I had another array of float-type values and this method worked well for me.
I don't know what's happening this time

**Comment by mhsmith** [comment]
Assuming `ecgclas` is a Numpy array, you can convert it to a Java array by using a Python list as an intermediate. The easiest way is to use the Numpy [`tolist`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html) method, e.g.:

```
ecgclas.callAttr("tolist").toJava(int[].class);
```

**Comment by LuArtur** [comment]
solved

**Comment by sdurandeu** [comment]
@LuArtur @mhsmith Is there anything else I need to do to solve this? I cannot seem to go past the following error when trying to send a value from numpy into Java as integer:

```
05-01 18:21:45.009 21455 21556 W System.err: java.lang.ClassCastException: TypeError: Cannot convert int64 object to java.lang.Integer
05-01 18:21:45.009 21455 21556 W System.err:    at <python>.java.chaquopy.p2j(conversion.pxi:242)
05-01 18:21:45.009 21455 21556 W System.err:    at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_toJava(chaquopy_java.pyx:208)
05-01 18:21:45.009 21455 21556 W System.err:    at com.chaquo.python.PyObject.toJava(Native Method)
05-01 18:21:45.009 21455 21556 W System.err:    at com.feebris.SignalQualityAlgorithmsModule.analysePulseoxRecording(SignalQualityAlgorithmsModule.java:152)
05-01 18:21:45.009 21455 21556 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-01 18:21:45.009 21455 21556 W System.err:    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-01 18:21:45.009 21455 21556 W System.err:    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
05-01 18:21:45.009 21455 21556 W System.err:    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-01 18:21:45.009 21455 21556 W System.err:    at android.os.Handler.handleCallback(Handler.java:883)
05-01 18:21:45.009 21455 21556 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:100)
05-01 18:21:45.009 21455 21556 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
05-01 18:21:45.010 21455 21556 W System.err:    at android.os.Looper.loop(Looper.java:214)
05-01 18:21:45.010 21455 21556 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
05-01 18:21:45.010 21455 21556 W System.err:    at java.lang.Thread.run(Thread.java:919)
```

However, I'm quite sure I'm missing something basic. The code in the python side is like this:

```python
....

print(type(signals_mode["SpO2"])) // prints <class 'numpy.int64'>
print(type(signals_mode["HR"])) // prints <class 'numpy.int64'>

return signals_mode, anotherParam
```

Then in Java:
```
List<PyObject> resultModel = this.myModule.get("myMethod").call(param1, param2).asList();

Map<PyObject, PyObject> signals_mode = resultModel.get(0).asMap();

WritableMap map = Arguments.createMap();
map.putInt("value1", signals_mode.get("SpO2").toJava(int.class)); --> the exception is thrown here
map.putInt("value2", signals_mode.get("HR").toJava(int.class));
map.putString("reason", resultModel.get(1).toString());
promise.resolve(map);
```

Thanks!!

**Comment by sdurandeu** [comment]
As it happens, I found the solution minutes afterwards :smile:

I used `item()` as explained here: https://stackoverflow.com/questions/9452775/converting-numpy-dtypes-to-native-python-types/11389998

**Comment by LuArtur** [comment]
Sebastián hablas español? 


---Desde mi teléfono con SIJÚ

El May 1, 2020 5:44:33 PM UTC, Sebastian Durandeu <notifications@github.com> escribió:
@LuArtur @mhsmith Is there anything else I need to do to solve this? I
cannot seem to go past the following error when trying to send a value
from numpy into Java as integer:

```
05-01 18:21:45.009 21455 21556 W System.err:
java.lang.ClassCastException: TypeError: Cannot convert int64 object to
java.lang.Integer
05-01 18:21:45.009 21455 21556 W System.err:    at
<python>.java.chaquopy.p2j(conversion.pxi:242)
05-01 18:21:45.009 21455 21556 W System.err:    at
<python>.chaquopy_java.Java_com_chaquo_python_PyObject_toJava(chaquopy_java.pyx:208)
05-01 18:21:45.009 21455 21556 W System.err:    at
com.chaquo.python.PyObject.toJava(Native Method)
05-01 18:21:45.009 21455 21556 W System.err:    at
com.feebris.SignalQualityAlgorithmsModule.analysePulseoxRecording(SignalQualityAlgorithmsModule.java:152)
05-01 18:21:45.009 21455 21556 W System.err:    at
java.lang.reflect.Method.invoke(Native Method)
05-01 18:21:45.009 21455 21556 W System.err:    at
com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-01 18:21:45.009 21455 21556 W System.err:    at
com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
05-01 18:21:45.009 21455 21556 W System.err:    at
com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-01 18:21:45.009 21455 21556 W System.err:    at
android.os.Handler.handleCallback(Handler.java:883)
05-01 18:21:45.009 21455 21556 W System.err:    at
android.os.Handler.dispatchMessage(Handler.java:100)
05-01 18:21:45.009 21455 21556 W System.err:    at
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
05-01 18:21:45.010 21455 21556 W System.err:    at
android.os.Looper.loop(Looper.java:214)
05-01 18:21:45.010 21455 21556 W System.err:    at
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
05-01 18:21:45.010 21455 21556 W System.err:    at
java.lang.Thread.run(Thread.java:919)
```

However, I'm quite sure I'm missing something basic. The code in the
python side is like this:

```python
....

print(type(signals_mode["SpO2"])) // prints <class 'numpy.int64'>
print(type(signals_mode["HR"])) // prints <class 'numpy.int64'>

return signals_mode, anotherParam
```

Then in Java:
```
List<PyObject> resultModel = this.myModule.get("myMethod").call(param1,
param2).asList();

Map<PyObject, PyObject> signals_mode = resultModel.get(0).asMap();

WritableMap map = Arguments.createMap();
map.putInt("value1", signals_mode.get("SpO2").toJava(int.class)); -->
the exception is thrown here
map.putInt("value2", signals_mode.get("HR").toJava(int.class));
map.putString("reason", resultModel.get(1).toString());
promise.resolve(map);
```

Thanks!!

**Comment by mhsmith** [comment]
Since Chaquopy version 8.0.0, NumPy arrays and Java arrays of the same type can now converted directly, which gives much better performance.
