### ISSUE TITLE
Got problem while 'pip install "face_recognition"' 

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#24]
_From @hushanhsiang on January 16, 2018 13:43_

To install "face_recognition" package on my PC (Windows10) is no problem but I got a problem when I put "install face_recognition" in build.gradel (Module:app) as below.
pip{
                install "requests"
                install "face_recognition"
            }

Error message:
Error:Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python'' finished with non-zero exit value 1

To remove 'install "face_recognition"' will be OK but I'd like to use face_recongnition to run my project.
Is it possible to install this package with Chaquopy? Thanks.

_Copied from original issue: chaquo/chaquopy-hello#6_

**Comment by mhsmith** [comment]
When reporting build errors, please include the details of the error from the "Gradle console" tool window.

**Comment by mhsmith** [comment]
_From @hushanhsiang on January 16, 2018 22:55_


Below is the Gradle console:
`Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]

Configuration on demand is an incubating feature.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:extractPythonBuildPackages UP-TO-DATE
:app:generateDebugPythonRequirements
Installing for armeabi-v7a
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting face_recognition
  Using cached face_recognition-1.0.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting numpy (from face_recognition)
  Using cached https://chaquo.com/pypi/numpy/numpy-1.9.2-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting face-recognition-models>=0.2.0 (from face_recognition)

  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement face-recognition-models>=0.2.0 (from face_recognition) (from versions: 0.1.3)
No matching distribution found for face-recognition-models>=0.2.0 (from face_recognition) (NOTE: Chaquopy only supports wheels, not sdist packages)
Exit status 1

:app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

7 actionable tasks: 1 executed, 6 up-to-date
`

**Comment by mhsmith** [comment]
_From @hushanhsiang on January 16, 2018 22:57_

Same code but seems got different Error of "Gradle console":
`Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]

Configuration on demand is an incubating feature.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:extractPythonBuildPackages UP-TO-DATE
:app:generateDebugPythonRequirements
Installing for armeabi-v7a
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting face_recognition
  Using cached face_recognition-1.0.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting numpy (from face_recognition)
  Using cached https://chaquo.com/pypi/numpy/numpy-1.9.2-cp36-cp36m-android_15_armeabi_v7a.whl
Collecting dlib>=19.5 (from face_recognition)

  Could not find a version that satisfies the requirement dlib>=19.5 (from face_recognition) (from versions: )
No matching distribution found for dlib>=19.5 (from face_recognition) (NOTE: Chaquopy only supports wheels, not sdist packages)
Exit status 1

:app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

7 actionable tasks: 1 executed, 6 up-to-date
`

**Comment by mhsmith** [comment]
OK, face_recognition also requires scipy, so we won't be able to support it right now (#25).

**Comment by MeloniF** [comment]
Hello Mr. Smith
My team and I are working on a project aimed to recognize patterns in faces. We are using Python with OpenCV, Dlib, and Imutils and we intend to include our workflow in an Android project.  We would like to make the integration using Chaquopy. Any news about the implementation of the libraries above cited? 
Thanks

**Comment by mhsmith** [comment]
After many requests, we're working on OpenCV right now, and expect to release it within the next week. It looks like Imutils requires only OpenCV, so that should work automatically once OpenCV is available.

Dlib is not currently a priority; however, we would probably be willing to add it in return for a small payment. If this is something you would consider, please contact us by email.

**Comment by mycodeself** [comment]
Some updates on this? Im working currently in project with face_recognition and Chaquopy. 

I get runtime error:

`     Caused by: com.chaquo.python.PyException: AttributeError: module 'face_recognition' has no attribute 'load_image_file'
        at <python>.face_recognition.read_face_encodings(face_recognition.py:5)
        at <python>.face_recognition.compare_face_images(face_recognition.py:10)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)`

**Comment by mhsmith** [comment]
Thanks, we've already fixed this problem in development and we'll release the fix in the next few days.

**Comment by mhsmith** [comment]
Fixed in Chaquopy 6.2.1.

**Comment by Nadeem1222** [comment]
when i install face_recognition.."pip install face_recognition" 

ERROR: Command errored out with exit status 1:
     command: /Users/balouchnadeem/PycharmProjects/1st/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-record-jQW5PK/install-record.txt --single-version-externally-managed --compile --install-headers /Users/balouchnadeem/PycharmProjects/1st/venv/include/site/python2.7/dlib
         cwd: /private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/
    Complete output (40 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/Users/balouchnadeem/PycharmProjects/1st/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/balouchnadeem/PycharmProjects/1st/venv/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py", line 125, in get_cmake_version
        "\n*******************************************************************\n")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/balouchnadeem/PycharmProjects/1st/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-install-5JKu_1/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zk/kw5d445528l23_gytnndhvdc0000gn/T/pip-record-jQW5PK/install-record.txt --single-version-externally-managed --compile --install-headers /Users/balouchnadeem/PycharmProjects/1st/venv/include/site/python2.7/dlib Check the logs for full command output.

**Comment by mhsmith** [comment]
I notice that you're using Python 2.7, which Chaquopy hasn't supported since version 5.0.0. What version of Chaquopy are you using?

The `pip` block in `build.gradle`, as described [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements), is the only supported way to run pip with Chaquopy. Is that what you're using? If so, please post that block.

**Comment by liyanhrxy** [comment]
```
java.lang.UnsatisfiedLinkError: no chaquopy_java in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.chaquo.python.GenericPlatform.<init>(GenericPlatform.java:13)
	at com.chaquo.python.Python.getInstance(Python.java:28)
	at com.chaquo.java.PyObjectTest.setUp(PyObjectTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
##### how to fix this
