### ISSUE TITLE
Dear Chaquopy please add those packages

### ISSUE THREAD

**Issue by Aniskonig** [chaquo/chaquopy#243]
Dear can you please add **Cython, pystan, python-dateutil, pytz, six and fbprophet** to your [repository](https://chaquo.com/pypi-7.0/) because when i try to install them :
```
        python {
            buildPython "C:/Users/aniso/AppData/Local/Programs/Python/Python38/python.exe"
            pip {
                install "Cython"
                install "fbprophet"
                // The same thing for the others
            }
        }
```
I got this error

>   error: CCompiler.compile: Chaquopy cannot compile native code
and
> Failed to install "package name"

**Thanks for all CHAQUOPY you're the best**

**Comment by mhsmith** [comment]
Thanks for the report. The only packages in this list which currently fail to install are pystan and fbprophet. (Cython would be required for building the packages, but not running them.)

These packages aren't currently a priority, but if anyone else wants them too, please add a thumbs-up to the original post and we may provide them in the future.

**Comment by Aniskonig** [comment]
Please tell me what i have to do to solve this problem i need them for my project

**Comment by mhsmith** [comment]
We might be able to provide them in return for a payment. If you'd be interested in this, please contact us at the email address on [our website](https://chaquo.com/chaquopy/contact/).

**Comment by Aniskonig** [comment]
I’m student sir/madam and I need it for my graduation project that’s all From: Malcolm SmithSent: 16 March 2020 11:30To: chaquo/chaquopyCc: Aniskonig; ManualSubject: Re: [chaquo/chaquopy] pystan and fbprophet (#243) We might be able to provide them in return for a payment. If you'd be interested in this, please contact us at the email address on our website.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by mhsmith** [comment]
I understand, but it takes a significant amount of time to build and test new packages, so we won't usually add them for free unless they're very popular.

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building these packages yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by mhsmith** [comment]
`fbprophet` has now been renamed to `prophet`.

**Comment by mhsmith** [comment]
*Originally posted in #1232 by @tk-ray*

----



#### Chaquopy version
v15.0.1

#### Relevant parts of your build.gradle file
```
chaquopy {
    sourceSets {
        getByName("main") {
            srcDir("src/main/python")
        }
    }
    defaultConfig {
        version = "3.8"
        pip {
            install "pandas"
            install "numpy"
            install "prophet"
        }
    }
}
```

#### Describe your issue
```
> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-13.1
Collecting pandas
  Using cached https://chaquo.com/pypi-13.1/pandas/pandas-1.3.2-0-cp38-cp38-android_21_arm64_v8a.whl (9.8 MB)
Collecting numpy
  Using cached https://chaquo.com/pypi-13.1/numpy/numpy-1.19.5-0-cp38-cp38-android_21_arm64_v8a.whl (3.8 MB)
Collecting prophet
  Using cached prophet-1.1.5.tar.gz (65 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting chaquopy-libcxx>=10000
  Using cached https://chaquo.com/pypi-13.1/chaquopy-libcxx/chaquopy_libcxx-11000-0-py3-none-android_21_arm64_v8a.whl (308 kB)
Collecting pytz>=2017.3
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting chaquopy-libgfortran>=4.9
  Using cached https://chaquo.com/pypi-13.1/chaquopy-libgfortran/chaquopy_libgfortran-4.9-0-py3-none-android_21_arm64_v8a.whl (495 kB)
Collecting chaquopy-openblas>=0.2.20
  Using cached https://chaquo.com/pypi-13.1/chaquopy-openblas/chaquopy_openblas-0.2.20-5-py3-none-android_21_arm64_v8a.whl (4.3 MB)
Collecting cmdstanpy>=1.0.4
  Using cached cmdstanpy-1.2.4-py3-none-any.whl (94 kB)
Collecting matplotlib>=2.0.0
  Using cached https://chaquo.com/pypi-13.1/matplotlib/matplotlib-3.6.0-0-cp38-cp38-android_21_arm64_v8a.whl (6.9 MB)
Collecting holidays>=0.25
  Using cached holidays-0.55-py3-none-any.whl (1.1 MB)
Collecting importlib-resources
  Using cached importlib_resources-6.4.3-py3-none-any.whl (35 kB)
Collecting tqdm>=4.36.1
  Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting stanio<2.0.0,>=0.4.0
  Using cached stanio-0.5.1-py3-none-any.whl (8.1 kB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.53.1-py3-none-any.whl (1.1 MB)
Collecting chaquopy-freetype>=2.9.1
  Using cached https://chaquo.com/pypi-13.1/chaquopy-freetype/chaquopy_freetype-2.9.1-2-py3-none-android_21_arm64_v8a.whl (533 kB)
Collecting pillow>=6.2.0
  Using cached https://chaquo.com/pypi-13.1/pillow/Pillow-9.2.0-0-cp38-cp38-android_21_arm64_v8a.whl (488 kB)
Collecting packaging>=20.0
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
Collecting kiwisolver>=1.0.1
  Using cached https://chaquo.com/pypi-13.1/kiwisolver/kiwisolver-1.4.5-0-cp38-cp38-android_21_arm64_v8a.whl (70 kB)
Collecting contourpy>=1.0.1
  Using cached https://chaquo.com/pypi-13.1/contourpy/contourpy-1.0.5-0-cp38-cp38-android_21_arm64_v8a.whl (212 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Collecting chaquopy-libpng>=1.6.34
  Using cached https://chaquo.com/pypi-13.1/chaquopy-libpng/chaquopy_libpng-1.6.34-1-py3-none-android_21_arm64_v8a.whl (175 kB)
Collecting zipp>=3.1.0; python_version < "3.10"
  Using cached zipp-3.20.0-py3-none-any.whl (9.4 kB)
Collecting chaquopy-libjpeg>=1.5.3
  Using cached https://chaquo.com/pypi-13.1/chaquopy-libjpeg/chaquopy_libjpeg-1.5.3-1-py3-none-android_21_arm64_v8a.whl (176 kB)
Building wheels for collected packages: prophet
  Building wheel for prophet (PEP 517): started
  Building wheel for prophet (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/bin/python /home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpl_2bh50g
       cwd: /tmp/pip-install-inwaoyzt/prophet
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-38
  creating build/lib.linux-x86_64-cpython-38/prophet
  creating build/lib.linux-x86_64-cpython-38/prophet/stan_model
  /tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'test_suite'
    warnings.warn(msg)
  Compiling cmdstanpy model
  Installing cmdstan to /tmp/pip-install-inwaoyzt/prophet/build/lib.linux-x86_64-cpython-38/prophet/stan_model/cmdstan-2.33.1
  CmdStan install directory: /tmp/pip-install-inwaoyzt/prophet/build/lib.linux-x86_64-cpython-38/prophet/stan_model
  Installing CmdStan version: 2.33.1
  Downloading CmdStan version 2.33.1
  Download successful, file: /tmp/tmp6af_xvcc         
  Extracting distribution
                                                         Unpacked download as cmdstan-2.33.1
  Building version cmdstan-2.33.1, may take several minutes, depending on your system.
  cmd: make build -j12
  cwd: None
  10:52:05 - cmdstanpy - WARNING - CmdStan installation failed.
  Command "make build" failed
  Command ['make', 'build', '-j12']
        error during processing No such file or directory
  CmdStan installation failed.
  Command "make build" failed
  Command ['make', 'build', '-j12']
        error during processing No such file or directory
  /bin/sh: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:117: *** "Need to set TBB_CXX_TYPE for non-standard compiler other than gcc or clang.".  Stop.
  Traceback (most recent call last):
    File "/home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 420, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 402, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 199, in <module>
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 111, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/wheel/_bdist_wheel.py", line 378, in run
      self.run_command("build")
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-9wlrtm9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "<string>", line 160, in run
    File "<string>", line 147, in build_models
    File "<string>", line 121, in build_cmdstan_model
    File "<string>", line 98, in install_cmdstan_deps
  RuntimeError: CmdStan failed to install in repackaged directory
  ----------------------------------------
ERROR: Failed to install prophet from https://files.pythonhosted.org/packages/28/bb/1fc769838af6e75f23606e831f60c661a8d80074a5761bf6418b64568712/prophet-1.1.5.tar.gz#sha256=80973c0b8a22d835bfa9d6665a78ebc63115135eaef0f73b46ee14e9bad3ca1a.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
```

If I export TBB_CXX_TYPE="gcc", also failed to compile cmdstan.

```
CmdStan install directory: /tmp/pip-install-vc58cuth/prophet/build/lib.linux-x86_64-cpython-38/prophet/stan_model
  Installing CmdStan version: 2.33.1
  Downloading CmdStan version 2.33.1
  Download successful, file: /tmp/tmpppeea3q1         
  Extracting distribution
                                                          Unpacked download as cmdstan-2.33.1
  Building version cmdstan-2.33.1, may take several minutes, depending on your system.
  cmd: make build -j12
  cwd: None
  14:44:52 - cmdstanpy - WARNING - CmdStan installation failed.
  Command "make build" failed
  Command ['make', 'build', '-j12']
        error during processing No such file or directory
  CmdStan installation failed.
  Command "make build" failed
  Command ['make', 'build', '-j12']
        error during processing No such file or directory
  /bin/sh: Chaquopy_cannot_compile_native_code: command not found
  cp bin/linux-stanc bin/stanc
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/sundials/sundials_math.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/sundials/sundials_math.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/nvector/serial/nvector_serial.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/nvector/serial/nvector_serial.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_diag.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_diag.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_io.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_io.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_ls.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_ls.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_spils.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_spils.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_bbdpre.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_bbdpre.o
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_nls_stg.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_nls_stg.o
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_diag.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_diag.o] Error 127
  make: *** Waiting for unfinished jobs....
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_direct.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_direct.o
  bash: Chaquopy_cannot_compile_native_code: command not found
  Chaquopy_cannot_compile_native_code -pipe   -D_REENTRANT  -O3 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -DNO_FPRINTF_OUTPUT     -O3  -c -x c -include stan/lib/stan_math/lib/sundials_6.1.1/include/stan_sundials_printf_override.hpp stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea_io.c -o stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea_io.o
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/sundials/sundials_math.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/sundials/sundials_math.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_ls.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_ls.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_nls_stg.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_nls_stg.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_spils.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_spils.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_bbdpre.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_bbdpre.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_io.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_io.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_direct.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodes_direct.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/nvector/serial/nvector_serial.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/nvector/serial/nvector_serial.o] Error 127
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea_io.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea_io.o] Error 127
  bash: Chaquopy_cannot_compile_native_code: command not found
  chmod +x bin/stanc
  stan/lib/stan_math/make/libraries:63: recipe for target 'stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea.o' failed
  make: *** [stan/lib/stan_math/lib/sundials_6.1.1/src/cvodes/cvodea.o] Error 127
  Traceback (most recent call last):
    File "/home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/tkyang/work/atv/chiron/otv/apps/atv/app/build/python/env/debug/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 420, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 402, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 199, in <module>
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 111, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/wheel/_bdist_wheel.py", line 378, in run
      self.run_command("build")
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-frkeca9r/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "<string>", line 160, in run
    File "<string>", line 147, in build_models
    File "<string>", line 121, in build_cmdstan_model
    File "<string>", line 98, in install_cmdstan_deps
  RuntimeError: CmdStan failed to install in repackaged directory
```
