### ISSUE TITLE
torch package error

### ISSUE THREAD

**Issue by xiaomei1995** [chaquo/chaquopy#247]
pip {
                install "Beautifulsoup4"
                install "bs4"
                install "torch"
            }

# the python scipy test.py
import torch

# error is:
/QarthLog: [PatchStore] createDisableExceptionQarthFile
    [PatchStore] create disable file for mycanera.zdl.com.mycamera uid is 10722
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mycanera.zdl.com.mycamera, PID: 14040
    com.chaquo.python.PyException: RuntimeError: Unable to find torch_shm_manager at /android_asset/chaquopy/requirements-common.zip/torch/bin/torch_shm_manager
        at <python>.torch.manager_path(__init__.py:244)
        at <python>.torch.<module>(__init__.py:249)
        at <python>.java.android.importer.load_module_impl(importer.py:435)
        at <python>.java.android.importer.load_module(importer.py:353)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.text.<module>(text.py:12)
        at <python>.java.android.importer.load_module_impl(importer.py:435)
        at <python>.java.android.importer.load_module(importer.py:353)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
        at <python>.importlib.import_module(__init__.py:126)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModule(Native Method)
        at mycanera.zdl.com.mycamera.MainActivity.detectBox(MainActivity.java:362)
        at mycanera.zdl.com.mycamera.MainActivity.onClick(MainActivity.java:193)
        at android.view.View.performClick(View.java:7192)
        at android.view.View.performClickInternal(View.java:7166)
        at android.view.View.access$3500(View.java:824)
        at android.view.View$PerformClick.run(View.java:27592)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8169)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Process: Sending signal. PID: 14040 SIG: 9
Process 14040 terminated.

**Comment by mhsmith** [comment]
Please edit your top-level build.gradle file to change com.chaquo.python:gradle to version 7.0.2. This will allow you to use PyTorch version 1.4.0 for all ABIs.

(Alternatively, if you use Chaquopy version 6.3.0 then you can use PyTorch version 1.1.0, but this is available for armeabi-v7a only.)
