### ISSUE TITLE
torch CPUAllocator memory error

### ISSUE THREAD

**Issue by xiaomei1995** [chaquo/chaquopy#249]
# com.chaquo.python:gradle to version 7.0.2

# python
import torch
model = torch.load(torchPath)
output, _ = model(torch.randn(1, 3, 500, 400))

# error is 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mycanera.zdl.com.mycamera, PID: 25426
    com.chaquo.python.PyException: RuntimeError: [enforce fail at CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 38400000 bytes. Buy new RAM!
    (no backtrace available)

**Comment by mhsmith** [comment]
I see that 38400000 == 1 * 3 * 500 * 400 * 64. Does the problem happen with `torch.randn` alone, without any model?

Do you have any other torch-related code or environment variables which could be relevant? For example, could it be attempting to allocate memory on a GPU?

What devices or emulators does the problem occur on?

**Comment by xiaomei1995** [comment]
@mhsmith 

# this problem occur on HUAWEI HONOR 10 (6G RAM + 128G ROM)

# python
from craft import CRAFT
import torch
torchPath = "/storage/emulated/0/OCR/craft.pkl"
model = torch.load(torchPath)

def detect_lines():
    print('start test torch!!!')
    example = torch.randn(1, 3, 500, 400)
    output, _ = model(example)
    # output =torch.randn(1, 3, 768, 768)
    print("torch detection over!!!",output.shape)

# error is
I/python.stdout: start test torch!!!
     
D/: [ZeroHung]zrhung_send_event: wp = 257, ret = 0
D/: [ZeroHung]zrhung_send_event: wp = 258, ret = 0
W/libc: memalign(64, 38400000) failed: returning null pointer
I/BlockMonitor: dispatchingThrewException In MainThread
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
    [PatchStore] create disable file for mycanera.zdl.com.mycamera uid is 10722
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mycanera.zdl.com.mycamera, PID: 17645
    com.chaquo.python.PyException: RuntimeError: [enforce fail at CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 38400000 bytes. Buy new RAM!
    (no backtrace available)
        at <python>.torch.nn.modules.conv.conv2d_forward(conv.py:341)
        at <python>.torch.nn.modules.conv.forward(conv.py:345)
        at <python>.torch.nn.modules.module.__call__(module.py:532)
        at <python>.torch.nn.modules.container.forward(container.py:100)
        at <python>.torch.nn.modules.module.__call__(module.py:532)
        at <python>.craft.forward(craft.py:26)
        at <python>.torch.nn.modules.module.__call__(module.py:532)
        at <python>.craft.forward(craft.py:76)
        at <python>.torch.nn.modules.module.__call__(module.py:532)
        at <python>.craft_detector.detect_lines(craft_detector.py:12)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at mycanera.zdl.com.mycamera.MainActivity.detectBox(MainActivity.java:363)
        at mycanera.zdl.com.mycamera.MainActivity.onClick(MainActivity.java:193)
        at android.view.View.performClick(View.java:7192)
        at android.view.View.performClickInternal(View.java:7166)
        at android.view.View.access$3500(View.java:824)
        at android.view.View$PerformClick.run(View.java:27592)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8169)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Process: Sending signal. PID: 17645 SIG: 9
Process 17645 terminated.

**Comment by mhsmith** [comment]
Can you upload the model file and the app source code to GitHub, or at least a simplified version which shows the same problem?

**Comment by mhsmith** [comment]
And can you confirm that the problem doesn't occur when doing the same thing on a desktop OS, with the same version of PyTorch?

**Comment by mhsmith** [comment]
If this is still a problem, please reopen and provide the requested information.
