### ISSUE TITLE
Image processing problems

### ISSUE THREAD

**Issue by davidyang180** [chaquo/chaquopy#260]
I used chaquopy to call OpenCV image processing algorithm a few days ago, which is useful, but 
there are errors after testing in the same environment today. What is the cause of this problem?

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.demo.myapplication/com.demo.myapplication.MainActivity}: com.chaquo.python.PyException: ValueError: not enough values to unpack (expected 3, got 2)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: com.chaquo.python.PyException: ValueError: not enough values to unpack (expected 3, got 2)
        at <python>.sehuan.findcnts_and_box_point(sehuan.py:64)
        at <python>.sehuan.identification(sehuan.py:138)
        at <python>.sehuan.<module>(sehuan.py:156)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:153)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.demo.myapplication.MainActivity.callPythonCode(MainActivity.java:48)
        at com.demo.myapplication.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**Comment by mhsmith** [comment]
I assume your `findcnts_and_box_point` function is something like [this one](https://github.com/gengyi/RMB-2/blob/1a8ef2509129cd3577d358522e13198bb51b36fb/rmb.py#L54), and the error comes from calling `cv2.findContours`.

Searching Google for `cv2.findContours "expected 3 got 2"` gives many explanations of this error.

If it worked a few days ago and it's not working now, then you'd better examine what you've changed in that time.
