### ISSUE TITLE
Simple Example Android API Code..

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy#29]
I'd like to write a simple example code of Android API but failed. Please give me some ideas.

The python code which is in "py_test.py" of "test1" python package folder :
```
from java import *

class py_print():
    def __init__(self, name):
        name="Chaquopy"
        print(name)

```
The Java code:
```
import com.chaquo.python.*;

public class MainActivity extends AppCompatActivity {
    protected Python py;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        py = Python.getInstance();
        PyObject py_test = py.getModule("test1.py_test");
        stream= py_test.py_print.call("Chaquopy");
        System.out.println(stream)
```
Plan to send a string to python from Java, and python return a string to Java.
python can print the string from Java and Java can printh the string from python, to confirm if it works.
Thanks.

**Comment by mhsmith** [comment]
How does it fail?

**Comment by hushanhsiang** [comment]
Ok, I knew above code will generate Grandle error, I need your correction to let it work.

Is there a document to descript how Java can call the method of Python's class or Python's function?
And I need a simple example.

Below modified code without Grandle error but Logcat generate:``` No module named 'test1.py_test.py_print'; 'test1.py_test' is not a package```

```
package com.oscarhu.python.java_call_py1;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.chaquo.python.*;
public class MainActivity extends AppCompatActivity {
    protected Python py;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        py = Python.getInstance();
        PyObject py_test = py.getModule("test1.py_test.py_print");
        PyObject stream= py_test.call("Chaquopy");
        System.out.println(stream);
```
I need a way for Java call Python's method and fucction with return a string.
Thanks..

**Comment by mhsmith** [comment]
`py_print` is a member of the module, not a module itself. You can access it like this:
```
PyObject py_test = py.getModule("test1.py_test");
py_test.callAttr("py_print", "Chaquopy");
```
If you wanted to get a reference to a module member without immediately calling it, you could also use [get()](https://chaquo.com/chaquopy/doc/current/java/com/chaquo/python/PyObject.html#get-java.lang.Object-):
```
PyObject py_print = py_test.get("py_print");
py_print.call("Chaquopy");
```
The [Java API demo](https://github.com/chaquo/chaquopy/blob/master/app/src/main/java/com/chaquo/python/demo/JavaDemoActivity.java) also demonstrates how to convert a Python return value to a Java string.

**Comment by hushanhsiang** [comment]
It's working to call Python's class/method, I knew there's ".callAttr" used in Java API Demo, but the document says the first argument is "key", I don't know what's the definition of "key".
 Would you please tell me what is "key"?

Which part of Java API demo to demonstrate about get a return Java string from Python?
Thanks.

**Comment by mhsmith** [comment]
"key" is the name of the attribute being used. It's the same as the "name" argument to [getattr()](https://docs.python.org/3/library/functions.html#getattr), but it's called "key" for consistency with the Java [Map](https://developer.android.com/reference/java/util/Map.html) interface which PyObject implements.

You can convert a PyObject to a Java string using `.toJava(String.class)`, or just `.toString()`.

**Comment by hushanhsiang** [comment]
Below is the most simple example of Java API of Chaquopy which is workable that I can create.

The python code which is in "py_test.py" of "test1" python package folder :
```
from java import *

def py_function(name):
    print(name)
    return("Return from Python")
```
The Java code:
```
public class MainActivity extends AppCompatActivity {
    protected Python py;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        py = Python.getInstance();
        PyObject py_test = py.getModule("test1.py_test");
        PyObject stream = py_test.callAttr("py_function","Chaquopy_from Java");
        System.out.println(stream.toString());
```
I change the method of class (the previous code) to a fuction since I got problem to use method of python's class.

How to use  "py_return" method in Java code as below?
 I cannot find a document in Chaquopy website to talk about it. Thanks.
```
from java import *

class py_class():
    def __init__(self, name):
        print( name)
    @property
    def py_return(self):
        return("Return form py_return")
```

**Comment by mhsmith** [comment]
Please describe what you've tried and what happened. That way, I can understand how the documentation can be improved.

**Comment by hushanhsiang** [comment]
If I tried ```PyObject stream= py_test.callAttr("py_class.py_return")``` as below:
```
        py = Python.getInstance();
        PyObject py_test = py.getModule("test1.py_test");
        PyObject stream= py_test.callAttr("py_class.py_return");
        System.out.println(stream.toString());
```
The error will be ```  AttributeError: module 'test1.py_test' has no attribute 'py_class.py_return'``` as below:
```
1-28 21:37:26.452 5093-5093/com.oscarhu.python.java_call_py1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.oscarhu.python.java_call_py1, PID: 5093
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oscarhu.python.java_call_py1/com.oscarhu.python.java_call_py1.MainActivity}: com.chaquo.python.PyException: AttributeError: module 'test1.py_test' has no attribute 'py_class.py_return'
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                 Caused by: com.chaquo.python.PyException: AttributeError: module 'test1.py_test' has no attribute 'py_class.py_return'
                                                                                    at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows (.c:4596)(chaquopy_java.pyx:226)
                                                                                    at com.chaquo.python.PyObject.callAttrThrows(Native Method)
                                                                                    at com.chaquo.python.PyObject.callAttr(PyObject.java:135)
                                                                                    at com.oscarhu.python.java_call_py1.MainActivity.onCreate(MainActivity.java:26)
                                                                                    at android.app.Activity.performCreate(Activity.java:6323)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5451) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```


If changed to below: 
```
        py = Python.getInstance();
        PyObject py_test = py.getModule("test1.py_test");
        PyObject py_class = py.getModule("test1.py_test.py_class");
        PyObject stream= py_class.callAttr("py_return");
        System.out.println(stream.toString());
```
The error will be:``` No module named 'test1.py_test.py_class'; 'test1.py_test' ```.

```
01-28 21:46:40.223 6311-6311/com.oscarhu.python.java_call_py1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.oscarhu.python.java_call_py1, PID: 6311
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oscarhu.python.java_call_py1/com.oscarhu.python.java_call_py1.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'test1.py_test.py_class'; 'test1.py_test' is not a package
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                 Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'test1.py_test.py_class'; 'test1.py_test' is not a package
                                                                                    at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:950)
                                                                                    at <python>._find_and_load(<frozen importlib._bootstrap>:971)
                                                                                    at <python>._gcd_import(<frozen importlib._bootstrap>:994)
                                                                                    at <python>.import_module(/data/user/0/com.oscarhu.python.java_call_py1/files/chaquopy/stdlib.zip/importlib/__init__.py:126)
                                                                                    at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule (.c:2790)(chaquopy_java.pyx:128)
                                                                                    at com.chaquo.python.Python.getModule(Native Method)
                                                                                    at com.oscarhu.python.java_call_py1.MainActivity.onCreate(MainActivity.java:25)
                                                                                    at android.app.Activity.performCreate(Activity.java:6323)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5451) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
01-28 21:46:40.264 6311-6311/? I/Process: Sending signal. PID: 6311 SIG: 9
```
Between Module and Attribution, I have no idea how to handle class method without an example code.
Thanks.

**Comment by mhsmith** [comment]
I don't know why you've used `@property`. In Python that would mean you have to use attribute rather than method syntax:
```
py_class("Oscar").py_return     # py_test.callAttr("py_class", "Oscar").get("py_return")
```

If you'd used [`@classmethod`](https://docs.python.org/3/library/functions.html#classmethod) instead of `@property`, then you could do this:

```
py_class.py_return()            # py_test.get("py_class").callAttr("py_return")
```

Or if you'd not used any decorators and made it a normal instance method:
```
py_class("Oscar").py_return()   # py_test.callAttr("py_class", "Oscar").callAttr("py_return")
```

I'll add some more one-line examples like this to the documentation soon.

**Comment by hushanhsiang** [comment]
It's great to have your words. I modify my code to the three condition as below:
Python code which is in "py_test.py" of "test1" python package folder:
```
from java import *


class py_class():
    def __init__(self, name):
        print( name)
    @property
    def py_return1(self):
        return("Return form py_return-1")

    @classmethod
    def py_return2(self):
        return("Return form py_return-2")

    def py_return3(self):
        return("Return form py_return-3")
```
Java side:
```
public class MainActivity extends AppCompatActivity {
    protected Python py;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);
        py = Python.getInstance();
        PyObject py_test = py.getModule("test1.py_test");

        PyObject stream =py_test.callAttr("py_class", "Oscar").get("py_return1");
        System.out.println(stream.toString());

        stream = py_test.get("py_class").callAttr("py_return2");
        System.out.println(stream.toString());

        stream = py_test.callAttr("py_class", "Chaquopy").callAttr("py_return3");
        System.out.println(stream.toString());

    }
}

```
There's no any problem and the Locat result:
```
01-30 08:03:34.014 4400-4400/com.oscarhu.python.java_call_py1 I/python.stdout: Oscar
01-30 08:03:34.014 4400-4400/com.oscarhu.python.java_call_py1 I/python.stdout:  
01-30 08:03:34.016 4400-4400/com.oscarhu.python.java_call_py1 I/System.out: Return form py_return-1
01-30 08:03:34.017 4400-4400/com.oscarhu.python.java_call_py1 I/System.out: Return form py_return-2
01-30 08:03:34.018 4400-4400/com.oscarhu.python.java_call_py1 I/python.stdout: Chaquopy
01-30 08:03:34.019 4400-4400/com.oscarhu.python.java_call_py1 I/python.stdout:  
01-30 08:03:34.020 4400-4400/com.oscarhu.python.java_call_py1 I/System.out: Return form py_return-3
01-30 08:03:34.037 4400-4642/com.oscarhu.python.java_call_py1 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
```
This simple example of Java API will be no problem with simple argument transmition.
Thank you very much.

**Comment by mhsmith** [comment]
Some further examples are now in the documentation [here](https://chaquo.com/chaquopy/doc/current/java.html).

**Comment by Rajesh041988** [comment]
I tried above solution but i got the error : Unresolved reference 'classmethod' 
Inspection info: This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items. on @classmethod
 and also i added : defaultConfig {
        ndk {
           abiFilters "x86", "armeabi-v7a"
        }
    }
but getting error : No python interpreter configured for the module
please give me the suggestion.

**Comment by mhsmith** [comment]
Only a few features of the Python Community Edition plugin will work properly with Chaquopy. Most of the IDE assistance will be unavailable, but the build and runtime processes should still work fine. See #96 for details.

**Comment by Rajesh041988** [comment]
I tried hushanhsiang's above example to call python script from my android java but i always getting 'null' stream. Also i tried ' py_class.py_return() ' this for calling python but gives error like "py_return" not recognized by java , how can i solved it?

**Comment by Rajesh041988** [comment]
Thank you for your quick reply, its very helpful. I have one more query : how can i call '**if __name__ == "__main__":** 'from my java (android)

**Comment by mhsmith** [comment]
You can get `__name__` just like any other module variable: `py.getModule(...).get("__name__")`. 

However, `__name__` will never have the value `"__main__"` in Chaquopy, because it's running within an Android app process, not as a stand-alone Python interpreter.

Please create separate issues for any further questions.
