### ISSUE TITLE
How to load audio file using Librosa?

### ISSUE THREAD

**Issue by sayantan99** [chaquo/chaquopy#301]
import librosa as lr

def test():

	(signal, rate)= lr.load("heart.wav", sr=None)

	return rate

Though my audio file and python file are in the same folder. I am getting this error.

UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
2020-05-31 19:17:01.942 8141-8141/com.example.chao D/AndroidRuntime: Shutting down VM
2020-05-31 19:17:01.950 8141-8141/com.example.chao E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chao, PID: 8141
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.chao/com.example.chao.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/heart.wav'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)

**Comment by mhsmith** [comment]
See #144 .
