### ISSUE TITLE
Can .so files be run using Chaquopy?

### ISSUE THREAD

**Issue by sayan-sen** [chaquo/chaquopy#302]
i am trying to call a .so file but it fails. 

**MainActivity.java:**
```
Python py = Python.getInstance();
PyObject pyf = py.getModule("temp");
```
**temp.py:**
```
from test1 import showimg
showimg(1,2)
```
I am trying to call _**test1.so**_ file instead of **_test1.py_** but it fails:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.styleapp, PID: 8801
    com.chaquo.python.PyException: ELFError: Magic number does not match
        at <python>.java._vendor.elftools.common.utils._assert_with_exception(utils.py:101)
        at <python>.java._vendor.elftools.common.utils.elf_assert(utils.py:69)
        at <python>.java._vendor.elftools.elf.elffile._identify_file(elffile.py:229)
        at <python>.java._vendor.elftools.elf.elffile.__init__(elffile.py:61)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.temp.<module>(temp.py:1)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:503)
        at <python>.java.android.importer.exec_module(importer.py:546)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:152)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.styleapp.MainActivity.runthemodel(MainActivity.java:126)
        at com.example.styleapp.MainActivity.access$000(MainActivity.java:45)
        at com.example.styleapp.MainActivity$2.onMenuItemClick(MainActivity.java:102)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27355)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7410)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```
But if i call **_test1.py_**, it runs succesfully. Here is my **test1.py**:
```
def showimg(i,j):
    print(i+j)
```
Why does it fail? Previously i have been told that Chaquopy doesnt import-and-run .pyc files. Does it not support .so files?

**Comment by mhsmith** [comment]
You can load .so files if they're built for Android (*not* Linux). However, if you're receiving that error then it probably isn't a valid .so file at all. Where did it come from?

**Comment by sayan-sen** [comment]
i built it using cython:
```
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize('test1.py')
)
```
How to build .so file for android? you have any suggestions?

**Comment by mhsmith** [comment]
Are you doing this because you want to hide your code? If you're not satisfied with merely compiling to pyc format, as we discussed in #295, then you should look into Python obfuscation tools, which will be be much easier than trying to compile for Android using Cython.

**Comment by sayan-sen** [comment]
Actually I need to build that .so file in Android env, so for that how to use this command using Chaquopy:
`python setup.py build_ext -b /sdcard/Download/ -t .
`
**Setup.py:**
```
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize('test1.py')
)
```

This will build the .so file in /sdcard/Download/ location. How to run that command in chaquopy?

**Comment by sayan-sen** [comment]
am trying to use 
`PyObject os= py.getModule("setup.py build_ext -b /sdcard/Download/ -t .");
`
But it gives runtime error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.styleapp, PID: 13103
    com.chaquo.python.PyException: ValueError: 'test1.py' doesn't match any files
        at <python>.Cython.Build.Dependencies.nonempty(Dependencies.py:114)
        at <python>.Cython.Build.Dependencies.create_extension_list(Dependencies.py:815)
        at <python>.Cython.Build.Dependencies.cythonize(Dependencies.py:965)
        at <python>.setup.<module>(setup.py:5)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:503)
        at <python>.java.android.importer.exec_module(importer.py:546)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:961)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:961)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:152)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.styleapp.MainActivity.runthemodel(MainActivity.java:127)
        at com.example.styleapp.MainActivity.access$000(MainActivity.java:47)
        at com.example.styleapp.MainActivity$2.onMenuItemClick(MainActivity.java:103)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27355)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7410)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by sayan-sen** [comment]
I need to Cythonize because because .pyc bytecode is decompileable and the obfuscation is easily reverse-engineered.
So now am using:
`        PyObject os= py.getModule("setup");
`
where setup.py:
```
from setuptools import setup
from Cython.Build import cythonize
import os
print(os.getcwd())
os.chdir('/sdcard/Download')
print(os.getcwd())

setup(
    ext_modules=cythonize('test1.py')
)
```
I have put the python script **_test1.py_** in **_/sdcard/Download_**. 
But now it throws the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.styleapp, PID: 18166
    com.chaquo.python.PyException: SystemExit: usage:  [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or:  --help [cmd1 cmd2 ...]
       or:  --help-commands
       or:  cmd --help
    
    error: no commands supplied
        at <python>.distutils.core.setup(core.py:136)
        at <python>.setuptools.setup(__init__.py:161)
        at <python>.setup.<module>(setup.py:8)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:503)
        at <python>.java.android.importer.exec_module(importer.py:546)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:152)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.styleapp.MainActivity.runthemodel(MainActivity.java:127)
        at com.example.styleapp.MainActivity.access$000(MainActivity.java:47)
        at com.example.styleapp.MainActivity$2.onMenuItemClick(MainActivity.java:103)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27355)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7410)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```
Is it because am not passing args to setup.py? like `setup.py build_ext --inplace`

**Comment by sayan-sen** [comment]
Currently am trying to use os.system:
```
import os
os.system('python3 setup.py build_ext -b "/sdcard/Download/" -t .')
```
But 
```
PyObject os = py.getModule("os");
os.callAttr("system","python3 setup.py build_ext -b /sdcard/Download/ -t .");
``` 
is not even calling the _setup.py_ script.

**Comment by mhsmith** [comment]
You won't be able to compile a Cython module on an actual Android device, because most devices don't come with a compiler.

If you really need to build your code into .so file, then you can license our package build tool which was used to build everything in the [native package repository](https://chaquo.com/pypi-7.0/). It supports Distutils, Cython, CMake, and many other build tools, and handles a wide variety of cross-compilation issues.

The tool runs on Linux only, not Mac or Windows. It comes with an optional Dockerfile for easier dependency management and reproducibility.

The license fee for this tool is $250 -- this is separate to the license for Chaquopy itself. If you'd like to order it, please [email us](https://chaquo.com/chaquopy/contact/) for payment instructions.

**Comment by sayan-sen** [comment]
So the licensed package build tool builds the .so files for Android platform?

**Comment by mhsmith** [comment]
Yes, the way it works is:

* You provide a setup.py script, which it looks like you've already done.
* The tool builds a .whl file which contains the .so.
* You install the .so using [pip install](https://chaquo.com/chaquopy/doc/current/android.html#requirements) in your build.gradle file, just like any other package.

The tool comes with full instructions.
