### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#31]
Received a request for this via email: thumbs up and subscribe if you want it too.

**Comment by mhsmith** [comment]
`opencv-python` can now be installed with Chaquopy 3.1.0 or later (though as always, using the newest version is recommended).

If you want to use the test data, you'll currently need to add the following [`extractPackages`](https://chaquo.com/chaquopy/doc/current/android.html#resource-files) line:

```
extractPackages "cv2.data"
```

This will be added as one of the default `extractPackages` in the next release of Chaquopy.

**Comment by Rajesh041988** [comment]
Got the error :
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'cv2'
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.java._vendor.six.reraise(six.py:686)
        at <python>.java.chaquopy.import_override(import.pxi:59)
        at <python>.img_quality_checker.<module>(img_quality_checker.py:1)
        at <python>.java.android.importer.load_module_impl(importer.py:435)
        at <python>.java.android.importer.load_module(importer.py:353)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
        at <python>.importlib.import_module(__init__.py:126)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.kalptech.imagepro.activities.MainActivity$1.onClick(MainActivity.java:100)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

please provide one example of using opencv

**Comment by mhsmith** [comment]
You'll need to add it as a requirement in your `build.gradle` file, using the syntax described [here](https://chaquo.com/chaquopy/doc/current/android.html#requirements). The package name is `opencv-python`.

**Comment by Rajesh041988** [comment]
I added following lines in my build.gradle, but still getting error:
 python {
            pip {
                install "opencv-python"
            }

**Error :**
04-16 15:27:06.909 20396-20396/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kalptech.imagepro, PID: 20396
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kalptech.imagepro/com.kalptech.imagepro.activities.MainActivity}: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2485)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
     Caused by: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at <python>.java.android.importer.initialize_importlib(importer.py:62)
        at <python>.java.android.importer.initialize(importer.py:40)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:130)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.kalptech.imagepro.activities.MainActivity.onCreate(MainActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:6355)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5601) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by mhsmith** [comment]
Now it seems to be failing at an even earlier stage, without even getting as far as OpenCV. 
* What version of Chaquopy are you using? (`com.chaquo.python:gradle` in your top-level build.gradle file)
* Please post the `python` and `ndk` blocks from your build.gradle file.
* Was adding the `pip` block to build.gradle the only change in the app since your previous comment, or were there other changes as well?

**Comment by Rajesh041988** [comment]
build:gradle (Project) :
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://chaquo.com/maven" }
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'

        classpath "com.chaquo.python:gradle:6.0.0"
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
------------------------------------------------------------------------
build:gradle (app)   :+1: 

apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'        // Add this line for python

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.kalptech.imagepro"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        python {
            pip {
                install "opencv-python"
            }
            buildPython "D:/RAJESH/Softwares/Python/python-3.7.3.exe"
            extractPackages "cv2"

        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

configurations.all {exclude group: 'com.android.support', module: 'support-v4'}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.commit451:PhotoView:1.2.4'
}

**Comment by Rajesh041988** [comment]
> 
> 
> build:gradle (Project) :
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
> repositories {
> google()
> jcenter()
> maven { url "https://chaquo.com/maven" }
> 
> ```
> }
> dependencies {
>     classpath 'com.android.tools.build:gradle:3.3.0'
> 
>     classpath "com.chaquo.python:gradle:6.0.0"
>     
>     // NOTE: Do not place your application dependencies here; they belong
>     // in the individual module build.gradle files
> }
> ```
> 
> }
> 
> allprojects {
> repositories {
> google()
> jcenter()
> 
> ```
> }
> ```
> 
> }
> ## task clean(type: Delete) {
> delete rootProject.buildDir
> }
> 
> build:gradle (app) :
> 
> apply plugin: 'com.android.application'
> apply plugin: 'com.chaquo.python' // Add this line for python
> 
> android {
> compileSdkVersion 28
> defaultConfig {
> applicationId "com.kalptech.imagepro"
> minSdkVersion 16
> targetSdkVersion 28
> versionCode 1
> versionName "1.0"
> testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> 
> ```
>     ndk {
>         abiFilters "armeabi-v7a", "x86"
>     }
>     python {
>         pip {
>             install "opencv-python"
>         }
>         buildPython "D:/RAJESH/Softwares/Python/python-3.7.3.exe"
>         extractPackages "cv2"
> 
>     }
> }
> buildTypes {
>     release {
>         minifyEnabled false
>         proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>     }
> }
> ```
> 
> }
> 
> configurations.all {exclude group: 'com.android.support', module: 'support-v4'}
> dependencies {
> implementation fileTree(dir: 'libs', include: ['*.jar'])
> implementation 'com.android.support:appcompat-v7:28.0.0'
> implementation 'com.android.support.constraint:constraint-layout:1.1.3'
> testImplementation 'junit:junit:4.12'
> androidTestImplementation 'com.android.support.testrunning_man1.0.2'
> androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> 
> ```
> implementation 'com.commit451:PhotoView:1.2.4'
> ```
> 
> }

**Comment by Rajesh041988** [comment]
I solved above issue by following bellow : 
file > invalidate catches / restart.....

now i want the package name for 'pill' and 'logging' 
i got following error : 
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'PIL'
