### ISSUE TITLE
Unable to read the file from sdcard folder in Python script

### ISSUE THREAD

**Issue by VPrasannakumar** [chaquo/chaquopy#312]
Hi,
I am running python script from android Java code using chaquopy.

**JAVA source code -**
 ```
 if (!Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }
        Python python = Python.getInstance();
        PyObject pythonFile = python.getModule("generate_FP");
        File path = new File(Environment.getExternalStorageDirectory() + "/media/audio/ringtones/Albg.mp3");
     if(path.exists()) {
           // PyObject helloWorldString = pythonFile.callAttr("generate_fp", "/media/audio/ringtones/Albg.mp3");
            PyObject helloWorldString = pythonFile.callAttr("generate_fp", path.toString());
            Log.v("MainActivity   ", "Python - " + helloWorldString.toString());
        }else
            Log.v("MainActivity   ", "Python - file is not exist" );
```

**Python script -**

```
 print('filename is',filename)
    filename = str(Environment.getExternalStorageDirectory())+filename
    if os.path.exists(filename):
        print('true')
    else :
        print('false')
    print(os.access('filename',os.R_OK))  **Output - False**
```

**Error message** 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gaian.testpython/com.gaian.testpython.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/media/audio/ringtones/Albg.mp3'`

Please help for resolving this issue
Thank you.

**Comment by mhsmith** [comment]
You need to request the external storage permission. See [here](https://stackoverflow.com/questions/32431723) for an example.

**Comment by VPrasannakumar** [comment]
I have given external storage permission also
`   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"></uses-permission>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"></uses-permission>`

**Comment by mhsmith** [comment]
On newer versions of Android it's not enough to list them in your AndroidManifest anymore, you also need to interactively request the user's permission. See the answer in my previous link.

**Comment by VPrasannakumar** [comment]
Dear mhsmith,
I added that functionality already. Could you please check the below for activity class

`public class MainActivity extends AppCompatActivity {

    final static String TAG ="MainActivity";

    private static final int REQUEST_PERMISSIONS = 100;
    private static final String PERMISSIONS_REQUIRED[] = new String[]{
            android.Manifest.permission.READ_EXTERNAL_STORAGE
            , Manifest.permission.WRITE_EXTERNAL_STORAGE,Manifest.permission.ACCESS_NETWORK_STATE
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {

            checkPermissions();
        }




    }

    private void navigatetoBrowser(){

        if (!Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }


        Python python = Python.getInstance();
        PyObject pythonFile = python.getModule("generate_FP");
        File path = new File(Environment.getExternalStorageDirectory() + "/media/audio/ringtones/Albg.mp3");

       if(path.exists()) {
            //PyObject helloWorldString = pythonFile.callAttr("generate_fp", "/media/audio/ringtones/Albg.mp3");
           PyObject helloWorldString = pythonFile.callAttr("generate_fp", path.toString());
            Log.v("MainActivity   ", "Python - " + helloWorldString.toString());
        }else
            Log.v("MainActivity   ", "Python - file is not exist" );

    }


    private void checkPermissions() {
        boolean permissionsGranted = checkPermission(PERMISSIONS_REQUIRED);
        if (permissionsGranted) {
            navigatetoBrowser();
            Toast.makeText(this, "You've granted all required permissions!", Toast.LENGTH_SHORT).show();
        } else {
            boolean showRationale = true;
            for (String permission : PERMISSIONS_REQUIRED) {
                showRationale = ActivityCompat.shouldShowRequestPermissionRationale(this, permission);
                if (!showRationale) {
                    break;
                }
            }

            ActivityCompat.requestPermissions(MainActivity.this, PERMISSIONS_REQUIRED, REQUEST_PERMISSIONS);

        }
    }
    private boolean checkPermission(String permissions[]) {
        for (String permission : permissions) {
            if (ContextCompat.checkSelfPermission(getApplicationContext(), permission) != PackageManager.PERMISSION_GRANTED) {
                return false;
            }
        }
        return true;
    }
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        Log.d(TAG, "requestCode: " + requestCode);
        //Log.d(TAG, "Permissions:" + Arrays.toString(permissions));
        //Log.d(TAG, "grantResults: " + Arrays.toString(grantResults));

        if (requestCode == REQUEST_PERMISSIONS) {
            boolean hasGrantedPermissions = true;
            for (int i = 0; i < grantResults.length; i++) {
                if (grantResults[i] != PackageManager.PERMISSION_GRANTED) {
                    hasGrantedPermissions = false;
                    break;
                }
            }

            if (!hasGrantedPermissions) {

                finish();
            }else{

                navigatetoBrowser();
            }

        } else {

            finish();
        }
    }
}
`

**Comment by mhsmith** [comment]
It looks correct to me, but I know the rules around external storage have changed in recent versions of Android. 

Try adding some code to read the same file in Java using a FileInputStream. If it works in Java but not in Python, then please post details here (including which devices the problem happens on), and I'll look into it further. If it doesn't work work in Java either, then your problem isn't related to Chaquopy and you should seek help elsewhere.

**Comment by VPrasannakumar** [comment]
Dear Smith,
I am able to read the file from sdcard using Fileinputstream in JAVA but not in the python and also I have created media player. Its playing.

**Device details** - Android OS 10 and Model Samsung - A50S

**Python sample code**- 
  print('filename is',filename)
    filename = str(Environment.getExternalStorageDirectory())+filename
    if os.path.exists(filename):
        **print('true')** This one is coming
    else :
        print('false')
    print(os.access('filename',os.W_OK)) - **False** coming

`2020-06-12 12:23:53.181 13238-13238/? V/MainActivity: file size- 255
2020-06-12 12:23:53.182 13238-13238/? V/MediaPlayer-JNI: native_setup
2020-06-12 12:23:53.182 13238-13238/? V/MediaPlayerNative: constructor
2020-06-12 12:23:53.183 13238-13238/? V/MediaPlayerNative: setListener
2020-06-12 12:23:53.186 13238-13238/? V/MediaPlayer-JNI: setDataSourceFD: fd 56
2020-06-12 12:23:53.186 13238-13238/? V/MediaPlayerNative: setDataSource(56, 0, 576460752303423487)
2020-06-12 12:23:53.200 13238-13238/? V/MediaPlayerNative: setVideoSurfaceTexture
2020-06-12 12:23:53.200 13238-13238/? V/MediaPlayerNative: prepare
2020-06-12 12:23:53.215 13238-13255/? V/MediaPlayerNative: message received msg=200, ext1=10973, ext2=0
2020-06-12 12:23:53.215 13238-13255/? W/MediaPlayerNative: info/warning (10973, 0)
2020-06-12 12:23:53.218 13238-13255/? V/MediaPlayerNative: message received msg=1, ext1=0, ext2=0
2020-06-12 12:23:53.218 13238-13255/? V/MediaPlayerNative: MediaPlayer::notify() prepared
2020-06-12 12:23:53.218 13238-13255/? V/MediaPlayerNative: signal application thread
2020-06-12 12:23:53.218 13238-13238/? V/MediaPlayerNative: prepare complete - status=0
2020-06-12 12:23:53.220 13238-13238/? V/MediaPlayerNative: invoke 72
2020-06-12 12:23:53.224 13238-13238/? V/MediaPlayer-JNI: start
2020-06-12 12:23:53.224 13238-13238/? V/MediaPlayerNative: start
2020-06-12 12:23:53.309 13238-13255/? V/MediaPlayerNative: message received msg=6, ext1=0, ext2=0
2020-06-12 12:23:53.478 13238-13255/? V/MediaPlayerNative: message received msg=211, ext1=0, ext2=0
2020-06-12 12:23:53.478 13238-13255/? V/MediaPlayerNative: message received msg=211, ext1=0, ext2=0
2020-06-12 12:23:54.225 13238-13238/com.gaian.testpython V/MediaPlayer-JNI: stop
2020-06-12 12:23:54.225 13238-13238/com.gaian.testpython V/MediaPlayerNative: stop
2020-06-12 12:23:54.225 13238-13255/com.gaian.testpython V/MediaPlayerNative: message received msg=8, ext1=0, ext2=0
2020-06-12 12:23:54.226 13238-13255/com.gaian.testpython V/MediaPlayerNative: message received msg=211, ext1=0, ext2=0
2020-06-12 12:23:54.476 13238-13238/com.gaian.testpython W/aian.testpytho: Accessing hidden method Landroid/os/Handler;-><init>(Landroid/os/Looper;Landroid/os/Handler$Callback;Z)V (greylist, JNI, allowed)
2020-06-12 12:23:54.477 13238-13238/com.gaian.testpython W/aian.testpytho: Accessing hidden method Landroid/os/Handler;-><init>(Z)V (greylist, JNI, allowed)
2020-06-12 12:23:54.681 13238-13238/com.gaian.testpython W/aian.testpytho: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (greylist, JNI, allowed)
2020-06-12 12:23:54.683 13238-13238/com.gaian.testpython W/aian.testpytho: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (greylist, JNI, allowed)
2020-06-12 12:23:56.402 13238-13238/com.gaian.testpython W/python.stderr: /data/user/0/com.gaian.testpython/files/chaquopy/AssetFinder/requirements/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
2020-06-12 12:23:56.405 13238-13238/com.gaian.testpython I/python.stdout: filename is
2020-06-12 12:23:56.405 13238-13238/com.gaian.testpython I/python.stdout:  
2020-06-12 12:23:56.406 13238-13238/com.gaian.testpython I/python.stdout: /media/audio/ringtones/Albg.mp3
2020-06-12 12:23:56.406 13238-13238/com.gaian.testpython I/python.stdout:  
2020-06-12 12:23:56.411 13238-13238/com.gaian.testpython I/python.stdout: true
2020-06-12 12:23:56.411 13238-13238/com.gaian.testpython I/python.stdout:  
2020-06-12 12:23:56.411 13238-13238/com.gaian.testpython I/python.stdout: False
2020-06-12 12:23:56.411 13238-13238/com.gaian.testpython I/python.stdout:  
2020-06-12 12:23:56.450 13238-13238/com.gaian.testpython D/AndroidRuntime: Shutting down VM
2020-06-12 12:23:56.451 13238-13238/com.gaian.testpython E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gaian.testpython, PID: 13238
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gaian.testpython/com.gaian.testpython.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: 'ffprobe'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: 'ffprobe'
        at <python>.subprocess._execute_child(subprocess.py:1702)
        at <python>.subprocess.__init__(subprocess.py:854)
        at <python>.pydub.utils.mediainfo_json(utils.py:274)
        at <python>.pydub.audio_segment.from_file(audio_segment.py:685)
        at <python>.generate_FP.read(generate_FP.py:46)
        at <python>.generate_FP.generate_fp(generate_FP.py:119)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:281)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:253)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.gaian.testpython.MainActivity.navigatetoBrowser(MainActivity.java:103)
        at com.gaian.testpython.MainActivity.checkPermissions(MainActivity.java:116)
        at com.gaian.testpython.MainActivity.onCreate(MainActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7860) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) `

**Comment by mhsmith** [comment]
OK, the PermissionError is different now, and it looks like the problem is not that it can't read the file, but that it can't run ffmpeg (#143).

Unless you can provide your own copy of ffmpeg, you'll have to either decode the MP3 to raw audio using the Android API, or use a .wav file instead.

**Comment by VPrasannakumar** [comment]
Thank you mhsmith. It's working with.wav file.
