### ISSUE TITLE
permission denied on reading file from storage

### ISSUE THREAD

**Issue by vikasgola** [chaquo/chaquopy#318]
```
if (! Python.isStarted()) {
            Python.start(AndroidPlatform(this))
        }

if((Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) and (checkSelfPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED)){
            requestPermissions(
                Array<String>(1000) {android.Manifest.permission.READ_EXTERNAL_STORAGE},
                PERMISSION_REQUEST_STORAGE
            )
        }


        var py = Python.getInstance()
        var pyf = py.getModule("converter")

        var obj = pyf.callAttr("stl_to_gltf", "/storage/emulated/0/Download/wolf.stl", "/storage/emulated/0/Download/wolf.glb")


```

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shahidhar.jeweldisp, PID: 6240
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shahidhar.jeweldisp/com.shahidhar.jeweldisp.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wolf.stl'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wolf.stl'
        at <python>.converter.stl_to_gltf(converter.py:97)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.shahidhar.jeweldisp.MainActivity.onCreate(MainActivity.kt:94)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

```

**Comment by vikasgola** [comment]
Reading file 
```
 with open(path_to_stl, "rb") as f:
    somthings...........
```

**Comment by vikasgola** [comment]
Also, have all permissions in manifest
```

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by mhsmith** [comment]
Please read the Android permissions documentation more carefully. When `requestPermissions` returns, the permission has still not been granted. You need to implement `onRequestPermissionsResult`.

**Comment by vikasgola** [comment]
@mhsmith Its implemented 
```

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        if(requestCode==PERMISSION_REQUEST_STORAGE){
            if(grantResults[0]==PackageManager.PERMISSION_GRANTED){
                Toast.makeText(this,"Permission Granted",Toast.LENGTH_SHORT).show()
            }else{
                Toast.makeText(this,"Permission Denied",Toast.LENGTH_SHORT).show()
                finish()
            }
        }
    }
```

**Comment by vikasgola** [comment]
got it. need to do all things in OnRequestPermissionsResult

**Comment by vikasgola** [comment]
Nope. still permission error

**Comment by vikasgola** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shahidhar.jeweldisp, PID: 17231
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1000, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.shahidhar.jeweldisp/com.shahidhar.jeweldisp.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wolf.stl'
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0/Download/wolf.stl'
        at <python>.converter.stl_to_gltf(converter.py:99)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.shahidhar.jeweldisp.MainActivity.onRequestPermissionsResult(MainActivity.kt:101)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8285)
        at android.app.Activity.dispatchActivityResult(Activity.java:8135)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
I/Process: Sending signal. PID: 17231 SIG: 9

```

**Comment by vikasgola** [comment]
```
    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        if(requestCode==PERMISSION_REQUEST_STORAGE){
            if(grantResults[0]==PackageManager.PERMISSION_GRANTED){
                Toast.makeText(this,"Permission Granted",Toast.LENGTH_SHORT).show()

                var py = Python.getInstance()
                var pyf = py.getModule("converter")
                val path = File(
                    Environment.getExternalStorageDirectory()
                        .toString() + "/Download/"
                )
                var obj = pyf.callAttr("stl_to_gltf", path.toString()+"/wolf.stl", path.toString()+"/wolf.glb")


                createRenderables("/storage/emulated/0/Download/wolf.glb")
                createIndirectLight()

                // enable dynamic resolution
                //        val options = modelViewer.view.dynamicResolutionOptions
                //        options.enabled = true
                //        modelViewer.view.dynamicResolutionOptions = options

                                modelViewer.view.ambientOcclusion = View.AmbientOcclusion.SSAO

                //        val bloom = modelViewer.view.bloomOptions
                //        bloom.enabled = true
                //        modelViewer.view.bloomOptions = bloom
            }else{
                Toast.makeText(this,"Permission Denied",Toast.LENGTH_SHORT).show()
                finish()
            }
        }
    }

```

**Comment by mhsmith** [comment]
I'm not up to date with the current Android rules on external storage, but try adding some code to read the same file in Java using a FileInputStream. If it works in Java but not in Python, then please post details here (including which devices the problem happens on), and I'll look into it further. If it doesn't work work in Java either, then your problem isn't related to Chaquopy and you should seek help elsewhere.

**Comment by mintheinwin** [comment]
Hi vikasgola, 
I had a problem like your question when I requested read file permission. I always got return permission denied for read file permission request. How you solve your issues. Can you share your ideas?
