### ISSUE TITLE
Using Android Studio to generate APK and App Clash out.

### ISSUE THREAD

**Issue by openit123** [chaquo/chaquopy#320]
I am using android studio, when using cable connecting mobile to debug is working. The apps is fine.
But When I generate apk, and send to my mobile, install it, the app would clash.
Below is the Error message:

```
2020-06-19 14:55:22.327 6066-6066/no.nordicsemi.android.nrftoolbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: no.nordicsemi.android.nrftoolbox, PID: 6066
    java.lang.RuntimeException: Unable to start activity ComponentInfo{no.nordicsemi.android.nrftoolbox/no.nordicsemi.android.nrftoolbox.hrs.HRSActivity}: java.lang.ClassNotFoundException: Didn't find class "com.chaquo.python.PyException" on path: DexPathList[[zip file "/data/app/no.nordicsemi.android.nrftoolbox-chMEPgeuum3OCwRnKRt2og==/base.apk"],nativeLibraryDirectories=[/data/app/no.nordicsemi.android.nrftoolbox-chMEPgeuum3OCwRnKRt2og==/lib/arm64, /data/app/no.nordicsemi.android.nrftoolbox-chMEPgeuum3OCwRnKRt2og==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.chaquo.python.PyException" on path: DexPathList[[zip file "/data/app/no.nordicsemi.android.nrftoolbox-chMEPgeuum3OCwRnKRt2og==/base.apk"],nativeLibraryDirectories=[/data/app/no.nordicsemi.android.nrftoolbox-chMEPgeuum3OCwRnKRt2og==/lib/arm64, /data/app/no.nordicsemi.android.nrftoolbox-chMEPgeuum3OCwRnKRt2og==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.chaquo.python.Python.startNative(Native Method)
        at com.chaquo.python.Python.a(:50)
        at no.nordicsemi.android.nrftoolbox.hrs.HRSActivity.b(:275)
        at no.nordicsemi.android.nrftoolbox.profile.BleProfileActivity.onCreate(:90)
        at android.app.Activity.performCreate(Activity.java:7810)
        at android.app.Activity.performCreate(Activity.java:7799)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
```

**Comment by mhsmith** [comment]
Does the problem happen on all devices, including the Android emulator? If it only happens on some devices, which ones?

Could you email me a copy of your APK, or upload it somewhere and send me the link? A simpler app which shows the same problem would also be fine. Of course, I'll treat anything you send me as confidential.

**Comment by mhsmith** [comment]
If this is still a problem, please reopen the issue and give the requested information.

**Comment by mhsmith** [comment]
Duplicate of #261.

**Comment by mhsmith** [comment]
This will be fixed in the next version of Chaquopy. Meanwhile, you can work around it by editing your build.gradle file to change every appearance of `minifyEnabled true` to `minifyEnabled false`.
