### ISSUE TITLE
Android Error:- Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '__pycache__'

### ISSUE THREAD

**Issue by Unicas** [chaquo/chaquopy#358]
Hi there, this error has been frustrating me from a lot time. I am not sure why but my app crashes when I try to run my application. The error that I get in the Logcat is:
`Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '__pycache__'`
I am trying to say **pip install pillow and pytesseract**

Here is how I am trying to do it:

`python {
            buildPython "E:\\python\\python.exe"

             pip{
                install "pillow"
                install "pytesseract"
            }
        }`

Can someone please help me.

**Comment by mhsmith** [comment]
Please post the full stack trace, and any relevant sections of your code.

**Comment by Unicas** [comment]
Here is the full stack trace:
```
08-04 16:18:33.441 4058-4058/com.example.java_with_python E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.java_with_python, PID: 4058
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.java_with_python/com.example.java_with_python.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '__pycache__'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5305)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '__pycache__'
        at <python>.shutil._rmtree_safe_fd(shutil.py:640)
        at <python>.shutil._rmtree_safe_fd(shutil.py:642)
        at <python>.shutil.rmtree(shutil.py:709)
        at <python>.java.android.importer.__init__(importer.py:274)
        at <python>.pkgutil.get_importer(pkgutil.py:419)
        at <python>.java.android.importer.initialize_importlib(importer.py:64)
        at <python>.java.android.importer.initialize(importer.py:35)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:128)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.example.java_with_python.MainActivity.onCreate(MainActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2280)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
        at android.app.ActivityThread.access$800(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5305) 
```

**Comment by mhsmith** [comment]
Does the problem happen every time you start the app?

Which devices or emulators has the problem happened on?

Does clearing the app's data in the settings make the problem go away? If so, can you work out a sequence of actions which makes the problem come back?

From the line numbers it looks like you're using Chaquopy 7.0.2. Try changing the version of `com.chaquo.python:gradle` in your top-level build.gradle file, and if the problem still happens, please post the new stack trace.

**Comment by Unicas** [comment]
Yes, the problem happens every time I start the app. The problem happens on the Nox emulator. And clearing app data doesn't work. I changed the version to `8.0.7`. But the same error.

**Comment by mhsmith** [comment]
> The problem happens on the Nox emulator.

Does it happen on the official Android emulator, or on any physical device?

And does it happen with any of the Chaquopy [demo apps](https://github.com/chaquo)? If not, can you share your app's source code with me, or a reduced version which reproduces the problem? The easiest way would be to use a private GitHub repository. Of course, I'll treat anything you send me as confidential.

> I changed the version to 8.0.7. But the same error.

There is no version 8.0.7, the current version is 8.0.1. Try changing the version of `com.chaquo.python:gradle` to 8.0.1, and rebuild and reinstall your app. Then if the problem still happens, please post the new stack trace.

**Comment by Unicas** [comment]
I apologize for writing `8.0.7` here. I actually have used version `8.0.1` only. Well I tried removing the pip. And!!! The error changed :-(  The stack says:
`Process: com.example.java_with_python, PID: 3919
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.java_with_python/com.example.java_with_python.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '.idea'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5305)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '.idea'
        at <python>.shutil._rmtree_safe_fd(shutil.py:646)
        at <python>.shutil._rmtree_safe_fd(shutil.py:648)
        at <python>.shutil.rmtree(shutil.py:715)
        at <python>.java.android.importer.__init__(importer.py:342)
        at <python>.java.android.importer.hook(importer.py:50)
        at <python>.pkgutil.get_importer(pkgutil.py:419)
        at <python>.java.android.importer.initialize_importlib(importer.py:59)
        at <python>.java.android.importer.initialize(importer.py:34)
        at <python>.java.android.initialize(__init__.py:14)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:285)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:257)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:132)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.example.java_with_python.MainActivity.onCreate(MainActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2280)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
        at android.app.ActivityThread.access$800(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5305)` 

And then I again put the pip back. But the error was same as without pip. Means the error changed...

**Comment by mhsmith** [comment]
This is very strange, there shouldn't be any `.idea` directory at runtime. 

Can you answer the questions in the first half of [my previous comment](https://github.com/chaquo/chaquopy/issues/358#issuecomment-669125917)?

**Comment by Unicas** [comment]
Ok!! So nox is an android emulator. Actually when I just made a simple app for first that just returns the text worked all fine. But after I used some other functions like getting the text from image it did'nt worked. I again made my python code replaced with the old ones it gave me the error.

Can it be because of the I.D.E ie `Pycharm-20` that I use.

**Comment by Unicas** [comment]
Ok!! so I didn't find any solution on how to solve this, and there was only one way that I can solve it, The most difficult ones starting a new one project. Ok, I am not sure how but Actually that still didn't work on the Nox emulator but worked on the Physical device and other emulators. So I think now I should work on this. Hopefully no further errors. So now I should go fast uninstall the Nox emulator because my Computer System is not a High-End Computer and running two emulators on it is enough!!!

**Comment by mhsmith** [comment]
OK, I recommend you use the standard Android Studio IDE and emulator.

**Comment by mhsmith** [comment]
OK, if you want me to look into this further then you'll need to provide me with at least an APK, and details of exactly how you built it. 

In general you'll probably find everything much easier if you use the standard Android Studio IDE and emulator.

**Comment by zeynabimani** [comment]
Hi. I have almost the same problem. I just want to start Python in my android application, but when I use this code I get an error.
The code is:

`if (!Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
}`

When I use this code in any part of the program MainActivity or somewhere else I got the error and I don't know why?!

The error is:
> 2020-08-19 18:19:04.135 12263-12263/com.dji.sdk.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dji.sdk.sample, PID: 12263
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dji.sdk.sample/com.dji.sdk.sample.internal.controller.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.chaquo.python.PyException" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dji.sdk.sample-ImLlWv7TGO-MqNuoILbVIA==/base.apk", dex file "InMemoryDexFile[cookie=[0, 494810873152]]", dex file "InMemoryDexFile[cookie=[0, 494810874496]]"],nativeLibraryDirectories=[/data/app/com.dji.sdk.sample-ImLlWv7TGO-MqNuoILbVIA==/lib/arm64, /data/app/com.dji.sdk.sample-ImLlWv7TGO-MqNuoILbVIA==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2977)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6831)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.chaquo.python.PyException" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dji.sdk.sample-ImLlWv7TGO-MqNuoILbVIA==/base.apk", dex file "InMemoryDexFile[cookie=[0, 494810873152]]", dex file "InMemoryDexFile[cookie=[0, 494810874496]]"],nativeLibraryDirectories=[/data/app/com.dji.sdk.sample-ImLlWv7TGO-MqNuoILbVIA==/lib/arm64, /data/app/com.dji.sdk.sample-ImLlWv7TGO-MqNuoILbVIA==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.chaquo.python.Python.startNative(Native Method)
        at com.chaquo.python.Python.a(:50)
        at com.dji.sdk.sample.internal.controller.MainActivity.onCreate(:113)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6831) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927) 

I read the documentation, and I know one way for starting python is to change the application name in androidManifest.xml file, but I can't do this because I use a Sample Application, and I can't change the application name in the manifest file. 

Can you please help me find the problem?
