### ISSUE TITLE
Problem installing python library "populartimes"

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#359]
_Originally posted by @LLansman in https://github.com/chaquo/chaquopy/issues/53#issuecomment-670483508_

Executing tasks: [:app:assembleDebug] in project C:\Users\bonol\Downloads\MaHaLuz

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting populartimes
  Could not find a version that satisfies the requirement populartimes (from versions: )
No matching distribution found for populartimes
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'py'' finished with non-zero exit value 1
  
  To view full details in Android Studio:
  * In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
  * In version 3.5 and older, click the 'Toggle view' button to the left of this message.
  * Then scroll up to see the full output.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by mhsmith** [comment]
_Originally posted by @LLansman in https://github.com/chaquo/chaquopy/issues/53#issuecomment-670495936_

Similar thing happens while trying installing numpy library:

Executing tasks: [:app:assembleDebug] in project C:\Users\bonol\Downloads\MaHaLuz

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting numpy
  Using version 1.17.4 (newest version is 1.19.1, but Chaquopy prefers native wheels)
  Downloading https://chaquo.com/pypi-7.0/numpy/numpy-1.17.4-3-cp38-cp38-android_16_armeabi_v7a.whl (3.6MB)
Collecting chaquopy-openblas>=0.2.20 (from numpy)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /pypi-7.0/chaquopy-openblas/
  Downloading https://chaquo.com/pypi-7.0/chaquopy-openblas/chaquopy_openblas-0.2.20-5-py3-none-android_16_armeabi_v7a.whl (4.0MB)
Exception:
Traceback (most recent call last):
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 302, in _error_catcher
    yield
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 384, in read
    data = self._fp.read(amt)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_vendor\cachecontrol\filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "C:\Users\bonol\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\bonol\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\bonol\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\bonol\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\bonol\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\basecommand.py", line 236, in main
    status = self.run(options, args)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\commands\install.py", line 310, in run
    resolver.resolve(requirement_set)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\resolve.py", line 208, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\operations\prepare.py", line 308, in prepare_linked_requirement
    unpack_url(
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\download.py", line 835, in unpack_url
    unpack_http_url(
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\download.py", line 674, in unpack_http_url
    from_path, content_type = _download_http_url(link,
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\download.py", line 902, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\download.py", line 624, in _download_url
    consume(downloaded_chunks)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\utils\misc.py", line 847, in consume
    deque(iterator, maxlen=0)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\download.py", line 590, in written_chunks
    for chunk in chunks:
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\utils\ui.py", line 159, in iter
    for x in it:
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_internal\download.py", line 555, in resp_read
    for chunk in resp.raw.stream(
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\bonol\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\bonol\Downloads\MaHaLuz\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='chaquo.com', port=443): Read timed out.
Chaquopy: Exit status 2

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'py'' finished with non-zero exit value 1
  
  To view full details in Android Studio:
  * In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
  * In version 3.5 and older, click the 'Toggle view' button to the left of this message.
  * Then scroll up to see the full output.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 41s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by mhsmith** [comment]
Populartimes is not on PyPI, so you'll have to install it from a GitHub URL, as it says in [the populartimes README](https://github.com/m-wrzr/populartimes). Add this to your build.gradle file:

```
pip {
    install "git+https://github.com/m-wrzr/populartimes"
}
```

As for Numpy, it looks like you're having some network problem. Could your connection be blocked by some kind of proxy or firewall?

**Comment by LLansman** [comment]
Hi, I installed pupulartimes in build.gradle as you mentioned ,

python{
            pip{
                //install "--user populartimes"
                install "git+https://github.com/m-wrzr/populartimes"
            }
        }

In the python file :
## imports
import populartimes

And got this on Logcat:

2020-08-09 08:36:58.466 11392-11392/com.example.mahaluz E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mahaluz, PID: 11392
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mahaluz/com.example.mahaluz.MainActivity}: com.chaquo.python.PyException: NameError: name 'populartimes' is not defined
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: com.chaquo.python.PyException: NameError: name 'populartimes' is not defined
        at <python>.popularTimes.gran_morsi_popular_times(popularTimes.py:15)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.example.mahaluz.MainActivity.onCreate(MainActivity.java:41)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

what am I doing wrong?

**Comment by mhsmith** [comment]
Fixed in https://github.com/m-wrzr/populartimes/issues/96.

**Comment by mhsmith** [comment]
To make your app pick up the current version of populartimes, use the Build > Rebuild Project command in Android Studio.

It would also be a good idea to install a specific commit from GitHub, rather than using the master branch, which could change constantly. For example, this would install [the commit](https://github.com/m-wrzr/populartimes/commit/44df0141925a8dc635d9e634aef9041bd6c38b9d) which was current when I wrote this comment:

```
install "git+https://github.com/m-wrzr/populartimes@44df0141925a8dc635d9e634aef9041bd6c38b9d"
```

This syntax is fully explained in the [pip documentation](https://pip.pypa.io/en/stable/reference/pip_install/#git)
