### ISSUE TITLE
Chaquopy error: FileNotFoundError: [Errno 2] No such file or directory: '/crt.jpg'

### ISSUE THREAD

**Issue by Unicas** [chaquo/chaquopy#361]
Hello guys and I am getting an error in python chaquopy. I want to open a image file that I have kept in the same directory where the python files are kept. The error that I get is:
`FileNotFoundError: [Errno 2] No such file or directory: '/crt.jpg'`
Here is my code how I want the file using the `os module` and `pillow module`:
``path = os.path.join(os.path.dirname(__file__) ,"/crt.jpg")``

Here is the full stack:
```
08-10 17:18:49.175 28593-28593/animation.xyz.photoeditor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: animation.xyz.photoeditor, PID: 28593
    java.lang.RuntimeException: Unable to start activity ComponentInfo{animation.xyz.photoeditor/animation.xyz.photoeditor.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/crt.jpg'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/crt.jpg'
        at <python>.PIL.Image.open(Image.py:2843)
        at <python>.main.test(main.py:7)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:285)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:257)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at animation.xyz.photoeditor.MainActivity.onCreate(MainActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Thanks in advance for the answer

**Comment by mhsmith** [comment]
As the [`os.path,join` documentation](https://docs.python.org/3/library/os.path.html#os.path.join) says, "If a component is an absolute path, all previous components are thrown away and joining continues from the absolute path component." So remove the slash from `/crt.jpg`.
