### ISSUE TITLE
Unable to list contents of directory despite permissions given

### ISSUE THREAD

**Issue by varunalumnux** [chaquo/chaquopy#371]
I followed instrutctions in #38 and #144

This is my android code.

Code snippet to get the external storage permissions.
```java

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
```
```
Python py;
    private static final int STORAGE_PERMISSION_CODE = 101;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        checkPermission(
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                STORAGE_PERMISSION_CODE);
        if(!Python.isStarted())
        {
            Python.start(new AndroidPlatform(this));
        }
        py = Python.getInstance();
}

// Function to check and request permission
    public void checkPermission(String permission, int requestCode) {

        // Checking if permission is not granted
        if (ContextCompat.checkSelfPermission(
                MainActivity.this,
                permission)
                == PackageManager.PERMISSION_DENIED) {
            ActivityCompat
                    .requestPermissions(
                            MainActivity.this,
                            new String[]{permission},
                            requestCode);
        }
        else{
            Toast.makeText(this,"Permssion already given",Toast.LENGTH_SHORT).show();
        }
    }

```
Java code that calls Python script
```java 
String[] image_string =  {"DCIM/Camera/Image1.jpg","DCIM/Camera/Image1.jpg" };
PyObject pyo = py.getModule("script");
PyObject obj = pyo.callAttr("openafile", image_string[0]);
```

Python script.py

``` python
import os
from android.os import Environment


def openafile(file_name):
    print(type(Environment.getExternalStorageDirectory()))
    print(str(Environment.getExternalStorageDirectory()))
    print(os.path.isdir(str(Environment.getExternalStorageDirectory())))
    print(os.listdir(str(Environment.getExternalStorageDirectory())))
```

I get the following error.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.varunbachalli.pythonjava, PID: 29942
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
        at android.view.View.performClick(View.java:7201)
        at android.view.View.performClickInternal(View.java:7170)
        at android.view.View.access$3500(View.java:806)
        at android.view.View$PerformClick.run(View.java:27562)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
        at android.view.View.performClick(View.java:7201) 
        at android.view.View.performClickInternal(View.java:7170) 
        at android.view.View.access$3500(View.java:806) 
        at android.view.View$PerformClick.run(View.java:27562) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     **Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/storage/emulated/0'**
        at <python>.script.openafile(script.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:285)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:257)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.varunbachalli.pythonjava.MainActivity.get_pixel_positions(MainActivity.java:56)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409) 
        at android.view.View.performClick(View.java:7201) 
        at android.view.View.performClickInternal(View.java:7170) 
        at android.view.View.access$3500(View.java:806) 
        at android.view.View$PerformClick.run(View.java:27562) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by mhsmith** [comment]
Unfortunately recent versions of Android have introduced [new restrictions](https://developer.android.com/training/data-storage#scoped-storage) on external storage. Please try accessing the path in Java/Kotlin. If that doesn't work either, then your problem has nothing to do with Chaquopy and you should seek help elsewhere.

**Comment by mhsmith** [comment]
As I understand it, the recommended way to access the user's photos is now to use `ContentResolver` and `MediaStore` as described [here](https://developer.android.com/training/data-storage/shared/media). This will return `content` URLs, which can be read into a byte array and passed to Python as described [here](https://github.com/chaquo/chaquopy/issues/339#issuecomment-658151563).

**Comment by varunalumnux** [comment]
You're right it was not a chaquopy problem. Rather an android problem. Sorry for wasting your time here.

I used a work around of using 

android:requestLegacyExternalStorage="true"

But thanks again for your help and time.

**Comment by samc30496** [comment]
Hi @varunalumnux, how were you finally able to do it? Can you share the changes you did?

**Comment by mhsmith** [comment]
The android:requestLegacyExternalStorage attribute is described [here](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage).
