### ISSUE TITLE
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'jclass'

### ISSUE THREAD

**Issue by everydaysayhello** [chaquo/chaquopy#380]
I want to package chaquopy into an AAR file, but when I called it, it always said that I couldn't find the "jclass" ，can you help me?

**Comment by mhsmith** [comment]
Please post the full stack trace and the relevant parts of your code.

**Comment by everydaysayhello** [comment]
> 请发布完整的堆栈跟踪以及代码的相关部分。

2020-10-13 08:44:58.370 27460-27460/com.letgo.importaar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.letgo.importaar, PID: 27460
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.letgo.importaar/com.letgo.importaar.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'jclass'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'jclass'
        at <python>.java.chaquopy.import_override(import.pxi:20)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.pythontest.<module>(pythontest.py:1)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:549)
        at <python>.java.android.importer.exec_module(importer.py:594)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:156)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.letgo.mylibraryaar.pythontest.test(pythontest.java:48)
        at com.letgo.importaar.MainActivity.onCreate(MainActivity.java:14)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by everydaysayhello** [comment]
> Please post the full stack trace and the relevant parts of your code.

![Uploading 截屏2020-10-13 上午8.45.48.png…]()

**Comment by everydaysayhello** [comment]
> Please post the full stack trace and the relevant parts of your code.

![Uploading 截屏2020-10-13 上午8.45.48.png…]()

**Comment by everydaysayhello** [comment]
> Please post the full stack trace and the relevant parts of your code.

my python code:
import jclass
def hello():
    CurrentTime = jclass("java.util.Calendar")
    Mytime = CurrentTime.getInstance()
    year = Mytime.get(CurrentTime.YEAR)
    month = Mytime.get(CurrentTime.MONTH)+1
    day = Mytime.get(CurrentTime.DAY_OF_MONTH)
    hour = Mytime.get(CurrentTime.HOUR)
    min = Mytime.get(CurrentTime.MINUTE)
    sec = Mytime.get(CurrentTime.SECOND)
    print(f"{hour}:{min}:{sec}   {day}/{month}/{year}")

**Comment by everydaysayhello** [comment]
> Please post the full stack trace and the relevant parts of your code.

If I only write "print ('hello world')" in "Python", it can be executed correctly, and if I package "chaquopy" directly into the project, I can "import jclass".Thank you for your help!

**Comment by mhsmith** [comment]
`jclass` isn't a module, it's a function in the `java` module. You should write `from java import jclass`.

**Comment by everydaysayhello** [comment]
> `jclass` isn't a module, it's a function in the `java` module. You should write `from java import jclass`.

Oh, oh, it's my carelessness，Thank you very much！
