### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy' on Android Studio

### ISSUE THREAD

**Issue by aswathy89** [chaquo/chaquopy#392]
Below error is showing while trying to install numby-quaternion module

Collecting numpy-quaternion
  Using cached https://files.pythonhosted.org/packages/cb/bb/1ff7d20234ffef492330cb2e6f9f091f0978f3b5356aad0df71d3ad3c091/numpy-quaternion-2020.9.5.14.42.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bridge Global\AppData\Local\Temp\pip-install-edx3wunk\numpy-quaternion\setup.py", line 15, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bridge Global\AppData\Local\Temp\pip-install-edx3wunk\numpy-quaternion\
ERROR: Failed to install numpy-quaternion from https://files.pythonhosted.org/packages/cb/bb/1ff7d20234ffef492330cb2e6f9f091f0978f3b5356aad0df71d3ad3c091/numpy-quaternion-2020.9.5.14.42.2.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install numpy-quaternion from https://files.pythonhosted.org/packages/cb/bb/1ff7d20234ffef492330cb2e6f9f091f0978f3b5356aad0df71d3ad3c091/numpy-quaternion-2020.9.5.14.42.2.tar.gz.

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/Bridge'' finished with non-zero exit value 1

Please help me with a solution

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but if anyone else wants it too, please click the thumbs-up button above and subscribe to this issue.

You could also try using one of the following pure-Python alternatives:
* [pyquaternion](https://pypi.org/project/pyquaternion/)
* [quaternionic](https://pypi.org/project/quaternionic/)
* [Quaternion](https://pypi.org/project/Quaternion/)

**Comment by mhsmith** [comment]
The package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.
