### ISSUE TITLE
python-obd

### ISSUE THREAD

**Issue by AbdAlRahman-Odeh-99** [chaquo/chaquopy#398]
I am building an application that uses python-obd in android studio, during the build i can see that it is collecting the obd library but during the run i get this error.

Caused by: com.chaquo.python.PyException: NameError: name 'obd' is not defined

**Comment by mhsmith** [comment]
Please post the build log, the full exception trace, and the relevant sections of your code.

**Comment by AbdAlRahman-Odeh-99** [comment]
``

**Comment by AbdAlRahman-Odeh-99** [comment]
Build:
Already collected the package 
`python{
            pip{
                install "obd"
            }
        }`

obd.py:

import obd
def init():
    connection = obd.OBD()
    while(1):
        if connection.is_connected():
            print("Car is connected")
            cmd = obd.commands.RPM  # select an OBD command (sensor)
            response = connection.query(cmd)  # send the command, and parse the response
            return response.value
            print(response.value)  # returns unit-bearing values thanks to Pint
        else:
            print("Car not connected")

MainActivity.java:

if (!Python.isStarted())
            Python.start(new AndroidPlatform(this));
        Python python = Python.getInstance();
        PyObject pythonFile = python.getModule("obd");
        PyObject pythonMethod = pythonFile.callAttr("init");
        String rpm = pythonMethod.toString();
        System.out.println("RPM: "+rpm);
        text.setText("RPM: "+rpm);

Exception:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.training.test_8_obd, PID: 14324
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.training.test_8_obd/com.training.test_8_obd.MainActivity}: com.chaquo.python.PyException: AttributeError: module 'obd' has no attribute 'OBD'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: com.chaquo.python.PyException: AttributeError: module 'obd' has no attribute 'OBD'
        at <python>.obd.init(obd.py:4)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:285)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:257)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.training.test_8_obd.MainActivity.onCreate(MainActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167)`

**Comment by AbdAlRahman-Odeh-99** [comment]
Thanks, I think that solved that problem but now i have another Error com.chaquo.python.PyException: ImportError: bad magic number in 'serial': b'\x03\xf3\r\n'.

I even created a new project and also the same error pops up

Exception:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.training.test_10_obd2, PID: 5307
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.training.test_10_obd2/com.training.test_10_obd2.MainActivity}: com.chaquo.python.PyException: ImportError: bad magic number in 'serial': b'\x03\xf3\r\n'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: com.chaquo.python.PyException: ImportError: bad magic number in 'serial': b'\x03\xf3\r\n'
        at <python>.java.android.importer.get_code(importer.py:597)
        at <python>.java.android.importer.exec_module(importer.py:549)
        at <python>.java.android.importer.exec_module(importer.py:594)
        at <python>.java.chaquopy.import_override(import.pxi:20)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.obd.utils.<module>(utils.py:39)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.obd.OBDCommand.<module>(OBDCommand.py:33)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.obd.commands.<module>(commands.py:35)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.obd.obd.<module>(obd.py:38)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.obd.<module>(__init__.py:41)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.obdReader.<module>(obdReader.py:1)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:549)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:156)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.training.test_10_obd2.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
`

**Comment by mhsmith** [comment]
From the line numbers it looks like you're using Chaquopy 8.0.1, which uses Python 3.8, yet you've somehow ended up with a Python 2.7 .pyc on the device. I haven't seen anything like this before.

Are you still installing obd using the `pip` block in build.gradle? Is there anything else in the `python` block, such as a `buildPython` line?

Here are some things you can try:

* Upgrade to the current Chaquopy version, 9.0.0.
* Install Python 3.8.6: if you're on Windows you should use the installer from [here](https://www.python.org/downloads/windows/), and run it with default settings. Then do a clean rebuild (Build >Rebuild Project). 
* If the problem is still present, please post the full output from that build.

**Comment by mhsmith** [comment]
> Are you still installing `obd` using the pip block in build.gradle?

In particular, have you copied the library to your source directory at any point? 

Have you manually altered anything in the `build` directory, or run any Python processes there?

> Is there anything else in the python block, such as a `buildPython` line?

Or have you configured the `sourceSets` block at all?

**Comment by mhsmith** [comment]
By the way, I should warn you that if you plan to use this library to access a serial port, you'll probably need to root your device.

**Comment by AbdAlRahman-Odeh-99** [comment]
- Actually my python version is 3.7.1 (because i was planning to use kivy) and in `build.gradle` I specified `buildPython` in `python` to block the `python3.7.exe`.
- Yes, i am still installing `obd` in the pip block and collecting is successful.
- This wasn't my first time importing libraries using chaquopy because i used the library `requests` before to send POST requests to a server, but this was my first time to run into an error like this.
- The python script works fine with `python3.7` on pyCharm and i actually connected my pc to a car and it worked but when I moved that code to Android it kept giving me that error.
- I played around with the code and I imported the `requests` instead of `obd` and tested it and it worked fine so i knew it had something to do with the line `import obd`.

**Comment by AbdAlRahman-Odeh-99** [comment]
As for suggestions for the solution:
- I upgraded my `chaquopy 9.0.0` , but that didn't work
- Installing `python 3.8.6` and commenting the `buildPython `inside `python `block finally that solved the problem, I didn't know that changing from 3.7.1 to 3.8.6 would make this huge difference. Big thanks for that

**Comment by AbdAlRahman-Odeh-99** [comment]
My project is an android app that reads data then sends them to a NodeJS server that pushed the data into Kafka server to be processed then consumed by another application and now i will start trying to connect the app to the obd but i had to make sure that the python script actually gives me the required results.

**Comment by mhsmith** [comment]
Python 3.7 should have worked with a warning, while Python 2.7 should have failed with a build error, so I don't understand what's happened here. Anyway, I'm glad it's working now.
