### ISSUE TITLE
OverflowError: value too large to convert to int8_t

### ISSUE THREAD

**Issue by Robbi-Blechdose** [chaquo/chaquopy#40]
I'm working on an app and am getting this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.chaquo.python.hello, PID: 7109
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.python.hello/hello.MainActivity}: com.chaquo.python.PyException: OverflowError: value too large to convert to int8_t
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: com.chaquo.python.PyException: OverflowError: value too large to convert to int8_t
                      at <python>.java.chaquopy.CQPEnv.SetByteArrayElement(env.pxi:409)
                      at <python>.java.chaquopy.array_set(array.pxi:180)
                      at <python>.java.chaquopy.JavaArray.__init__(array.pxi:66)
                      at <python>.java.chaquopy.JavaClass.__call__(class.pxi:120)
                      at <python>.java.chaquopy.ArrayClass.__call__(array.pxi:27)
                      at <python>.java.chaquopy.p2j_array(conversion.pxi:261)
                      at <python>.java.chaquopy.p2j(conversion.pxi:226)
                      at <python>.java.chaquopy.JavaMethod.__call__(class.pxi:706)
                      at <python>.java.chaquopy.JavaMultipleMethod.__call__(class.pxi:930)
                      at <python>.java.chaquopy.JavaMultipleMethod.__get__.lambda3(class.pxi:892)
                      at <python>.onCreate(/android_asset/chaquopy/app.zip/hello.py:23)
                      at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
                      at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
                      at com.chaquo.python.PyObject.callAttrThrows(Native Method)
                      at com.chaquo.python.PyObject._chaquopyCall(PyObject.java:155)
                      at hello.MainActivity.onCreate(MainActivity.java:24)
                      at android.app.Activity.performCreate(Activity.java:5231)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
Disconnected from the target VM, address: 'localhost:8618', transport: 'socket'
```

My code looks like this:
```
from android.os import Bundle
from android.app import Activity
from android.graphics import BitmapFactory
from com.chaquo.python.hello import R
from java import jvoid, Override, static_proxy
import ftrobopy

class MainActivity(static_proxy(Activity)):

    @Override(jvoid, [Bundle])
    def onCreate(self, state):
        Activity.onCreate(self, state)
        self.setContentView(R.layout.activity_main)
        fttxt = ftrobopy.ftTXT('192.168.2.128', 65000)
        fttxt.startOnline()
        fttxt.queryStatus()
        self.findViewById(R.id.txtInfo).setText(fttxt.getDevicename() + " Firmware Version: " + fttxt.getFirmwareVersion())
        fttxt.startCameraOnline()
        while True:
            frame = fttxt.getCameraFrame()
            if frame != None:
                framesize = len(frame)
                bitmap = BitmapFactory.decodeByteArray(frame, 0, framesize)
                self.findViewById(R.id.cameraImage).setImageBitmap(bitmap)
```
The error started occuring when I added the call to decodeByteArray. Is there any way to fix this?

**Comment by Robbi-Blechdose** [comment]
That fixed the error! Thanks so much for the quick answer!

**Comment by mhsmith** [comment]
Unfortunately I'm not familiar with either ftrobopy or BitmapFactory. But perhaps you could try narrowing the problem down by trying to load and display a known image from a file?

**Comment by Robbi-Blechdose** [comment]
The problem is the loop IMO, is there a known way to do a "main loop" with chaquopy?

**Comment by mhsmith** [comment]
Oh right, I see what you mean. This issue isn't specific to Chaquopy, you've just got to fit into Android's event-driven model, and not block the main thread.

Try using [Handler.postDelayed](https://developer.android.com/reference/android/os/Handler.html#postDelayed(java.lang.Runnable,%20long)) to schedule a callback. There's an example of how to create a Runnable in the [Python API documentation](https://chaquo.com/chaquopy/doc/current/python.html#dynamic-proxy). Then every time it calls you back, you can call it again to schedule the next update.

**Comment by Robbi-Blechdose** [comment]
Works like a charm! Thanks!

**Comment by mhsmith** [comment]
Continued in #41.
