### ISSUE TITLE
 Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by Spidey-code** [chaquo/chaquopy#417]
After you said to change the code  https://github.com/chaquo/chaquopy/issues/144 from this , I encountered same problem file not founderror. Do i have to change the code in android studio or python file
`Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.androidwithpython/files/chaquopy/AssetFinder/app/D:\\Raju\\Python\\project\\datasets\\soilexcel.xlsx'`
**this is the error im getting**

**This is the runtime error** 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.androidwithpython, PID: 1520
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.androidwithpython/com.example.androidwithpython.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.androidwithpython/files/chaquopy/AssetFinder/app/D:\\Raju\\Python\\project\\datasets\\soilexcel.xlsx'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.androidwithpython/files/chaquopy/AssetFinder/app/D:\\Raju\\Python\\project\\datasets\\soilexcel.xlsx'
        at <python>.zipfile.__init__(zipfile.py:1251)
        at <python>.openpyxl.reader.excel._validate_archive(excel.py:96)
        at <python>.openpyxl.reader.excel.__init__(excel.py:124)
        at <python>.openpyxl.reader.excel.load_workbook(excel.py:313)
        at <python>.pandas.io.excel._openpyxl.load_workbook(_openpyxl.py:481)
        at <python>.pandas.io.excel._base.__init__(_base.py:359)
        at <python>.pandas.io.excel._openpyxl.__init__(_openpyxl.py:470)
        at <python>.pandas.io.excel._base.__init__(_base.py:819)
        at <python>.pandas.io.excel._base.read_excel(_base.py:310)
        at <python>.pandas.util._decorators.wrapper(_decorators.py:208)
        at <python>.LocalDataset.main(LocalDataset.py:11)
        at <python>.LocalDataset.<module>(LocalDataset.py:13)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:507)
        at <python>.java.android.importer.exec_module(importer.py:556)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:156)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.androidwithpython.MainActivity.onCreate(MainActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
`

**Comment by mhsmith** [comment]
Please read #144 more carefully. The data file should be in the same directory as the Python file, and there should be no absolute paths in your code.
