### ISSUE TITLE
OSError: SavedModel file does not exist at: linear.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by Emma-o** [chaquo/chaquopy#428]
hello, sorry for the inconvenience. I am trying to load a previously trained model but when I run I get the following error:

```
2021-01-15 15:23:08.231 24028-24028/com.chaquo.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chaquo.myapplication, PID: 24028
    com.chaquo.python.PyException: **OSError: SavedModel file does not exist at: linear.h5/{saved_model.pbtxt|saved_model.pb}**
        at <python>.tensorflow.python.saved_model.loader_impl.parse_saved_model(loader_impl.py:80)
        at <python>.tensorflow.python.keras.saving.save.load_model(save.py:149)
        at <python>.plot.hello2(plot.py:38)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:285)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:257)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.chaquo.myapplication.MainActivity$onCreate$1.onClick(MainActivity.kt:39)
        at android.view.View.performClick(View.java:7191)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:7164)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27862)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

I have imported
```
import tensorflow as tf
import numpy as np
from tensorflow import keras
from os.path import dirname, join
filename = join(dirname(__file__), "linear.h5")
```

the function is:
```	
def hello2():

    new_model = keras.models.load_model('linear.h5')
    x=new_predictions = new_model.predict([15])
    return x
```

I have tried running training the model at the same time and it doesn't give me errors when I do that but for obvious reasons I need to use a trained model.
I add screenshots.
![Captura de pantalla de 2021-01-15 15-29-41](https://user-images.githubusercontent.com/37258888/104780656-b327f680-5746-11eb-8745-60765963675d.png)
![Captura de pantalla de 2021-01-15 15-30-11](https://user-images.githubusercontent.com/37258888/104780657-b3c08d00-5746-11eb-8a43-7785c22c428a.png)

**Comment by mhsmith** [comment]
You're putting the filename in a variable, but then you don't seem to be using that variable.

**Comment by Emma-o** [comment]
Thank you very much, I had not realized that.
After correcting I got the following error 'sample_weight_mode' but I corrected it by adding the following
 
**compile = False** 

def hello2 ():

     new_model = keras.models.load_model (filename, **compile = False** )
     x = new_predictions = new_model.predict ([10])
     return x
