### ISSUE TITLE
Unable to install wikipedia-api

### ISSUE THREAD

**Issue by Eik420** [chaquo/chaquopy#432]
I tried to install the wikipedia-api with

```
python{
   pip{
      install "wikipedia-api"
   }
}
```

but it doesn't compile with this error:

```

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting wikipedia-api
  Using cached https://files.pythonhosted.org/packages/ef/3d/289963bbf51f8d00cdf7483cdc2baee25ba877e8b4eb72157c47211e3b57/Wikipedia-API-0.5.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\eikes\AndroidStudioProjects\WikiReader\app\build\generated\python\bp.zip\setuptools\__init__.py", line 14, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\eikes\AndroidStudioProjects\WikiReader\app\build\generated\python\bp.zip\setuptools\dist.py", line 24, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\eikes\AppData\Local\Temp\pip-install-s75uz8g0\wikipedia-api\
      File "C:\Users\eikes\AndroidStudioProjects\WikiReader\app\build\generated\python\bp.zip\setuptools\depends.py", line 7, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\Users\eikes\AndroidStudioProjects\WikiReader\app\build\generated\python\bp.zip\setuptools\py33compat.py", line 54, in <module>
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    
    ----------------------------------------
ERROR: Failed to install wikipedia-api from https://files.pythonhosted.org/packages/ef/3d/289963bbf51f8d00cdf7483cdc2baee25ba877e8b4eb72157c47211e3b57/Wikipedia-API-0.5.4.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
Failed to install wikipedia-api from https://files.pythonhosted.org/packages/ef/3d/289963bbf51f8d00cdf7483cdc2baee25ba877e8b4eb72157c47211e3b57/Wikipedia-API-0.5.4.tar.gz.

```

i tested it with install "numpy", that works..

**Comment by mhsmith** [comment]
This is fixed in Chaquopy 9.1.0: see #416.
