### ISSUE TITLE
Issue in passing wave file path

### ISSUE THREAD

**Issue by pawarbhushan08** [chaquo/chaquopy#442]
@mhsmith 
I am trying to pass the file path to my python code. I am getting following error for permissions. I am settings all necessary android permissions. 

Error Logs:

2021-01-30 22:53:57.128 17579-17579/com.example.decodingexercise E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.decodingexercise, PID: 17579
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.decodingexercise/com.example.decodingexercise.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/mnt/sdcard/audioData/file_1.wav'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/mnt/sdcard/audioData/file_1.wav'
        at <python>.scipy.io.wavfile.read(wavfile.py:264)
        at <python>.helloworldscript.fsk_demodulator(helloworldscript.py:19)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.decodingexercise.MainActivity.getPythonHelloWorld(MainActivity.kt:26)
        at com.example.decodingexercise.MainActivity.onCreate(MainActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by mhsmith** [comment]
On API level 29 and later, direct access to the external storage directory ("sdcard") is limited by the [scoped storage policy](https://developer.android.com/training/data-storage#scoped-storage). Instead, you should access this location using the [system file picker](https://developer.android.com/training/data-storage/use-cases#open-document):

```
class MyActivity : AppCompatActivity() {
    val REQUEST_OPEN = 0

    fun ... {
        startActivityForResult(
            Intent(if (Build.VERSION.SDK_INT >= 19) Intent.ACTION_OPEN_DOCUMENT
                   else Intent.ACTION_GET_CONTENT).apply {
                addCategory(Intent.CATEGORY_OPENABLE)
                setType("*/*")
            }, REQUEST_OPEN)
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        if (requestCode == REQUEST_OPEN && resultCode == RESULT_OK) {
            val content = contentResolver.openInputStream(data!!.data!!)!!.use { 
                // readBytes only exists in Kotlin. For Java, see 
                // https://stackoverflow.com/a/10297073
                it.readBytes() 
            }
            myPythonModule.callAttr("process", content)
        }
    }
}
```

The Python function can then access the data in several ways:

```
def process(content):
    # `content` is already a bytes-like object, but if you need a standard `bytes`:
    content = bytes(content)

    # If you need a file-like object:
    import io
    content_file = io.BytesIO(content)

    # If you need a filename (less efficient):
    import tempfile
    with tempfile.NamedTemporaryFile() as temp_file:
        temp_file.write(content)
        filename = temp_file.name
```
