### ISSUE TITLE
failed for task ':app:generateDebugPythonLicenseAssets'

### ISSUE THREAD

**Issue by stianyu** [chaquo/chaquopy#446]
#### Chaquopy version & Relevant parts of your build.gradle file

classpath "com.chaquo.python:gradle:8.0.0"

classpath 'com.android.tools.build:gradle:3.5.2'
#### build output
**org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateDebugPythonLicenseAssets'.**
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
... more
**Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:652)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:471)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:367)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:154)
**Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:128)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:636)
	... 117 more
**Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 123 more

**Comment by mhsmith** [comment]
From email: 

> My partner built our project successfully at a time last week, but we don't know why it worked. Unfortunately, when he modified the code which of parts engaged python script today, errors occurred again and we don't know how to fix it. Also, I attach the error stack trace in a text file. It seems like a random error and depends on the network. 

Sorry, I don't have any more suggestions beyond what I sent before, which I'll repeat here:

I've had reports of problems like this caused by a proxy: see https://github.com/chaquo/chaquopy/issues/113#issuecomment-502185307. Please consult your IT department to see whether your proxy or firewall configuration could be causing this behaviour. 

It could also be related to your Java installation: make sure you're using the JVM which comes with Android Studio.

Are you able to visit chaquo.com in a web browser on the same machine?

**Comment by stianyu** [comment]
>Are you able to visit chaquo.com in a web browser on the same machine?
Yes. Besides, I'm able to download python package resources at a very low speed.

**Comment by mhsmith** [comment]
As you mentioned in your email that you have the problem on one machine but not on another, you might be able to work out the cause by investigating the differences between the machines.

Does your top-level build-gradle file use the Maven repository at "https://chaquo.com/maven", or are you using a different repository?

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information and I'll reopen the issue.
