### ISSUE TITLE
TimeoutException: com.chaquo.python.PyObject.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#465]
```
java.util.concurrent.TimeoutException: com.chaquo.python.PyObject.finalize() timed out after 10 seconds
	at com.chaquo.python.PyObject.closeNative(Native Method)
	at com.chaquo.python.PyObject.close(PyObject.java:75)
	at com.chaquo.python.PyObject.finalize(PyObject.java:371)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by Masum95** [comment]
any update on this bug ?

**Comment by mhsmith** [comment]
Not yet. Has it been happening to you? If so, what Python packages are you using?

**Comment by mhsmith** [comment]
Report from @huweiko:

> My application started two threads, one for deep learning model loading, using PyTorch, and the other for some data processing. The thread that executed PyTorch reported an error.

```
uncaughtException::java.util.concurrent.TimeoutException:com.chaquo.python.PyObject.finalize() timed out after 10 seconds
at com.chaquo.python.PyObject.closeNative(PyObject.java:-2)
at com.chaquo.python.PyObject.close(PyObject.java:7)
at com.chaquo.python.PyObject.finalize(PyObject.java:1)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
at java.lang.Daemons$Daemon.run(Daemons.java:139)
at java.lang.Thread.run(Thread.java:923)
```

**Comment by mhsmith** [comment]
This has been reported by many users of Electron Cash (https://github.com/Electron-Cash/Electron-Cash/issues/1501).

I was finally able to reproduce it myself while running [this line of the NeuroKit2 unit test](https://github.com/neuropsychology/NeuroKit/blob/fd7114ecc0182bd2d7a05a587109b677f1cbd4b1/tests/tests_eda.py#L70).  This line takes over 10 seconds to execute (the official Windows build is the same), so my guess is that it calls some native code which doesn't release the GIL.

```
2020-10-26 17:38:37.980 30098-30115/com.chaquo.python.pkgtest3 E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: com.chaquo.python.pkgtest3, PID: 30098
    java.util.concurrent.TimeoutException: com.chaquo.python.PyObject.finalize() timed out after 10 seconds
        at com.chaquo.python.PyObject.closeNative(Native Method)
        at com.chaquo.python.PyObject.close(PyObject.java:74)
        at com.chaquo.python.PyObject.finalize(PyObject.java:347)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
```

To identify which object is being finalized without needing the GIL on the finalization thread, I did this:

* Make the `PyObject` constructor log `identityHashCode` and `toString`.
* Make  `PyObject.close` log `identityHashCode`. 

The object was the `chaquopy.utils.console` module which was accessed during PythonConsoleActivity startup, and it's perfectly reasonable for that to be garbage collected a few tens of seconds later.

**Comment by mhsmith** [comment]
In order to fix this, we'll have to avoid calling any Python code within `finalize`. Instead, put the Python object's address into a Java queue, and create a separate thread which consumes that queue. The consumer thread may block when it calls into Python to release the object, but that won't block the finalizer thread.

This can probably be tested by using `ctypes.PyDLL` to call the native `sleep` function without releasing the GIL, then calling `System.gc` on a different thread.
