### ISSUE TITLE
Unable to use easyocr package

### ISSUE THREAD

**Issue by Ponprabhakar-pg** [chaquo/chaquopy#475]
#### Chaquopy version
9.1

#### Devices or emulators where the issue happens
Devices

#### Relevant parts of your code
```
from PIL import Image
import re
from io import BytesIO
import cv2
import matplotlib.pyplot as plt
import easyocr
import base64
from os.path import dirname, join
from com.chaquo.python import Python

def main(bName,im):
    files_dir=str(Python.getPlatform().getApplication().getFilesDir())
    fileimg1=join(dirname(files_dir),"input.jpg")
    fileimg2=join(dirname(files_dir),"output.jpg")
    print("**********Reached Python**************")
    text = bName
    pattern = list(text.split(" "))
    print(pattern)
    imgb = bytes(im, 'ascii')
    img_bytes = base64.decodebytes(imgb)
    with open(fileimg1, 'wb') as ip:
        ip.write(img_bytes)
    reader = easyocr.Reader(['en'])
    image = cv2.imread(fileimg1)
    res = reader.readtext(fileimg1)
    for (bbox, text, prob) in res:
    # unpack the bounding box
        (tl, tr, br, bl) = bbox
        tl = (int(tl[0]), int(tl[1]))
        tr = (int(tr[0]), int(tr[1]))
        br = (int(br[0]), int(br[1]))
        bl = (int(bl[0]), int(bl[1]))
        cv2.rectangle(image, tl, br, (0, 255, 0), 2)
        cv2.putText(image, text, (tl[0], tl[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 0, 0), 2)
    plt.rcParams['figure.figsize'] = (16, 16)
    cv2.imwrite(fileimg2, image)
    encoded_string = ' '
    with open(fileimg2, "rb") as op:
        encoded_string = base64.b64encode(op.read())
    return ""+str(encoded_string,'utf-8')
```

#### Describe your issue
showing error in this specific part of code
 reader = easyocr.Reader(['en'])

**Comment by mhsmith** [comment]
What error?

**Comment by Ponprabhakar-pg** [comment]
> What error?

unable to access location

**Comment by mhsmith** [comment]
I doubt that has anything to do with your code. If your app is crashing, you can find the full error message by following the instructions [here](https://stackoverflow.com/a/23353174).

**Comment by Ponprabhakar-pg** [comment]
> I doubt that message has anything to do with this code. If your app is crashing, you can find the full error message by following the instructions [here](https://stackoverflow.com/a/23353174).

I have attached the error that I got from android studio!. Its poiting towards -> "reader = easyocr.Reader(['en'])" this specific line in my python code is trubbling.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: krunal.com.example.cameraapp, PID: 11347
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {krunal.com.example.cameraapp/krunal.com.example.cameraapp.MainActivity2}: com.chaquo.python.PyException: URLError: <urlopen error [Errno 7] No address associated with hostname>
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4950)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4991)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7574)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.chaquo.python.PyException: URLError: <urlopen error [Errno 7] No address associated with hostname>
        at <python>.urllib.request.do_open(request.py:1353)
        at <python>.urllib.request.https_open(request.py:1393)
        at <python>.urllib.request._call_chain(request.py:502)
        at <python>.urllib.request._open(request.py:542)
        at <python>.urllib.request.open(request.py:525)
        at <python>.urllib.request.urlopen(request.py:222)
        at <python>.urllib.request.urlretrieve(request.py:247)
        at <python>.easyocr.utils.download_and_unzip(utils.py:553)
        at <python>.easyocr.easyocr.__init__(easyocr.py:86)
        at <python>.myScript.main(myScript.py:23)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at krunal.com.example.cameraapp.MainActivity2.processAndSetImage(MainActivity2.java:238)
        at krunal.com.example.cameraapp.MainActivity2.onActivityResult(MainActivity2.java:171)
        at android.app.Activity.dispatchActivityResult(Activity.java:8274)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4943)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4991) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7574) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
I/Process: Sending signal. PID: 11347 SIG: 9

**Comment by mhsmith** [comment]
This is answered in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#no-address-associated-with-hostname).

**Comment by Ponprabhakar-pg** [comment]
Ok I came out of that error, but got a new error saying pytorch version is too old, what can I do for that?


E/AndroidRuntime: FATAL EXCEPTION: main
    Process: krunal.com.example.cameraapp, PID: 31028
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {krunal.com.example.cameraapp/krunal.com.example.cameraapp.MainActivity2}: com.chaquo.python.PyException: RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132)
    (no backtrace available)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4950)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4991)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7574)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.chaquo.python.PyException: RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132)
    (no backtrace available)
        at <python>.torch.serialization.__init__(serialization.py:224)
        at <python>.torch.serialization.load(serialization.py:527)
        at <python>.easyocr.recognition.get_recognizer(recognition.py:169)
        at <python>.easyocr.easyocr.__init__(easyocr.py:231)
        at <python>.myScript.main(myScript.py:23)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at krunal.com.example.cameraapp.MainActivity2.processAndSetImage(MainActivity2.java:238)
        at krunal.com.example.cameraapp.MainActivity2.onActivityResult(MainActivity2.java:171)
        at android.app.Activity.dispatchActivityResult(Activity.java:8274)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4943)
        	... 11 more
I/Process: Sending signal. PID: 31028 SIG: 9

> This is answered in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#no-address-associated-with-hostname).

**Comment by mhsmith** [comment]
We currently provide PyTorch version 1.4.0, so for best compatibility you should generate your data files with the same version. For future updates, you can subscribe to #477.

Please create separate issues for any further problems.
