### ISSUE TITLE
Mediapipe package

### ISSUE THREAD

**Issue by Anirudh1681** [chaquo/chaquopy#479]
Will the Mediapipe python package be added in the repository of Chaquopy?
If yes, Thanks in advance
If no, Is there anybody working on using python script in android studio?

**Comment by mhsmith** [comment]
Thanks for the report. This package isn't currently a priority, but you can subscribe to this issue for any future updates. And if anyone else wants it too, please click the thumbs-up button above.

**Comment by abhay6694** [comment]
I am also using mediapipe library in one of my project. I wanted to run android app with python code and mediapipe is the only library which didn't get download. When can we expect support for this or what is the alternative for this?

**Comment by mhsmith** [comment]
Chaquopy supports several other image processing and machine learning libraries including OpenCV, TensorFlow and PyTorch. 

Alternatively, you could use the [Chaquopy Python API](https://chaquo.com/chaquopy/doc/current/python.html) to access the MediaPipe Java API from Python. Unfortunately it looks like they don't release a pre-built AAR, and the [process for building one yourself](https://google.github.io/mediapipe/getting_started/android.html) is quite complex.

**Comment by abhay6694** [comment]
So what is the procedure to support mediapipe in chaquopy library. Is it something we can do in few days because my entire project is dependant on it and changing it will be very difficult as we want to launch the product asap.
Please guide me through this.

**Comment by UtsaChattopadhyay** [comment]
Is there any updates on this?
Can I install mediapipe and run in android studio?
Thanks

**Comment by mhsmith** [comment]
It still isn't available, but if you'd like to try building it yourself, the package build tool is now open-source. Follow the instructions [here](https://github.com/chaquo/build-wheel), and if you're successful, please make a pull request so we can add the package to the public repository.

**Comment by badchewie** [comment]
I still can't install mediapipe via .whl method. in my app level gradle under default config I have ;

python {
pip {
       install "/home/master/mediapipe-0.9.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 

}
}

but when I run the project I get this error.


could not find a version that satisfies the requirement mediapipe=0.9.0.1

**Comment by mhsmith** [comment]
Linux wheels cannot be installed on Android. The only options are the ones already mentioned above.

**Comment by mhsmith** [comment]
Sorry, I don't know anything more about this package except what's written above.

**Comment by mhsmith** [comment]
But if you want to try one of those approaches, I'll be happy to help you with any issues that come up.

**Comment by badchewie** [comment]
Hello there , 
I'd like to try and build mediapipe package by myself via using your build package tool , but I did not understand the following intsructions in https://github.com/chaquo/build-wheel . Can you guide me through it ?

**Comment by mhsmith** [comment]
What part didn't you understand?

**Comment by quantiantechnologies** [comment]
Please add this library.

**Comment by MayurQuantian** [comment]
Please add this library. I needed in my project

**Comment by KUSHAL-JAIN-au9** [comment]
Please add media pipe library in chaquopy

**Comment by AshweeniKulkarni21** [comment]
please add Mediapipe library in Chaquopy

**Comment by ChetanAlmelkar** [comment]
We need this library for my project. Please add Asap.

**Comment by mhsmith** [comment]
Please don't post "+1" comments with no useful content. They won't make us work on the package any sooner, and they'll spam everyone subscribed to this issue. Click the thumbs up button at the top of the page instead.

**Comment by rolandeke** [comment]
I am also trying to install mediapipe on my android project using chaquo library but I get the same error message that there's no version  found for mediapipe, is there a way that the team can see how best they can include this so it would be easier for developers using your library to install mediapipe?

**Comment by rolandeke** [comment]
I am trying to build mediapipe following the instruction that was given in the README file in the repository [https://github.com/chaquo/build-wheel](https://github.com/chaquo/build-wheel). I am faced with the following error 

```
Traceback (most recent call last):
  File "./build-wheel.py", line 810, in <module>
    BuildWheel().main()
  File "./build-wheel.py", line 97, in main
    self.unpack_and_build()
  File "./build-wheel.py", line 107, in unpack_and_build
    self.find_target()
  File "./build-wheel.py", line 198, in find_target
    versions = [ver for ver in os.listdir(target_dir) if ver.startswith(self.python)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/IMOTECH/Projects/chaquopy/maven/com/chaquo/python/target'
```

I downloaded the maven target using the command that was stated and the .zip files are all available in the required folder `target/download-target.sh maven/com/chaquo/python/target/3.8.16-0`.

Can I please get help as to where I am going wrong? We really need Chaquopy to support media pipe. Thank you

**Comment by mhsmith** [comment]
As the README implies, you shouldn't run the download command exactly as written, but modify it to point at "`maven` in the root of this repository".

**Comment by rolandeke** [comment]
I guess that was exactly what I did but now I am getting a different error when I run the build code 

` ./build-wheel.py --python 3.8 --abi x86_64 ./packages/scipy`

[build-wheel.py: mkdir -p /home/user/IMOTECH/Projects/chaquopy/server/pypi/packages/scipy/build/1.4.1
build-wheel.py: cd /home/user/IMOTECH/Projects/chaquopy/server/pypi/packages/scipy/build/1.4.1
build-wheel.py: mkdir -p /home/user/IMOTECH/Projects/chaquopy/server/pypi/packages/scipy/build/1.4.1/cp38-cp38-android_21_x86_64
build-wheel.py: python3.8 /home/user/IMOTECH/Projects/chaquopy/server/pypi/create-build-env.py /home/user/IMOTECH/Projects/chaquopy/server/pypi/packages/scipy/build/1.4.1/cp38-cp38-android_21_x86_64/env
Traceback (most recent call last):
  File "/home/user/IMOTECH/Projects/chaquopy/server/pypi/create-build-env.py", line 26, in <module>
    pip_whl, = glob(f"{ensurepip.__path__[0]}/_bundled/pip-*.whl")  # Note comma
ValueError: not enough values to unpack (expected 1, got 0)
build-wheel.py: Error: Command returned exit status 1](url)

**Comment by mhsmith** [comment]
Please run `python3.8` and post the output of the following commands:
```
>>> import ensurepip
>>> import os
>>> ensurepip.__path__
>>> list(os.walk(ensurepip.__path__[0]))
```

Please also let me know :
* Your Linux distribution name and version
* Where you got your copy of `python3.8`

**Comment by rolandeke** [comment]
![image](https://github.com/chaquo/chaquopy/assets/47756447/c7238c41-90dd-4f44-b106-1631fd27493d)

 `python3.8`

```
Python 3.8.10 (default, Mar 13 2023, 10:26:41)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ensurepip
>>> import os
>>> ensurepip.__path__
['/usr/lib/python3.8/ensurepip']
>>> list(os.walk(ensurepip.__path__[0]))
[('/usr/lib/python3.8/ensurepip', ['__pycache__'], ['__main__.py', '_uninstall.py', '__init__.py']), ('/usr/lib/python3.8/ensurepip/__pycache__', [], ['__init__.cpython-38.pyc', '_uninstall.cpython-38.pyc', '__main__.cpython-38.pyc'])]
>>>
```
`cat  /etc/os-release`

```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
I download my `python3.8 ` from using the apt package manager, and I am running my Linux Distribution on WSL on a Windows 11 Host.

**Comment by mhsmith** [comment]
OK, it appears that Debian-based distributions install the pip wheels in /usr/share/python-wheels rather than /usr/lib/python3.8/ensurepip/_bundled. 

build-wheel will have to be updated to handle this. And we should check what Fedora-based distributions do as well.

But why are you trying to build SciPy? As mentioned at #648, that isn't currently possible, because we don't have a working Fortran compiler. But if all you need is a copy of SciPy to build another package against, that can be "downloaded manually from [the public repository](https://chaquo.com/pypi-7.0/)" as mentioned in the [README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md#adding-a-package).

**Comment by mhsmith** [comment]
Meanwhile, you can work around the problem by using a version of Python from miniconda, as described in the [README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md).

**Comment by rolandeke** [comment]
> But why are you trying to build SciPy? As mentioned at #648, that isn't currently possible, because we don't have a working Fortran compiler. But if all you need is a copy of SciPy to build another package against, that can be "downloaded manually from [the public repository](https://chaquo.com/pypi-7.0/)" as mentioned in the [README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md#adding-a-package).


I am not actually trying to build SciPy I was just using it to test out the build-wheel. I intend on building [Mediapipe ](https://github.com/google/mediapipe), as it is needed by the project that we are currently working on. 

Also, if you can help me understand a little better when I used chaquopy in my `build.gradle` app level and pass the `options "--extra-index-url", "https://pypi.org/"`.  I am expecting that it should download the package from the Python package repository but I also get an error. 

Lastly, I downloaded the `mediapipe-0.10.3-cp38-cp38-win_amd64.whl` file using `pip download` and referenced it in my `pip block` in my `build.gradle` file as mentioned in the [documentation ](https://chaquo.com/chaquopy/doc/current/android.html) I still get an error building my project.

**Comment by rolandeke** [comment]
> PyPI is enabled by default, so you don't have to add it as an extra URL. But the only wheels that will work on Android are those built for the platforms `android` or `any`. Linux, Mac and Windows wheels will not work.

Okay now I understand, but is there a way I can use your `build-wheel` tool to build .whl file for Mediapipe so it can run on Android? I guess this is the main idea as to why I am trying to get the build-wheel file to work. 

I also encountered an error while executing the `./build-wheel.py --python 3.8 --abi x86_64 ./packages/matplotlib` file which states 
```
ERROR: Could not find a version that satisfies the requirement chaquopy-freetype==2.9.1 (from versions: none)
ERROR: No matching distribution found for chaquopy-freetype==2.9.1
```

**Comment by mhsmith** [comment]
> is there a way I can use your `build-wheel` tool to build .whl file for Mediapipe so it can run on Android?

Yes, that's what the tool is for. But some packages require a lot of patching to build for Android. As mentioned above, Mediapipe uses the Bazel build system, and I've only encountered that before when building TensorFlow, which was extremely difficult. MediaPipe is probably not so difficult, but I wouldn't expect it to be easy.

So it's worth looking into whether you could install MediaPipe for Android using their official instructions, and then access its Java API from Python using Chaquopy.

> I also encountered an error while executing the `./build-wheel.py --python 3.8 --abi x86_64 ./packages/matplotlib`

Please create a new issue and post the full build log.

**Comment by rolandeke** [comment]
Issue has still not been fixed. Tried building the mediapipe module but I still can't get it to work on the application chaquopy still throw a Module Not Found Error, and I even try to download it from pip since it is available on pip but still to no avail. It would be really helpful if the chaquopy team can help resolve this issue so we can be able to install Mediapipe

**Comment by mhsmith** [comment]
I never said the availability of Mediapipe had been fixed, only that specific issue with the build-wheel tool.

**Comment by maq796113** [comment]
it's December 2023, yet no update

**Comment by dipenpadhiyar** [comment]
I have read all the comments in this thread [March 27 2024], It is difficult to manage all the pacages in Chaquopy, @mhsmith.
I want to use MediaPipe in my project, and I have also read your suggestions.

<details><summary>Details</summary>
<p>
It still isn't available, but if you'd like to try building it yourself, the package build tool is now open-source. Follow the instructions [here](https://github.com/chaquo/build-wheel), and if you're successful, please make a pull request so we can add the package to the public repository.
</p>
</details> 

Most ML/Python developers want direct integration of the ML pipeline in Android, and MediaPipe is one of them because the developer wants to apply MediaPipe to images and video 😅. 

So, can you help me guide the process, I know everyone's time is valuable; if you guys have any solutions, please share.

**Comment by mhsmith** [comment]
Sorry, I don't have time to look into this any further at the moment. Everything I know is in the comments above.
