### ISSUE TITLE
How do I use it tflite-runtime?

### ISSUE THREAD

**Issue by YUGEEV5** [chaquo/chaquopy#480]
#### Chaquopy version

```
my use version is 9.1.0
python {

            pyc {
                src false
            }

            pip{
                install "pywavelets"
                install "numpy"
                install "matplotlib"
                install "scikit-learn"
                install "tflite-runtime"
            }
        }
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
```

#### Relevant parts of your code

```
import pywt
import numpy as np
import matplotlib.pyplot as plt
import io
from sklearn.preprocessing import MinMaxScaler
import tflite
def text(data):
    interpreter = tflite.Interpreter(model_path='model.tflite')
    interpreter.allocate_tensors()
    inputIndex=interpreter.get_input_details()[0]["index"]
    outputIndex = interpreter.get_output_details()[0]["index"]
    data = rdata.reshape((-1,5000,1,1))
    data = rdata.astype(np.float32)
    interpreter.set_tensor(inputIndex, data)
    interpreter.invoke()
    prediction = interpreter.get_tensor(outputIndex)
    print(prediction)
    return prediction
```

#### Describe your issue

The following problems occurred when I was running on my mobile phone
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yu.bluetooh, PID: 658
    com.chaquo.python.PyException: ModuleNotFoundError: No module named 'tflite'
        at <python>.java.chaquopy.import_override(import.pxi:20)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.main.<module>(main.py:6)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:507)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:155)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.yu.bluetooth.Recive$DemoHandler.handleMessage(Recive.java:481)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
It means that I import errors，but how can I use it?

**Comment by mhsmith** [comment]
At runtime the module name is `tflite_runtime.interpreter`. See https://www.tensorflow.org/lite/guide/python#run_an_inference_using_tflite_runtime.

**Comment by YUGEEV5** [comment]
> At runtime the module name is `tflite_runtime.interpreter`. See https://www.tensorflow.org/lite/guide/python#run_an_inference_using_tflite_runtime.

Yes, I have another problem now，I put my .tflite file in the python file
this like:
```
.python
├── main.py
└── model.tflite
```
But when I load it, it says I can't open it, so where should I put my model.tflite files?
It's error code is:
```
 com.chaquo.python.PyException: ValueError: Could not open 'model.tflite'.
 at <python>.tflite_runtime.interpreter.__init__(interpreter.py:208)
 at <python>.main.text(main.py:31)
```

**Comment by mhsmith** [comment]
See [this section](https://chaquo.com/chaquopy/doc/current/android.html#data-files) of the documentation.
