### ISSUE TITLE
Unable to send request to an API which is running in localhost

### ISSUE THREAD

**Issue by Ponprabhakar-pg** [chaquo/chaquopy#487]
#### Chaquopy version

latest version

#### Devices or emulators where the issue happens

physical device

#### Relevant parts of your code

```
def main(bName,im):
	print("**********Reached Python**************")
	API_ENDPOINT = "http://127.0.0.1:5000/conImageStat"
	data = {'image':im,
			'book_name':bName,
			}

	# sending post request and saving response as response object
	r = requests.post(url = API_ENDPOINT, data = data)

	# extracting response text
	resurl = r.text

	return resurl
```

#### Describe your issue

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: krunal.com.example.cameraapp, PID: 5315
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {krunal.com.example.cameraapp/krunal.com.example.cameraapp.MainActivity2}: com.chaquo.python.PyException: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /conImageStat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737fee9760>: Failed to establish a new connection: [Errno 111] Connection refused'))
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4950)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4991)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7574)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.chaquo.python.PyException: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /conImageStat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x737fee9760>: Failed to establish a new connection: [Errno 111] Connection refused'))
        at <python>.requests.adapters.send(adapters.py:516)
        at <python>.requests.sessions.send(sessions.py:655)
        at <python>.requests.sessions.request(sessions.py:542)
        at <python>.requests.api.request(api.py:61)
        at <python>.requests.api.post(api.py:119)
        at <python>.myScript.main(myScript.py:18)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at krunal.com.example.cameraapp.MainActivity2.processAndSetImage(MainActivity2.java:238)
        at krunal.com.example.cameraapp.MainActivity2.onActivityResult(MainActivity2.java:171)
        at android.app.Activity.dispatchActivityResult(Activity.java:8274)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4943)
```

**Comment by mhsmith** [comment]
Is your server actually running on the same Android device? If so, please explain what the server is and how you're running it. 

Or if you're running the server on your development machine, then you'll need to connect using an external IP address of that machine, not 127.0.0.1.

**Comment by Ponprabhakar-pg** [comment]
I'm running server on my development machine, how can get external ip and I connect?

**Comment by mhsmith** [comment]
Please use Google or StackOverflow to answer that question. This tracker is only for issues specific to Chaquopy.

**Comment by Ponprabhakar-pg** [comment]
Got it, Thank you mhsmith!

> Please use Google or StackOverflow to answer that question. This tracker is only for issues specific to Chaquopy.
