### ISSUE TITLE
Using chaquopy7.0.3 pip install "openpyxl" failed

### ISSUE THREAD

**Issue by hjlogzw** [chaquo/chaquopy#490]
#### Chaquopy version
7.0.3 

#### Relevant parts of your build.gradle file

python {
            buildPython "D:/python3.8/python.exe"
            pip{
                install "requests"
                install "urlencode==0.0.1"
                install "urllib3==1.26.4"
                install "pyquery==1.4.3"
                install "numpy"
                install "opencv-python==4.5.1.48"
                install "Pillow"
                install "pycryptodome"
                install "scipy"
                install "openpyxl"
            }
        }

#### Describe your issue
 
“Toggle view” :
Chaquopy: Failed to process E:\codeTest\YX_application\app\build\pip\debug\armeabi-v7a\openpyxl-3.0.7.dist-info
Traceback (most recent call last):
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\metadata.py", line 733, in __init__
  File "D:\python3.8\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\python3.8\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python3.8\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python3.8\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python3.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\chaquopy\pip_install.py", line 341, in <module>
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\chaquopy\pip_install.py", line 59, in main
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\chaquopy\pip_install.py", line 137, in pip_install
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\database.py", line 555, in __init__
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\metadata.py", line 742, in __init__
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\metadata.py", line 281, in __init__
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\metadata.py", line 383, in read_file
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\metadata.py", line 478, in set
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\version.py", line 714, in is_valid_constraint_list
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\version.py", line 704, in is_valid_matcher
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\version.py", line 104, in __init__
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\version.py", line 98, in parse_requirement
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\util.py", line 237, in parse_requirement
  File "E:\codeTest\YX_application\app\build\generated\python\bp.zip\pip\_vendor\distlib\util.py", line 220, in get_versions
SyntaxError: invalid constraint: 

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'D:/python3.8/python.exe'' finished with non-zero exit value 1

**Comment by mhsmith** [comment]
As mentioned in the [change log](https://chaquo.com/chaquopy/doc/current/changelog.html), this issue was fixed in Chaquopy version 8.0.1. 

To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle`. If possible, I recommend you use the current version, 9.1.0.
