### ISSUE TITLE
com.chaquo.python.PyException: OSError: dlopen failed: undefined symbol

### ISSUE THREAD

**Issue by hjlogzw** [chaquo/chaquopy#494]
#### Chaquopy version
9.1.0

#### Devices or emulators where the issue happens
use  emulator named OPPO PCRT00

#### Relevant parts of your code
```
def embed(cover_image_path, stego_image_dir, cover_image, msg_file_path, password, channel, payload=p.payload):

     me = os.path.abspath(os.path.dirname(__file__))
     lib = ctypes.cdll.LoadLibrary(os.path.join(me, "lib", "stc.so"))
```

#### Describe your issue
I'm trying to use python call function in stc.so, I put stc.so under the project directory: app/src/main/python/lib/stc.so
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.YX_app, PID: 4103
    com.chaquo.python.PyException: OSError: dlopen failed: undefined symbol: Java_com_sina_weibo_sdk_net_HttpManager_calcOauthSignNative__Landroid_content_Context_2Ljava_lang_String_2Ljava_lang_String_2
        at <python>.ctypes.__init__(__init__.py:373)
        at <python>.java.android.importer.CDLL_init_override(importer.py:137)
        at <python>.ctypes.LoadLibrary(__init__.py:451)
        at <python>.stc.embed(stc.py:108)
        at <python>.embed_main.main_embed(embed_main.py:61)
        at <python>.example_embed.start_main(example_embed.py:14)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.yx_application.MainActivity$1.run(MainActivity.java:40)
        at java.lang.Thread.run(Thread.java:761)

```

**Comment by mhsmith** [comment]
You'll have to find whatever library contains that symbol, add it to your app, and load it before stc.so.
