### ISSUE TITLE
Can Chaquopy 9.1.0 support Scikit-Image 0.17.2

### ISSUE THREAD

**Issue by Josonlchui** [chaquo/chaquopy#509]
1)I use python 3.8 to write small api program to interface with android studio with Chaquopy 9.1.0. 

2)Setup in build.gradle(app) as follows;
        python {

            buildPython "C:/Users/user/anaconda3/envs/rembg/python.exe"
            pip
                   {

                       install "rembg"
                    }
        }
3) Build error as follows, Can Chaquopy support Scikit-Image 0.17.2 or only 0.16.2?

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting rembg
Collecting torch>=1.7.0 (from rembg)
  Using cached https://chaquo.com/pypi-7.0/torch/torch-1.8.1-3-cp38-cp38-android_16_armeabi_v7a.whl
Collecting tqdm>=4.51.0 (from rembg)
  Using cached https://files.pythonhosted.org/packages/b4/20/9f1e974bb4761128fc0d0a32813eaa92827309b1756c4b892d28adfb4415/tqdm-4.61.1-py2.py3-none-any.whl
Collecting torchvision>=0.8.1 (from rembg)
  Using cached https://chaquo.com/pypi-7.0/torchvision/torchvision-0.9.1-1-cp38-cp38-android_16_armeabi_v7a.whl
Collecting hsh>=1.1.0 (from rembg)
  Using cached https://files.pythonhosted.org/packages/0a/d1/336bc05affc776b3b34ac1cddcf8f7e1fd081cef9b4034d778b5833c6c20/hsh-1.1.0-py2.py3-none-any.whl
Collecting numpy>=1.19.5 (from rembg)
  Using cached https://files.pythonhosted.org/packages/66/03/818876390c7ff4484d5a05398a618cfdaf0a2b9abb3a7c7ccd59fe181008/numpy-1.21.0.zip
Collecting flask>=1.1.2 (from rembg)
  Using cached https://files.pythonhosted.org/packages/54/4f/1b294c1a4ab7b2ad5ca5fc4a9a65a22ef1ac48be126289d97668852d4ab3/Flask-2.0.1-py3-none-any.whl
Collecting scikit-image>=0.17.2 (from rembg)
  Using cached https://files.pythonhosted.org/packages/6e/be/a8ccf9d949a55023cf02438310e068c263ce3dd6bbf31f9229d3db6e551a/scikit-image-0.18.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-evraboiq\scikit-image\setup.py", line 14, in <module>
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-evraboiq\scikit-image\
ERROR: Failed to install scikit-image>=0.17.2 from https://files.pythonhosted.org/packages/6e/be/a8ccf9d949a55023cf02438310e068c263ce3dd6bbf31f9229d3db6e551a/scikit-image-0.18.1.tar.gz (from rembg).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Or try using one of the following versions, which are available as pre-built wheels: ['0.16.2'].
Chaquopy: Exit status 1
Failed to install scikit-image>=0.17.2 from https://files.pythonhosted.org/packages/6e/be/a8ccf9d949a55023cf02438310e068c263ce3dd6bbf31f9229d3db6e551a/scikit-image-0.18.1.tar.gz (from rembg).

> Task :app:generateDebugPythonRequirements FAILED

Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/user/anaconda3/envs/rembg/python.exe'' finished with non-zero exit value 1

Thanks.

**Comment by mhsmith** [comment]
Thanks, we'll take a look at this, but it might not be for a couple of weeks.

**Comment by mdamaan08** [comment]
Failed to install scikit-learn==0.20.2 from https://files.pythonhosted.org/packages/49/0e/8312ac2d7f38537361b943c8cde4b16dadcc9389760bb855323b67bac091/scikit-learn-0.20.2.tar.gz.

Please update the solution ASAP.

**Comment by mhsmith** [comment]
As well as scikit-learn, rembg also requires newer versions of numpy, scipy, and pillow. So we won't be able to support it just now. Sorry about that.

If anyone else needs a newer vesion of scikit-learn, please click the thumbs up button above and post a comment explaining why you need it. Or if you need a newer version of numpy, scipy, or pillow, please create a separate issue, and explain why you need it.

**Comment by eldon97** [comment]
i definitely need the newer version of the library, because there is a lot of fixes and improvement on the algorithm. as you said scikit-image version that chaquopy used currently is version 0.16.2 which is really outdated because that version already release from 3 years ago. it's not sufficient to use the outdated version. at least if you don't mind please update only for scikit-image library to the latest version 0.19.3 because as i already said before in my issue, the function that i use (peak_local_max) is producing different result between old and new version therefore the newer version give the better result in my case.

**Comment by mhsmith** [comment]
Version 0.19.3 is more difficult to build, so I've done version 0.18.3 instead, which gives the same output with your peak_local_max example.

I'm not able to fully test it at the moment, so I've put it in a temporary repository. To use it, add the following line to the `pip` section of your build.gradle file:
```
options "--extra-index-url", "https://chaquo.com/pypi-test/"
```

Please let me know how you get on.

**Comment by eldon97** [comment]
great! i have tested the version 0.18.3 and in my case it's sufficient to get the best result. it works fine. thank you.
