### ISSUE TITLE
com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.chaquopyexamlpe/files/chaquopy/AssetFinder/app/src/main/python/pretrained/modnet_photographic_portrait_matting.ckpt'

### ISSUE THREAD

**Issue by fadiboy-1998** [chaquo/chaquopy#517]
Hi there this error is frustrating me from long time...
i have a pretrained model in my src/main/python/pretrained directory...
it is giving me the error of no such directory...

using chaquopy version ---> com.chaquo.python:gradle:9.1.0

full stack is---->
```
2021-07-10 15:18:06.680 10344-10344/com.example.chaquopyexamlpe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chaquopyexamlpe, PID: 10344
    java.lang.RuntimeException: Unable to resume activity {com.example.chaquopyexamlpe/com.example.chaquopyexamlpe.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.chaquopyexamlpe/files/chaquopy/AssetFinder/app/src/main/python/pretrained/modnet_photographic_portrait_matting.ckpt'
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/user/0/com.example.chaquopyexamlpe/files/chaquopy/AssetFinder/app/src/main/python/pretrained/modnet_photographic_portrait_matting.ckpt'
        at <python>.torch.serialization.__init__(serialization.py:211)
        at <python>.torch.serialization._open_file_like(serialization.py:230)
        at <python>.torch.serialization.load(serialization.py:579)
        at <python>.inference.parameter_load(inference.py:47)
        at <python>.inference.__init__(inference.py:43)
        at <python>.inference.imageBGRemover(inference.py:277)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.chaquopyexamlpe.MainActivity$1.onActivityResult(MainActivity.java:78)
        at com.example.chaquopyexamlpe.MainActivity$1.onActivityResult(MainActivity.java:49)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
        at android.app.Fragment.performStart(Fragment.java:2534)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2984)
        at android.app.FragmentController.dispatchStart(FragmentController.java:189)
        at android.app.Activity.performStart(Activity.java:7035)
        at android.app.Activity.performRestart(Activity.java:7104)
        at android.app.Activity.performResume(Activity.java:7109)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by mhsmith** [comment]
As it says in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#data-files), data files within a top-level package (i.e. a top-level directory containing an `__init__.py` file) will not be available until the first time that package is imported. 

Does the `pretrained` directory contain an `__init__.py` file? Assuming it does, the file is only necessary if there are some Python modules in the directory. If there are no modules in that directory, then you can remove the `__init__.py` file. If there are modules there, then you'll have to run `import pretrained` to make your data files available.

**Comment by fadiboy-1998** [comment]
I have no __init__.py file under this directory 
this is my project structure:

![Capture](https://user-images.githubusercontent.com/62032619/125235476-f6c97a80-e2fb-11eb-869e-820671080500.PNG)

and this  is where I want the file path :
![2](https://user-images.githubusercontent.com/62032619/125235642-37c18f00-e2fc-11eb-8dbe-5add0fa89766.PNG)


and the is how I am using it further:
![1](https://user-images.githubusercontent.com/62032619/125235683-4740d800-e2fc-11eb-8622-436f4c1d8fb2.PNG)


and the log cat is same as i have shared before...

**Comment by fadiboy-1998** [comment]
Thanks for the help...
solved the problem
Thanks...

**Comment by mhsmith** [comment]
Thanks, I guess you saw the same thing as I did from your deleted comment: that the path should be [relative to the Python file](https://chaquo.com/chaquopy/doc/current/android.html#data-files), not relative to the project directory.
