### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by rishabh-gupta-boop** [chaquo/chaquopy#536]
I run a chaquo in my android studio with importing external module and python script.
My download module by 
```
pip {
                install "instabot"

            }
```
inside defaultConfig>python

then i change some code in my module file by going 
"C:\Users\Rishabh Gupta\AndroidStudioProjects\Intabotee\app\build\pip\debug\common\instabot\api/api.py"

In this file have a function that create new file where the script is run so i change into android cache location by

from com.chaquo.python import Python
then: str(Python.getPlatform().getApplication().getFilesDir())

But after running in my emulator the code in api.py change into default one and what i wrote above is replace with default code.

Here's is my error in logcat:
```
2021-08-23 16:42:22.581 12168-12168/com.example.intabotee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.intabotee, PID: 12168
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.intabotee/com.example.intabotee.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '//config//log/'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '//config//log/'
        at <python>.os.makedirs(os.py:223)
        at <python>.instabot.api.api.__init__(api.py:93)
        at <python>.instabot.bot.bot.__init__(bot.py:191)
        at <python>.main.<module>(main.py:14)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:783)
        at <python>.java.android.importer.exec_module(importer.py:507)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:155)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.example.intabotee.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:7906)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)  
```

**Comment by rishabh-gupta-boop** [comment]
Please anyone help me, I building an app that done automation for Instagram

**Comment by mhsmith** [comment]
You can't edit any code in the `build` directory, your changes will be overwritten when you build the app. If necessary, you can copy the code to your `src/main/python` directory and edit it there. But I don't think there's any need to do that, because this API already has a [`base_path` argument](https://github.com/ohld/igbot/blob/master/instabot/bot/bot.py#L137) which you can set to the app's files directory.

Note that you are using a package whose own documentation says it is [unmaintained and unreliable](https://github.com/ohld/igbot/blob/master/OLD_README.md).
