### ISSUE TITLE
Problem when using pandas.read_pickle

### ISSUE THREAD

**Issue by LarsG21** [chaquo/chaquopy#538]
I get an Error when trying to open an pandas dataframe from an pickle file.

#### Chaquopy version
 9.1.0

#### Devices or emulators where the issue happens
Emulated Pixel 5 API 24, API 30
Oneplus 7T

#### Relevant parts of your code
```
if not os.path.exists(os.path.join(pickles_path, threshold_pickle_name)):
        print("No fitting correlation Dataframe found",pickles_path, threshold_pickle_name)
    else:
        print("Using existing correlation Dataframe:", pickles_path, threshold_pickle_name)
threshold_df = pd.read_pickle(os.path.join(pickles_path, threshold_pickle_name))
print(type(threshold_df))
print(threshold_df.columns)
print(threshold_df.head())
```

#### Describe your issue
    
In Pycharm this code works fine. But in chaquopy it crashes at the .collumns or .head(). It seems to not read in the dataframe correctly.
The pandas.read_csv() function seems to work fine but i cant use it for my application.

Console:
```
I/python.stdout:  Using existing correlation Dataframe: /storage/emulated/0/Android/data/com.chaquo.myapplication/files/Download/

I/python.stdout:  
    test_scores.pickle

I/python.stdout: <class 'pandas.core.frame.DataFrame'>    (Output of print(type(threshold_df))

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chaquo.myapplication, PID: 3679
    com.chaquo.python.PyException: AttributeError: 'NoneType' object has no attribute 'axes'
        at <python>.pandas._libs.properties.AxisProperty.__get__(properties.pyx:63)
        at <python>.pandas.core.generic.__getattr__(generic.py:5175)
        at <python>.Lib_Functs.compare_using_paths(Lib_Functs.py:236)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.chaquo.myapplication.MainActivity$onCreate$1.onClick(MainActivity.kt:34)
        at android.view.View.performClick(View.java:7520)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
I/Process: Sending signal. PID: 3679 SIG: 9
````

**Comment by mhsmith** [comment]
> 'NoneType' object has no attribute 'axes'

Several people on StackOverflow say this error is caused by creating a pickle file with one version of Pandas and loading it with a different (probably older) version:

* https://stackoverflow.com/questions/68171140
* https://stackoverflow.com/questions/63812418

Chaquopy currently provides Pandas version 0.25.3. Can you reproduce the same error when trying to load the pickle file with that Pandas version in Pycharm?

If so, the simplest workaround would be to regenerate the pickle file with that Pandas version or older. 

If that isn't possible, let me know and I'll look into whether we can update the Chaquopy Pandas version.

**Comment by LarsG21** [comment]
Hello,

thanks for the quick answer.
When I try to use it with this version in Pycharm I get this Error:

Traceback (most recent call last):
  File "C:\Users\Lars\anaconda3\envs\pandas_test2\lib\site-packages\pandas\io\pickle.py", line 155, in read_pickle
    return pickle.load(f)
ValueError: unsupported pickle protocol: 5

So it seems your explanation is right and the older version of pandas cant handle those pickles. 
I now have to verify if the rest of my program also works with the old version of pandas.

If you could update the Chaquopy Pandas version this would be nice :D

**Comment by mhsmith** [comment]
> ValueError: unsupported pickle protocol: 5

That's probably caused by the Python version rather than the Pandas version. Can you test it with Python 3.8 or later, and Pandas 0.25.3?

**Comment by mhsmith** [comment]
Pandas version 1.3.2 is now available.
