### ISSUE TITLE
Support flower (pip package name "flwr")

### ISSUE THREAD

**Issue by devwithzachary** [chaquo/chaquopy#559]
I'm currently attempting to get flower working https://flower.dev/ however my first issue is that is requires a newer version of numpy (1.19) than what is currently rebuild in chaquopy.

I have attempted to build a newer version however hit the below error:
```

[Building wheel for numpy (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7u3qospz/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7u3qospz/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qkdymx1j --python-tag cp38
       cwd: /tmp/pip-install-7u3qospz/numpy/
  Complete output (73 lines):
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  ERROR: Command errored out with exit status 1:

  Processing numpy/random/_mt19937.pyx
  Processing numpy/random/mtrand.pyx
  Processing numpy/random/_sfc64.pyx
  Processing numpy/random/_generator.pyx
  Processing numpy/random/_pcg64.pyx
  Processing numpy/random/bit_generator.pyx
  Processing numpy/random/_bounded_integers.pyx.in
  Processing numpy/random/_common.pyx
  Processing numpy/random/_philox.pyx
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils.disabledcompiler' in numpy.distutils; trying from distutils
  customize DisabledCompiler
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7u3qospz/numpy/setup.py", line 448, in <module>
      setup_package()
    File "/tmp/pip-install-7u3qospz/numpy/setup.py", line 440, in setup_package
      setup(**metadata)
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/tmp/pip-install-7u3qospz/numpy/setup.py", line 118, in configuration
      config.add_subpackage('numpy')
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/misc_util.py", line 1016, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/misc_util.py", line 982, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "numpy/setup.py", line 8, in configuration
      config.add_subpackage('core')
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/misc_util.py", line 1016, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/misc_util.py", line 982, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "numpy/core/setup.py", line 751, in configuration
      blas_info = get_info('blas_opt', 0)
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 581, in get_info
      return cl().get_info(notfound_action)
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 841, in get_info
      self.calc_info()
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 2026, in calc_info
      if self._calc_info(blas):
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 2012, in _calc_info
      return getattr(self, '_calc_info_{}'.format(name))()
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 1935, in _calc_info_mkl
      info = get_info('blas_mkl')
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 581, in get_info
      return cl().get_info(notfound_action)
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 841, in get_info
      self.calc_info()
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 1292, in calc_info
      info = self.check_libs2(lib_dirs, mkl_libs)
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 997, in check_libs2
      exts = self.library_extensions()
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 956, in library_extensions
      c = customized_ccompiler()
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/system_info.py", line 216, in customized_ccompiler
      global_compiler = _customized_ccompiler()
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/__init__.py", line 50, in customized_ccompiler
      c.customize('')
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/ccompiler.py", line 88, in <lambda>
      m = lambda self, *args, **kw: func(self, *args, **kw)
    File "/tmp/pip-install-7u3qospz/numpy/numpy/distutils/ccompiler.py", line 533, in CCompiler_customize
      self.compile([fn], output_dir=tmpdir,
    File "/media/sf_shared/FLDemo/backend/app/build/generated/python/bp.zip/setuptools/monkey.py", line 155, in compile
    File "/media/sf_shared/FLDemo/backend/app/build/generated/python/bp.zip/setuptools/monkey.py", line 185, in chaquopy_block_native
  distutils.errors.DistutilsPlatformError: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7u3qospz/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7u3qospz/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qkdymx1j --python-tag cp38 Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7u3qospz/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7u3qospz/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qkdymx1j --python-tag cp38 Check the logs for full command output.]([url](url))

```

Any assistance or pointers would be great!

**Comment by mhsmith** [comment]
Thanks for the report. I'll look into providing a new version of NumPy and get back to you in the next few days.

**Comment by devwithzachary** [comment]
Good Afternoon, just wanted to check in to see if there had been any progress? No pressure either way,

**Comment by mhsmith** [comment]
Yes, it looks like it will be possible. I should have more news soon.

**Comment by mhsmith** [comment]
NumPy 1.21.4 is now available for Chaquopy, and `flwr` can be installed successfully.

**Comment by mhsmith** [comment]
NumPy 1.21.4 is incompatible with TensorFlow 2.1.0 (#570), so we've removed it from the default repository for Python 3.8. We've replaced it with NumPy 1.19.5, so `flwr` can still be installed.

If you need a newer version of NumPy, you can either:

* Use [Python 3.9 or later](https://chaquo.com/chaquopy/doc/current/android.html#python-version); or
* On Python 3.8, add this line to the `pip` block in your build.gradle file:

      options "--extra-index-url", "https://chaquo.com/pypi-extra/"
