### ISSUE TITLE
unable to build package "sklearn"

### ISSUE THREAD

**Issue by Eldho-Abraham-coder** [chaquo/chaquopy#563]
Chaquopy version
com.chaquo.python:gradle:7.0.2

Relevant parts of your build.gradle file
sourceSets{ 
    main{         
     python{  
             srcDirs=["src/main/python"]         
     }   
  } 
} 
python{     
          //buildPython "C:/Python/Python39"     
         //buildPython "python3"      
pip {        
         install "numpy"         
         install "pandas"       
         install "scipy"        
         install "matplotlib"        
         //install "os"         
        //install "pickle"         
        install "dill"         
        //install "copy"        
        install "scipy"        
        install "sklearn"   
  }     

Describe your issue
build fails
Collecting sklearn
  Using cached https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\PICC\latest\SmartPICC_App_Gen2\app\build\generated\python\bp.zip\setuptools\__init__.py", line 14, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\PICC\latest\SmartPICC_App_Gen2\app\build\generated\python\bp.zip\setuptools\dist.py", line 24, in <module>
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\PICC\latest\SmartPICC_App_Gen2\app\build\generated\python\bp.zip\setuptools\depends.py", line 7, in <module>
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Eldho\AppData\Local\Temp\pip-install-m_xpy7wp\sklearn\
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "<frozen zipimport>", line 259, in load_module
      File "C:\test\app\build\generated\python\bp.zip\setuptools\py33compat.py", line 54, in <module>
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    
    ----------------------------------------
ERROR: Failed to install sklearn from https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install sklearn from https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz.

**Comment by mhsmith** [comment]
See #416, and please search for existing issues before creating new ones.
