### ISSUE TITLE
Process 'command 'python3'' finished for "numpy==1.19.5"

### ISSUE THREAD

**Issue by msh-nayan** [chaquo/chaquopy#564]
Hello,
Greetings. 

#### Chaquopy version

9.1.0 (paid version)

#### Relevant parts of your build.gradle file

(1) root label build.gradle file

```
dependencies {
        classpath "com.android.tools.build:gradle:4.1.2"
        classpath "com.chaquo.python:gradle:9.1.0"
}
```

(2) app label build.gradle file 
```
plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}
```

```
sourceSets {
            main {
                python {
                    srcDirs = ["src/main/python"]
                }
            }
        }
        python {
            buildPython "/usr/bin/python3"
            buildPython "python3"
            pip {
                install "numpy==1.19.5"
                install "pandas"
                install "scikit-learn"
                install "tensorflow"
                install "h5py"
            }
        }
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
```

#### Describe your issue

If we use that specif "numpy==1.19.5" version, we get the following error

```
Executing tasks: [clean, :app:assembleBjitDebug] in project /home/msh/Android/AndroidStudioProject/01_Official_Projects/01_Android/EdgeAI/00_on_device/00_od1/p1246_jasmy_labo.Edge_AI/EdgeAIAndroid


> Configure project :app
Warning: This version of Chaquopy has not been tested with Android Gradle plugin versions beyond 4.1.1. If you experience problems, please edit the version of com.android.tools.build:gradle in your top-level build.gradle file. See https://chaquo.com/chaquopy/doc/current/versions.html.

> Task :clean
> Task :app:clean
> Task :app:preBuild UP-TO-DATE
> Task :app:preBjitDebugBuild UP-TO-DATE
> Task :app:compileBjitDebugAidl NO-SOURCE
> Task :app:compileBjitDebugRenderscript NO-SOURCE
> Task :app:generateBjitDebugBuildConfig
> Task :app:extractPythonBuildPackages

> Task :app:generateBjitDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting numpy==1.19.5
  Using cached https://files.pythonhosted.org/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip
Collecting pandas
  Using version 1.3.2 (newest version is 1.3.4, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/pandas/pandas-1.3.2-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting scikit-learn
  Using version 0.24.1 (newest version is 1.0.1, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/scikit-learn/scikit_learn-0.24.1-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting tensorflow
  Using cached https://chaquo.com/pypi-7.0/tensorflow/tensorflow-2.1.0-9-cp38-cp38-android_21_arm64_v8a.whl
Collecting h5py
  Using version 2.10.0 (newest version is 3.6.0, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/h5py/h5py-2.10.0-1-cp38-cp38-android_21_arm64_v8a.whl
Collecting python-dateutil>=2.7.3 (from pandas)
  Using cached https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
Collecting pytz>=2017.3 (from pandas)
  Using cached https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl
Collecting chaquopy-libcxx>=10000 (from pandas)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libcxx/chaquopy_libcxx-10000-0-py3-none-android_21_arm64_v8a.whl
Collecting chaquopy-openblas>=0.2.20 (from scikit-learn)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-openblas/chaquopy_openblas-0.2.20-5-py3-none-android_21_arm64_v8a.whl
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Using cached https://files.pythonhosted.org/packages/ff/fe/8aaca2a0db7fd80f0b2cf8a16a034d3eea8102d58ff9331d2aaf1f06766a/threadpoolctl-3.0.0-py3-none-any.whl
Collecting scipy>=0.19.1 (from scikit-learn)
  Using version 1.4.1 (newest version is 1.7.2, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/scipy/scipy-1.4.1-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting joblib>=0.11 (from scikit-learn)
  Using cached https://files.pythonhosted.org/packages/3e/d5/0163eb0cfa0b673aa4fe1cd3ea9d8a81ea0f32e50807b0c295871e4aab2e/joblib-1.1.0-py2.py3-none-any.whl
Collecting google-pasta>=0.1.6 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl
Collecting protobuf>=3.8.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/c1/12/7479ece04931984162698bfaa05cbb2fc23d7f6ee1ab5146cfc6ade56a31/protobuf-3.19.1-py2.py3-none-any.whl
Collecting wheel>=0.26; python_version >= "3" (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/04/80/cad93b40262f5d09f6de82adbee452fd43cdff60830b56a74c5930f7e277/wheel-0.37.0-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow)
  Using version 1.39.0 (newest version is 1.42.0, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/grpcio/grpcio-1.39.0-0-cp38-cp38-android_21_arm64_v8a.whl
Collecting tensorboard<2.2.0,>=2.1.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/d9/41/bbf49b61370e4f4d245d4c6051dfb6db80cec672605c91b1652ac8cc3d38/tensorboard-2.1.1-py3-none-any.whl
Collecting tensorflow-estimator<2.2.0,>=2.1.0rc0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/18/90/b77c328a1304437ab1310b463e533fa7689f4bfc41549593056d812fab8e/tensorflow_estimator-2.1.0-py2.py3-none-any.whl
Collecting absl-py>=0.7.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/2c/03/e3e19d3faf430ede32e41221b294e37952e06acc96781c417ac25d4a0324/absl_py-1.0.0-py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow)
Collecting wrapt>=1.11.1 (from tensorflow)
Collecting astor>=0.6.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Collecting gast==0.2.2 (from tensorflow)
Collecting keras-preprocessing>=1.1.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/79/4c/7c3275a01e12ef9368a892926ab932b33bb13d55794881e3573482b378a7/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl
Collecting opt-einsum>=2.3.2 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/bc/19/404708a7e54ad2798907210462fd950c3442ea51acc8790f3da48d2bee8b/opt_einsum-3.3.0-py3-none-any.whl
Collecting six>=1.12.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting keras-applications>=1.0.8 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting chaquopy-hdf5>=1.10.2 (from h5py)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-hdf5/chaquopy_hdf5-1.10.2-1-py3-none-android_21_arm64_v8a.whl
Collecting chaquopy-libgfortran>=4.9 (from chaquopy-openblas>=0.2.20->scikit-learn)
  Using cached https://chaquo.com/pypi-7.0/chaquopy-libgfortran/chaquopy_libgfortran-4.9-0-py3-none-android_21_arm64_v8a.whl
Collecting setuptools>=41.0.0 (from tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/18/ad/ec41343a49a0371ea40daf37b1ba2c11333cdd121cb378161635d14b9750/setuptools-59.2.0-py3-none-any.whl
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/b1/0e/0636cc1448a7abc444fb1b3a63655e294e0d2d49092dc3de05241be6d43c/google_auth_oauthlib-0.4.6-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/1e/73/51137805d1b8d97367a8a77cae4a792af14bb7ce58fbd071af294c740cf0/Werkzeug-2.0.2-py3-none-any.whl
Collecting google-auth<2,>=1.6.3 (from tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/fb/7a/1b3eb54caee1b8c73c2c3645f78a382eca4805a301a30c64a078e736e446/google_auth-1.35.0-py2.py3-none-any.whl
Collecting requests<3,>=2.21.0 (from tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/92/96/144f70b972a9c0eabbd4391ef93ccd49d0f2747f4f6a2a2738e99e5adc65/requests-2.26.0-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/9f/d4/2c7f83915d437736996b2674300c6c4b578a6f897f34e40f5c04db146719/Markdown-3.3.6-py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl
Collecting rsa<5,>=3.1.4; python_version >= "3.6" (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/e9/93/0c0f002031f18b53af7a6166103c02b9c0667be528944137cc954ec921b3/rsa-4.7.2-py3-none-any.whl
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/ea/c1/4740af52db75e6dbdd57fc7e9478439815bbac549c1c05881be27d19a17d/cachetools-4.2.4-py3-none-any.whl
Collecting charset-normalizer~=2.0.0; python_version >= "3" (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/de/c8/820b1546c68efcbbe3c1b10dd925fbd84a0dda7438bc18db0ef1fa567733/charset_normalizer-2.0.7-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/af/f4/524415c0744552cce7d8bf3669af78e8a069514405ea4fcbd0cc44733744/urllib3-1.26.7-py2.py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3" (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl
Collecting importlib-metadata>=4.4; python_version < "3.10" (from markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/c4/1f/e2238896149df09953efcc53bdcc7d23597d6c53e428c30e572eda5ec6eb/importlib_metadata-4.8.2-py3-none-any.whl
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/e8/5d/9dd1c29e5a786525f6342f6c1d812ed2e37edc653ad297048c1668988053/oauthlib-3.1.1-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard<2.2.0,>=2.1.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy: started
  Running setup.py bdist_wheel for numpy: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -S -c "import setuptools, tokenize;__file__='/tmp/pip-install-hsm7q_p7/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-w0juavja --python-tag py3:
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_philox.pyx
  Traceback (most recent call last):
    File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 59, in process_pyx
      from Cython.Compiler.Version import version as cython_version
  ModuleNotFoundError: No module named 'Cython'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 235, in <module>
      main()
    File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 231, in main
      find_process_files(root_dir)
    File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 222, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 188, in process
      processor_function(fromfile, tofile)
    File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 64, in process_pyx
      raise OSError('Cython needs to be installed in Python as a module')
  OSError: Cython needs to be installed in Python as a module
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-hsm7q_p7/numpy/setup.py", line 508, in <module>
      setup_package()
    File "/tmp/pip-install-hsm7q_p7/numpy/setup.py", line 488, in setup_package
      generate_cython()
    File "/tmp/pip-install-hsm7q_p7/numpy/setup.py", line 285, in generate_cython
      raise RuntimeError("Running cythonize failed!")
  RuntimeError: Running cythonize failed!
  
  ----------------------------------------
  Running setup.py clean for numpy
  Complete output from command /usr/bin/python3 -u -S -c "import setuptools, tokenize;__file__='/tmp/pip-install-hsm7q_p7/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Running from numpy source directory.
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Failed cleaning build dir for numpy
Failed to build numpy
Installing collected packages: numpy, six, python-dateutil, pytz, chaquopy-libcxx, pandas, chaquopy-libgfortran, chaquopy-openblas, threadpoolctl, scipy, joblib, scikit-learn, google-pasta, protobuf, wheel, grpcio, setuptools, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, oauthlib, charset-normalizer, certifi, urllib3, idna, requests, requests-oauthlib, google-auth-oauthlib, absl-py, werkzeug, zipp, importlib-metadata, markdown, tensorboard, tensorflow-estimator, termcolor, wrapt, astor, gast, keras-preprocessing, opt-einsum, chaquopy-hdf5, h5py, keras-applications, tensorflow
  Running setup.py install for numpy: started
    Running setup.py install for numpy: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hsm7q_p7/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --no-user-cfg install --record /tmp/pip-record-wqcw0bo6/install-record.txt --single-version-externally-managed --no-compile --home=/tmp/pip-target-ib0vyo9_ --prefix=:
    Running from numpy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
    
    
    Cythonizing sources
    numpy/random/_bounded_integers.pxd.in has not changed
    Processing numpy/random/_philox.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-hsm7q_p7/numpy/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hsm7q_p7/numpy/setup.py", line 508, in <module>
        setup_package()
      File "/tmp/pip-install-hsm7q_p7/numpy/setup.py", line 488, in setup_package
        generate_cython()
      File "/tmp/pip-install-hsm7q_p7/numpy/setup.py", line 285, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hsm7q_p7/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --no-user-cfg install --record /tmp/pip-record-wqcw0bo6/install-record.txt --single-version-externally-managed --no-compile --home=/tmp/pip-target-ib0vyo9_ --prefix=" failed with error code 1 in /tmp/pip-install-hsm7q_p7/numpy/
Chaquopy: Exit status 1

> Task :app:generateBjitDebugPythonRequirements FAILED

> Task :app:mergeBjitDebugPythonSources
Warning: Failed to compile to .pyc format: buildPython version 3.6.9 is incompatible. See https://chaquo.com/chaquopy/doc/current/android.html#android-bytecode.

> Task :app:javaPreCompileBjitDebug
> Task :app:generateBjitDebugResValues
> Task :app:generateBjitDebugResources
> Task :app:checkBjitDebugAarMetadata
> Task :app:createBjitDebugCompatibleScreenManifests
> Task :app:extractDeepLinksBjitDebug

> Task :app:processBjitDebugMainManifest
[org.tensorflow:tensorflow-lite:2.7.0] /home/msh/.gradle/caches/transforms-2/files-2.1/1ae9fc9ca7a7f2f20dd1340acd519115/jetified-tensorflow-lite-2.7.0/AndroidManifest.xml Warning:
	Package name 'org.tensorflow.lite' used in: org.tensorflow:tensorflow-lite:2.7.0, org.tensorflow:tensorflow-lite-api:2.7.0.
[org.tensorflow:tensorflow-lite-support:0.3.0] /home/msh/.gradle/caches/transforms-2/files-2.1/c1368a8b9f702fb51aa6aca1abdb33de/jetified-tensorflow-lite-support-0.3.0/AndroidManifest.xml Warning:
	Package name 'org.tensorflow.lite.support' used in: org.tensorflow:tensorflow-lite-support:0.3.0, org.tensorflow:tensorflow-lite-support-api:0.3.0.

> Task :app:processBjitDebugManifest
> Task :app:mergeBjitDebugNativeDebugMetadata NO-SOURCE
> Task :app:mergeBjitDebugShaders
> Task :app:mergeBjitDebugResources
> Task :app:compileBjitDebugShaders NO-SOURCE
> Task :app:generateBjitDebugAssets UP-TO-DATE
> Task :app:generateBjitDebugPythonAppAssets
> Task :app:generateBjitDebugPythonLicenseAssets
> Task :app:generateBjitDebugPythonMiscAssets
> Task :app:processBjitDebugJavaRes NO-SOURCE
> Task :app:generateBjitDebugPythonJniLibs
> Task :app:mergeBjitDebugJniLibFolders
> Task :app:checkBjitDebugDuplicateClasses
> Task :app:processBjitDebugManifestForPackage
> Task :app:processBjitDebugResources
> Task :app:validateSigningBjitDebug
> Task :app:mergeBjitDebugNativeLibs

> Task :app:stripBjitDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libchaquopy_java.so, libcrypto_chaquopy.so, libpython3.8.so, libsqlite3_chaquopy.so, libssl_chaquopy.so, libtensorflow_inference.so, libtensorflowlite_jni.so.

> Task :app:mergeLibDexBjitDebug
> Task :app:desugarBjitDebugFileDependencies
> Task :app:mergeExtDexBjitDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateBjitDebugPythonRequirements'.
> Process 'command 'python3'' finished with non-zero exit value 1
  
  To view full details in Android Studio:
  * In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
  * In version 3.5 and older, click the 'Toggle view' button to the left of this message.
  * Then scroll up to see the full output.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s
29 actionable tasks: 29 executed

```

Ubuntu version : Ubuntu 18.04.5 LTS
Android Studio version : Android Studio Arctic Fox | 2020.3.1 Patch 2 (Build #AI-203.7717.56.2031.7678000, built on August 27, 2021, Runtime version: 11.0.10+0-b96-7249189 amd64)

Just to let you know, we have a plan to use the latest Chaquopy version (10.0.1) & Python version 3.8.11... but can you please help us, if we use that specific numpy version, what is the issue and how to overcome it?

Thanks.

**Comment by mhsmith** [comment]
As shown [here](https://chaquo.com/pypi-7.0/numpy/), we currently only provide NumPy versions 1.17.4 and 1.21.4.
