### ISSUE TITLE
Gradle fails at building python packages

### ISSUE THREAD

**Issue by audvi** [chaquo/chaquopy#567]
Hello, 
I have a android app with a python parts that used to work well. But after cleaning my app, I cannot rebuild it : it fails installing python packages with pip. No package works.
I don't understand what is going wrong.
Here is my build log file : 
```
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0, 
Collecting scipy==1.4.1
Exception:
Traceback (most recent call last):
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\basecommand.py", line 236, in main
    status = self.run(options, args)
  File "D:\r\IA2Android\build\generated\python\bp.zip\pip\_internal\commands\install.py", line 304, in run
    resolver.resolve(requirement_set)
  File "D:\\build\generated\python\bp.zip\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\resolve.py", line 208, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\operations\prepare.py", line 247, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\req\req_install.py", line 310, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "D:\IA2Android\build\generated\python\bp.zip\pip\_internal\index.py", line 500, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\index.py", line 458, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "D:\r\IA2Android\build\generated\python\bp.zip\pip\_internal\index.py", line 613, in _get_pages
    page = self._get_page(location)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\index.py", line 732, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_internal\index.py", line 836, in get_page
    resp = session.get(
  File "D:\IA2Android\build\generated\python\bp.zip\pip\_vendor\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\A2Android\build\generated\python\bp.zip\pip\_internal\download.py", line 401, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\requests\sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\requests\sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\requests\sessions.py", line 210, in resolve_redirects
    resp = self.send(
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\cachecontrol\adapter.py", line 42, in send
    cached_response = self.controller.cached_request(request)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\cachecontrol\controller.py", line 137, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\cachecontrol\serialize.py", line 98, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\cachecontrol\serialize.py", line 190, in _loads_v4
    cached = msgpack.loads(data, encoding='utf-8')
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\msgpack\fallback.py", line 121, in unpackb
    ret = unpacker._unpack()
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\msgpack\fallback.py", line 606, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\msgpack\fallback.py", line 606, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "D:\\IA2Android\build\generated\python\bp.zip\pip\_vendor\msgpack\fallback.py", line 623, in _unpack
    return bytes(obj)
MemoryError
Chaquopy: Exit status 2

> Task :IA2Android:generateDebugPythonRequirements FAILED
```
I am using Chaquopy 9.0.0 with gradle plugin 4.0.0

Thank you for your help

**Comment by mhsmith** [comment]
It looks like pip is failing while trying to load something from its cache, so maybe the cache has been corrupted. Try deleting the directory `C:\Users\YOUR_USERNAME\AppData\Local\chaquopy\pip`.

If that doesn't work, try updating to the newest version of Chaquopy.

**Comment by audvi** [comment]
Thank you for your answer. 
I tried clearing pip cache with no success.
Then I updated chaquopy version, gradle version(4.2.0) and plugin (7.0.1). So it made have upgrading Android studio....with the exact same error.
Python is 3.8.5
pip is 21.3.1

**Comment by mhsmith** [comment]
What Chaquopy version are you using now?

Does the problem happen on any other build machine?

**Comment by audvi** [comment]
I am using chaquopy 10.0.1
The program work on other another machine (at least with old settings) but I did not dare to do a rebuild

**Comment by audvi** [comment]
Wait, I managed to get 1 library : scipy
But it fails at the next one (numpy), I tried to switch to another lin (pandas) with the same failure : 
```
> Task :IA2Android:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0, https://github.com/neuropsychology/NeuroKit/zipball/master
Collecting scipy==1.4.1
  Using cached https://chaquo.com/pypi-7.0/scipy/scipy-1.4.1-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting pandas==0.25.3
ERROR: Exception:
Traceback (most recent call last):
...
MemoryError
Chaquopy: Exit status 2

```

**Comment by mhsmith** [comment]
> The program work on other another machine (at least with old settings) but I did not dare to do a rebuild

I haven't had any other reports of this problem, so you probably don't need to worry about that.

Here are a couple of other things you could try, if you haven't already:
* Do a clean build (in Android Studio, Build > Rebuild Project)
* Install the newest version of Python 3.8, and make sure the [`buildPython`](https://chaquo.com/chaquopy/doc/current/android.html#buildpython) setting is pointing at it.
* Reboot the build machine.

After deleting the pip cache directory and building again, is the stack trace exactly the same? If not, can you post the new stack trace?

**Comment by audvi** [comment]
Hello, 
I did all of it and it worked ! I can build my app again :)
Thank you very much !
