### ISSUE TITLE
AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#57]
```
java.lang.RuntimeException: Unable to create application com.chaquo.python.android.PyApplication: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5977)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
     Caused by: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at <python>.initialize(/data/user/0/niu.testapp/files/chaquopy/bootstrap.zip/java/android/importer.py:59)
        at <python>.initialize(/data/user/0/niu.testapp/files/chaquopy/bootstrap.zip/java/android/__init__.py:16)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:140)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:135)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.chaquo.python.android.PyApplication.onCreate(PyApplication.java:16)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5974)
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6780) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) 
```

**Comment by mhsmith** [comment]
What do you have in the `pip` block of your `build.gradle`?

If possible, could you also email your APK to me, or upload it somewhere and send me the link? It should be found under `app/build/outputs/apk`.

**Comment by mhsmith** [comment]
It's also worth trying Build > Clean Project in case Gradle has somehow gotten confused.

**Comment by chaocharleswang** [comment]
I tried cleaning, rebuilding. Still not work. I created a new one with the same configuration. It works again. Weird.

________________________________

**Comment by mhsmith** [comment]
So has the problem resolved itself? If you can still reproduce it, I'd still like to take a look at the corresponding APK. It will of course be treated as confidential.

**Comment by mhsmith** [comment]
If it's still happening, it could be a problem with Instant Run, in which case uninstalling and reinstalling the app might help.

**Comment by chaocharleswang** [comment]
Updated Android Studio. The problem disappears.

**Comment by chaocharleswang** [comment]
I got the same error suddenly.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: frontierapp.sonosvideo, PID: 18076
    java.lang.RuntimeException: Unable to create application frontierapp.sonosvideo.App: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at <python>.java.android.importer.initialize_importlib(importer.py:62)
        at <python>.java.android.importer.initialize(importer.py:40)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:130)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.chaquo.python.android.PyApplication.onCreate(PyApplication.java:16)
        at frontierapp.sonosvideo.App.onCreate(App.java:49)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mhsmith** [comment]
Merged from #118:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testdemo, PID: 18076
    java.lang.RuntimeException: Unable to create application com.testdemo.App: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.chaquo.python.PyException: AssertionError: Finder for '/android_asset/chaquopy/requirements-common.zip' is NoneType
        at <python>.java.android.importer.initialize_importlib(importer.py:62)
        at <python>.java.android.importer.initialize(importer.py:40)
        at <python>.java.android.initialize(__init__.py:13)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:283)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:255)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
        at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:130)
        at com.chaquo.python.Python.start(Python.java:51)
        at com.chaquo.python.android.PyApplication.onCreate(PyApplication.java:16)
        at com.testdemo.App.onCreate(App.java:49)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

> My project worked yesterday. But it does not work today without any changes.
>
>I switched chaquo to the old version 6.0.0. It worked well. Then I switched it back to the latest version 6.2.1. It works well again. Can you please check the problem?

**Comment by mhsmith** [comment]
Please provide the following information:
* Device type
* Android version
* Version of `android.tools.build:gradle` in your project’s top-level `build.gradle` file

**Comment by mhsmith** [comment]
The same error appeared in https://github.com/chaquo/chaquopy/issues/31#issuecomment-483594599.

**Comment by mhsmith** [comment]
This area has changed significantly in Chaquopy 6.3.0. If the problem happens again on that version or newer, please reopen and give details.
