### ISSUE TITLE
Error while running OpenCV with Chaquopy

### ISSUE THREAD

**Issue by ragequitting101** [chaquo/chaquopy#574]
#### Chaquopy version

Chaquopy version 10.0.1

#### build.gradle (:app)
```
android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.footmeasurement"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            pip {
                install "imutils==0.5.4"
                install "matplotlib==3.1.2"
                install "opencv-python==4.5.1.48"
                install "scikit-image==0.16.2"
                install "sklearn==0.0"
            }
        }
    }
    ...
}
```

Hello!

I'm trying to use Chaquopy to run this project in Android Studio (https://github.com/wildoctopus/FeetAndShoeMeasurement) but I have some errors I'm not sure how to fix.

My code reads the image from a file in the MainActivity of the Java part, then converts it to a byte array before sending it over to the Python section for processing.
```
if (! Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }

        // Get bitmap of image
        Drawable drawable = getResources().getDrawable(R.drawable.barefeet1);
        Bitmap bitmap= ((BitmapDrawable)drawable).getBitmap();
        // Convert bitmap to byte array
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);
        byte[] imageInByte = stream.toByteArray();

        Python py = Python.getInstance();
        PyObject module = py.getModule("main");
        String result = module.callAttr("main",imageInByte).toString();
```

In main.py, I receive the byte array here,
```
def main(oimg):
    preprocessedOimg = preprocess(oimg)
```
then send it to this method in a different class:
```
def preprocess(img):

    img = cv2.cvtColor(np.float32(img), cv2.COLOR_RGB2HSV)

    img = cv2.GaussianBlur(img, (9, 9), 0)
    img = img/255

    return img
```

The first line of this code is where the error happens. The line used to look like this:
`img = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)`
but that gave me an error with the this in the error message, so I added the np.float().
```
Caused by: com.chaquo.python.PyException: TypeError: Expected Ptr<cv::UMat> for argument 'src'
        at <python>.utils.preprocess(utils.py:14)
        at <python>.main.main(main.py:21)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.footmeasurement.MainActivity.onCreate(MainActivity.java:42)
...
```

After adding the function, I now have this error:
```
2021-12-14 17:54:40.977 4758-4758/com.example.footmeasurement E/cv::error(): OpenCV(4.5.1) Error: Unspecified error (> Invalid number of channels in input image:
    >     'VScn::contains(scn)'
    > where
    >     'scn' is 1
    ) in cv::impl::(anonymous namespace)::CvtHelper<cv::impl::(anonymous namespace)::Set<3, 4, -1>, cv::impl::(anonymous namespace)::Set<3, -1, -1>, cv::impl::(anonymous namespace)::Set<0, 5, -1>, cv::impl::(anonymous namespace)::NONE>::CvtHelper(cv::InputArray, cv::OutputArray, int) [VScn = cv::impl::(anonymous namespace)::Set<3, 4, -1>, VDcn = cv::impl::(anonymous namespace)::Set<3, -1, -1>, VDepth = cv::impl::(anonymous namespace)::Set<0, 5, -1>, sizePolicy = cv::impl::(anonymous namespace)::NONE], file /home/smith/git/chaquo/python/server/pypi/packages/opencv-python/build/4.5.1.48/cp38-cp38-android_16_x86/src/opencv/modules/imgproc/src/color.simd_helpers.hpp, line 92
2021-12-14 17:54:41.076 4758-4758/com.example.footmeasurement E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.footmeasurement, PID: 4758
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.footmeasurement/com.example.footmeasurement.MainActivity}: com.chaquo.python.PyException: error: OpenCV(4.5.1) /home/smith/git/chaquo/python/server/pypi/packages/opencv-python/build/4.5.1.48/cp38-cp38-android_16_x86/src/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::(anonymous namespace)::CvtHelper<cv::impl::(anonymous namespace)::Set<3, 4, -1>, cv::impl::(anonymous namespace)::Set<3, -1, -1>, cv::impl::(anonymous namespace)::Set<0, 5, -1>, cv::impl::(anonymous namespace)::NONE>::CvtHelper(cv::InputArray, cv::OutputArray, int) [VScn = cv::impl::(anonymous namespace)::Set<3, 4, -1>, VDcn = cv::impl::(anonymous namespace)::Set<3, -1, -1>, VDepth = cv::impl::(anonymous namespace)::Set<0, 5, -1>, sizePolicy = cv::impl::(anonymous namespace)::NONE]'
    > Invalid number of channels in input image:
    >     'VScn::contains(scn)'
    > where
    >     'scn' is 1
    
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.chaquo.python.PyException: error: OpenCV(4.5.1) /home/smith/git/chaquo/python/server/pypi/packages/opencv-python/build/4.5.1.48/cp38-cp38-android_16_x86/src/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::(anonymous namespace)::CvtHelper<cv::impl::(anonymous namespace)::Set<3, 4, -1>, cv::impl::(anonymous namespace)::Set<3, -1, -1>, cv::impl::(anonymous namespace)::Set<0, 5, -1>, cv::impl::(anonymous namespace)::NONE>::CvtHelper(cv::InputArray, cv::OutputArray, int) [VScn = cv::impl::(anonymous namespace)::Set<3, 4, -1>, VDcn = cv::impl::(anonymous namespace)::Set<3, -1, -1>, VDepth = cv::impl::(anonymous namespace)::Set<0, 5, -1>, sizePolicy = cv::impl::(anonymous namespace)::NONE]'
    > Invalid number of channels in input image:
    >     'VScn::contains(scn)'
    > where
    >     'scn' is 1
    
        at <python>.utils.preprocess(utils.py:14)
        at <python>.main.main(main.py:21)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.footmeasurement.MainActivity.onCreate(MainActivity.java:42)
...
```

I'm not sure whether this is because the libraries cannot run this code, or I sent the image in the wrong format, or chaquopy cannot be used to run it. Is there anything I can try to fix the problem?

Thank you!

**Comment by mhsmith** [comment]
You're passing the image as a JPEG file, so the first thing you do on the Python side should be to call a function which can decode a JPEG file. This should work:
```
import numpy as np
img = cv2.imdecode(np.asarray(img, dtype=np.uint8), cv2.IMREAD_COLOR)
```

**Comment by ragequitting101** [comment]
That fixed it. Thank you!
