### ISSUE TITLE
"ValueError: Shapes (512, 11) and (512, 10) are incompatible" 

### ISSUE THREAD

**Issue by jdom05** [chaquo/chaquopy#587]
#### Chaquopy version

Chaquopy 7.0.3 
Android Gradle Plugin Version 3.3.0 
Gradle Version 4.10.1

#### Devices or emulators where the issue happens

Physical device: HUAWEI ANE-LX1 (Android 9.0, API 28)
Virtual device: Pixel 5 (Android 10.0, API 29)

#### Relevant parts of your code

```
pip {
        install "numpy == 1.17.4"
        install "scikit-learn == 0.24.1"
        install "tensorflow == 2.1.0"
        install "wrapt == 1.12.1"
    }
```

#### Describe your issue

The application builds correctly. However, when trying to run it on a device (either virtual or phyisical), after few seconds of the application starting, the screen becomes black and then the app stops. 
The stack trace is the following:
```
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/AndroidRuntime: Shutting down VM
W/mobi.mobilitap: Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
E/mobi.mobilitap: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobi.mobilitapp, PID: 10429
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mobi.mobilitapp/com.mobi.mobilitapp.MainActivity}: com.chaquo.python.PyException: ValueError: Shapes (512, 11) and (512, 10) are incompatible
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: com.chaquo.python.PyException: ValueError: Shapes (512, 11) and (512, 10) are incompatible
        at <python>.tensorflow.python.framework.tensor_shape.assert_is_compatible_with(tensor_shape.py:1110)
        at <python>.tensorflow.python.ops.resource_variable_ops.assign(resource_variable_ops.py:819)
        at <python>.tensorflow.python.keras.backend.batch_set_value(backend.py:3323)
        at <python>.tensorflow.python.keras.saving.hdf5_format.load_weights_from_hdf5_group(hdf5_format.py:699)
        at <python>.tensorflow.python.keras.engine.network.load_weights(network.py:1222)
        at <python>.tensorflow.python.keras.engine.training.load_weights(training.py:234)
        at <python>.model_prediction.load(model_prediction.py:18)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:281)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:253)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:209)
        at com.mobi.mobilitapp.MainActivity.onCreate(MainActivity.java:181)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
I/Process: Sending signal. PID: 10429 SIG: 9
```

Thank you very much!

**Comment by mhsmith** [comment]
You mentioned in your email that this app used to work in 2021. Are you absolutely sure that you haven't changed the source code in any way since then, or the model files, or anything else?

If so, the problem is probably caused by a new version of a Python library being released in the meantime, and you can fix it by pinning the versions that were current when your app last worked, as described at https://github.com/chaquo/chaquopy/issues/582#issuecomment-1042380842.

Unfortunately TensorFlow has many requirements, so this may take some time. I suggest you do a clean rebuild of your app to get the pip log, and then start with the direct requirements: those that say `(from tensorflow)`. If that doesn't help, then you can move onto the indirect requirements further down in the log, which look something like `(from tensorboard<2.2.0,>=2.1.0->tensorflow)`.

However, first I still recommend you try building with the current stable version of Chaquopy. Your email said you got build errors with that version, so if that still happens, please create a separate issue with the details.

If none of that works, you can post the relevant lines of model_prediction.py here and I'll have a look, but I'm not a TensorFlow expert.

**Comment by jdom05** [comment]
Hi @mhsmith, we have found a newer version of the code that only making the changes described at #582 the Android Studio app runs properly.

Thank you very much for your help, it has been very useful!
