### ISSUE TITLE
saecmca

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#594]
_Originally posted by @saecmca in https://github.com/chaquo/chaquopy/issues/250#issuecomment-1076220182_

**build.gradle(:app)**
```
defaultConfig {
        applicationId "com.example.application"
        sourceSets {
            main {
                python {
                    srcDirs = ["src/main/python"]
                }
            }
        }
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        python {
            buildPython "C:/Users/manikandan.r/Downloads/python3.10.0.exe"
            pip {
                install "opencv-python"
            }
        }
```
**build.gradle(Application)**
```
repositories {
        google()
        jcenter()
	maven { url "https://chaquo.com/maven" }
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
	    classpath "com.chaquo.python:gradle:7.0.2"
}
```

**MainActivity**
```
if (!Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
        }
        Python pyInstance = Python.getInstance();
        PyObject pyModule = pyInstance.getModule("ProcessImage");
        PyObject pyAttribute = pyModule.callAttr("test");

        TextView tv = (TextView) findViewById(R.id.textView);
        tv.setText(pyAttribute.toString());
```

**ProcessImage.py**
```
import cv2

def test():
    return "testing testing"
```
**My error is**
```
Process 'command 'C:/Users/manikandan.r/Downloads/python3.10.0.exe'' finished with non-zero exit value 1638
To view full details in Android Studio:
* In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
* In version 3.5 and older, click the 'Toggle view' button to the left of this message.
* Then scroll up to see the full output.
```

**If I comment buildpython**
```
Process 'command 'py'' finished with non-zero exit value 1

To view full details in Android Studio:
* In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
* In version 3.5 and older, click the 'Toggle view' button to the left of this message.
* Then scroll up to see the full output.
```

**Comment by mhsmith** [comment]
_Originally posted by @saecmca in https://github.com/chaquo/chaquopy/issues/250#issuecomment-1076228205_

I have downloaded chaquopy-matplotlib-master project from github

These are the pip installed in build.gradle.
```
python {
          //  buildPython "C:/Users/manikandan.r/Downloads/python.exe"
            pip {
                install "numpy"
                install "pandas"
                install "scipy"
                install "matplotlib"
                install "opencv-python"
             }
        }
```
Added python package and ProcessImage.py class but this face different error

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.myapplication/com.chaquo.myapplication.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'ProcessImage'

**Comment by mhsmith** [comment]
It doesn't looks like your comments are related to the old issue you posted in, so I've moved them here. Please create separate issues for separate problems in future.

I'll skip your first comment because I assume from your second comment that you've already solved it. If that's not the case, please post the "full details" as the message says.

> ModuleNotFoundError: No module named 'ProcessImage'

Are you sure you've put ProcessImage.py in the right place? The default location is src/main/python, as it says in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-source).

**Comment by mhsmith** [comment]
_Originally posted by @saecmca in https://github.com/chaquo/chaquopy/issues/250#issuecomment-1077583930_

I created sample app and uploaded into GitHub please check what is the problem
https://github.com/saecmca/Python
 
 Process: com.e.python, PID: 12459
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.e.python/com.e.python.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: /data/user/0/com.e.python/files/chaquopy/AssetFinder/requirements
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)


sourceSets {
            main {
                python {
                    srcDirs = ["src/main/python"]
                }
            }
        }

 python {
            buildPython "C:/Users/manikandan.r/Downloads/python.exe" (versions 3.10 and 3.8.10)
            pip {
                install "opencv-python"
             }
        }

If you have any working sample with external python class please share the link.

![image](https://user-images.githubusercontent.com/9863262/159933483-22f42c82-343a-415e-bd7e-3cb4cbecbff4.png)

**Comment by mhsmith** [comment]
Your Python source file is in the wrong place: see my previous comment.

> If you have any working sample with external python class please share the link.

See `chaquopy-matplotlib`, which you already mentioned in your previous comment.

If you have any futher errors, please post the complete stack trace, including any "Caused by" sections.
