### ISSUE TITLE
PuLP not working

### ISSUE THREAD

**Issue by Dana-ggq** [chaquo/chaquopy#603]
Hi!
I'm new to Android and I'd like to build a small app that uses an optimization python algorithm written with PuLP. I've been trying to make it work for weeks with no result. It seems that there is a problem with the PuLP solver not working in chaquopy. My question is whether PuLP can be used in chaquopy ? 

This is one of the errors I'm getting. But there are many more sice I tried a lot of different things to make it work.

'/data/data/com.example.myapplication/files/chaquopy/AssetFinder/requirements/pulp/apis/../solverdir/cbc/linux/64/cbc'

Thank you for your answer.

**Comment by mhsmith** [comment]
Please post the [full stack trace](https://stackoverflow.com/a/23353174), and the relevant sections of your code.

**Comment by Dana-ggq** [comment]
This is the stack trace 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 11095
    com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied: '/data/data/com.example.myapplication/files/chaquopy/AssetFinder/requirements/pulp/apis/../solverdir/cbc/linux/64/cbc'
        at <python>.subprocess._execute_child(subprocess.py:1704)
        at <python>.subprocess.__init__(subprocess.py:858)
        at <python>.pulp.apis.coin_api.solve_CBC(coin_api.py:194)
        at <python>.pulp.apis.coin_api.actualSolve(coin_api.py:137)
        at <python>.pulp.pulp.solve(pulp.py:1913)
        at <python>.myscript.main(myscript.py:52)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.example.myapplication.MainActivity$1.onClick(MainActivity.java:62)
        at android.view.View.performClick(View.java:7441)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`
Here is my code
```
    prob = pulp.LpProblem('MostEfficientConfiguration', LpMinimize)
    data['appliances_category'] = data['id'].astype(str) + data['category']
    appliances_category = list(data['appliances_category'])

    prices = dict(zip(appliances_category, data['price']))
    consumption = dict(zip(appliances_category, data['consumption']))

    appliances_var = LpVariable.dicts("appliance", appliances_category,0,1,cat='Integer')

    prob += lpSum([appliances_var[a] * consumption[a] for a in appliances_category])
    prob += lpSum([appliances_var[a] * prices[a] for a in appliances_category]) <= buget

    for c in unique_categories:
        lista = [item for item in appliances_category if item[-len(c):] == c]
        total = ""
        for index in lista:
            formula = 1*appliances_var[index]
            total += formula
        prob += (total == 1)

    solver_list = listSolvers(onlyAvailable=True)

    prob.solve()


    result = LpStatus[prob.status]
    if LpStatus[prob.status] == "Optimal":
        for v in prob.variables():
            if v.varValue>0:
                id = re.sub('[^0-9]', '', v.name)
                result += " " + id
    return result`
```

The line where it crashes is this one :
`  prob.solve()`

I also tried a bunch of things from here [https://coin-or.github.io/pulp/guides/how_to_configure_solvers.html](url) , like giving the path to the solver and Configuring where the CMD solvers write their temporary files, but nothing seems to work.

**Comment by mhsmith** [comment]
Unfortunately it looks like this feature requires an external executable (#605), so we won't be able to support it at the moment. Sorry about that.

**Comment by mhsmith** [comment]
It's been over a year and only one person has requested this package, so we won't be building it in the foreseeable future.

However, the package build tool is now open-source, so if you'd like to try building this package yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add it to the public repository.

If anyone else wants this package, please click the thumbs-up button above and post a comment, and I'll reopen the issue.
