### ISSUE TITLE
Telethon throws OperationalError: unable to open database file

### ISSUE THREAD

**Issue by EgorSigolaev** [chaquo/chaquopy#610]
#### Chaquopy version
classpath "com.chaquo.python:gradle:11.0.0"

#### Devices or emulators where the issue happens
Samsung S20+, snapdragon, android 11

#### Relevant parts of your code
Kotlin code
```
    private fun getLine(): String{
        val python = Python.getInstance()
        val pythonFile = python.getModule("start")
        return pythonFile.callAttr("parse").toString()
    }
```

Python code
```
from telethon import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty
import os, sys
import configparser
import csv
import time

import telethon

def parse():
    api_id = "aecret_id"
    api_hash = "secret_hash"
    phone = "secret_phone"
    client = TelegramClient(phone, api_id, api_hash)
    client.start()
    return "Hello World"
```

#### Describe your issue
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.egorsigolaev.telegramparser/com.egorsigolaev.telegramparser.MainActivity}: com.chaquo.python.PyException: OperationalError: unable to open database file
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: com.chaquo.python.PyException: OperationalError: unable to open database file
        at <python>.telethon.sessions.sqlite._cursor(sqlite.py:228)
        at <python>.telethon.sessions.sqlite.__init__(sqlite.py:47)
        at <python>.telethon.client.telegrambaseclient.__init__(telegrambaseclient.py:273)
        at <python>.start.parse(start.py:15)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:380)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:352)
        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
        at com.egorsigolaev.telegramparser.MainActivity.getLine(MainActivity.kt:22)
        at com.egorsigolaev.telegramparser.MainActivity.onCreate(MainActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
```
[![image](https://user-images.githubusercontent.com/44138374/165001972-9f413ad6-15fb-4e71-afd9-4e03adeacec7.png)](url)

The same code on pc is running well without crashes or any problems. Permission on Internet defined in manifest.

**Comment by mhsmith** [comment]
As it says [here](https://docs.telethon.dev/en/stable/concepts/sessions.html#what-are-sessions), the first parameter to `TelegramClient` is a filename, relative to the working directory. But the working directory is not writable on Android. So you should pass an absolute filename starting with `os.environ["HOME"]`, which points to your app's [internal storage directory](https://chaquo.com/chaquopy/doc/current/android.html#android-os).

**Comment by EgorSigolaev** [comment]
So I just have to pass os.environ["HOME"] in first method parametr? Or I have to create a file and then pass full path to it?

**Comment by mhsmith** [comment]
Construct a filename within that directory, as shown at https://github.com/chaquo/chaquopy/issues/604#issuecomment-1103652236. Then Telethon will create the file in the correct place.

**Comment by EgorSigolaev** [comment]
Thanks. It is done now. But there is the next problem. com.chaquo.python.PyException: EOFError: EOF when reading a line.
Kotlin code is the same. Crashing on line pythonFile.callAttr("parse").toString()

**Comment by mhsmith** [comment]
If you look at [auth.py:21](https://github.com/LonamiWebs/Telethon/blob/v1.24.0/telethon/client/auth.py#L21), it's trying to read a phone number and possibly a password from standard input. If you want to enable standard input, have a look at the [chaquopy-console](https://github.com/chaquo/chaquopy-console) template. Otherwise, you'll have to pass those values as parameters.

**Comment by EgorSigolaev** [comment]
Thanks. I understood. But one more question. Is it possible to use mutithreading? Because when I call python script my UI is freezing. But when I call like this
`Thread{
            runCode()
        }.start()`
my app crashes with error: com.chaquo.python.PyException: RuntimeError: There is no current event loop in thread 'Dummy-1'.
[
![image](https://user-images.githubusercontent.com/44138374/165345492-5df09019-4b25-435f-b811-2fed243d0a93.png)
](url)
Sorry for being annoying, but I could not find all that in the documentation.

**Comment by mhsmith** [comment]
Instead of posting screenshots of stack traces, please copy them as text, so that other users will be able to find them in searches.

Telethon is an asyncio library, so you'll have to learn how to use asyncio correctly in a background thread. Search for this error message in the Telethon documentation and issue tracker, and you'll find many discussions.

**Comment by EgorSigolaev** [comment]
Still haven't understood how to make normal mutlithreading. Even if I use asyncio library, my app still run python code in main thread and my UI is freezing. I checked chaquopy apps as examples, but there is no multithreading inside. I think the problem is in telethon, but it supports asyncio that I didn't userstand how to work with. If I solve it, I will definetely buy license key for my purposes. Is it possible to contact you via telegram? or whatsapp?
