### ISSUE TITLE
How to Run Async Function In Chaquopy

### ISSUE THREAD

**Issue by pdisk** [chaquo/chaquopy#632]
How can I run async python functions in kotlin using chaquopy

I tried making a normal function run the async function and running the main function with asyncio 

`    loop = asyncio.get_event_loop()`
`   loop.run_until_complete(main())`

But the Problem is This Method Blocks The Code
The app stops responding until the the code it fully executed

So my question is How can I properly use async function using chaquopy?

**Comment by hetingrui** [comment]
> 如何使用chaquopy在kotlin中运行异步python函数
> 
> 我尝试让普通函数运行异步函数并使用异步运行主函数
> 
> ` loop = asyncio.get_event_loop()` ` loop.run_until_complete(main())`
> 
> 但问题是此方法阻止了代码 应用程序停止响应，直到它完全执行的代码
> 
> 所以我的问题是如何使用chaquopy正确使用异步功能？

Do you know how to write the java code now?

Python code like:
  async def asyncTest():
      await asyncio.sleep(1)
      return "asdasdasdasd"
 def main():
      asyncio.run(asyncTest())

Java Code like:
@Override public void run() {
            py.getModule("main").callAttr("main");
        }

how to write the right java code?

**Comment by hetingrui** [comment]
> Do you know how to write the java code now?
> 
> Python code like: async def asyncTest(): await asyncio.sleep(1) return "asdasdasdasd" def main(): asyncio.run(asyncTest())
> 
> Java Code like: @OverRide public void run() { py.getModule("main").callAttr("main"); }
> 
> how to write the right java code?



> Like any other blocking function, you'll have to run it on a separate thread. You can create the thread in Java/Kotlin, or in Python, using the standard library APIs of each language.

I have the same question, how to write the java code to call a async python method?
@OverRide public void run() {
py.getModule("main").callAttr("main");
}

**Comment by mhsmith** [comment]
The code you posted should work fine. Whatever is returned by `asyncTest` will then be returned by `asyncio.run`.

If you have a problem, please explain what it is.

**Comment by hetingrui** [comment]
> The code you posted should work fine. Whatever is returned by `asyncTest` will then be returned by `asyncio.run`.
> 
> If you have a problem, please explain what it is.
```java
//java code
package com.chaquo.python.console;
//import
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PyObject pyObject = Python.getInstance().getModule("main").callAttr("main");
    }
}
```

```python
# python code
import asyncio
async def test():
    print("async!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    await asyncio.sleep(1)
def main():
    print("hello!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    asyncio.run(test(),debug=False)
    print("hello for 2 times")
```
![image](https://user-images.githubusercontent.com/32641980/230955161-20be0227-f87c-4968-8275-26eab4019634.png)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chaquo.python.console, PID: 4584
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.python.console/com.chaquo.python.console.MainActivity}: com.chaquo.python.PyException: SyntaxError: invalid syntax (base_events.py, line 296)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: com.chaquo.python.PyException: SyntaxError: invalid syntax (base_events.py, line 296)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.asyncio.<module>(__init__.py:21)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.main.<module>(main.py:1)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
        at <python>.java.android.importer.exec_module(importer.py:554)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.chaquo.python.console.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:6709)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6121) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by mhsmith** [comment]
As you discovered in #860, you'll have to run the async function within `asyncio.run`.
