### ISSUE TITLE
Launching code from subdirectory

### ISSUE THREAD

**Issue by Kruptein** [chaquo/chaquopy#637]
#### Chaquopy version
12.0.0

#### Devices or emulators where the issue happens
This is on custom hardware running android 9

#### Describe your issue
I recently restructured my code to have my python code in a "src" subdirectory, as the main root directory was starting to get crowded. In python I can just run `python src/entrypoint.py` or cd into the src folder and run the entrypoint.

My first attempt to mimick this with chaquopy was doing `py.getModule("src/entrypoint")` instead of `py.getModule("entrypoint")`. This actually starts running the code, but it can't import any of the other modules because it's probably looking in a directory up.

I tried two things at this point:
1) Manually edit the path to include that subdirectory by adding the following at the top of my entrypoint:
```python
if hasattr(sys, "getandroidapilevel"):
    print("Android mode")
    sys.path.insert(0, sys.path[0] + "/src")
```
This however gives a FileNotFoundError while importing a module (and I noticed that the device itself actually does not have the src directory, but does include all other directories in the root folder.

2) Modifying the srcDir as per docs to "src/main/python/src", but this just fails to launch the entrypoint everytime. (and I do need the data files from the rootfolder so unsure if this is even a route I want to take.

Stack trace for 1)
```
2022-06-16 15:59:14.602 4829-4845/com.lastgameboard.game.planarallyserver.develop W/Binder: Caught a RuntimeException from the binder stub implementation.
    com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.lastgameboard.game.planarallyserver.develop/files/chaquopy/AssetFinder/app/src'
        at <python>.utils.<module>(utils.py:30)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.src/planarserver.<module>(planarserver.py:19)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
        at <python>.java.android.importer.exec_module(importer.py:532)
        at <python>.java.android.importer.exec_module(importer.py:581)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:155)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.lastgameboard.game.planarally_server.VttApplication.initialize(VttApplication.kt:29)
        at com.lastgameboard.sdk.gameboardvttconnectorservice.GameboardVttConnectorManager.initialize(GameboardVttConnectorManager.kt:9)
        at com.lastgameboard.sdk.gameboardvttconnectorcommon.IVttServiceManager$Stub.onTransact(IVttServiceManager.java:67)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by mhsmith** [comment]
You can alter `sys.path` at runtime to load Python files from a local directory. But the `AssetFinder` paths for loading code from your APK are handled specially, so please don't try to modify them, or create your own. Even if it works with the current version of Chaquopy, it might not keep working in the future.

Chaquopy's rules for packaginging Python code are pretty simple:
* Anything covered by a [`srcDir` or `srcDirs`](https://chaquo.com/chaquopy/doc/current/android.html#android-source) setting will be merged together into a single tree in the app.
* Anything *not* covered by one of those settings will not be available in the app.

So if you want to access data files at runtime with a [path relative to `__file__`](https://chaquo.com/chaquopy/doc/current/android.html#android-data), you'll have to include them within one of those directories. 

Also, note that `srcDir` will append to the existing list. 
```
python.srcDir "src/main/python/src"
```

And since the default list already includes src/main/python, this would cause everything in the `src` subdirectory to be added twice, which will cause all kinds of confusion. So if you want to replace the existing list, use `srcDirs` instead:
```
python.srcDirs = ["src/main/python/src"]
```

To keep things simple, I suggest you limit your app to just one Python source directory if possible.

**Comment by Kruptein** [comment]
> But the AssetFinder paths for loading code from your APK are handled specially

Yeah I assumed as much, it was just a random attempt to see if it did the trick, which it clearly didn't :).

> Also, note that srcDir will append to the existing list.

Ah, I misunderstood that, my bad. I'll try the srcDirs approach then thanks!

> To keep things simple, I suggest you limit your app to just one Python source directory if possible.

There is only one directory that contains all python code, it's just that the directory right above it contains some general data files that also need to be bundled.

So just to be clear my original "src/main/python" folder looked a bit like:

```
- __init__.py
- api/
    - __init__.py
    - rooms.py
    - ...
- database.sqlite
- entrypoint.py
- models/
    - __init__.py
    - base.py
    - ...
- static/
    - some_image.png
    - ...
- templates/
    - index.html
- utils.py
```

whereas now it changed to:
```
- database.sqlite
- src/
    - __init__.py
    - api/
        - __init__.py
        - rooms.py
        - ...
    - entrypoint.py
    - models/
        - __init__.py
        - base.py
        - ...
    - utils.py
- static/
    - some_image.png
    - ...
- templates/
    - index.html
```

But I'll report back on the use of setting srcDirs to that src folder

**Comment by mhsmith** [comment]
I think that rather than messing with the `srcDirs`, you should make `src` a proper package with a more meaningful name, and fix the `import` statements to reflect that.

For example, if entrypoint.py contains `import utils`, that should be changed to `from . import utils`. Similarly, `from api import rooms` would become `from .api import rooms`.

**Comment by Kruptein** [comment]
sure that's probably indeed cleaner, but then I have to run my entrypoint as `python -m src.entrypoint`, which is not really a problem for me, but how would that translate to the `py.getModule` call, or will that work fine without changes ?

**Comment by mhsmith** [comment]
`getModule("src.entrypoint")` is the correct syntax. Using a slash rather than a dot might currently work, but it isn't guaranteed.

**Comment by Kruptein** [comment]
Cheers, I'll report back with my findings!
