### ISSUE TITLE
Cannot build a project without a local.properties file

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#672]
#### Chaquopy version
12.0.1

#### Describe your issue

The Android Gradle plugin is capable of building a project with no local.properties file, as long as the ANDROID_HOME or ANDROID_SDK_ROOT environment variable is set. So the absence of this file should not be a fatal error:
```
java.io.FileNotFoundException: C:\Users\smith\cygwin\git\beeware\toga\examples\command\android\gradle\Command Example\local.properties (The system cannot find the file specified)
        at com.chaquo.python.PythonPlugin.createTicketTask(PythonPlugin.groovy:497)
        at com.chaquo.python.PythonPlugin$createTicketTask$9.callCurrent(Unknown Source)
        at com.chaquo.python.PythonPlugin.afterEvaluate(PythonPlugin.groovy:168)
```

**Comment by mhsmith** [comment]
Fixed in e38edf17ce7.
