### ISSUE TITLE
Module Tkinter fails to install

### ISSUE THREAD

**Issue by rpcd** [chaquo/chaquopy#73]
Tried to install Tkinter via pip and gradle fails as well

This is the error:
W/System.err: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'Tkinter'
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.reraise(/data/user/0/com.vkintsys.inforce/files/chaquopy/bootstrap.zip/java/_vendor/six.py:686)
        at <python>.java.chaquopy.import_override(import.pxi:59)
        at <python>.<module>(/android_asset/chaquopy/app.zip/AUX_Flash_AUX_Bootloader.py:24)
        at <python>.load_module_impl(/data/user/0/com.vkintsys.inforce/files/chaquopy/bootstrap.zip/java/android/importer.py:391)
        at <python>.load_module(/data/user/0/com.vkintsys.inforce/files/chaquopy/bootstrap.zip/java/android/importer.py:311)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.reraise(/data/user/0/com.vkintsys.inforce/files/chaquopy/bootstrap.zip/java/_vendor/six.py:686)
        at <python>.java.chaquopy.import_override(import.pxi:59)
        at <python>.select_program(/android_asset/chaquopy/app.zip/python_bridge.py:77)
        at <python>.write_serial(/android_asset/chaquopy/app.zip/python_bridge.py:110)
        at <python>.chaquopy_java.call(chaquopy_java.pyx:274)
        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:246)
        at com.chaquo.python.PyObject.callAttrThrows(Native Method)
        at com.chaquo.python.PyObject.callAttr(PyObject.java:140)
        at com.vkintsys.inforce.utilities.EnginePython$onCreateView$1.onClick(EnginePython.kt:78)
        at android.view.View.performClick(View.java:5623)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)

**Comment by mhsmith** [comment]
tkinter isn't included in Chaquopy. We're unlikely ever to add it unless there's significant demand, because our focus is on supporting native Android user interfaces.

**Comment by rpcd** [comment]
That's ok ... I agree, wanted to bring to your attention just now ... all our ui is android

**Comment by rpcd** [comment]
Thank you
