### ISSUE TITLE
ERROR: Failed to install pyclipper from https://files.pythonhosted.org/packages/45/9e/0ad12b045017ab57a05844084d376569a023c604b1061065c604fa3bf953/pyclipper-1.3.0.post3.tar.gz (from easyocr==1.6.2).

### ISSUE THREAD

**Issue by daniyal214** [chaquo/chaquopy#737]
build.gradle(:app)

```
plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion 30
    ndkVersion "25.1.8937393"

    defaultConfig {
        applicationId "com.example.imagetovolley"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "x86"
        }

        python {
            pip {
                install "wheel"
                install "pybind11"
                install "decorator"
                install "matplotlib"
                install "numpy"
                install "opencv-python"
                install "Pillow"
                install "PyYAML"
                install "scipy"
                install "torch"
                install "torchvision"
                install "tqdm"
                install "pandas"
                install "seaborn"
                install "fuzzywuzzy"
                install "imutils"
                install "requests"
                install "scikit-build"
                install "pybind11"
//                install "patch-ng"
                install "git+https://github.com/JaidedAI/EasyOCR@f94dcffa5d49fccd7d203f0d8082a64a9bdf87f7"
            }


            buildPython "C:/Users/GCS/AppData/Local/Programs/Python/Python36//python.exe"
        }

        sourceSets {
            main {
                python.srcDir "src/main/python"
            }
        }



    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.4.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'id.zelory:compressor:2.1.1'
    implementation 'com.karumi:dexter:6.2.1'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
//    implementation 'com.squareup.okhttp3:okhttp:3.14.7'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'com.squareup.retrofit2:retrofit:2.8.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.8.1'
    implementation 'com.google.api-client:google-api-client:1.23.0'
//    implementation 'com.google.android.gms:play-services:11.8.0'
//    implementation 'com.google.android.gms:play-services:9.0.2'
    implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'
    implementation 'net.sourceforge.jtds:jtds:1.3.1'
    implementation 'com.google.api-client:google-api-client:1.23.0'
    implementation 'com.google.android.gms:play-services-location:11.0.1'

}
```

build.gradle(project_level)

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
        maven {url "https://chaquo.com/maven"}
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.0"
        classpath 'com.chaquo.python:gradle:9.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

error:

```
> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting git+https://github.com/JaidedAI/EasyOCR@f94dcffa5d49fccd7d203f0d8082a64a9bdf87f7
  Cloning https://github.com/JaidedAI/EasyOCR (to revision f94dcffa5d49fccd7d203f0d8082a64a9bdf87f7) to c:\users\gcs\appdata\local\temp\pip-req-build-v6_ky_ip
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/bb/ae/02bad7c64ca060e037869584242729796a5eda0376bb944a3e03f4d9491b/wheel-0.38.0-py3-none-any.whl
Collecting pybind11
  Using cached https://files.pythonhosted.org/packages/1d/53/e6b27f3596278f9dd1d28ef1ddb344fd0cd5db98ef2179d69a2044e11897/pybind11-2.10.1-py3-none-any.whl
Collecting decorator
  Using cached https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
Collecting matplotlib
  Using version 3.1.2 (newest version is 3.6.1, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/matplotlib/matplotlib-3.1.2-1-cp38-cp38-android_16_armeabi_v7a.whl
Collecting numpy
  Using version 1.19.5 (newest version is 1.23.4, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/numpy/numpy-1.19.5-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting opencv-python
  Using version 4.5.1.48 (newest version is 4.6.0.66, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/opencv-python/opencv_python-4.5.1.48-1-cp38-cp38-android_16_armeabi_v7a.whl
Collecting Pillow
  Using version 8.4.0 (newest version is 9.3.0, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/pillow/Pillow-8.4.0-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting PyYAML
Collecting scipy
  Using version 1.4.1 (newest version is 1.9.3, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/scipy/scipy-1.4.1-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting torch
  Using cached https://chaquo.com/pypi-7.0/torch/torch-1.8.1-3-cp38-cp38-android_16_armeabi_v7a.whl
Collecting torchvision
  Using cached https://chaquo.com/pypi-7.0/torchvision/torchvision-0.9.1-1-cp38-cp38-android_16_armeabi_v7a.whl
Collecting tqdm
  Using cached https://files.pythonhosted.org/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl
Collecting pandas
  Using version 1.3.2 (newest version is 1.5.1, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/pandas/pandas-1.3.2-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting seaborn
  Using cached https://files.pythonhosted.org/packages/77/18/7354cb68dd7906d5a3118e0ed3e30c37502f9e6253139ecfcf4fa33af210/seaborn-0.12.1-py3-none-any.whl
Collecting fuzzywuzzy
  Using cached https://files.pythonhosted.org/packages/43/ff/74f23998ad2f93b945c0309f825be92e04e0348e062026998b5eefef4c33/fuzzywuzzy-0.18.0-py2.py3-none-any.whl
Collecting imutils
Collecting requests
  Using cached https://files.pythonhosted.org/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl
Collecting scikit-build
  Using cached https://files.pythonhosted.org/packages/c6/46/ee73936200f9da8f9e7d8bcec14de1a5c857f972278b1a6066ae3edb5b4c/scikit_build-0.16.1-py3-none-any.whl
Collecting opencv-python-headless<=4.5.4.60 (from easyocr==1.6.2)
  Using version 4.5.1.48 (newest version is 4.5.4.60, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/opencv-python-headless/opencv_python_headless-4.5.1.48-2-cp38-cp38-android_16_armeabi_v7a.whl
Collecting scikit-image (from easyocr==1.6.2)
  Using version 0.18.3 (newest version is 0.19.3, but Chaquopy prefers native wheels)
  Downloading https://chaquo.com/pypi-7.0/scikit-image/scikit_image-0.18.3-0-cp38-cp38-android_16_armeabi_v7a.whl (11.6MB)
Collecting python-bidi (from easyocr==1.6.2)
  Using cached https://files.pythonhosted.org/packages/33/b0/f942d146a2f457233baaafd6bdf624eba8e0f665045b4abd69d1b62d097d/python_bidi-0.4.2-py2.py3-none-any.whl
Collecting Shapely (from easyocr==1.6.2)
  Using version 1.7.0 (newest version is 1.8.5.post1, but Chaquopy prefers native wheels)
  Using cached https://chaquo.com/pypi-7.0/shapely/Shapely-1.7.0-0-cp38-cp38-android_16_armeabi_v7a.whl
Collecting pyclipper (from easyocr==1.6.2)
  Using cached https://files.pythonhosted.org/packages/45/9e/0ad12b045017ab57a05844084d376569a023c604b1061065c604fa3bf953/pyclipper-1.3.0.post3.tar.gz
    Complete output from command python setup.py egg_info:
    Distribution mode: Compiling Cython generated .cpp sources.
    C:\Users\GCS\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GCS\AppData\Local\Temp\pip-install-di5wp3yj\pyclipper\setup.py", line 102, in <module>
        cmdclass=cmdclass,
      File "E:\DANIYAL_OLD_PC\Android_Chaquopy_ANPR\app\build\generated\python\bp.zip\setuptools\__init__.py", line 129, in setup
      File "C:\Users\GCS\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "E:\DANIYAL_OLD_PC\Android_Chaquopy_ANPR\app\build\generated\python\bp.zip\setuptools\dist.py", line 363, in __init__
      File "C:\Users\GCS\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "E:\DANIYAL_OLD_PC\Android_Chaquopy_ANPR\app\build\generated\python\bp.zip\setuptools\dist.py", line 519, in finalize_options
      File "E:\DANIYAL_OLD_PC\Android_Chaquopy_ANPR\app\build\generated\python\bp.zip\pkg_resources\__init__.py", line 2327, in load
      File "E:\DANIYAL_OLD_PC\Android_Chaquopy_ANPR\app\build\generated\python\bp.zip\pkg_resources\__init__.py", line 2333, in resolve
      File "c:\users\gcs\appdata\local\temp\pip-install-di5wp3yj\pyclipper\.eggs\setuptools_scm-7.0.5-py3.6.egg\setuptools_scm\__init__.py", line 5
        from __future__ import annotations
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\GCS\AppData\Local\Temp\pip-install-di5wp3yj\pyclipper\
ERROR: Failed to install pyclipper from https://files.pythonhosted.org/packages/45/9e/0ad12b045017ab57a05844084d376569a023c604b1061065c604fa3bf953/pyclipper-1.3.0.post3.tar.gz (from easyocr==1.6.2).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install pyclipper from https://files.pythonhosted.org/packages/45/9e/0ad12b045017ab57a05844084d376569a023c604b1061065c604fa3bf953/pyclipper-1.3.0.post3.tar.gz (from easyocr==1.6.2).

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/GCS/AppData/Local/Programs/Python/Python36//python.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateDebugPythonRequirements'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: com.chaquo.python.BuildPythonFailedException: Process 'command 'C:/Users/GCS/AppData/Local/Programs/Python/Python36//python.exe'' finished with non-zero exit value 1

To view full details in Android Studio:
* In version 3.6 and newer, click the 'Build: failed' caption to the left of this message.
* In version 3.5 and older, click the 'Toggle view' button to the left of this message.
* Then scroll up to see the full output.
	at com.chaquo.python.PythonPlugin.execBuildPython(PythonPlugin.groovy:483)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:483)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:195)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:77)
	at com.chaquo.python.PythonPlugin$_createReqsTask_closure9$_closure32.doCall(PythonPlugin.groovy:309)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:670)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:643)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:63)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
	... 30 more

```

**Comment by mhsmith** [comment]
See #584, and please search for existing issues before creating new ones.
