### ISSUE TITLE
Is the OSerror error android studio's error or python's error?

### ISSUE THREAD

**Issue by duongpt582** [chaquo/chaquopy#763]
#### Relevant parts of your build.gradle file

- python 3.10
- ndk: newest

#### Describe your issue
<!-- If reporting a build failure, please include the complete build log:

* Caused by: com.chaquo.python.PyException: OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

**Comment by mhsmith** [comment]
Please post the full stack trace, and the `python` section of your build.gradle file.

**Comment by duongpt582** [comment]
#### full stack here
FATAL EXCEPTION: main
                                                                                                    Process: com.location.callerlocator, PID: 11504
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.location.callerlocator/com.location.callerlocator.MapsActivity}: com.chaquo.python.PyException: OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    Caused by: com.chaquo.python.PyException: OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
                                                                                                    	at <python>.shapely.geos.load_dll(geos.py:60)
                                                                                                    	at <python>.shapely.geos.<module>(geos.py:87)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.shapely.coords.<module>(coords.py:8)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.shapely.geometry.base.<module>(base.py:18)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.shapely.geometry.<module>(__init__.py:4)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.ShapeFileWithCountry.<module>(ShapeFileWithCountry.py:10)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:241)
                                                                                                    	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:883)
                                                                                                    	at <python>.java.android.importer.exec_module(.\java\android\importer.py:545)
                                                                                                    	at <python>.java.android.importer.exec_module(.\java\android\importer.py:597)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:688)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:1006)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1027)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1050)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:241)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:992)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1027)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1050)
                                                                                                    	at <python>.importlib.import_module(__init__.py:126)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:154)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.location.callerlocator.MapsActivity.onCreate(MapsActivity.java:96)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8000)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7984)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:223) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

#### python section
        python {
            version "3.10"
            pip {
                install 'pyshp'
                install 'Cython'
                install 'shapely==1.7.0'
//                install 'shapely-2.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'
            }
        }

#### python code in file_python.py
"""
Getting a random point inside a country based on its name.
In this solution, the shapefile with countries was used.
"""

# imports
import re
import random
import shapefile
from shapely.geometry import shape, Point


# function that takes a shapefile location and a country name as inputs
def random_point_in_country(shp_location, country_name):
    shapes = shapefile.Reader(shp_location) # reading shapefile with pyshp library
    country = [s for s in shapes.records() if country_name in s][0] # getting feature(s) that match the country name 
    country_id = int(re.findall(r'\d+', str(country))[0]) # getting feature(s)'s id of that match

    shapeRecs = shapes.shapeRecords()
    feature = shapeRecs[country_id].shape.__geo_interface__

    shp_geom = shape(feature)

    minx, miny, maxx, maxy = shp_geom.bounds
    while True:
        p = Point(random.uniform(minx, maxx), random.uniform(miny, maxy))
        if shp_geom.contains(p):
            print(p.y, p.x)
            return p.y, p.x

random_point_in_country("World_Countries.shp", "Vietnam")

####  python code in activity.java
  Log.d(TAG, "onCreate: Python started?: " + Python.isStarted());
        if (! Python.isStarted()) {
            Python.start(new AndroidPlatform(this));
            Log.d(TAG, "onCreate: Python started?: " + Python.isStarted());
        }
        Python py = Python.getInstance();
        PyObject pyObject = py.getModule("ShapeFileWithCountry.py");
        Log.d(TAG, "onCreate: Python: " + pyObject.toString());

#### thanks for debug with me <3

**Comment by mhsmith** [comment]
We currently only support shapely on Python 3.8, not Python 3.10. Try changing the `python { version }` setting.

**Comment by mhsmith** [comment]
Shapely version 1.8.5 is now available for Python 3.9 and 3.10.
