### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.example.yolov5demo/files/chaquopy/AssetFinder/app/utils/general.py'

### ISSUE THREAD

**Issue by DeemAQ** [chaquo/chaquopy#764]
I'm trying to integrate yolov5 with android, there is a directory that contains python scripts that are callable in detect.py and I get this error

`com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.example.yolov5demo/files/chaquopy/AssetFinder/app/utils/general.py'
`

**Comment by mhsmith** [comment]
Please post the following:
* The full stack trace
* The `python` section of your build.gradle file
* The relevant sections of your code

**Comment by DeemAQ** [comment]
full stack trace:

`  E  FATAL EXCEPTION: pool-3-thread-1
                                                                                                    Process: com.example.yolov5demo, PID: 9694
                                                                                                    com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.example.yolov5demo/files/chaquopy/AssetFinder/app/utils/general.py'
                                                                                                    	at <python>.pathlib.stat(pathlib.py:1198)
                                                                                                    	at <python>.utils.general.file_date(general.py:278)
                                                                                                    	at <python>.utils.torch_utils.select_device(torch_utils.py:110)
                                                                                                    	at <python>.detect.run(detect.py:46)
                                                                                                    	at <python>.torch.autograd.grad_mode.decorate_context(grad_mode.py:27)
                                                                                                    	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
                                                                                                    	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
                                                                                                    	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
                                                                                                    	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
                                                                                                    	at com.example.yolov5demo.CameraActivity.detect(CameraActivity.kt:174)
                                                                                                    	at com.example.yolov5demo.CameraActivity.access$detect(CameraActivity.kt:24)
                                                                                                    	at com.example.yolov5demo.CameraActivity$capture$1.onCaptureSuccess(CameraActivity.kt:161)
                                                                                                    	at androidx.camera.core.imagecapture.TakePictureRequest.lambda$onResult$2$androidx-camera-core-imagecapture-TakePictureRequest(TakePictureRequest.java:200)
                                                                                                    	at androidx.camera.core.imagecapture.TakePictureRequest$$ExternalSyntheticLambda2.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of system`


the python section contains [yolov5](https://github.com/ultralytics/yolov5)

here is a screen shot
<img width="861" alt="Screenshot 2023-01-01 at 8 22 41 AM" src="https://user-images.githubusercontent.com/47563674/210161834-0c68b61a-76e7-4e4c-8534-8fb30d368ff6.png">

build.gradle:
`defaultConfig {
        applicationId "com.example.yolov5demo"
        minSdk 27
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            version "3.8"

            pip {
                install "matplotlib"
                install "seaborn"
                install "-r", "requirements.txt"
            }
        }
        sourceSets {
            main {
                python.srcDir "src/main/python"
            }
        }
    }`


here is where I call the python script (detect.py) 

    `private fun capture(imageCapture: ImageCapture) {
        imageCapture.takePicture(cameraExecutor, object : OnImageCapturedCallback() {
            override fun onCaptureSuccess(image: ImageProxy) {
                val byteBuffer = image.planes[0].buffer
                val bytes = ByteArray(byteBuffer.capacity())
                byteBuffer[bytes]
                val bitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
                val byteOutputStream = ByteArrayOutputStream()
                bitmap.compress(Bitmap.CompressFormat.JPEG, 100, byteOutputStream)
                val imageBytes = byteOutputStream.toByteArray()
                detect(imageBytes)
            }override fun onError(e: ImageCaptureException) {
                Toast.makeText(this@CameraActivity, e.message, Toast.LENGTH_LONG).show()
                e.printStackTrace()
            }
        })
    }private fun detect(image: ByteArray) {
        val py = Python.getInstance()
        val pyObject = py.getModule("detect")
        val result = pyObject.callAttr("run", image)
        showResult(result)
    }

**Comment by DeemAQ** [comment]
@mhsmith can you help me please...

**Comment by mhsmith** [comment]
This package expects to be able to access its own .py files at runtime. We'll have an easy solution for this in the next version of Chaquopy (#754). Meanwhile, you can extract the file manually using the technique from https://github.com/chaquo/chaquopy/issues/501#issuecomment-845265141.
