### ISSUE TITLE
Unable to install rpy2 package

### ISSUE THREAD

**Issue by ivbabar** [chaquo/chaquopy#769]
I'm trying to integrate Chaquo into Android Studio, things are working fine untill I try to install the rpy2 package  
pip{
                install "rpy2"
            }
Which I need to run R code from the python. Any help would be much appreciated.

#### Chaquopy version

    id 'com.chaquo.python' version '13.0.0' apply false

#### Relevant parts of your build.gradle file

defaultConfig {
        applicationId "com.example.rplayground"
        minSdk 28
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            version "3.8"
            pip{
                install "rpy2"
            }
            pyc {
                src false
            }
            buildPython "D:/Python/python.exe"
        }
    }

#### logs
Executing tasks: [:app:assembleDebug] in project D:\AndroidStudioProjects\RPlayground

> Task :app:createDebugVariantModel UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Collecting rpy2
  Using cached https://files.pythonhosted.org/packages/8b/39/4a9d9e59ba062f156a642af7271bed418584406a6e65c3a23d1ded8c4a77/rpy2-3.5.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'D:\Python\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Raja Babar\\AppData\\Local\\Temp\\pip-install-wtyq2ucr\\rpy2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Raja Babar\\AppData\\Local\\Temp\\pip-install-wtyq2ucr\\rpy2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\
    Complete output (36 lines):
    Traceback (most recent call last):
      File "C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\./rpy2/situation.py", line 224, in get_r_home
        r_home = r_home_from_subprocess()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\./rpy2/situation.py", line 78, in r_home_from_subprocess
        tmp = subprocess.check_output(cmd, universal_newlines=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python\Lib\subprocess.py", line 466, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python\Lib\subprocess.py", line 548, in run
        with Popen(*popenargs, **kwargs) as process:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python\Lib\subprocess.py", line 1024, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "D:\Python\Lib\subprocess.py", line 1493, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\setup.py", line 121, in <module>
        c_extension_status = get_r_c_extension_status()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\setup.py", line 101, in get_r_c_extension_status
        r_home = situation.get_r_home()
                 ^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\./rpy2/situation.py", line 227, in get_r_home
        r_home = r_home_from_registry()
                 ^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Raja Babar\AppData\Local\Temp\pip-install-wtyq2ucr\rpy2\./rpy2/situation.py", line 91, in r_home_from_registry
        from packaging.version import Version
    ModuleNotFoundError: No module named 'packaging'
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Failed to install rpy2 from https://files.pythonhosted.org/packages/8b/39/4a9d9e59ba062f156a642af7271bed418584406a6e65c3a23d1ded8c4a77/rpy2-3.5.7.tar.gz.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

**Comment by mhsmith** [comment]
Thanks for the report. This package contains native components, so it would have to be built into a wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/build-wheel). And if you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

**Comment by ivbabar** [comment]
Thanks for the prompt response, we are evaluating other options as well at the moment and will certainly do that if we go towards this path.

**Comment by ivbabar** [comment]
@mhsmith Okay, I'm going to give it a try (wish me best of luck), will update you on it.

**Comment by ivbabar** [comment]
I did this
python3 build-wheel.py --toolchain /home/user-name/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64 /home/user-name/Desktop/build-wheel/build-wheel/server/pypi/packages/rpy2


Getting this error, any idea?

Traceback (most recent call last):
  File "build-wheel.py", line 833, in <module>
    BuildWheel().main()
  File "build-wheel.py", line 83, in main
    self.parse_args()
  File "build-wheel.py", line 172, in parse_args
    self.detect_toolchain()
  File "build-wheel.py", line 546, in detect_toolchain
    for word in open(clang).read().split():
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 26: invalid continuation byte

**Comment by mhsmith** [comment]
That's not the correct way to use `--toolchain`: it requires a standalone toolchain directory with various Chaquopy-specific modifications. 

I suggest you start by following the section ["Building with Docker"](https://github.com/chaquo/build-wheel#building-with-docker). I recognize that this process is a bit awkward, but it's the best option we have at the moment. We'll try to simplify it in the future.

**Comment by ivbabar** [comment]
Thanks for the guidance, I wish that toolchain directory comes with the build-wheel project.
Okay let me try the docker way.

**Comment by ivbabar** [comment]
I tried it using docker
~/Desktop/build-wheel/build-wheel/server/pypi$ sudo docker run -v $(pwd)/packages:/root/pypi/packages -v $(pwd)/dist:/root/pypi/dist     build-wheel --toolchain target/toolchains/x86_64 rpy2

Now getting below error

build-wheel.py: Toolchain ABI: x86_64, API level: 21
Traceback (most recent call last):
  File "pypi/build-wheel.py", line 833, in <module>
    BuildWheel().main()
  File "pypi/build-wheel.py", line 86, in main
    self.meta = self.load_meta()
  File "pypi/build-wheel.py", line 705, in load_meta
    meta = yaml.safe_load(meta_str)
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 142, in parse_implicit_document_start
    if not self.check_token(DirectiveToken, DocumentStartToken,
  File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.8/site-packages/yaml/scanner.py", line 255, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 1, column 2:
     	package:
     ^

**Comment by mhsmith** [comment]
The error message is self-explanatory: you have some stray whitespace at the start of the meta.yaml file. Remove it and try again.

If you're unsure about the format of this file, you can check the other meta.yaml files in the repository for examples, or meta-schema.yaml for a full specification.

**Comment by ivbabar** [comment]
@mhsmith Thanks for the correction but now getting below error, although I have added R_HOME into my PATH
here is the PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/bin/Postman:/usr/lib/R"
**Logs**
build-wheel.py: Toolchain ABI: x86_64, API level: 21
build-wheel.py: mkdir -p /root/pypi/packages/rpy2/build/3.5.7
build-wheel.py: cd /root/pypi/packages/rpy2/build/3.5.7
build-wheel.py: mkdir -p /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64
build-wheel.py: python3.8 -m pip --disable-pip-version-check download --no-deps --no-binary rpy2 --no-build-isolation rpy2==3.5.7
Collecting rpy2==3.5.7
  Downloading https://files.pythonhosted.org/packages/8b/39/4a9d9e59ba062f156a642af7271bed418584406a6e65c3a23d1ded8c4a77/rpy2-3.5.7.tar.gz (213kB)
  Saved ./rpy2-3.5.7.tar.gz
  Running setup.py (path:/tmp/pip-download-w21eexqj/rpy2/setup.py) egg_info for package rpy2 produced metadata for project name unknown. Fix your #egg=rpy2 fragments.
Successfully downloaded unknown
build-wheel.py: tar -C /tmp/build-wheel-fcaawynw -xf rpy2-3.5.7.tar.gz
build-wheel.py: mv /tmp/build-wheel-fcaawynw/rpy2-3.5.7 /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src
build-wheel.py: rm -rf /tmp/build-wheel-fcaawynw
build-wheel.py: mv /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src/pyproject.toml /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src/pyproject-chaquopy-disabled.toml
build-wheel.py: mkdir -p /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/requirements
build-wheel.py: cd /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src
build-wheel.py: python3.8 -m pip --disable-pip-version-check wheel -v --no-deps --no-clean --build-option --keep-temp -e .
Created temporary directory: /tmp/pip-ephem-wheel-cache-y75cbnuk
Created temporary directory: /tmp/pip-req-tracker-dpjk9q4x
Created requirements tracker '/tmp/pip-req-tracker-dpjk9q4x'
Created temporary directory: /tmp/pip-wheel-7_uuta1u
Obtaining file:///root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src
  Added file:///root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src to build tracker '/tmp/pip-req-tracker-dpjk9q4x'
  Running setup.py (path:/root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src/setup.py) egg_info for package from file:///root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src
    Running command python setup.py egg_info
    Unable to determine R home: [Errno 2] No such file or directory: 'R'
    running egg_info
    creating UNKNOWN.egg-info
    writing UNKNOWN.egg-info/PKG-INFO
    writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
    writing top-level names to UNKNOWN.egg-info/top_level.txt
    writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
    reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
    reading manifest template '[MANIFEST.in](http://manifest.in/)'
    /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'
      warnings.warn(msg)
    warning: no files found matching 'README' anywhere in distribution
    warning: no previously-included files matching '*patch*' found anywhere in distribution
    warning: no previously-included files matching '*diff*' found anywhere in distribution
    warning: no previously-included files matching '.hg' found anywhere in distribution
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '_rinterface_cffi_build'
    warning: no files found matching 'rpy/__init__.py'
    warning: no files found matching 'rpy/situation.py'
    warning: no files found matching '*.py' under directory 'rpy/robjects'
    warning: no files found matching '*.py' under directory 'rpy/ipython'
    warning: no files found matching '*.py' under directory 'rpy/interactive'
    warning: no files found matching '*.py' under directory 'rpy/rlike'
    no previously-included directories found matching 'dist'
    warning: no files found matching 'doc/source/rpy2_logo.png'
    writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
  Source in /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src has version 0.0.0, which satisfies requirement UNKNOWN==0.0.0 from file:///root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src
  Removed UNKNOWN==0.0.0 from file:///root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src from build tracker '/tmp/pip-req-tracker-dpjk9q4x'
Building wheels for collected packages: UNKNOWN
  Created temporary directory: /tmp/pip-wheel-79lqx65o
  Running setup.py bdist_wheel for UNKNOWN: started
  Destination directory: /tmp/pip-wheel-79lqx65o
  Running command /usr/local/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-79lqx65o --keep-temp
  Unable to determine R home: [Errno 2] No such file or directory: 'R'
  /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'
    warnings.warn(msg)
  running bdist_wheel
  running build
  cffi mode: CFFI_MODE.ANY
  ---
  CFFI_MODE.ANY
  ABI mode interface built.
  API mode interface not built because: [COMPILATION_STATUS.NO](http://compilation_status.no/)_R
  To change the API/ABI build mode, set or modify the environment variable RPY2_CFFI_MODE.
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_egg_info
  running egg_info
  writing UNKNOWN.egg-info/PKG-INFO
  writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
  writing top-level names to UNKNOWN.egg-info/top_level.txt
  reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
  reading manifest template '[MANIFEST.in](http://manifest.in/)'
  warning: no files found matching 'README' anywhere in distribution
  warning: no previously-included files matching '*patch*' found anywhere in distribution
  warning: no previously-included files matching '*diff*' found anywhere in distribution
  warning: no previously-included files matching '.hg' found anywhere in distribution
  warning: no files found matching 'MANIFEST'
  warning: no files found matching '_rinterface_cffi_build'
  warning: no files found matching 'rpy/__init__.py'
  warning: no files found matching 'rpy/situation.py'
  warning: no files found matching '*.py' under directory 'rpy/robjects'
  warning: no files found matching '*.py' under directory 'rpy/ipython'
  warning: no files found matching '*.py' under directory 'rpy/interactive'
  warning: no files found matching '*.py' under directory 'rpy/rlike'
  no previously-included directories found matching 'dist'
  warning: no files found matching 'doc/source/rpy2_logo.png'
  writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
  Copying UNKNOWN.egg-info to build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0-py3.8.egg-info
  running install_scripts
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  adding license file "AUTHORS" (matched pattern "AUTHORS*")
  creating build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-79lqx65o/UNKNOWN-0.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'UNKNOWN-0.0.0.dist-info/AUTHORS'
  adding 'UNKNOWN-0.0.0.dist-info/LICENSE'
  adding 'UNKNOWN-0.0.0.dist-info/METADATA'
  adding 'UNKNOWN-0.0.0.dist-info/WHEEL'
  adding 'UNKNOWN-0.0.0.dist-info/top_level.txt'
  adding 'UNKNOWN-0.0.0.dist-info/RECORD'
  Running setup.py bdist_wheel for UNKNOWN: finished with status 'done'
  Stored in directory: /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src
Successfully built UNKNOWN
Removed build tracker '/tmp/pip-req-tracker-dpjk9q4x'
/usr/local/lib/python3.8/site-packages/pip/_internal/commands/wheel.py:107: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
build-wheel.py: mkdir -p /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/fix_wheel
build-wheel.py: unzip -d /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/fix_wheel -q /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src/UNKNOWN-0.0.0-py3-none-any.whl
build-wheel.py: cp -a /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/src/LICENSE /root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/fix_wheel/rpy2-3.5.7.dist-info
build-wheel.py: Processing native binaries
Traceback (most recent call last):
  File "pypi/build-wheel.py", line 833, in <module>
    BuildWheel().main()
  File "pypi/build-wheel.py", line 109, in main
    self.unpack_and_build()
  File "pypi/build-wheel.py", line 150, in unpack_and_build
    return self.fix_wheel(wheel_filename)
  File "pypi/build-wheel.py", line 600, in fix_wheel
    for path, _, _ in csv.reader(open(f"{info_dir}/RECORD")):
NotADirectoryError: [Errno 20] Not a directory: '/root/pypi/packages/rpy2/build/3.5.7/cp38-cp38-android_21_x86_64/fix_wheel/rpy2-3.5.7.dist-info/RECORD'

**Comment by ivbabar** [comment]
@mhsmith Any suggestions?

**Comment by ivbabar** [comment]
@mhsmith I even tried adding a docker file for R at /server/R/Dockerfile
FROM r-base
COPY . /usr/local/src/myscripts
WORKDIR /usr/local/src/myscripts
CMD ["Rscript", "myscript.R"]

then did
sudo docker build -t myscript server/R
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM r-base
 ---> 3de1ef2039fb
Step 2/4 : COPY . /usr/local/src/myscripts
 ---> Using cache
 ---> 1dea8b73ebf5
Step 3/4 : WORKDIR /usr/local/src/myscripts
 ---> Using cache
 ---> 705c4b8d5b2d
Step 4/4 : CMD ["Rscript", "myscript.R"]
 ---> Using cache
 ---> d71209c4d0ff
Successfully built d71209c4d0ff
Successfully tagged myscript:latest
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

But still no luck. Please confirm if there is a solution beyond that or it won't be possible to use rpy2 using chaqoupy.

**Comment by mhsmith** [comment]
Sorry for the slow reply. To get this working, it looks like you'd probably have to build R itself for Android. Unfortunately I don't know anything specific about how to do that. But the general approach to building a Python library that depends on a non-Python library can be seen in the build files for pyzmq and chaquopy-libzmq.

**Comment by mhsmith** [comment]
It's been over a year, and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
