### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '' when building project

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#772]
Hi,
I had some trouble building my project as I got an error from Python:
`ValueError: invalid literal for int() with base 10: ''`

I looked in the relevant script and saw that the variable `size_str` was empty and supposed to be converted to an int, which seemed to cause the error.

#### Chaquopy version
13.0.0

#### Relevant parts of your build.gradle file
```
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

        python {
            version "3.8"
            pip {
                options "--upgrade"
                options "--upgrade-strategy", "eager"
                options "--compile"
                options "--progress-bar", "on"
                options "--only-binary", ":all:"    //Ignore source distributions

                options "--extra-index-url", "<path/to/build-wheel/fork>/server/pypi/dist/"

                install "numpy"
            }
            pyc {
                stdlib true
                pip true
                src true
            }
        }
```

#### Describe your issue
```
Executing tasks: [:app:assembleDebug] in project <path/to/project>

> Task :app:createDebugVariantModel UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:packageDebugResources UP-TO-DATE
> Task :app:parseDebugLocalResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugKotlin UP-TO-DATE
> Task :app:extractPythonBuildPackages UP-TO-DATE

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0, <path/to/build-wheel/fork>/server/pypi/dist/
Collecting charset-normalizer<3.0,>=2.0
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/charset-normalizer/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/db/51/a507c856293ab05cdc1db77ff4bc1268ddd39f29e7dc4919aa497f0adbec/charset_normalizer-2.1.1-py3-none-any.whl
Collecting pyatv==0.10.3
  Using cached https://files.pythonhosted.org/packages/10/11/2ef80cbe30db482c387faf87e4a3a8a523278b07dc0f5274e8f7e15f2460/pyatv-0.10.3-py3-none-any.whl
Collecting cryptography>=36.0.2 (from pyatv==0.10.3)
Collecting miniaudio>=1.45 (from pyatv==0.10.3)
Collecting async-timeout>=4.0.2 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/async-timeout/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl
Collecting requests>=2.23.0 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/requests/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/d2/f4/274d1dbe96b41cf4e0efb70cbced278ffd61b5c7bb70338b62af94ccb25b/requests-2.28.2-py3-none-any.whl
Collecting mediafile>=0.8.1 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/mediafile/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/5a/db/f08befa54604a8192fbd4fc009f99585c693f43bd175f73162695978ee30/mediafile-0.11.0-py3-none-any.whl
Collecting protobuf>=3.19.3 (from pyatv==0.10.3)
Collecting zeroconf>=0.38.1 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/zeroconf/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/3f/ff/a8d7faaa3573b6e4c775cacbf911a0afbcb4928ce71b3de43119227a396a/zeroconf-0.39.4-py3-none-any.whl
Collecting srptools>=0.2.0 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/srptools/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/8d/b8/3f935d7f7d6bc25a88859beb0a6e246313012a12ae4844665322f771a5cb/srptools-1.0.1-py2.py3-none-any.whl
Collecting chacha20poly1305-reuseable>=0.0.3 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/chacha20poly1305-reuseable/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/78/43/0e632aa9951b052fea863f7185d4baf1d6bd63e6f846fa92fb9d86177bff/chacha20poly1305_reuseable-0.0.4-py3-none-any.whl
Collecting bitarray>=2.1.2 (from pyatv==0.10.3)
Collecting aiohttp<5,>=3.8.1 (from pyatv==0.10.3)
Collecting ifaddr>=0.1.7 (from pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/ifaddr/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/9c/1f/19ebc343cc71a7ffa78f17018535adc5cbdd87afb31d7c34874680148b32/ifaddr-0.2.0-py3-none-any.whl
Collecting cffi>=1.12 (from cryptography>=36.0.2->pyatv==0.10.3)
Collecting wheel (from miniaudio>=1.45->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/wheel/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/bd/7c/d38a0b30ce22fc26ed7dbc087c6d00851fb3395e9d0dac40bec1f905030c/wheel-0.38.4-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.23.0->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/certifi/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl
Collecting idna<4,>=2.5 (from requests>=2.23.0->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/idna/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests>=2.23.0->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/urllib3/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/fe/ca/466766e20b767ddb9b951202542310cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl
Collecting six>=1.9 (from mediafile>=0.8.1->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/six/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting mutagen>=1.46 (from mediafile>=0.8.1->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/mutagen/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/03/ee/114d7016d2e34f341e212fefb5e7bd87785077ebcfff0ad23a497c70eea1/mutagen-1.46.0-py3-none-any.whl
Collecting frozenlist>=1.1.1 (from aiohttp<5,>=3.8.1->pyatv==0.10.3)
Collecting aiosignal>=1.1.2 (from aiohttp<5,>=3.8.1->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/aiosignal/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<5,>=3.8.1->pyatv==0.10.3)
Collecting multidict<7.0,>=4.5 (from aiohttp<5,>=3.8.1->pyatv==0.10.3)
Collecting attrs>=17.3.0 (from aiohttp<5,>=3.8.1->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/attrs/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/fb/6e/6f83bf616d2becdf333a1640f1d463fef3150e2e926b7010cb0f81c95e88/attrs-22.2.0-py3-none-any.whl
Collecting pycparser (from cffi>=1.12->cryptography>=36.0.2->pyatv==0.10.3)
  WARNING: Url '<path/to/build-wheel/fork>/server/pypi/dist/pycparser/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
Collecting chaquopy-libffi>=3.4.4 (from cffi>=1.12->cryptography>=36.0.2->pyatv==0.10.3)
Installing collected packages: charset-normalizer, pycparser, chaquopy-libffi, cffi, cryptography, wheel, miniaudio, async-timeout, certifi, idna, urllib3, requests, six, mutagen, mediafile, protobuf, ifaddr, zeroconf, srptools, chacha20poly1305-reuseable, bitarray, frozenlist, aiosignal, multidict, yarl, attrs, aiohttp, pyatv
Successfully installed aiohttp-3.8.3 aiosignal-1.3.1 async-timeout-4.0.2 attrs-22.2.0 bitarray-2.6.2 certifi-2022.12.7 cffi-1.15.1 chacha20poly1305-reuseable-0.0.4 chaquopy-libffi-3.4.4 charset-normalizer-2.1.1 cryptography-36.0.2 frozenlist-1.3.3 idna-3.4 ifaddr-0.2.0 mediafile-0.11.0 miniaudio-1.55 multidict-6.0.4 mutagen-1.46.0 protobuf-4.21.12 pyatv-0.10.3 pycparser-2.21 requests-2.28.2 six-1.16.0 srptools-1.0.1 urllib3-1.26.14 wheel-0.38.4 yarl-1.8.2 zeroconf-0.39.4
Chaquopy: Failed to process <path/to/project>/app/build/pip/debug/arm64-v8a/aiohttp-3.8.3.dist-info
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<path/to/project>/app/build/generated/python/bp.zip/chaquopy/pip_install.py", line 371, in <module>
  File "<path/to/project>/app/build/generated/python/bp.zip/chaquopy/pip_install.py", line 66, in main
  File "<path/to/project>/app/build/generated/python/bp.zip/chaquopy/pip_install.py", line 160, in pip_install
ValueError: invalid literal for int() with base 10: ''

> Task :app:generateDebugPythonRequirements FAILED
> Task :app:mergeDebugPythonSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:generateDebugPythonAppAssets UP-TO-DATE
> Task :app:generateDebugPythonMiscAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:generateDebugPythonJniLibs UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'python3.8'' finished with non-zero exit value 1
  
  To view full details in Android Studio:
  * Click the 'Build: failed' caption to the left of this message.
  * Then scroll up to see the full output.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
34 actionable tasks: 1 executed, 33 up-to-date

```

**Comment by IsakTheHacker** [comment]
I solved it! The issue was caused by including:
`options "--compile"`

Maybe this should be noted in the Chaquopy documentation?

**Comment by mhsmith** [comment]
Thanks for the report. I'm not sure why you were using the `--compile` option, but you can control .pyc compilation using Chaquopy's own options as described [here](https://chaquo.com/chaquopy/doc/current/android.html#android-bytecode).

The documentation does hint at this by saying you can't use pip options "which relate to the target environment". I think there are too many of those options to list them all, but I'm open to suggestions for how this wording could be improved.

Meanwhile, this error message is obviously unhelpful, so I'll leave the issue open until that's fixed.

**Comment by mhsmith** [comment]
And thanks very much for the new package versions which you contributed in the other issues. I'll look at adopting them into the official Chaquopy repository as soon as I can.
