### ISSUE TITLE
pyatv crashes with ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#786]
#### Chaquopy version
13.0.0

#### Devices or emulators where the issue happens
This issue does not seem to relate to the emulator, I think, but I just used the standard emulator in Android Studio if that matters.

#### Relevant parts of your code
This part of the code causes the crash:
```kotlin
private fun getPyatvHandle(): PyObject {
	val py = initPythonInterpreter()
	return py.getModule("pyatv")
}
```

#### Describe your issue
The app crashes with this error:
```Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'google```

This is the full stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <project>, PID: 6016
    java.lang.RuntimeException: Unable to start activity ComponentInfo{<project>.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'google'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'google'
        at <python>.java.chaquopy.import_override(import.pxi:20)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.pyatv.support.<module>(__init__.py:10)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.pyatv.interface.<module>(interface.py:39)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.pyatv.<module>(__init__.py:14)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
        at <python>.java.android.importer.exec_module(.\java\android\importer.py:545)
        at <python>.java.android.importer.exec_module(.\java\android\importer.py:597)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at <project>.MainActivity.getPyatvHandle(MainActivity.kt:30)
        at <project>.MainActivity.onCreate(MainActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:7998)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by IsakTheHacker** [comment]
I updated to the latest version: 14.0.2 and the issue still occurs :(

**Comment by mhsmith** [comment]
Pyatv appears to have a [requirement on protobuf](https://github.com/postlund/pyatv/blob/v0.10.3/base_versions.txt), which should prevent this error. However, when I try to install it, I get a different build-time error from the requirement on miniaudio.

Please explain exactly how you're installing pyatv, and any modifications you've made to it.

**Comment by IsakTheHacker** [comment]
Hi, I have not made any modifications to pyatv itself and I am using these build scripts to package protobuf and miniaudio for Chaquopy:
- [protobuf](https://github.com/IsakTheHacker/chaquopy-build-wheel/tree/master/server/pypi/packages/protobuf)
- [miniaudio](https://github.com/IsakTheHacker/chaquopy-build-wheel/tree/master/server/pypi/packages/miniaudio)

They are located at my [fork](https://github.com/IsakTheHacker/chaquopy-build-wheel) of the build-wheel repository

**Comment by mhsmith** [comment]
OK, I was able to complete the build with the following changes:
* Adding miniaudio from your build script above
* Updating bitarray from your build script [here](https://github.com/IsakTheHacker/chaquopy-build-wheel/tree/master/server/pypi/packages/bitarray)
* Installing `pyatv==0.10.0`, because the current version requires a newer version of `cryptography`, which it doesn't look like you have a build script for.

After doing that, I was able to import `pyatv` without any error. 

So my guess is that there's something wrong with your build of `protobuf`. But the good news is, you don't need to build that package because they have pure-Python wheels on PyPI. So try removing your build and see if that helps.

**Comment by IsakTheHacker** [comment]
After downgrading pyatv to 0.10.0 it finally works as intended! Thank you so much for your help.

However, when using the library in the code I have come across another issue, since pyatv is asynchronous I can't just call the methods and functions using module.callAttr(). The way I solved this was by creating a wrapper Python script:

```python
import asyncio
import pyatv

loop = asyncio.get_event_loop()

def scan():
    return loop.run_until_complete(pyatv.scan(loop))
```

This feels like a really bad solution though, is there any way to call async code from Chaquopy? If not, is this something that could be added perhaps?

**Comment by mhsmith** [comment]
You can always just write the equivalent code in Kotlin:
```kotlin
val loop = py.getModule("asyncio").callAttr("get_event_loop")
loop.callAttr("run_until_complete", py.getModule("pyatv").callAttr("scan", loop))
```

But if the scan takes more than a small fraction of a second, it would be a good idea to do it on a background thread so it doesn't block the UI.
