### ISSUE TITLE
The medthod savefig() of matplotlib cant save image 

### ISSUE THREAD

**Issue by LongPham1** [chaquo/chaquopy#835]
Chaquopy version : 13.0.0
Devices or emulators where the issue happens:xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp
My code in android is:
``
public class MainActivity extends Activity {
    Button b1, b2, b3;
    ImageView imv;

    private Bitmap bmp;
    private Bitmap operation;
    private static final String TAG = "MainActivity";
    public static String fileDir = "C:\\Users\\ADMIN";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        
        if(!Python.isStarted()){
            Python.start(new AndroidPlatform(this));
        }
        Python python = Python.getInstance();
        PyObject plotmatriX = python.getModule("Myscript1");
        PyObject module = python.getModule("numpy");

        int[] kernel = new int[]{1,2,3,4};

        PyObject matrix = module.callAttr("matrix", kernel);
        plotmatriX.callAttr("plot_matrix", matrix);

        Intent second_activity = new Intent(MainActivity.this, MainActivity2.class);
        startActivity(second_activity);
    }
}
``
And the python code is:

``
import os
import matplotlib.pyplot as plt
import numpy

def plot_matrix(matrix):
    # matrix = matrix.astype(float)
    file = r"C:\Users\ADMIN\AppData\Local\Google\AndroidStudio2021.2\device-explorer\xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp\data\data\com.example.myapplication2\files"
    plt.imshow(matrix)
    plt.savefig(file + "\matrix_plot.png")

plot_matrix([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
``

Even though the python code which I provided is located in src/main/python/Myscript1.py, and the code python in vscode is the same. But I don't even know why is in vscode it runs so well, and it even shows the image exactly where the file should go but in android studio getting the error:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication2, PID: 2443
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication2/com.example.myapplication2.MainActivity}: com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: 'C:\\Users\\ADMIN\\AppData\\Local\\Google\\AndroidStudio2021.2\\device-explorer\\xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp\\data\\data\\com.example.myapplication2\\files\\matrix_plot.png'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3520)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
     Caused by: com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: 'C:\\Users\\ADMIN\\AppData\\Local\\Google\\AndroidStudio2021.2\\device-explorer\\xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp\\data\\data\\com.example.myapplication2\\files\\matrix_plot.png'
        at <python>.matplotlib.cbook.to_filehandle(__init__.py:432)
        at <python>.matplotlib.cbook.open_file_cm(__init__.py:447)
        at <python>.contextlib.__enter__(contextlib.py:113)
        at <python>.matplotlib.backends.backend_agg.print_png(backend_agg.py:529)
        at <python>.matplotlib.backend_bases.print_figure(backend_bases.py:2082)
        at <python>.matplotlib.figure.savefig(figure.py:2180)
        at <python>.matplotlib.pyplot.savefig(pyplot.py:722)
        at <python>.Myscript1.plot_matrix(Myscript1.py:12)
        at <python>.Myscript1.<module>(Myscript1.py:14)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
        at <python>.java.android.importer.exec_module(.\java\android\importer.py:545)
        at <python>.java.android.importer.exec_module(.\java\android\importer.py:597)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.example.myapplication2.MainActivity.onCreate(MainActivity.java:37)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Activity.performCreate(Activity.java:8083)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3493)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7864) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011) 
And not yet, when I checked the file where the permission has been, then it can write normally. I don't understand, please help me

**Comment by LongPham1** [comment]
> Chaquopy version : 13.0.0 Devices or emulators where the issue happens:xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp My code in android is: `` public class MainActivity extends Activity { Button b1, b2, b3; ImageView imv;
> 
> ```
> private Bitmap bmp;
> private Bitmap operation;
> private static final String TAG = "MainActivity";
> public static String fileDir = "C:\\Users\\ADMIN";
> 
> @Override
> protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     setContentView(R.layout.activity_main);
>     
>     if(!Python.isStarted()){
>         Python.start(new AndroidPlatform(this));
>     }
>     Python python = Python.getInstance();
>     PyObject plotmatriX = python.getModule("Myscript1");
>     PyObject module = python.getModule("numpy");
> 
>     int[] kernel = new int[]{1,2,3,4};
> 
> 
>     PyObject matrix = module.callAttr("matrix", kernel);
>     plotmatriX.callAttr("plot_matrix", matrix);
> 
> 
>     Intent second_activity = new Intent(MainActivity.this, MainActivity2.class);
>     startActivity(second_activity);
> }
> ```
> 
> } `` And the python code is:
> 
> `` import os import matplotlib.pyplot as plt import numpy
> 
> def plot_matrix(matrix): # matrix = matrix.astype(float) file = r"C:\Users\ADMIN\AppData\Local\Google\AndroidStudio2021.2\device-explorer\xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp\data\data\com.example.myapplication2\files" plt.imshow(matrix) plt.savefig(file + "\matrix_plot.png")
> 
> plot_matrix([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]) ``
> 
> Even though the python code which I provided is located in src/main/python/Myscript1.py, and the code python in vscode is the same. But I don't even know why is in vscode it runs so well, and it even shows the image exactly where the file should go but in android studio getting the error:
> 
> E/AndroidRuntime: FATAL EXCEPTION: main Process: com.example.myapplication2, PID: 2443 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication2/com.example.myapplication2.MainActivity}: com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: 'C:\Users\ADMIN\AppData\Local\Google\AndroidStudio2021.2\device-explorer\xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp\data\data\com.example.myapplication2\files\matrix_plot.png' at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3520) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:236) at android.app.ActivityThread.main(ActivityThread.java:7864) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011) Caused by: com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: 'C:\Users\ADMIN\AppData\Local\Google\AndroidStudio2021.2\device-explorer\xiaomi-m2004j19c-adb-0bdfceb20407-aZiP2T._adb-tls-connect._tcp\data\data\com.example.myapplication2\files\matrix_plot.png' at .matplotlib.cbook.to_filehandle(**init**.py:432) at .matplotlib.cbook.open_file_cm(**init**.py:447) at .contextlib.**enter**(contextlib.py:113) at .matplotlib.backends.backend_agg.print_png(backend_agg.py:529) at .matplotlib.backend_bases.print_figure(backend_bases.py:2082) at .matplotlib.figure.savefig(figure.py:2180) at .matplotlib.pyplot.savefig(pyplot.py:722) at .Myscript1.plot_matrix(Myscript1.py:12) at .Myscript1.(Myscript1.py:14) at .importlib._bootstrap._call_with_frames_removed(:219) at .importlib._bootstrap_external.exec_module(:843) at .java.android.importer.exec_module(.\java\android\importer.py:545) at .java.android.importer.exec_module(.\java\android\importer.py:597) at .importlib._bootstrap._load_unlocked(:671) at .importlib._bootstrap._find_and_load_unlocked(:975) at .importlib._bootstrap._find_and_load(:991) at .importlib._bootstrap._gcd_import(:1014) at .importlib.import_module(**init**.py:127) at .chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:154) at com.chaquo.python.Python.getModuleNative(Native Method) at com.chaquo.python.Python.getModule(Python.java:84) at com.example.myapplication2.MainActivity.onCreate(MainActivity.java:37) at android.app.Activity.performCreate(Activity.java:8109) at android.app.Activity.performCreate(Activity.java:8083) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3493) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692)  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)  at android.os.Handler.dispatchMessage(Handler.java:106)  at android.os.Looper.loop(Looper.java:236)  at android.app.ActivityThread.main(ActivityThread.java:7864)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)  And not yet, when I checked the file where the permission has been, then it can write normally. I don't understand, please help me

**Comment by mhsmith** [comment]
To write files within your app, see [this FAQ section](https://chaquo.com/chaquopy/doc/current/faq.html#faq-write).
