### ISSUE TITLE
Failed to install grpcio>=1.48.2

### ISSUE THREAD

**Issue by fahim44** [chaquo/chaquopy#843]
#### Chaquopy version

` id 'com.chaquo.python' version '14.0.2' apply false`

#### Relevant parts of your build.gradle file

```gradle
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {
            version "3.8"
            buildPython "/usr/bin/python3.8"

            pip {
                install "-r", "requirements.txt"
            }
        }
```

#### Describe your issue

```
Collecting grpcio>=1.48.2
  Using cached grpcio-1.53.0.tar.gz (22.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9rjvxm85/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9rjvxm85/grpcio/setup.py'"'"';import chaquopy_monkey; chaquopy_monkey.disable_native();f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /tmp/pip-pip-egg-info-lantilse
         cwd: /tmp/pip-install-9rjvxm85/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9rjvxm85/grpcio/setup.py", line 262, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-9rjvxm85/grpcio/setup.py", line 209, in check_linker_need_libatomic
        cpp_test = subprocess.Popen(cxx + ['-x', 'c++', '-std=c++14', '-'],
      File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib64/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'Chaquopy_cannot_compile_native_code'
    ----------------------------------------
ERROR: Failed to install grpcio>=1.48.2 from https://files.pythonhosted.org/packages/9d/13/f7e3834ba272c0058c66de57272fb3b20dde69003032fdb6b4d7c36eebed/grpcio-1.53.0.tar.gz#sha256=a4952899b4931a6ba12951f9a141ef3e74ff8a6ec9aa2dc602afa40f63595e33 (from tensorboard>=2.4.1->-r requirements.txt (line 21)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
```

**Comment by mhsmith** [comment]
You can work around this by using a slightly older version of tensorboard. Edit your requirements.txt to change `tensorboard>=2.4.1` to `tensorboard==2.11.2`.

Newer versions of pip are able to do this kind of backtracking automatically, but Chaquopy still uses pip 20.1.
