### ISSUE TITLE
Python async

### ISSUE THREAD

**Issue by hetingrui** [chaquo/chaquopy#860]
Python async method return a value:
```
async def func():
    value = await get_value()
    return value
```
value should be a integer when get_value() success

java:
```
PyObject obj = pymodule.callAttr('func');
System.out.println(obj);
```

It output `I/System.out: <coroutine object func at 0x8a603f68>`
How to get the int value instead of a coroutine

==========================================

I also tried to change python code like:

```
def func:
    async def test():
        value = await get_value()
        return value
    ans = asyncio.run(test(),debug=False)
    return ans
```
And java got error
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.androidui, PID: 19334
    com.chaquo.python.PyException: SyntaxError: invalid syntax (client.py, line 43)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.source_to_code(<frozen importlib._bootstrap_external>:906)
        at <python>.importlib._bootstrap_external.get_code(<frozen importlib._bootstrap_external>:976)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:839)
        at <python>.java.android.importer.exec_module(importer.py:554)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.example.androidui.ItemDetailFragment$1.onClick(ItemDetailFragment.java:95)
        at android.view.View.performClick(View.java:5637)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by hetingrui** [comment]
The problem solved

**Comment by mhsmith** [comment]
The SyntaxError is probably from the missing parentheses after `def func`.
