### ISSUE TITLE
com.chaquo.python.PyException: ModuleNotFoundError - Module is present though

### ISSUE THREAD

**Issue by Lokuslick** [chaquo/chaquopy#868]
My use case is to build the Android app with Android SDK and a python module.

- I have created a basic Android project.
- Created a new module called py. 
- In py module, all the Python script exists in src/main/python.
- I have exposed the py module to the app module.
- When I ran the code. I got the below exception.

com.chaquo.python.PyException: ModuleNotFoundError: No module named 'user'

#### Chaquopy version
com.chaquo.python:gradle - 14.0.2

#### Devices or emulators where the issue happens
Pixel 5 API level 23

#### Relevant parts of your code
Check on this basic project 
[https://github.com/Lokuslick/ONDC2](https://github.com/Lokuslick/ONDC2)
Inside py module https://github.com/Lokuslick/ONDC2/tree/master/py

#### Describe your issue
```
Process: com.retro.ondc, PID: 10711
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.retro.ondc/com.retro.ondc.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'user'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'user'
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:973)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.retro.py.ExposeUseModule.callPythonFunction(ExposeUseModule.kt:17)
        at com.retro.ondc.MainActivity.displayPythonResult(MainActivity.kt:26)
        at com.retro.ondc.MainActivity.onCreate(MainActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    ```

**Comment by mhsmith** [comment]
You're using the Chaquopy plugin in both the `app` module and the `py` module. But as it says [here](https://chaquo.com/chaquopy/doc/current/android.html#android-plugin):

> The Chaquopy plugin can also be used in an [Android library module](https://developer.android.com/studio/projects/android-library) (AAR). However, it can only be used in one module in a project: either in the app module, or in exactly one library module. If you use it in multiple modules, the build may fail, and even if it succeeds, only one module’s Python code will be included in the app.

**Comment by Lokuslick** [comment]
Hey @mhsmith Thanks for the help. But another issue popped out. 
When I ran the app it is getting the python file from my py module as expected.
I am using web3 package which has to be installed in the py module in the above repository (Have updated the above repo code). When I try to use the below block of installing a package I am getting the compilation error attached below.

**build.gradle**
```
python {
            pip {
                install "web3"
            }
        }
```
**Compilation error**
> Failed to install bitarray<3,>=2.4.0 from https://files.pythonhosted.org/packages/82/30/68a3ee41e6abbb521a3418fb25a7755127a1d6bf4604028bb404f833b2fc/bitarray-2.7.3.tar.gz#sha256=f71256a32609b036adad932e1228b66a6b4e2cae6be397e588ddc0babd9a78b9 (from eth-account>=0.8.0->web3).

![image](https://user-images.githubusercontent.com/33567165/236838538-fc19b2dc-d138-4e0b-986c-358b33af5fd4.png)
