### ISSUE TITLE
support for scikit-learn==1.2.2 

### ISSUE THREAD

**Issue by civilaakash** [chaquo/chaquopy#878]
Please add support for latest version of scikit-learn=1.2.2
//////////////////////////////////////////////////////////////////////////////////////////////////////////////
 Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
    ERROR: Command errored out with exit status 1:

     command: '''Python38\python.exe' '''Pybot2\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\..~1\AppData\Local\Temp\tmp_41pro2i'
         cwd: ''\Temp\pip-install-4p_v7dyr\scikit-learn
    Complete output (30 lines):
    Partial import of sklearn during the build process.
    ''\Temp\pip-build-env-8s0uf_pu\overlay\Lib\site-packages\scipy\__init__.py:173: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.17.3)
      warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
    Traceback (most recent call last):
      File "''Pybot2\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "''Pybot2\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "''Pybot2\app\build\generated\python\bp\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "''\Temp\pip-build-env-8s0uf_pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "''\Temp\pip-build-env-8s0uf_pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
        super(_BuildMetaLegacyBackend,
      File "''\Temp\pip-build-env-8s0uf_pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
        exec(code, locals())
      File "<string>", line 669, in <module>
      File "<string>", line 663, in setup_package
      File "<string>", line 597, in configure_extension_modules
      File "''\Temp\pip-install-4p_v7dyr\scikit-learn\sklearn\_build_utils\__init__.py", line 47, in cythonize_extensions
        basic_check_build()
      File "''\Temp\pip-install-4p_v7dyr\scikit-learn\sklearn\_build_utils\pre_build_helpers.py", line 82, in basic_check_build
        compile_test_program(code)
      File "''\Temp\pip-install-4p_v7dyr\scikit-learn\sklearn\_build_utils\pre_build_helpers.py", line 38, in compile_test_program
        ccompiler.compile(
      File "''\Temp\pip-build-env-8s0uf_pu\site\chaquopy_monkey.py", line 56, in compile
        chaquopy_block_native("CCompiler.compile")
      File "''\Temp\pip-build-env-8s0uf_pu\site\chaquopy_monkey.py", line 87, in chaquopy_block_native
        raise DistutilsPlatformError("{}: {}".format(prefix, CHAQUOPY_NATIVE_ERROR))
    distutils.errors.DistutilsPlatformError: CCompiler.compile: Chaquopy cannot compile native code
    ----------------------------------------
ERROR: Failed to install scikit-learn==1.2.2 from https://files.pythonhosted.org/packages/c9/fa/8e158d81e3602da1e7bafbd4987938bc003fe4b0f44d65681e7f8face95a/scikit-learn-1.2.2.tar.gz#sha256=8429aea30ec24e7a8c7ed8a3fa6213adf3814a6efbea09e16e0a0c71e1a1a3d7.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install scikit-learn==1.2.2 from https://files.pythonhosted.org/packages/c9/fa/8e158d81e3602da1e7bafbd4987938bc003fe4b0f44d65681e7f8face95a/scikit-learn-1.2.2.tar.gz#sha256=8429aea30ec24e7a8c7ed8a3fa6213adf3814a6efbea09e16e0a0c71e1a1a3d7.

**Comment by mhsmith** [comment]
See #732, and please search for existing issues before creating new ones.

**Comment by mhsmith** [comment]
Scikit-learn version 1.1.3 is now available in the public repository for Python 3.8 and 3.9 (#732). If anyone needs a newer version than that, please click the thumbs up button above, and post a comment explaining why you need it.

Or if you'd like to try building the new version yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md). This package only required a small patch, so the update should not be too difficult. If you're successful, please make a pull request so we can add the new version to the public repository.

**Comment by 2245332767** [comment]
My Scikit-learn version ==1.1.3,
Collecting scikit-learn>=1.0.0
  Using cached https://chaquo.com/pypi-13.1/scikit-learn/scikit_learn-1.1.3-1-cp38-cp38-android_21_arm64_v8a.whl (7.0 MB)
 Now I need to change its version to 1.3.2，how can I do it? Help me,please.

**Comment by 2245332767** [comment]
> My Scikit-learn version ==1.1.3,
> Collecting scikit-learn>=1.0.0
> Using cached https://chaquo.com/pypi-13.1/scikit-learn/scikit_learn-1.1.3-1-cp38-cp38-android_21_arm64_v8a.whl (7.0 MB)
> Now I need to change its version to 1.3.2，how can I do it? Help me,please.

**Comment by mhsmith** [comment]
You'll need to change your app's Python version to 3.9 or 3.10, as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#python-version).

**Comment by 2245332767** [comment]
Thanks for your respond,but my app'Python version is 3.9.19.
![1720527309644](https://github.com/chaquo/chaquopy/assets/115978778/42ebbdbc-e5e9-4f9a-a432-0cf19e9d471b)

And I code pip{install "scikit-learn==1.3.2"},
it goes wrong:
Failed to install scikit-learn==1.3.2 from https://files.pythonhosted.org/packages/88/00/835e3d280fdd7784e76bdef91dd9487582d7951a7254f59fc8004fc8b213/scikit-learn-1.3.2.tar.gz#sha256=a2f54c76accc15a34bfb9066e6c7a56c1e7235dda5762b990792330b52ccfb05.
