### ISSUE TITLE
Libraries for Unzipping downloads - Alternatives to shutil

### ISSUE THREAD

**Issue by siddij3** [chaquo/chaquopy#882]
Hi there,

Wanted to ask if there are libraries that unzip files downloaded into the phone. I would use shutil in the PC environment, but shutil isn't supported by the platform, and zipfile throws errors if I try to implement the same functions despite using the necessary filepath correctors necessary for Android.

Thanks

**Comment by mhsmith** [comment]
As far as I know, shutil and zipfile both work fine. Please post the errors you received.

**Comment by mhsmith** [comment]
Both shutil and zipfile are in the standard library, so you don't need to install them.

**Comment by siddij3** [comment]
Okay thanks!

I managed to used shutil, but ran into the following errors:

```
FATAL EXCEPTION: main
                                                                                                    Process: ca.mcmaster.waterqualitymonitor, PID: 29391
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{ca.mcmaster.waterqualitymonitor/ca.mcmaster.testsuitecommon.SplashActivity}: com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: '/Model [15, 15] 0'
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: com.chaquo.python.PyException: OSError: [Errno 30] Read-only file system: '/Model [15, 15] 0'
                                                                                                    	at <python>.os.makedirs(os.py:223)
                                                                                                    	at <python>.shutil._ensure_directory(shutil.py:1128)
                                                                                                    	at <python>.shutil._unpack_zipfile(shutil.py:1151)
                                                                                                    	at <python>.shutil.unpack_archive(shutil.py:1241)
                                                                                                    	at <python>.functions.load_from_cloud(functions.py:64)
                                                                                                    	at <python>.backend.download_models(backend.py:61)
                                                                                                    	at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
                                                                                                    	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
                                                                                                    	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
                                                                                                    	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
                                                                                                    	at ca.mcmaster.testsuitecommon.SplashActivity.onCreate(SplashActivity.java:60)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8591)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8570)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
```

Relevant Code

```
import cloudinary
import cloudinary.api
import requests
import shutil
import os

def load_from_cloud():

    # Specify the public ID or the URL of the ZIP file to download
    zip_public_id = f'{get_model_folder_name()}.zip'  # Or provide the URL of the ZIP file
    # Get the download URL for the ZIP file from Cloudinary
    download_url = cloudinary.utils.cloudinary_url(zip_public_id,
                                                   resource_type='raw')[0]

    response = requests.get(download_url, stream=True)


    # save_path = f".\\{zip_public_id}"
    path = os.path.join(os.environ['HOME'], f'{zip_public_id}')


    with open(path, 'wb') as file:
        for chunk in response.iter_content(chunk_size=128):
            file.write(chunk)

    #Unzip file

    #
    # path = file_management.get_file_path()
    shutil.unpack_archive(path)
    return os.listdir(os.environ['HOME'])
```

**Comment by mhsmith** [comment]
By default, `unpack_archive` unpacks into the working directory, which is read-only on Android. You should pass a second argument to unpack into somewhere under `HOME`.

**Comment by siddij3** [comment]
Thanks!
