### ISSUE TITLE
Loading Models with Keras/Tensorflow

### ISSUE THREAD

**Issue by siddij3** [chaquo/chaquopy#884]
--
I'm trying to load models from Keras into the app, but the app crashes during the load_model section of the app. 

#### Chaquopy version
```
buildscript {
    repositories {
        jcenter()
        maven { url "https://chaquo.com/maven" }
        google()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
plugins {
    id 'com.chaquo.python' version '14.0.2' apply false
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.21' apply false

}
```

#### Devices or emulators where the issue happens
Samsung Galaxy Note 20

#### Relevant parts of your code
```
def download_models():
    global optimal_NNs

    path = file_management.get_file_path()

    file_name = functions.get_model_folder_name()

    i = 0
    for filename in os.listdir(os.environ['HOME']):
        if "Model " in filename:
            optimal_NNs = load_model(os.path.join(os.environ['HOME'], f'{filename}'))
            return optimal_NNs.optimizer
```

#### Describe your issue
Process: ca.mcmaster.waterqualitymonitor, PID: 28707
                                                                                                    com.chaquo.python.PyException: NotFoundError: Op type not registered 'DisableCopyOnRead' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
                                                                                                    	at <python>.tensorflow.python.framework.ops._get_op_def(ops.py:3712)
                                                                                                    	at <python>.tensorflow.python.framework.function_def_to_graph.function_def_to_graph_def(function_def_to_graph.py:218)
                                                                                                    	at <python>.tensorflow.python.framework.function_def_to_graph.function_def_to_graph(function_def_to_graph.py:58)
                                                                                                    	at <python>.tensorflow.python.saved_model.function_deserialization.load_function_def_library(function_deserialization.py:312)
                                                                                                    	at <python>.tensorflow.python.saved_model.load.__init__(load.py:113)
                                                                                                    	at <python>.tensorflow.python.keras.saving.saved_model.load.__init__(load.py:118)
                                                                                                    	at <python>.tensorflow.python.saved_model.load.load_internal(load.py:550)
                                                                                                    	at <python>.tensorflow.python.keras.saving.saved_model.load.load(load.py:89)
                                                                                                    	at <python>.tensorflow.python.keras.saving.save.load_model(save.py:150)
                                                                                                    	at <python>.backend.download_models(backend.py:54)
                                                                                                    	at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
                                                                                                    	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
                                                                                                    	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
                                                                                                    	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
                                                                                                    	at ca.mcmaster.testsuitecommon.SplashActivity$1.onClick(SplashActivity.java:99)
                                                                                                    	at android.view.View.performClick(View.java:7892)
                                                                                                    	at android.widget.TextView.performClick(TextView.java:16219)
                                                                                                    	at android.view.View.performClickInternal(View.java:7869)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30880)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by mhsmith** [comment]
Our TensorFlow version is probably too old for this model. For updates, please subscribe to #374.

**Comment by mhsmith** [comment]
Which model were you trying to use?

**Comment by siddij3** [comment]
I build a custom model that used the default save method.
https://res.cloudinary.com/duwn58xko/raw/upload/v1686854050/gold_fc_adam2.zip
zip file here to models

**Comment by PKDmeDEV** [comment]
what is the latest TensorFlow version supported ?

**Comment by mhsmith** [comment]
You can check for yourself [here](https://chaquo.com/pypi-7.0/). Note that tflite-runtime is much easier to build, so will often be a newer version than the main tensorflow package.
