### ISSUE TITLE
hrv-analysis and astropy libraries

### ISSUE THREAD

**Issue by KimiaHO** [chaquo/chaquopy#894]
I have a Python code with wide use of hrv-analysis library in Python. While installing the mentioned library, I always get the error that happens while installing astropy. I tried with different connections, or even installing astropy first from github and....
```
ERROR: Command errored out with exit status 1:
     command: 'D:\Program Files\Python\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Asus\\AppData\\Local\\Temp\\pip-req-build-v0zh5l7g\\setup.py'"'"'; __file__='"'"'C:\\Users\\Asus\\AppData\\Local\\Temp\\pip-req-build-v0zh5l7g\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
    ERROR: Command errored out with exit status 1:

         cwd: C:\Users\Asus\AppData\Local\Temp\pip-req-build-v0zh5l7g\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Asus\AppData\Local\Temp\pip-req-build-v0zh5l7g\setup.py", line 67, in <module>
        from extension_helpers import get_extensions  # noqa: E402
    ModuleNotFoundError: No module named 'extension_helpers'
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I couldn't find thee setup.py mentioned here. 
It would be very grateful for any help given that my project due date in near.

**Comment by mhsmith** [comment]
Astropy requires an `extractPackages` declaration: see https://github.com/chaquo/chaquopy/issues/812#issuecomment-1578166055.

**Comment by mhsmith** [comment]
If that doesn't work, please create a separate issue, and include the full stack trace and the relevant sections of your code.
