### ISSUE TITLE
gpt4all

### ISSUE THREAD

**Issue by luimtersta** [chaquo/chaquopy#895]
#### Chaquopy version
13.0.0 & 14.0.2

#### Devices or emulators where the issue happens
Android11

#### Relevant parts of your code
import gpt4all

#### Describe your issue
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.AppName, PID: 23313
    com.chaquo.python.PyException: FileNotFoundError: gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.so
        at <python>.java.android.importer.extract_if_changed(importer.py:498)
        at <python>.java.android.importer.extract_so(importer.py:675)
        at <python>.contextlib.__enter__(contextlib.py:113)
        at <python>.java.android.importer.CDLL_init_override(importer.py:166)
        at <python>.gpt4all.pyllmodel.load_llmodel_library(pyllmodel.py:32)
        at <python>.gpt4all.pyllmodel.<module>(pyllmodel.py:39)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.gpt4all.gpt4all.<module>(gpt4all.py:6)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.gpt4all.<module>(__init__.py:1)
        at <python>.java.chaquopy.import_override(import.pxi:26)
        at <python>.pyprogramname.<module>(pyprogramname.py:2)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
        at <python>.java.android.importer.exec_module(importer.py:554)
        at <python>.java.android.importer.exec_module(importer.py:606)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.AppName.MainActivity$MyViewModel$verniandoey$2.invokeSuspend(MainActivity.kt:364)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2a4bfbb, Dispatchers.Main.immediate]
I/Process: Sending signal. PID: 23313 SIG: 9
```

**Comment by mhsmith** [comment]
How exactly did you add gpt4all to your app?

**Comment by luimtersta** [comment]
Through pip install gpt4all in gradle.

**Comment by luimtersta** [comment]
I think it is because of ARM arch. Didn't notice it is the most probable cause.

**Comment by luimtersta** [comment]
When using Python higher than 3.8:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.AppName, PID: 28247
    com.chaquo.python.PyException: ImportError: bad magic number in 'gpt4all': b'U\r\r\n'
        at <python>.java.android.importer.get_code(importer.py:609)
        at <python>.java.android.importer.exec_module(importer.py:554)
        at <python>.java.android.importer.exec_module(importer.py:606)
        at <python>.java.chaquopy.import_override(import.pxi:20)
        at <python>.java.chaquopy.import_override(import.pxi:60)
        at <python>.pyprogramname.<module>(pyprogramname.py:2)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:241)
        at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:883)
        at <python>.java.android.importer.exec_module(importer.py:554)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:688)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:1006)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1027)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1050)
        at <python>.importlib.import_module(__init__.py:126)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
        at com.chaquo.python.Python.getModuleNative(Native Method)
        at com.chaquo.python.Python.getModule(Python.java:84)
        at com.AppName.MainActivity$MyViewModel$verniandoey$2.invokeSuspend(MainActivity.kt:364)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c4676b7, Dispatchers.Main.immediate]
I/Process: Sending signal. PID: 28247 SIG: 9

**Comment by mhsmith** [comment]
OK, it looks like no version of gpt4all is actually pure-Python, even though the older versions were released as `none-any` wheels. 

Since this package contains native components, it would have to be built into an Android-compatible wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md). And if you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

**Comment by luimtersta** [comment]
That seems to be not possible, the version tried with chaq was 0.1.7, also giving that error in other systems (my fault didn't notice). But it have the same kind of special LLM libraries as the new versions, which I can by other means run with chaquo, and those are built in file format elf64-x86-64 (and thereby cannot run on smartphones), probably it's x86-64 format from the very root, so it could need a completely new approach with more workload than the package itself.
I'll seek around,,,
