### ISSUE TITLE
pkgutil.iter_modules fails on missing directory

### ISSUE THREAD

**Issue by dbnicholson** [chaquo/chaquopy#920]
#### Chaquopy version

13.0.0

#### Devices or emulators where the issue happens

Pixel 2 API 30

#### Relevant parts of your code

I'm bundling Django and it uses `pkgutil.iter_modules` to find management commands provided by Django apps. The problem is that Django runs [`pkg_util.iter_modules([command_dir])`](https://github.com/django/django/blob/main/django/core/management/__init__.py#L35) without bothering to check that `command_dir` exists. Presumably this is because the default `iter_modules` returns an empty list when the specified directory doesn't exist.

#### Describe your issue

The app crashes with a `FileNotFoundError` `PyException` during startup.

```
07-26 19:50:01.775 18245 18245 E AndroidRuntime: FATAL EXCEPTION: main
07-26 19:50:01.775 18245 18245 E AndroidRuntime: Process: org.endlessos.testapp, PID: 18245
07-26 19:50:01.775 18245 18245 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.endlessos.testapp/org.endlessos.testapp.MainActivity}: com.chaquo.python.PyException: FileNotFoundError: kolibri/plugins/user_profile/management/commands
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: Caused by: com.chaquo.python.PyException: FileNotFoundError: kolibri/plugins/user_profile/management/commands
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.java.android.importer.listdir(.\java\android\importer.py:501)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.java.android.importer.iter_modules(.\java\android\importer.py:451)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.pkgutil.iter_modules(pkgutil.py:131)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.django.core.management.<listcomp>(__init__.py:30)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.django.core.management.find_commands(__init__.py:30)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.django.core.management.get_commands(__init__.py:74)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.django.core.management.call_command(__init__.py:106)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.kolibri.utils.main._migrate_databases(main.py:112)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.kolibri.utils.main.update(main.py:364)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.kolibri.utils.main.initialize(main.py:300)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.main.setup(main.py:17)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at org.endlessos.testapp.MainActivity.onCreate(MainActivity.java:34)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8051)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8031)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
07-26 19:50:01.775 18245 18245 E AndroidRuntime: 	... 12 more
```

**Comment by mhsmith** [comment]
I've merged this into #917 so we can see everything on one page.
