### ISSUE TITLE
importing android in python script

### ISSUE THREAD

**Issue by LogeshM05** [chaquo/chaquopy#929]
2023-08-09 11:37:07.423 4082-4082/com.example.pythonlifecycle W/System.err: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'android'
2023-08-09 11:37:07.427 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.java.chaquopy.import_override(import.pxi:20)
2023-08-09 11:37:07.427 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.java.chaquopy.import_override(import.pxi:60)
2023-08-09 11:37:07.427 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.androidsample.<module>(androidsample.py:1)
2023-08-09 11:37:07.427 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
2023-08-09 11:37:07.427 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.java.android.importer.exec_module(importer.py:554)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.importlib.import_module(__init__.py:127)
2023-08-09 11:37:07.428 4082-4082/com.example.pythonlifecycle W/System.err:     at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
2023-08-09 11:37:07.429 4082-4082/com.example.pythonlifecycle W/System.err:     at com.chaquo.python.Python.getModuleNative(Native Method)
2023-08-09 11:37:07.429 4082-4082/com.example.pythonlifecycle W/System.err:     at com.chaquo.python.Python.getModule(Python.java:84)
2023-08-09 11:37:07.429 4082-4082/com.example.pythonlifecycle W/System.err:     at com.example.pythonlifecycle.MainActivity$1.onClick(MainActivity.java:60)

**Comment by LogeshM05** [comment]
how to resolve this issue? can't we import android in python script

**Comment by mhsmith** [comment]
If you mean [this package](https://github.com/kivy/python-for-android/tree/master/pythonforandroid/recipes/android/src/android), it only works with Kivy. But if you tell me what you're trying to achieve, I might be able to suggest another solution.

**Comment by LogeshM05** [comment]
i want to access android lifecycle events in python

**Comment by mhsmith** [comment]
You can implement the lifecycle methods in in Java or Kotlin as shown [here](https://developer.android.com/guide/components/activities/activity-lifecycle), and then make those methods call into Python.
