### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by SocialNetUsr** [chaquo/chaquopy#93]
Hello, I am trying to install 'scapy' using chaquopy

The first error was relative to license. I managed to resolve it by using a  specific version of scapy

` pip {
install "scapy==v2.4.3rc1" 
}`

Now my problem is that i don't know how to import the scapy into my python script. I tried 
`import scapy.all`
or
`from scapy.all import sr1, IP, ICMP`

without any luck. The error that i get is 

**com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied**

Do you have any thoughts about this ?

**Comment by mhsmith** [comment]
If I add this version of scapy to the demo app, I can run the import statement in the Python console without any problems. So I suspect the error is actually caused by something else in your Python script.

Have a look at the stack trace of your error. If you still can't work out the cause, please post the stack trace and the relevant code.

**Comment by SocialNetUsr** [comment]
Hi mhsmith, i start a brand new app with the following configuration 


repositories {
        maven { url "https://chaquo.com/maven" }
}
dependencies {
        classpath "com.android.tools.build:gradle:3.3.1"
        classpath "com.chaquo.python:gradle:6.0.0"
}



defaultConfig {
       ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            pip {
                install "scapy==v2.4.3rc1"
            }
        }

added python script src/main/python/helper.py with content
` from scapy.all import *`

When i'm trying to build the project i still get the error  **com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied**

**The full stack** 

03/11 10:30:55: Launching app
$ adb shell am start -n "android.example.tmp.test1/android.example.tmp.test1.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: android.example.tmp.test1.test | android.example.tmp.test1
Waiting for application to come online: android.example.tmp.test1.test | android.example.tmp.test1
Waiting for application to come online: android.example.tmp.test1.test | android.example.tmp.test1
Connecting to android.example.tmp.test1
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application android.example.tmp.test1 is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
Connected to the target VM, address: 'localhost:8917', transport: 'socket'
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/chatty: uid=10087(android.example.tmp.test1) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10087(android.example.tmp.test1) identical 2 lines
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1393)
W/.tmp.test: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10087(android.example.tmp.test1) identical 10 lines
W/.tmp.test: JIT profile information will not be recorded: profile file does not exits.
I/InstantRun: starting instant run server: is main process
W/.tmp.test: Accessing hidden method Landroid/os/Handler;-><init>(Landroid/os/Looper;Landroid/os/Handler$Callback;Z)V (light greylist, JNI)
    Accessing hidden method Landroid/os/Handler;-><init>(Z)V (light greylist, JNI)
W/.tmp.test: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)
W/.tmp.test: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)
W/.tmp.test: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android.example.tmp.test1, PID: 10052
    java.lang.RuntimeException: Unable to start activity **ComponentInfo{android.example.tmp.test1/android.example.tmp.test1.MainActivity}: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied**
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     **Caused by: com.chaquo.python.PyException: PermissionError: [Errno 13] Permission denied**
        at <python>.socket.__init__(socket.py:144)
        at <python>.scapy.arch.linux.read_routes(linux.py:211)
        at <python>.scapy.route.resync(route.py:35)
        at <python>.scapy.route.__init__(route.py:27)
        at <python>.scapy.route.<module>(route.py:194)
        at <python>.java.android.importer.load_module_impl(importer.py:435)
        at <python>.java.android.importer.load_module(importer.py:353)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.scapy.all.<module>(all.py:27)
        at <python>.java.android.importer.load_module_impl(importer.py:435)
        at <python>.java.android.importer.load_module(importer.py:353)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.java.chaquopy.import_override(import.pxi:18)
        at <python>.helper.<module>(helper.py:1)
        at <python>.java.android.importer.load_module_impl(importer.py:435)
        at <python>.java.android.importer.load_module(importer.py:353)
        at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:626)
        at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:656)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:971)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:994)
        at <python>.importlib.import_module(__init__.py:126)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:154)
        at com.chaquo.python.Python.getModule(Native Method)
        at android.example.tmp.test1.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 10052 SIG: 9
Disconnected from the target VM, address: 'localhost:8917', transport: 'socket'

**Comment by mhsmith** [comment]
`scapy.arch.linux.read_routes(linux.py:211)` contains the following code:

```
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
```

This is probably failing because your app doesn't have the INTERNET permission. See [here](https://stackoverflow.com/questions/2378607) for how to fix this.

**Comment by SocialNetUsr** [comment]
Hi again, thanks for the response!

I have tried the 
`    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`
and it gives me a new error: **errno 1 operation not permitted android studio**

Also, i have tried the permissions
`   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />`

still not working. 

I'm using the emulator and my phone to check the application

**Comment by mhsmith** [comment]
If you have a new error, please post the stack trace.

**Comment by SocialNetUsr** [comment]
my new error  **[Errno 13] Permission denied**

$ adb install-multiple -r -t -p android.example.tmp.test1 C:\Projects\Msc\Android\Test1\app\build\intermediates\instant-run-apk\debug\app-debug.apk 
Split APKs installed in 1 s 910 ms
$ adb shell am start -n "android.example.tmp.test1/android.example.tmp.test1.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: android.example.tmp.test1.test | android.example.tmp.test1
Waiting for application to come online: android.example.tmp.test1.test | android.example.tmp.test1
Waiting for application to come online: android.example.tmp.test1.test | android.example.tmp.test1
Connecting to android.example.tmp.test1
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application android.example.tmp.test1 is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
    waiting for debugger to settle...
Connected to the target VM, address: 'localhost:9004', transport: 'socket'
I/chatty: uid=10101(android.example.tmp.test1) identical 2 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10101(android.example.tmp.test1) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1497)
W/.tmp.test: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10101(android.example.tmp.test1) identical 10 lines
W/.tmp.test: JIT profile information will not be recorded: profile file does not exits.
I/InstantRun: starting instant run server: is main process
W/.tmp.test: Accessing hidden method Landroid/os/Handler;-><init>(Landroid/os/Looper;Landroid/os/Handler$Callback;Z)V (light greylist, JNI)
    Accessing hidden method Landroid/os/Handler;-><init>(Z)V (light greylist, JNI)
W/.tmp.test: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)
W/.tmp.test: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)
W/.tmp.test: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/python.stderr: Exception ignored in: 
    <bound method SuperSocket.__del__ of <scapy.arch.linux.L3PacketSocket object at 0xd2a6a4ac>>
     
W/python.stderr: Traceback (most recent call last):
      File "/android_asset/chaquopy/requirements-common.zip/scapy/supersocket.py", line 127, in __del__
      File "/android_asset/chaquopy/requirements-common.zip/scapy/arch/linux.py", line 481, in close
    AttributeError
    : 
     **'L3PacketSocket' object has no attribute 'ins'**
     
W/.tmp.test1: type=1400 audit(0.0:1310): avc: denied { create } for scontext=u:r:untrusted_app:s0:c101,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c101,c256,c512,c768 tclass=packet_socket permissive=0

**Comment by mhsmith** [comment]
Sending ICMP packets is a privileged operation. Many devices will not allow a normal app to do it, no matter what permissions they have.

More information:
* https://stackoverflow.com/questions/7069503/android-app-allowing-socket-access-for-a-program
* https://unix.stackexchange.com/questions/382771/why-does-ping-need-setuid-permission
*  https://stackoverflow.com/questions/32749462/why-does-ping-works-on-some-devices-and-not-others

**Comment by SocialNetUsr** [comment]
Many thanks mhsmith for the help!!!

**Comment by ixenion** [comment]
> Many thanks mhsmith for the help!!!

But did you get it work?

**Comment by mhsmith** [comment]
Based on my previous comment, it probably isn't possible for a normal app to use ICMP on Android. Depending on what you're trying to achieve, maybe you could use TCP or UDP instead, for which the INTERNET permission should be enough.

**Comment by ixenion** [comment]
> Based on my previous comment, it probably isn't possible for a normal app to use ICMP on Android.

Its not possible even if the phone has root?

**Comment by mhsmith** [comment]
If you can arrange for the *app* to run as root, then maybe.

**Comment by ixenion** [comment]
> If you can arrange for the _app_ to run as root, then maybe.

Ahah, I know, that should be possible. May be how termux does (because scapy works there like a charm).
But I dont know how exactly termux does that. (but Id like to know :) )
