### ISSUE TITLE
No module named 'obspy'

### ISSUE THREAD

**Issue by NilukaD** [chaquo/chaquopy#938]
#### Relevant parts of your build.gradle file
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}

android {
    compileSdkVersion 32

    defaultConfig {
        applicationId "com.chaquo.myapplication"
        minSdkVersion 21
        targetSdkVersion 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
        python {
            buildPython "/usr/bin/python3.10"
            pip {
                install "matplotlib"
                install "scipy"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

#### Describe your issue
I am getting an error saying "No module named 'obspy'"

Detail error 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.myapplication/com.chaquo.myapplication.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'obspy'
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
                                                                                                    Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'obspy'
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:20)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:60)
                                                                                                    	at <python>.addition.<module>(addition.py:1)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
                                                                                                    	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:843)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:554)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:671)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.chaquo.myapplication.MainActivity.onCreate(MainActivity.kt:28)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7802)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7791)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)

**Comment by mhsmith** [comment]
We previously had a build of obspy for Python 3.6, but we didn't include it when we moved to Python 3.8 because it wasn't very popular. 

You can still use it by going back to an older version of Chaquopy. Based on the [commit history](https://github.com/search?q=repo%3Achaquo%2Fchaquopy+obspy&type=commits), we added obspy in August 2018 and removed it in January 2020, so that corresponds to [Chaquopy versions 4.0.0 to 6.3.0](https://chaquo.com/chaquopy/doc/current/changelog.html). Of course, you will also have to add obspy to the `pip` block of your build.gradle file.

However, during pre-release testing of version 6.3.0 I found that it failed the tests on the x86 emulator:
```
======================================================================
ERROR: test_basic (chaquopy.test.obspy.TestObspy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/core/util/libnames.py", line 95, in _load_cdll
  File "stdlib/ctypes/__init__.py", line 348, in __init__
OSError: dlopen failed: library "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/core/util/../../lib/libsignal_Linux_64bit_py36.so" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/app/chaquopy/test/obspy.py", line 11, in test_basic
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/signal/__init__.py", line 201, in <module>
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/signal/spectral_estimation.py", line 45, in <module>
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/signal/invsim.py", line 38, in <module>
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/signal/util.py", line 24, in <module>
  File "import.pxi", line 60, in java.chaquopy.import_override
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/signal/headers.py", line 18, in <module>
  File "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/core/util/libnames.py", line 98, in _load_cdll
ImportError: Could not load shared library "libsignal_Linux_64bit_py36.so".

 dlopen failed: library "/data/user/0/com.chaquo.python.pkgtest3/files/chaquopy/AssetFinder/requirements/obspy/core/util/../../lib/libsignal_Linux_64bit_py36.so" not found
```

Note that the error message mentions "64bit" even though this was running on 32-bit x86. I never got to the bottom of this because I was already planning to remove the package. But it may mean that you need to go earlier than Chaquopy 6.3.0 to find a working version.

If you'd like to try building a new version of this package, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi/README.md), and see the previous obspy recipe [here](https://github.com/chaquo/chaquopy/commit/1fe97ed0884956a35e597096775629d6637dfdcf). If you're successful, please make a pull request so we can add the package to the public repository.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.
