### ISSUE TITLE
Unable to build apk with module which wraps all integration with python

### ISSUE THREAD

**Issue by Gelassen** [chaquo/chaquopy#940]
#### Chaquopy version
```id("com.chaquo.python") version "14.0.2" apply false```

#### Relevant parts of your build.gradle file
```
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            // you may also import only some of them
        }
        python {    // this is not recognized in kts builds !!!
//            version "3.11"
            version "3.8"
            pip {
                install "matplotlib"
            }
            pyc {
                src false
            }
        }
```

#### Describe your issue
I have been following [this guide](https://albaspazio.medium.com/chaquopy-and-android-in-2023-d9739e95a05a) with workaround on existing issue with lack of support kotlin dsl. (It also has a clever wrapper around python invocation code). It encapsulates python code in a separate module. When I add this module, compilation fails with this stracktrace:
```
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
Caused by: com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-8.1.0-rc01-10154469-linux Daemon #0: Unexpected error during link, attempting to stop daemon.
This should not happen under normal circumstances, please file an issue if it does.
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.handleError(Aapt2Daemon.kt:193)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.handleError$default(Aapt2Daemon.kt:190)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:131)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.link(Aapt2DaemonManager.kt:176)
...
Caused by: java.io.IOException: Unable to make AAPT link command.
	at com.android.builder.internal.aapt.v2.Aapt2DaemonUtil.requestLink(Aapt2DaemonUtil.java:44)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doLink(Aapt2DaemonImpl.kt:175)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:124)
...
Caused by: com.android.builder.internal.aapt.AaptException: Dependent features configured but no package ID was set.
	at com.android.builder.internal.aapt.v2.AaptV2CommandBuilder.makeLinkCommand(AaptV2CommandBuilder.kt:316)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonUtil.requestLink(Aapt2DaemonUtil.java:42)
...
```  
Could you help with this please?

Sample code to reproduce the issue:
https://github.com/Gelassen/chaquopy-integration.git

**Comment by Gelassen** [comment]
I was able to run code with the latest python version with the latest but[ not-released-yet version of chaquopy](https://chaquo.com/chaquopy/doc/15.0/android.html). 

However, I am getting ```TypeError: 'MainActivity$testPythonModule$Params1' object is not subscriptable```, but it is seems to be just pure python related  issue.

**Comment by mhsmith** [comment]
This is probably caused by the same things as #939.

**Comment by Gelassen** [comment]
Thank you, I will close it to continue with updated issue #943
