### ISSUE TITLE
Call myClass.callAttr("sum_from_class", 3, 5).toInt() gives PyException: TypeError: MyClass.sum_from_class() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Gelassen** [chaquo/chaquopy#943]
#### Chaquopy version
    ```id("com.chaquo.python") version "15.0.0" apply false```

#### Devices or emulators where the issue happens
Default emulator with API 29

#### Relevant parts of your code

Added below

#### Describe your issue
I wrote a python script for test:
```

def sum(a, b):
    return a + b

class MyClass:

#     def __init__(self):
    def sum_from_class(a, b):
        return a + b

my_class = MyClass()
```
I am able to successfully call ```sum(a,b)``` outside of ```MyClass```, but not as a function call from ```MyClass```:
```
    fun runMyClassCase() {
        val py = Python.getInstance()
        val testModule = py.getModule("test")
        val myClass = testModule["my_class"]!!
        val result = myClass.callAttr("sum_from_class", 3, 5).toInt()
        Log.d("TAG", "Python MyClass.sum() call result $result")
    }
```
```
Caused by: com.chaquo.python.PyException: TypeError: MyClass.sum_from_class() takes 2 positional arguments but 3 were given
      at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
      at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
      at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
      at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
      at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
```

Moreover, at also used [this wrapper](https://albaspazio.medium.com/chaquopy-and-android-in-2023-d9739e95a05a) around ```chaquopy```, but similar call gives a different error:
```
    fun runOverSPython() {
        val py = SPython.getInstance(application)
        val myClass = py.instantiate("test", "my_class")
        val result = myClass.callAttr("sum_from_class", 3, 5)
        Log.d("TAG", "Python sum_from_class result ${result.toInt()}")
    }
```
```
Caused by: com.chaquo.python.PyException: TypeError: 'MyClass' object is not callable
      at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
      at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
      at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
      at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
      at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
``` 

However, this plain call of function out of the class works fine:
```
    fun runMyTestCase() {
        val py = Python.getInstance()
        val myClass = py.getModule("test")
        val result = myClass.callAttr("sum", 3, 5).toInt()
        Log.d("TAG", "Sum result from python module!! ${result}")
    }
```

**Comment by mhsmith** [comment]
> MyClass.sum_from_class() takes 2 positional arguments but 3 were given

You forgot to include `self` in the method definition.

> TypeError: 'MyClass' object is not callable

The "instantiate" function expects the name of a class, but you passed an *instance* of the class.

**Comment by Gelassen** [comment]
Thank you, got it.

**Comment by guruprakashIT** [comment]
Hello @mhsmith 

how to instantiate class of this object.

give me the example for the above sample program

**Comment by mhsmith** [comment]
The example code on [this page](https://chaquo.com/chaquopy/doc/current/java.html#examples) should demonstrate everything you need.
