### ISSUE TITLE
App is crashing on Runtime

### ISSUE THREAD

**Issue by surajsahani** [chaquo/chaquopy#947]
ATAL EXCEPTION: main
                                                                                                    Process: com.example.pythoneditorpoc, PID: 6391
                                                                                                    com.chaquo.python.PyException: ModuleNotFoundError: No module named 'pyscript'
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:973)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.example.pythoneditorpoc.MainActivity.onCreate$lambda$0(MainActivity.kt:23)
                                                                                                    	at com.example.pythoneditorpoc.MainActivity.$r8$lambda$rp-DpYoYIrkhQ452UcR6FoACyeE(Unknown Source:0)
                                                                                                    	at com.example.pythoneditorpoc.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7564)
                                                                                                    	at android.view.View.performClickInternal(View.java:7537)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29761)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8136)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by mhsmith** [comment]
If this is your own module, then see [here](https://chaquo.com/chaquopy/doc/current/android.html#android-source).

If it's a third-party module, then see [here](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements).
