### ISSUE TITLE
zipfile LZMA support fails

### ISSUE THREAD

**Issue by dbnicholson** [chaquo/chaquopy#952]
#### Chaquopy version

14.0.2, although I first found this on a locally built master based on 7c43c0a861d64d623748f2e070766a022a9a331f with the fixes from #917 and #924.

#### Devices or emulators where the issue happens

2 emulators:

```
    Name: test
  Device: pixel_5 (Google)
    Path: /home/dan/.android/avd/test.avd
  Target: Default Android System Image
          Based on: Android 12.0 ("S") Tag/ABI: default/x86_64
  Sdcard: 512 MB
---------
    Name: test-play
  Device: pixel_5 (Google)
    Path: /home/dan/.android/avd/test-play.avd
  Target: Google Play (Google Inc.)
          Based on: Android 12.0 ("S") Tag/ABI: google_apis_playstore/x86_64
  Sdcard: 512 MB
```

#### Relevant parts of your code

The java code simply runs:

```
Python.getInstance().getModule("testzipfile")
```

And the python module is:

```
print('Importing lzma')
import lzma

print('Importing zipfile')
import zipfile

print('Checking if zipfile support lzma')
zipfile._check_compression(zipfile.ZIP_LZMA)
```

#### Describe your issue

It crashes with zipfile saying that there's no LZMA support:

```
09-01 19:50:45.099 24427 24427 I python.stdout: Importing lzma
09-01 19:50:45.110 24427 24427 I python.stdout: Importing zipfile
09-01 19:50:45.110 24427 24427 I python.stdout: Checking if zipfile support lzma
09-01 19:50:45.118 24427 24427 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-01 19:50:45.120 24427 24427 E AndroidRuntime: FATAL EXCEPTION: main
09-01 19:50:45.120 24427 24427 E AndroidRuntime: Process: com.example.chaquopyzipfile, PID: 24427
09-01 19:50:45.120 24427 24427 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.chaquopyzipfile/com.example.chaquopyzipfile.MainActivity}: com.chaquo.python.PyException: RuntimeError: Compression requires the (missing) lzma module
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: Caused by: com.chaquo.python.PyException: RuntimeError: Compression requires the (missing) lzma module
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.zipfile._check_compression(zipfile.py:675)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.testzipfile.<module>(testzipfile.py:8)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:228)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:850)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.java.android.importer.exec_module(importer.py:554)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.java.android.importer.exec_module(importer.py:606)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:680)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:986)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1007)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1030)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.importlib.import_module(__init__.py:127)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at com.chaquo.python.Python.getModuleNative(Native Method)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at com.chaquo.python.Python.getModule(Python.java:84)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at com.example.chaquopyzipfile.MainActivity.onCreate(MainActivity.kt:28)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8051)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8031)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
09-01 19:50:45.120 24427 24427 E AndroidRuntime: 	... 12 more
```

What's interesting is that all `zipfile` does to determine if it has LZMA support is to try to import `lzma`. Which I did just before that. So, there's something about it being imported from `zipfile` that doesn't work correctly.

**Comment by dbnicholson** [comment]
Interesting, this also affects `ZIP_BZIP2`. I extended the python code to test all the zipfile compression schemes and not crash immediately:

```
import sys

print('Importing zlib')
import zlib

print('Importing bz2')
import bz2

print('Importing lzma')
import lzma

print('Importing zipfile')
import zipfile

for compression, name in (
    (zipfile.ZIP_STORED, 'ZIP_STORED'),
    (zipfile.ZIP_DEFLATED, 'ZIP_DEFLATED'),
    (zipfile.ZIP_BZIP2, 'ZIP_BZIP2'),
    (zipfile.ZIP_LZMA, 'ZIP_LZMA'),
):
    print(f'Checking if zipfile supports {name}')
    try:
        zipfile._check_compression(compression)
    except RuntimeError as err:
        print(f'{name} support failed: {err}', file=sys.stderr)
```

That results in:
```
09-01 21:02:27.755 26002 26002 I python.stdout: Importing zlib
09-01 21:02:27.755 26002 26002 I python.stdout: Importing bz2
09-01 21:02:27.759 26002 26002 I python.stdout: Importing lzma
09-01 21:02:27.767 26002 26002 I python.stdout: Importing zipfile
09-01 21:02:27.767 26002 26002 I python.stdout: Checking if zipfile supports ZIP_STORED
09-01 21:02:27.767 26002 26002 I python.stdout: Checking if zipfile supports ZIP_DEFLATED
09-01 21:02:27.767 26002 26002 I python.stdout: Checking if zipfile supports ZIP_BZIP2
09-01 21:02:27.767 26002 26002 W python.stderr: ZIP_BZIP2 support failed: Compression requires the (missing) bz2 module
09-01 21:02:27.767 26002 26002 I python.stdout: Checking if zipfile supports ZIP_LZMA
09-01 21:02:27.767 26002 26002 W python.stderr: ZIP_LZMA support failed: Compression requires the (missing) lzma module
```

A couple things I notice about this. Both bzip2 and liblzma are built statically and linked directly into the python _bz2 and _lzma modules. However, the zlib module is included in bootstrap-native to be used by zipfile/zipimport. Might the same treatment be needed for _bz2 and _lzma?

**Comment by dbnicholson** [comment]
Yeah, that seems to be it. `zipfile` is already in imported from the bootstrap. If I throw in:

```
import importlib
importlib.reload(zipfile)
```

It works.

**Comment by dbnicholson** [comment]
The `importlib.reload` workaround kind of works but later imports break in unusual ways. The patch in #953 fixes the issue for me.
