### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;

### ISSUE THREAD

**Issue by Bradly-s** [chaquo/chaquopy#955]
if (!Python.isStarted()){
            LogUtils.logWithMethodInfo("!Python.isStarted()");
            Python.start(new AndroidPlatform(this));
        }
在安卓MainActivity的onCreate方法中，加载python环境报错：
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;
                                                                                                    	at org.python.core.PyType.fromClass(PyType.java:2137)
                                                                                                    	at org.python.core.PyObject.<init>(PyObject.java:85)
                                                                                                    	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:22)
                                                                                                    	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
                                                                                                    	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:21)
                                                                                                    	at org.python.core.PyType$type___init___exposer.<init>(Unknown Source:0)
                                                                                                    	at org.python.core.PyType$PyExposer.<init>(Unknown Source:16)
                                                                                                    	at org.python.core.PyType.<clinit>(Unknown Source:2)
                                                                                                    	at org.python.core.PyType.fromClass(PyType.java:2137)
                                                                                                    	at org.python.core.PyObject.<init>(PyObject.java:85)
                                                                                                    	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:22)
                                                                                                    	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
                                                                                                    	at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:23)
                                                                                                    	at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source:2)
                                                                                                    	at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source:15)
                                                                                                    	at org.python.core.PyDataDescr.<clinit>(Unknown Source:2)
                                                                                                    	at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source:14)
                                                                                                    	at org.python.core.PyBuiltinCallable.<clinit>(Unknown Source:2)
                                                                                                    	at org.python.core.PyObject$PyExposer.<init>(Unknown Source:13)
                                                                                                    	at org.python.core.PyObject.<clinit>(Unknown Source:2)
                                                                                                    	at <python>.java.chaquopy.CQPEnv.check_exception(env.pxi:546)
                                                                                                    	at <python>.java.chaquopy.CQPEnv.expect_exception(env.pxi:517)
                                                                                                    	at <python>.java.chaquopy.CQPEnv.GetMethodID(env.pxi:123)
                                                                                                    	at <python>.java.chaquopy.JavaMethod.__init__(class.pxi:751)
                                                                                                    	at <python>.java.chaquopy.find_member(class.pxi:454)
                                                                                                    	at <python>.java.chaquopy.reflect_member(class.pxi:436)
                                                                                                    	at <python>.java.chaquopy.reflect_member(class.pxi:425)
                                                                                                    	at <python>.java.chaquopy.JavaClass.__getattribute__(class.pxi:141)
                                                                                                    	at <python>.copy.<module>(copy.py:124)
                                                                                                    	at <python>.zipimport.load_module(<frozen zipimport>:259)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.java._vendor.elftools.dwarf.lineprogram.<module>(lineprogram.py:10)
                                                                                                    	at <python>.zipimport.load_module(<frozen zipimport>:259)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.java._vendor.elftools.dwarf.dwarfinfo.<module>(dwarfinfo.py:17)
                                                                                                    	at <python>.zipimport.load_module(<frozen zipimport>:259)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.java._vendor.elftools.elf.elffile.<module>(elffile.py:34)
                                                                                                    	at <python>.zipimport.load_module(<frozen zipimport>:259)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.java.android.importer.<module>(importer.py:27)
                                                                                                    	at <python>.zipimport.load_module(<frozen zipimport>:259)
                                                                                                    	at <python>.java.chaquopy.import_override(import.pxi:26)
                                                                                                    	at <python>.java.android.<module>(__init__.py:9)
                                                                                                    	at <python>.zipimport.load_module(<frozen zipimport>:259)
                                                                                                    	at <python>.importlib._bootstrap._load_backward_compatible(<frozen importlib._bootstrap>:618)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:655)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:975)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:155)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)
                                                                                                    	at com.chaquo.python.android.AndroidPlatform.onStart(AndroidPlatform.java:132)
                                                                                                    	at com.chaquo.python.Python.start(Python.java:54)
                                                                                                    	at com.echooo.recognition_yolo_java.view.activity.MainActivityLast.onCreate(MainActivityLast.java:114)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8214)

**Comment by mhsmith** [comment]
Well, that's a completely different error, but this time the message is self-explanatory. You should call `toJava` on the return value of `pyObject.callAttr`, not `pyObject` itself.

Also, instead of using `toJava` for the basic Java types, you should use the methods `toString`, `toInt` etc, which are both more efficient and easier to read.

**Comment by Bradly-s** [comment]
好的，问题已解决，谢谢。
