### ISSUE TITLE
Update SciPy package to 1.8.1

### ISSUE THREAD

**Issue by pasdeloup** [chaquo/chaquopy#960]
We already moved forward with SciPy 1.6.3 available in #949 
But the research team I work with asked to go further as they need the 1.8.1 version to use the ` scipy.sparse.csr_array` type

This version is the last before SciPy switched to Meson for building and is also the last available in Kivy, so it should be reachable with proper patching.

**Comment by pasdeloup** [comment]
Current error is:
<details>
  <summary>Error Log</summary>

```
build-wheel: /home/jpasdeloup/Android/Sdk//ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar rc /home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/chaquopy/lib/libpthread.a
build-wheel: /home/jpasdeloup/Android/Sdk//ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar rc /home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/chaquopy/lib/librt.a
Running from numpy source directory.
Traceback (most recent call last):
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
    self.run_setup()
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 639, in <module>
    setup_package()
  File "setup.py", line 616, in setup_package
    cmdclass['build_ext'] = get_build_ext_override()
  File "setup.py", line 246, in get_build_ext_override
    import pythran
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/__init__.py", line 41, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx, Python
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/backend.py", line 7, in <module>
    from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/pythran/tables.py", line 151, in <module>
    inspect.getfullargspec(numpy.asarray)
AttributeError: module 'numpy' has no attribute 'asarray'
build-wheel: Error: Backend subprocess exited when trying to invoke build_wheel
```
</details>

And if I disable Pythran (as currently done in Kivy) with
`export SCIPY_USE_PYTHRAN=0`

I have instead the following error:
<details>
  <summary>Error Log</summary>

```
Running from numpy source directory.
Cythonizing sources
Running scipy/special/_generate_pyx.py
Running scipy/stats/_generate_pyx.py
Running scipy/linalg/_generate_pyx.py
Traceback (most recent call last):
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/_multiarray_umath.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/scipy/stats/_generate_pyx.py", line 46, in <module>
    make_biasedurn()
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/scipy/stats/_generate_pyx.py", line 22, in make_biasedurn
    dest.write(contents.format(NPY_OLD=str(bool(isNPY_OLD()))))
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/scipy/stats/_generate_pyx.py", line 11, in isNPY_OLD
    import numpy as np
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/__init__.py", line 154, in <module>
    from . import core
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/bin/python"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/_multiarray_umath.so: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/_multiarray_umath.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/scipy/special/_generate_pyx.py", line 233, in <module>
    import numpy
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/__init__.py", line 154, in <module>
    from . import core
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/bin/python"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/requirements/numpy/core/_multiarray_umath.so: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/tools/cythonize.py", line 317, in <module>
    main()
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/tools/cythonize.py", line 313, in main
    find_process_files(root_dir)
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/tools/cythonize.py", line 279, in find_process_files
    for result in pool.imap_unordered(lambda fn: process_generate_pyx(fn, lock), jobs):
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/tools/cythonize.py", line 279, in <lambda>
    for result in pool.imap_unordered(lambda fn: process_generate_pyx(fn, lock), jobs):
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/src/tools/cythonize.py", line 250, in process_generate_pyx
    raise RuntimeError("Running {} failed".format(path))
RuntimeError: Running scipy/stats/_generate_pyx.py failed
Traceback (most recent call last):
  File "setup.py", line 361, in generate_cython
    import pip
ModuleNotFoundError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/jpasdeloup/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
    self.run_setup()
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/home/jpasdeloup/code/vendor/chaquopy/server/pypi/packages/scipy/build/1.8.1/cp39-cp39-android_21_arm64_v8a/env/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 639, in <module>
    setup_package()
  File "setup.py", line 623, in setup_package
    generate_cython()
  File "setup.py", line 363, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
build-wheel: Error: Backend subprocess exited when trying to invoke build_wheel
```
</details>

**Comment by pasdeloup** [comment]
The issue comes from Cython generation that is mandatory since 1.7.0 as they don't ship the generated sources anymore (https://github.com/scipy/scipy/pull/14230)
This generation uses numpy at different places, let's see if we can hack it.
