### ISSUE TITLE
Some suggestions for code security

### ISSUE THREAD

**Issue by zwkaku** [chaquo/chaquopy#966]
Thank you very much for bringing us such an excellent and perfect framework to help us quickly use python to develop Android apps.
There are some suggestions that I hope the author can adopt, the code will be compiled in /assets/chaquopy/ directory to generate an app.imy file I tried to use the zip unzip tool to open the source code, so the code is not too safe. Can you automatically compile the source code into a.so file when compiling the app? app will call the.so file directly when running, so it will not burst the source code to be stolen. Hope the author can optimize

**Comment by mhsmith** [comment]
I don't think it's feasible for the Gradle plugin to automatically compile code into an .so file, there are too many complications. However, it does automatically compile into .pyc format whenever possible. And if you want to compile your own code into an .so file, you can use Cython along with our package build tool. 

For details on both of these options, see [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-obfuscate).

**Comment by zwkaku** [comment]
thanks for your reply. Ok, I'll look at this method

**Comment by zwkaku** [comment]
Hello author, I need your help with a question. I have completed building the whl by following the Chaquopy packages steps. After I added it to the project, my python file references the java.lang package causing an exception like this:
 

>   Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'java.lang'
                                                                                                    	at <python>.ydamap.init ydamap(ydamap.pyx:6)
                                                                                                    	at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:228)
                                                                                                    	at <python>.importlib._bootstrap_external.exec_module(<frozen importlib._bootstrap_external>:1181)
                                                                                                    	at <python>.java.android.importer.exec_module(importer.py:554)
                                                                                                    	at <python>.importlib._bootstrap._load_unlocked(<frozen importlib._bootstrap>:680)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:986)
                                                                                                    	at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:1007)
                                                                                                    	at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1030)
                                                                                                    	at <python>.importlib.import_module(__init__.py:127)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModuleNative(chaquopy_java.pyx:129)
                                                                                                    	at com.chaquo.python.Python.getModuleNative(Native Method)
                                                                                                    	at com.chaquo.python.Python.getModule(Python.java:84)

This is my import
> import json
import time
import traceback
import requests
from java import dynamic_proxy, static_proxy
from java.lang import Runnable, Thread
from android.webkit import WebView, WebViewClient
from python.app.src import EncryptTool
from com.yd.im import AndroidFunction
import base64
import random
from android.provider import Settings
from java.io import FileInputStream
from java.math import BigInteger
from java.security import MessageDigest



![image](https://github.com/chaquo/chaquopy/assets/39154896/bc9b3f72-364e-4f8c-98ac-bb866f530690)

**Comment by mhsmith** [comment]
It looks like the syntax to import Java classes doesn't work with Cython, probably because it's calling the C import API rather than looking up `builtins.__import__`. 

To work around this, you can use `jclass`:
```
from java import jclass
Runnable = jclass("java.lang.Runnable")
Thread = jclass("java.lang.Thread")
```

**Comment by zwkaku** [comment]
Thank you very, very, very, very, very, very much that it's resolved
