### ISSUE TITLE
Tensor convert to floatArray failed

### ISSUE THREAD

**Issue by 2270500219Y** [chaquo/chaquopy#983]
#### Relevant parts of build.gradle file

python block
```
python {
    pip {
        install "librosa==0.9.2"
        install "resampy==0.3.1"
        install "scipy"
         install "torch"
    }
}
```
dependencies block 
```
dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'org.pytorch:pytorch_android_lite:1.10.0'
}
```

#### Relevant parts of your code
```
public Tensor getdata(){

    Python py = Python.getInstance();
    PyObject feature = py.getModule("partition_train");
    PyObject py_feature = feature.callAttr("get_feature");
    float[] toTensor = py_feature.toJava(float[].class);
    Tensor batch_x = Tensor.fromBlob(toTensor, new long[]{batch_size, -1});
    return batch_x;
}
```

```
private Tensor model() {

    if (module == null) {
        module = LiteModuleLoader.load(assetFilePath(getApplicationContext(), "audio.ptl"));
    }
    Tensor batch_x = getdata();
    Tensor batch_output =module.forward(IValue.from(batch_x)).toTensor();

    return batch_output;
}
```

```
2023-10-03 21:10:04.794 11307-11307 AndroidRuntime          com.example.audio                    E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.audio, PID: 11307
                                                                                                    java.lang.ClassCastException: TypeError: Cannot convert Tensor object to float
                                                                                                    	at <python>.java.chaquopy.p2j(conversion.pxi:252)
                                                                                                    	at <python>.java.chaquopy.array_set(array.pxi:320)
                                                                                                    	at <python>.java.chaquopy.JavaArray._init_value(array.pxi:109)
                                                                                                    	at <python>.java.chaquopy.JavaBufferArray._init_value(array.pxi:265)
                                                                                                    	at <python>.java.chaquopy.JavaArray.__init__(array.pxi:105)
                                                                                                    	at <python>.java.chaquopy.JavaClass.__call__(class.pxi:135)
                                                                                                    	at <python>.java.chaquopy.ArrayClass.__call__(array.pxi:64)
                                                                                                    	at <python>.java.chaquopy.p2j_array(conversion.pxi:282)
                                                                                                    	at <python>.java.chaquopy.p2j(conversion.pxi:247)
                                                                                                    	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_toJava(chaquopy_java.pyx:167)
                                                                                                    	at com.chaquo.python.PyObject.toJava(Native Method)
                                                                                                    	at com.example.audio.MainActivity.getdata(MainActivity.java:313)
                                                                                                    	at com.example.audio.MainActivity.model(MainActivity.java:359)
                                                                                                    	at com.example.audio.MainActivity.denoise(MainActivity.java:328)
                                                                                                    	at com.example.audio.MainActivity.access$200(MainActivity.java:51)
                                                                                                    	at com.example.audio.MainActivity$2.onClick(MainActivity.java:124)
                                                                                                    	at android.view.View.performClick(View.java:7766)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
                                                                                                    	at android.view.View.performClickInternal(View.java:7739)
                                                                                                    	at android.view.View.access$3700(View.java:860)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29330)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8306)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```
#### Describe your issue
  I need to pass the result of the python function call as input into the mobile neural network model.
  It has to be Tensor.But PyObject cannot be converted directly to Tensor.
  So I tried to convert PyObject to floatArray and then to Tensor.
  If you can convert PyObject directly to Tensor, that's even better
  In the end I failed.Please help.

**Comment by mhsmith** [comment]
What is the Java data type – is it `org.pytorch.Tensor`?

What is the Python data type returned by `get_feature`? If possible, please post the source code of that function.

**Comment by mhsmith** [comment]
On GitHub, multi-line text blocks should be marked with <code>```</code> as shown [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by 2270500219Y** [comment]
> 什么是 Java 数据类型 – 是吗？`org.pytorch.Tensor`
> 
> 返回的 Python 数据类型是什么？如果可能，请发布该函数的源代码。`get_feature`
> 
> 在 GitHub 上，应标记多行文本块，[如下所示。](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)`` ``` ``

Yes,my neural network model needs an pytorch.Tensor input.
The returned Python data type is torch.Tensor.
I'm sorry, I couldn't publish my function for some reason.
Whether it is in github or chaquo, I am a novice.Thank you for your reply, help and tolerance,sir.

**Comment by mhsmith** [comment]
Because the message says `Cannot convert Tensor object to float`, as opposed to `float[]`, I think your Python function must be returning a sequence containing a Tensor, not a Tensor alone.

Once you do get a reference to the actual Tensor, according to https://github.com/pytorch/pytorch/issues/19143, the Python Tensor object doesn't support the buffer protocol, so converting it to a Java array would be very slow. As a workaround, they suggest calling `.numpy` to view the data as a NumPy array. 

You will probably also have to `flatten` or `reshape` the array to make it compatible with a 1-dimensional Java array.

**Comment by 2270500219Y** [comment]
> Because the message says `Cannot convert Tensor object to float`, as opposed to `float[]`, I think your Python function must be returning a sequence containing a Tensor, not a Tensor alone.
> 
> Once you do get a reference to the actual Tensor, according to [pytorch/pytorch#19143](https://github.com/pytorch/pytorch/issues/19143), the Python Tensor object doesn't support the buffer protocol, so converting it to a Java array would be very slow. As a workaround, they suggest calling `.numpy` to view the data as a NumPy array.
> 
> You will probably also have to `flatten` or `reshape` the array to make it compatible with a 1-dimensional Java array.

Yes, I successfully converted pytorch.tensor to flaot array by following your advice.
Thanks a lot for your suggests.
